<a href="https://colab.research.google.com/github/christophermagno/christophermagno/blob/main/Projects/Chicago%20Traffic%20Accident%20Analysis/chicago_traffic_crashes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🚗 Chicago Traffic Accident Analysis
## ⚒️ Tools Used
[![Python](https://img.shields.io/badge/Python-3776AB?logo=python&logoColor=fff)](#)
[![Pandas](https://img.shields.io/badge/Pandas-150458?logo=pandas&logoColor=fff)](#)
[![Jupyter](https://img.shields.io/badge/Jupyter-ffffff?logo=Jupyter)](#)
[![ETL](https://custom-icon-badges.demolab.com/badge/ETL-9370DB?logo=etl-logo&logoColor=fff)](#)
[![EDA](https://custom-icon-badges.demolab.com/badge/EDA-9370DB?logo=etl-logo&logoColor=fff)](#)
[![Tableau](https://custom-icon-badges.demolab.com/badge/Tableau-0176D3?logo=tableau&logoColor=fff)](#)

## 🚦 Chicago Traffic Crash Analysis (Python, Pandas, Tableau)
This project analyzes over **1 million traffic crash records** from the City of Chicago to identify patterns in accident frequency, severity, contributing factors, and high-risk locations. The objective was to demonstrate the ability to **work with large-scale, messy datasets**, perform **data wrangling and exploratory data analysis (EDA)** using **Python and pandas**, and communicate insights through **interactive Tableau visualizations**.

- **Dataset Size:** 1,010,926 rows × 48 columns (~549 MB)
- **Tools:** Python, pandas, NumPy, Tableau
- **Data Source:** Chicago Traffic Crashes - [data.gov](https://catalog.data.gov/dataset/traffic-crashes-crashes)

## 🎯 Objectives
- Perform large-scale data cleaning and transformation on a real-world public safety dataset
- Identify temporal, environmental, and behavioral factors contributing to traffic crashes
- Highlight high-risk locations for targeted safety improvements
- Translate analytical findings into business-relevant insights using data visualization

To view the Tableau visualization, please click [here](https://public.tableau.com/app/profile/christopher.magno/viz/ChicagoTrafficAccidentAnalysis/ChicagoRoadAccidentAnalysis)

In [ ]:
import json
import logging
import importlib
from pathlib import Path

import pandas as pd

from google.colab import drive

# Project Directory
PROJECT_DIR = Path('/content/drive/MyDrive/Colab Notebooks/christophermagno/Projects/Chicago Traffic Accident Analysis')

# Logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    datefmt='%m/%d/%y|%H:%M',
    force=True)
log = logging.getLogger('Chicago Traffic Analysis')


# Google Drive
drive.mount('/content/drive')
path_raw = PROJECT_DIR / 'chicago_traffic_crashes.csv'
path_export = PROJECT_DIR / 'chicago_traffic_crashes_CLEAN.csv'


log.info(f'{path_raw.name} exists: {path_raw.exists()}')

## Read dataset

In [ ]:
df = pd.read_csv(path_raw, encoding='ascii')

## Getting the general info to see what we're working with

In [ ]:
log.info(f'DataFrame shape {df.shape}')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020445 entries, 0 to 1020444
Data columns (total 48 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   CRASH_RECORD_ID                1020445 non-null  object
 1   CRASH_DATE_EST_I               74070 non-null    object
 2   CRASH_DATE                     1020445 non-null  object
 3   POSTED_SPEED_LIMIT             1020445 non-null  int64
 4   TRAFFIC_CONTROL_DEVICE         1020445 non-null  object
 5   DEVICE_CONDITION               1020445 non-null  object
 6   WEATHER_CONDITION              1020445 non-null  object
 7   LIGHTING_CONDITION             1020445 non-null  object
 8   FIRST_CRASH_TYPE               1020445 non-null  object
 9   TRAFFICWAY_TYPE                1020445 non-null  object
 10  LANE_CNT                       199032 non-null   float64
 11  ALIGNMENT                      1020445 non-null  object
 12  ROADWAY_SURFACE_COND           1020445 non-null  object
 13  ROAD_DEFECT                    1020445 non-null  object
 14  REPORT_TYPE                    986578 non-null   object
 15  CRASH_TYPE                     1020445 non-null  object
 16  INTERSECTION_RELATED_I         234608 non-null   object
 17  NOT_RIGHT_OF_WAY_I             45727 non-null    object
 18  HIT_AND_RUN_I                  320242 non-null   object
 19  DAMAGE                         1020445 non-null  object
 20  DATE_POLICE_NOTIFIED           1020445 non-null  object
 21  PRIM_CONTRIBUTORY_CAUSE        1020445 non-null  object
 22  SEC_CONTRIBUTORY_CAUSE         1020445 non-null  object
 23  STREET_NO                      1020445 non-null  int64
 24  STREET_DIRECTION               1020441 non-null  object
 25  STREET_NAME                    1020444 non-null  object
 26  BEAT_OF_OCCURRENCE             1020440 non-null  float64
 27  PHOTOS_TAKEN_I                 14550 non-null    object
 28  STATEMENTS_TAKEN_I             24342 non-null    object
 29  DOORING_I                      3259 non-null     object
 30  WORK_ZONE_I                    5537 non-null     object
 31  WORK_ZONE_TYPE                 4226 non-null     object
 32  WORKERS_PRESENT_I              1416 non-null     object
 33  NUM_UNITS                      1020445 non-null  int64
 34  MOST_SEVERE_INJURY             1018219 non-null  object
 35  INJURIES_TOTAL                 1018233 non-null  float64
 36  INJURIES_FATAL                 1018233 non-null  float64
 37  INJURIES_INCAPACITATING        1018233 non-null  float64
 38  INJURIES_NON_INCAPACITATING    1018233 non-null  float64
 39  INJURIES_REPORTED_NOT_EVIDENT  1018233 non-null  float64
 40  INJURIES_NO_INDICATION         1018233 non-null  float64
 41  INJURIES_UNKNOWN               1018233 non-null  float64
 42  CRASH_HOUR                     1020445 non-null  int64
 43  CRASH_DAY_OF_WEEK              1020445 non-null  int64
 44  CRASH_MONTH                    1020445 non-null  int64
 45  LATITUDE                       1012679 non-null  float64
 46  LONGITUDE                      1012679 non-null  float64
 47  LOCATION                       1012679 non-null  object
dtypes: float64(11), int64(6), object(31)
memory usage: 373.7+ MB

In [ ]:
df.info()

,CRASH_RECORD_ID,CRASH_DATE_EST_I,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
0,000c4307d8e9b39075cffdd0aade3603e0f96f14e41da9...,NaN,01/14/2025 12:25:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,SNOW,DAYLIGHT,SIDESWIPE SAME DIRECTION,DIVIDED - W/MEDIAN (NOT RAISED),...,0.0,0.0,2.0,0.0,12,3,1,41.997808,-87.655770,POINT (-87.655770494712 41.997807727633)
1,027b0b4c21460d3441fd83929abb9673c6fc0c7d575675...,NaN,05/23/2025 09:30:00 AM,30,STOP SIGN/FLASHER,UNKNOWN,UNKNOWN,DAYLIGHT,TURNING,DIVIDED - W/MEDIAN (NOT RAISED),...,0.0,0.0,2.0,0.0,9,6,5,41.946529,-87.688106,POINT (-87.688106391039 41.946529480518)
2,04d91dffc94f677358ca47056921ba5c4224320df27ed4...,Y,04/05/2025 08:00:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,UNKNOWN,PARKED MOTOR VEHICLE,NOT DIVIDED,...,0.0,0.0,1.0,0.0,20,7,4,41.899325,-87.715074,POINT (-87.715074373867 41.899324573751)
3,0b5603954d84b7341c7cad4f570ea039e85919f3750ccb...,NaN,05/23/2025 09:15:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PEDALCYCLIST,NOT DIVIDED,...,1.0,0.0,2.0,0.0,9,6,5,41.902793,-87.699412,POINT (-87.699412181285 41.902792968177)
4,00bce77960c2faa2a8782a8cac1d6e5715802d6c072a08...,NaN,01/14/2025 08:00:00 AM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,SNOW,DAYLIGHT,REAR END,FOUR WAY,...,0.0,0.0,2.0,0.0,8,3,1,41.691207,-87.720555,POINT (-87.720554863466 41.691206664451)

In [ ]:
df.head()

### Checking for null indices and rows

## Creating a backup

In [ ]:
df_cp1 = df.copy()

## Processing NaN Values

In [ ]:
df_cp1.columns

### Checking for NaN and Non-NaN columns
Get % of nulls in the columns

In [ ]:
# Create a null and non_null columns list
err_rates = df_cp1.isnull().mean() * 100
err_rates

### Checking for columns whose values are 75% or more NaN

In [ ]:
err_rates = df_cp1.isnull().mean() * 100
high_risk = err_rates[err_rates > 75]
high_risk

#### Removing data that is not useable

In [ ]:
df_cp1 = df_cp1.drop(high_risk.index, axis=1)

### Filling the rest of the NaN values with filler values
Get columns that have nulls in them

In [ ]:
err_cols = df_cp1.isnull().any()
err_mask = err_cols[err_cols == True].index
err_mask

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020445 entries, 0 to 1020444
Data columns (total 16 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   REPORT_TYPE                    986578 non-null   object
 1   HIT_AND_RUN_I                  320242 non-null   object
 2   STREET_DIRECTION               1020441 non-null  object
 3   STREET_NAME                    1020444 non-null  object
 4   BEAT_OF_OCCURRENCE             1020440 non-null  float64
 5   MOST_SEVERE_INJURY             1018219 non-null  object
 6   INJURIES_TOTAL                 1018233 non-null  float64
 7   INJURIES_FATAL                 1018233 non-null  float64
 8   INJURIES_INCAPACITATING        1018233 non-null  float64
 9   INJURIES_NON_INCAPACITATING    1018233 non-null  float64
 10  INJURIES_REPORTED_NOT_EVIDENT  1018233 non-null  float64
 11  INJURIES_NO_INDICATION         1018233 non-null  float64
 12  INJURIES_UNKNOWN               1018233 non-null  float64
 13  LATITUDE                       1012679 non-null  float64
 14  LONGITUDE                      1012679 non-null  float64
 15  LOCATION                       1012679 non-null  object
dtypes: float64(10), object(6)
memory usage: 124.6+ MB

In [ ]:
df_cp1[err_mask].info()

### Fill the columns with null values

In [ ]:
for col in df_cp1[err_mask]:
    log.info(f'{col}: {df_cp1[col].dtypes}')
    if df_cp1[col].dtypes == 'object':
        df_cp1[col] = df_cp1[col].fillna('Not Available')
    elif df_cp1[col].dtypes in ('int64', 'float64'):
        df_cp1[col] = df_cp1[col].fillna(0)
df_cp1.isnull().any()

### Creating a backup

In [ ]:
df_cp2 = df_cp1.copy()

## Checking and Validating data

### Unifying proper formatting for pd.Timestamp data type

In [ ]:
df_cp2.loc[:, 'CRASH_DATE'] = pd.to_datetime(df_cp2.loc[:, 'CRASH_DATE'], format='%m/%d/%Y %I:%M:%S %p')

Checking for categories

In [ ]:
col_values = {}
for col in df_cp2.columns.sort_values():
    if df_cp2[col].dtypes == 'object':
        if len(df_cp2[col].unique()) < 20:
            col_values[col] = list(df_cp2[col].unique())
log.info(json.dumps(col_values, indent=4))

To keep with current formatting, switching 'BLOWING SAND, SOIL, DIRT' to '/'

In [ ]:
df_cp2.loc[:, 'WEATHER_CONDITION'] = df_cp2.loc[:, 'WEATHER_CONDITION'].str.replace(', ', '/')
df_cp2.loc[:, 'WEATHER_CONDITION'].unique()

### Creating lists to process

In [ ]:
to_drop = [
    'BEAT_OF_OCCURRENCE',
    'MOST_SEVERE_INJURY', # Repeated in other INJURY_* columns
    'CRASH_HOUR',  # repeated in CRASH_DATE
    'CRASH_DAY_OF_WEEK',  # repeated in CRASH_DATE
    'CRASH_MONTH',  # repeated in CRASH_DATE
    'NUM_UNITS', # Would need clarification what this means
    'LOCATION',
    'REPORT_TYPE'
]

# Convert to Timestamp
to_datetime = [
    'CRASH_DATE',
    'DATE_POLICE_NOTIFIED',
]

to_consolidate = [
    'WEATHER_CONDITION',
    'TRAFFIC_CONTROL_DEVICE',
    'DEVICE_CONDITION', # Main metric
    'FIRST_CRASH_TYPE',
    'ALIGNMENT,'
    'TRAFFICWAY_TYPE',
    'ROADWAY_SURFACE_COND',
    'ROAD_DEFECT',
    'PRIM_CONTRIBUTORY_CAUSE',
    'SEC_CONTRIBUTORY_CAUSE',
    'ROADWAY_SURFACE_COND',
    'LIGHTING_CONDITION',
    'STREET_NAME', # Add this and STREET_NO together
    'STREET_NO' # Add this and STREET_NAME together
]

to_bools_manual = [
    'REPORT_TYPE', # Change to ON_SCENE
    'CRASH_TYPE', # Change to CRASH_SEVERE
    'HIT_AND_RUN_I'
]

to_ints_manual = [
    'DAMAGE'
]

to_ints = [
    'INJURIES_TOTAL',
    'INJURIES_FATAL',
    'INJURIES_INCAPACITATING',
    'INJURIES_NON_INCAPACITATING',
    'INJURIES_REPORTED_NOT_EVIDENT',
    'INJURIES_NO_INDICATION'
]

# No need to check these
valid = [
    'POSTED_SPEED_LIMIT',
    'STREET_DIRECTION',
    'LATITUDE',
    'LONGITUDE',
]

keys2 = to_consolidate + to_bools_manual + to_ints_manual + to_ints + to_datetime + to_drop + valid
diff = set(df_cp2.columns).difference(set(keys2))
log.debug(f'Diff {diff}: {df_cp2.shape[1]}/{len(keys2)}')

### Creating a backup

In [ ]:
df_cp3 = df_cp2.copy()

## Dropping unneeded Columns

In [ ]:
df_cp3 = df_cp3.drop(to_drop, axis=1)

## Begin Cleaning Process

### Stripping whitespaces from DataFrame

### Converting Datetime columns

In [ ]:
for column in to_datetime:
    df_cp3[column] = pd.to_datetime(df_cp3.loc[:, column], format='%m/%d/%Y %I:%M:%S %p')

                 CRASH_DATE DATE_POLICE_NOTIFIED
0       2025-01-14 12:25:00  2025-01-14 12:38:00
1       2025-05-23 09:30:00  2025-05-27 10:40:00
2       2025-04-05 20:00:00  2025-04-05 21:23:00
3       2025-05-23 09:15:00  2025-05-23 09:16:00
4       2025-01-14 08:00:00  2025-01-14 08:45:00
...                     ...                  ...
1020440 2025-10-18 11:42:00  2025-10-18 11:42:00
1020441 2025-10-18 03:50:00  2025-10-19 23:30:00
1020442 2025-10-18 17:08:00  2025-10-19 09:00:00
1020443 2025-10-19 01:50:00  2025-10-19 02:12:00
1020444 2023-06-23 16:30:00  2023-07-01 13:15:00

[1020445 rows x 2 columns]

In [ ]:
df_cp3[to_datetime]

### Converting Ints columns

In [ ]:
df_cp3['DAMAGE']

In [ ]:
# Converting to ints
df_cp3['DAMAGE'] = df_cp3['DAMAGE'].replace('$500 OR LESS', '-$500')
df_cp3['DAMAGE'] = df_cp3['DAMAGE'].replace('$501 - $1,500', '-$1500')
df_cp3['DAMAGE'] = df_cp3['DAMAGE'].replace('OVER $1,500', '+$1500')

In [ ]:
for column in to_ints:
    df_cp3[column] = df_cp3[column].astype(int)

### Converting Bools columns
-1 for Not Available
0 for False
1 for True

In [ ]:
df_cp3.columns

Renaming to CRASH_SEVERE

In [ ]:
df_cp3['CRASH_TYPE'].unique()

/tmp/ipython-input-509751621.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_cp3['CRASH_TYPE'] = df_cp3['CRASH_TYPE'].replace(

0          False
1          False
2          False
3           True
4          False
           ...
1020440     True
1020441    False
1020442    False
1020443    False
1020444     True
Name: CRASH_SEVERE, Length: 1020445, dtype: bool

In [ ]:
df_cp3['CRASH_TYPE'] = df_cp3['CRASH_TYPE'].replace(
    {
        'NO INJURY / DRIVE AWAY': False,
        'INJURY AND / OR TOW DUE TO CRASH': True,
     }
)
df_cp3 = df_cp3.rename({'CRASH_TYPE': 'CRASH_SEVERE'}, axis=1)
df_cp3.loc[:, 'CRASH_SEVERE']

Renaming to HIT_AND_RUN

In [ ]:
df_cp3['HIT_AND_RUN_I'].unique()

/tmp/ipython-input-3362145476.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_cp3['HIT_AND_RUN_I'] = df_cp3['HIT_AND_RUN_I'].replace(

0           True
1           True
2           True
3          False
4          False
           ...
1020440    False
1020441    False
1020442    False
1020443     True
1020444    False
Name: HIT_AND_RUN, Length: 1020445, dtype: bool

In [ ]:
df_cp3['HIT_AND_RUN_I'] = df_cp3['HIT_AND_RUN_I'].replace(
    {
        'Not Available': False,
        'N': False,
        'Y': True,
     }
)
df_cp3 = df_cp3.rename({'HIT_AND_RUN_I': 'HIT_AND_RUN'}, axis=1)
df_cp3.loc[:, 'HIT_AND_RUN']

### Creating a backup

In [ ]:
df_cp4 = df_cp3.copy()

### Converting Consolidate column
A manual process

In [ ]:
df_cp4['WEATHER_CONDITION'].unique()

In [ ]:
df_cp4['WEATHER_CONDITION'] = df_cp4['WEATHER_CONDITION'].replace({
    'CLEAR': 'Clear',
    'RAIN': 'Rain',
    'FREEZING RAIN/DRIZZLE': 'Rain',
    'SNOW': 'Snow',
    'BLOWING SNOW': 'Snow',
    'SEVERE CROSS WIND GATE': 'Windy',
    'BLOWING SAND/SOIL/DIRT': 'Windy',
    'CLOUDY/OVERCAST': 'Cloudy',
    'FOG/SMOKE/HAZE': 'Fog/Smoke',
    'SLEET/HAIL': 'Hail',

    'OTHER': 'Unknown',
    'UNKNOWN': 'Unknown',
 })

array(['TRAFFIC SIGNAL', 'STOP SIGN/FLASHER', 'NO CONTROLS', 'UNKNOWN',
       'OTHER', 'LANE USE MARKING', 'PEDESTRIAN CROSSING SIGN',
       'OTHER REG. SIGN', 'OTHER WARNING SIGN', 'YIELD', 'SCHOOL ZONE',
       'FLASHING CONTROL SIGNAL', 'DELINEATORS', 'NO PASSING',
       'RAILROAD CROSSING GATE', 'POLICE/FLAGMAN', 'RR CROSSING SIGN',
       'BICYCLE CROSSING SIGN', 'OTHER RAILROAD CROSSING'], dtype=object)

In [ ]:
df_cp4['TRAFFIC_CONTROL_DEVICE'].unique()

In [ ]:
df_cp4['TRAFFIC_CONTROL_DEVICE'] = df_cp4['TRAFFIC_CONTROL_DEVICE'].replace({
    'TRAFFIC SIGNAL': 'Traffic Signal',
    'STOP SIGN/FLASHER': 'Stop Sign',
    'FLASHING CONTROL SIGNAL': 'Flashing Signal',

    'YIELD': 'Yield',

    'LANE USE MARKING': 'Lane Marking',
    'OTHER REG. SIGN': 'Regulatory Sign',
    'OTHER WARNING SIGN': 'Warning Sign',

    'BICYCLE CROSSING SIGN': 'Crossing Sign - Bicycle',
    'PEDESTRIAN CROSSING SIGN': 'Crossing Sign - Pedestrian',

    'DELINEATORS': 'Delineators',
    'NO PASSING': 'No Passing Sign',

    'SCHOOL ZONE': 'School Zone',

    'POLICE/FLAGMAN': 'Person',

    'RR CROSSING SIGN': 'Railroad Crossing Sign',
    'RAILROAD CROSSING GATE': 'Railroad Crossing Sign',
    'OTHER RAILROAD CROSSING': 'Railroad Crossing Sign',

    'NO CONTROLS': 'No Controls',

    'OTHER': 'Unknown',
    'UNKNOWN': 'Unknown',
})

array(['FUNCTIONING PROPERLY', 'UNKNOWN', 'NO CONTROLS',
       'FUNCTIONING IMPROPERLY', 'OTHER', 'NOT FUNCTIONING',
       'WORN REFLECTIVE MATERIAL', 'MISSING'], dtype=object)

In [ ]:
df_cp4['DEVICE_CONDITION'].unique()

/tmp/ipython-input-2530443428.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_cp4['DEVICE_CONDITION'] = df_cp4['DEVICE_CONDITION'].replace(

0           True
1          False
2          False
3          False
4           True
           ...
1020440     True
1020441    False
1020442    False
1020443    False
1020444    False
Name: TRAFFIC_DEVICE_FUNCTIONING, Length: 1020445, dtype: bool

In [ ]:
df_cp4['DEVICE_CONDITION'] = df_cp4['DEVICE_CONDITION'].replace(
    {
        'FUNCTIONING PROPERLY': True,
        'UNKNOWN': False,
        'NO CONTROLS': False,
        'FUNCTIONING IMPROPERLY': False,
        'OTHER': False,
        'NOT FUNCTIONING': False,
        'WORN REFLECTIVE MATERIAL': False,
        'MISSING': False,
    }
)
df_cp4 = df_cp4.rename({'DEVICE_CONDITION': 'TRAFFIC_DEVICE_FUNCTIONING'}, axis=1)
df_cp4.loc[:, 'TRAFFIC_DEVICE_FUNCTIONING']

array(['SIDESWIPE SAME DIRECTION', 'TURNING', 'PARKED MOTOR VEHICLE',
       'PEDALCYCLIST', 'REAR END', 'ANGLE',
       'SIDESWIPE OPPOSITE DIRECTION', 'FIXED OBJECT', 'PEDESTRIAN',
       'REAR TO SIDE', 'HEAD ON', 'REAR TO FRONT', 'OTHER OBJECT',
       'OTHER NONCOLLISION', 'REAR TO REAR', 'OVERTURNED', 'ANIMAL',
       'TRAIN'], dtype=object)

In [ ]:
df_cp4['FIRST_CRASH_TYPE'].unique()

array(['DIVIDED - W/MEDIAN (NOT RAISED)', 'NOT DIVIDED', 'FOUR WAY',
       'DIVIDED - W/MEDIAN BARRIER', 'ONE-WAY', 'OTHER', 'PARKING LOT',
       'UNKNOWN', 'T-INTERSECTION', 'TRAFFIC ROUTE', 'ALLEY', 'DRIVEWAY',
       'UNKNOWN INTERSECTION TYPE', 'Y-INTERSECTION',
       'FIVE POINT, OR MORE', 'L-INTERSECTION', 'RAMP',
       'CENTER TURN LANE', 'NOT REPORTED', 'ROUNDABOUT'], dtype=object)

In [ ]:
df_cp4['TRAFFICWAY_TYPE'].unique()

In [ ]:
df_cp4['TRAFFICWAY_TYPE'] = df_cp4['TRAFFICWAY_TYPE'].replace({
    'DIVIDED - W/MEDIAN (NOT RAISED)': 'Divided',
    'DIVIDED - W/MEDIAN BARRIER': 'Divided',
    'NOT DIVIDED': 'Not Divided',

    'T-INTERSECTION': 'Intersection',
    'Y-INTERSECTION': 'Intersection',
    'L-INTERSECTION': 'Intersection',
    'UNKNOWN INTERSECTION TYPE': 'Intersection',

    'FOUR WAY': 'Four-Way',
    'ONE-WAY': 'One-Way',

    'PARKING LOT': 'Parking Lot',
    'DRIVEWAY': 'Driveway',

    'TRAFFIC ROUTE': 'Traffic Route',
    'ALLEY': 'Alley',
    'Ramp': 'Ramp',

    'FIVE POINT, OR MORE': 'Turn Lane',
    'CENTER TURN LANE': 'Turn Lane',
    'ROUNDABOUT': 'Roundabout',

    'NOT REPORTED': 'Unknown',
    'UNKNOWN': 'Unknown',
    'OTHER': 'Unknown',
})

0           Collision
1           Collision
2               Fixed
3          Pedestrian
4           Collision
              ...
1020440     Collision
1020441         Fixed
1020442     Collision
1020443     Collision
1020444     Collision
Name: CRASH_TYPE, Length: 1020445, dtype: object

In [ ]:
# collision, fixed, movement, nonmotorist
df_cp4['FIRST_CRASH_TYPE'] = df_cp4['FIRST_CRASH_TYPE'].replace(
    {
        'SIDESWIPE SAME DIRECTION': 'Collision',
        'SIDESWIPE OPPOSITE DIRECTION': 'Collision',
        'REAR END': 'Collision',
        'REAR TO SIDE': 'Collision',
        'HEAD ON': 'Collision',
        'REAR TO FRONT': 'Collision',
        'OTHER OBJECT': 'Collision',
        'REAR TO REAR': 'Collision',

        'TURNING': 'Collision',
        'ANGLE': 'Collision',
        'OVERTURNED': 'Collision',

        'PARKED MOTOR VEHICLE': 'Fixed',
        'FIXED OBJECT': 'Fixed',
        'TRAIN': 'Fixed',

        'PEDALCYCLIST': 'Pedestrian',
        'PEDESTRIAN': 'Pedestrian',
        'ANIMAL': 'Pedestrian',

        'OTHER NONCOLLISION': 'Other',
    }
)
df_cp4 = df_cp4.rename({'FIRST_CRASH_TYPE': 'CRASH_TYPE'}, axis=1)
df_cp4.loc[:, 'CRASH_TYPE']

array(['NO DEFECTS', 'UNKNOWN', 'SHOULDER DEFECT', 'WORN SURFACE',
       'RUT, HOLES', 'OTHER', 'DEBRIS ON ROADWAY'], dtype=object)

In [ ]:
df_cp4['ROAD_DEFECT'].unique()

/tmp/ipython-input-687373721.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_cp4['ROAD_DEFECT'] = df_cp4['ROAD_DEFECT'].replace(

In [ ]:
df_cp4['ROAD_DEFECT'] = df_cp4['ROAD_DEFECT'].replace(
    {
        'NO DEFECTS': False,
        'UNKNOWN': True,
        'SHOULDER DEFECT': True,
        'WORN SURFACE': True,
        'RUT, HOLES': True,
        'OTHER': True,
        'DEBRIS ON ROADWAY': True
    }
)

In [ ]:
df_cp4['ROADWAY_SURFACE_COND'] = df_cp4['ROADWAY_SURFACE_COND'].replace(
    {
        'SNOW OR SLUSH': 'Snow',
        'DRY': 'Dry',
        'WET': 'Wet',
        'ICE': 'Ice',
        'SAND, MUD, DIRT': 'Dirt/Mud',
        'OTHER': 'Unknown',
        'UNKNOWN': 'Unknown',
    }
)

array(['IMPROPER TURNING/NO SIGNAL', 'IMPROPER OVERTAKING/PASSING',
       'UNABLE TO DETERMINE', 'FOLLOWING TOO CLOSELY',
       'DISREGARDING TRAFFIC SIGNALS', 'IMPROPER LANE USAGE',
       'FAILING TO YIELD RIGHT-OF-WAY', 'NOT APPLICABLE',
       'UNDER THE INFLUENCE OF ALCOHOL/DRUGS (USE WHEN ARREST IS EFFECTED)',
       'FAILING TO REDUCE SPEED TO AVOID CRASH',
       'DRIVING SKILLS/KNOWLEDGE/EXPERIENCE', 'WEATHER',
       'DISREGARDING STOP SIGN', 'IMPROPER BACKING',
       'OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELESS, NEGLIGENT OR AGGRESSIVE MANNER',
       'TURNING RIGHT ON RED', 'EQUIPMENT - VEHICLE CONDITION',
       'PHYSICAL CONDITION OF DRIVER', 'DRIVING ON WRONG SIDE/WRONG WAY',
       'DISREGARDING ROAD MARKINGS',
       'EVASIVE ACTION DUE TO ANIMAL, OBJECT, NONMOTORIST',
       'ROAD ENGINEERING/SURFACE/MARKING DEFECTS',
       'VISION OBSCURED (SIGNS, TREE LIMBS, BUILDINGS, ETC.)',
       'DISTRACTION - FROM OUTSIDE VEHICLE',
       'DISTRACTION - OTHER ELECTRONIC DEVICE (NAVIGATION DEVICE, DVD PLAYER, ETC.)',
       'TEXTING', 'ROAD CONSTRUCTION/MAINTENANCE',
       'HAD BEEN DRINKING (USE WHEN ARREST IS NOT MADE)',
       'DISTRACTION - FROM INSIDE VEHICLE',
       'CELL PHONE USE OTHER THAN TEXTING', 'ANIMAL',
       'DISREGARDING OTHER TRAFFIC SIGNS', 'RELATED TO BUS STOP',
       'DISREGARDING YIELD SIGN', 'OBSTRUCTED CROSSWALKS',
       'PASSING STOPPED SCHOOL BUS',
       'BICYCLE ADVANCING LEGALLY ON RED LIGHT',
       'MOTORCYCLE ADVANCING LEGALLY ON RED LIGHT',
       'EXCEEDING AUTHORIZED SPEED LIMIT',
       'EXCEEDING SAFE SPEED FOR CONDITIONS'], dtype=object)

In [ ]:
df_cp4['PRIM_CONTRIBUTORY_CAUSE'].unique()

In [ ]:
contributory_cause_remap = {
    'IMPROPER TURNING/NO SIGNAL': 'Improper Turning',
    'IMPROPER OVERTAKING/PASSING': 'Improper Overtaking',
    'IMPROPER LANE USAGE': 'Improper Lane Usage',
    'IMPROPER BACKING': 'Improper Backing',

    'DRIVING SKILLS/KNOWLEDGE/EXPERIENCE': 'Inexperience',
    'DRIVING ON WRONG SIDE/WRONG WAY': 'Driving Wrong Way',

    'FOLLOWING TOO CLOSELY': 'Tailgating',

    'DISREGARDING STOP SIGN': 'Ignoring Traffic Sign',
    'DISREGARDING TRAFFIC SIGNALS': 'Ignoring Traffic Sign',
    'DISREGARDING ROAD MARKINGS': 'Ignoring Traffic Sign',
    'DISREGARDING OTHER TRAFFIC SIGNS': 'Ignoring Traffic Sign',
    'DISREGARDING YIELD SIGN': 'Ignoring Traffic Sign',

    'FAILING TO YIELD RIGHT-OF-WAY': 'Failing to Yield Right-of-Way',
    'TURNING RIGHT ON RED': 'Turning on Red',

    'PHYSICAL CONDITION OF DRIVER': 'Driver Physical Condition',

    'UNDER THE INFLUENCE OF ALCOHOL/DRUGS (USE WHEN ARREST IS EFFECTED)': 'Driving Under the Influence (Arrest)',
    'HAD BEEN DRINKING (USE WHEN ARREST IS NOT MADE)': 'Driving Under the Influence (No Arrest)',

    'WEATHER': 'Weather',
    'OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELESS, NEGLIGENT OR AGGRESSIVE MANNER': 'Aggressive Driving',

    'EQUIPMENT - VEHICLE CONDITION': 'Vehicle Condition',


    'VISION OBSCURED (SIGNS, TREE LIMBS, BUILDINGS, ETC.)': 'Vision Obscured',
    'OBSTRUCTED CROSSWALKS': 'Obstacle',
    'ROAD ENGINEERING/SURFACE/MARKING DEFECTS': 'Road Defects',

    'DISTRACTION - FROM OUTSIDE VEHICLE': 'Distracted Driver',
    'DISTRACTION - FROM INSIDE VEHICLE': 'Distracted Driver',
    'DISTRACTION - OTHER ELECTRONIC DEVICE (NAVIGATION DEVICE, DVD PLAYER, ETC.)': 'Distracted Driver',
    'CELL PHONE USE OTHER THAN TEXTING': 'Distracted Driver',
    'TEXTING': 'Driver Texting',

    'ROAD CONSTRUCTION/MAINTENANCE': 'Road Construction',

    'RELATED TO BUS STOP': 'Related to Bus Stop',
    'PASSING STOPPED SCHOOL BUS': 'Passing Stopped School Bus',

    'EVASIVE ACTION DUE TO ANIMAL, OBJECT, NONMOTORIST': 'Evasive Maneuver',
    'ANIMAL': 'Animal',

    'BICYCLE ADVANCING LEGALLY ON RED LIGHT': '2-Wheel Legally Advancing',
    'MOTORCYCLE ADVANCING LEGALLY ON RED LIGHT': '2-Wheel Legally Advancing',

    'FAILING TO REDUCE SPEED TO AVOID CRASH': 'Speeding',
    'EXCEEDING AUTHORIZED SPEED LIMIT': 'Speeding',
    'EXCEEDING SAFE SPEED FOR CONDITIONS': 'Speeding',

    'NOT APPLICABLE': 'Unknown',
    'UNABLE TO DETERMINE': 'Unknown',
 }

array(['IMPROPER OVERTAKING/PASSING', 'UNABLE TO DETERMINE',
       'FOLLOWING TOO CLOSELY', 'NOT APPLICABLE',
       'FAILING TO YIELD RIGHT-OF-WAY',
       'DRIVING SKILLS/KNOWLEDGE/EXPERIENCE', 'WEATHER',
       'EQUIPMENT - VEHICLE CONDITION',
       'FAILING TO REDUCE SPEED TO AVOID CRASH',
       'PHYSICAL CONDITION OF DRIVER', 'IMPROPER LANE USAGE',
       'OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELESS, NEGLIGENT OR AGGRESSIVE MANNER',
       'IMPROPER BACKING', 'DISREGARDING STOP SIGN',
       'UNDER THE INFLUENCE OF ALCOHOL/DRUGS (USE WHEN ARREST IS EFFECTED)',
       'IMPROPER TURNING/NO SIGNAL', 'ROAD CONSTRUCTION/MAINTENANCE',
       'DRIVING ON WRONG SIDE/WRONG WAY', 'DISREGARDING TRAFFIC SIGNALS',
       'EVASIVE ACTION DUE TO ANIMAL, OBJECT, NONMOTORIST',
       'CELL PHONE USE OTHER THAN TEXTING',
       'VISION OBSCURED (SIGNS, TREE LIMBS, BUILDINGS, ETC.)',
       'DISTRACTION - FROM OUTSIDE VEHICLE',
       'ROAD ENGINEERING/SURFACE/MARKING DEFECTS', 'TEXTING',
       'TURNING RIGHT ON RED', 'RELATED TO BUS STOP', 'ANIMAL',
       'DISTRACTION - FROM INSIDE VEHICLE',
       'DISREGARDING OTHER TRAFFIC SIGNS', 'DISREGARDING YIELD SIGN',
       'DISREGARDING ROAD MARKINGS',
       'HAD BEEN DRINKING (USE WHEN ARREST IS NOT MADE)',
       'PASSING STOPPED SCHOOL BUS',
       'MOTORCYCLE ADVANCING LEGALLY ON RED LIGHT',
       'DISTRACTION - OTHER ELECTRONIC DEVICE (NAVIGATION DEVICE, DVD PLAYER, ETC.)',
       'OBSTRUCTED CROSSWALKS', 'EXCEEDING SAFE SPEED FOR CONDITIONS',
       'BICYCLE ADVANCING LEGALLY ON RED LIGHT',
       'EXCEEDING AUTHORIZED SPEED LIMIT'], dtype=object)

In [ ]:
df_cp4['SEC_CONTRIBUTORY_CAUSE'].unique()

In [ ]:
df_cp4['PRIM_CONTRIBUTORY_CAUSE'] = df_cp4['PRIM_CONTRIBUTORY_CAUSE'].replace(contributory_cause_remap)
df_cp4['SEC_CONTRIBUTORY_CAUSE'] = df_cp4['SEC_CONTRIBUTORY_CAUSE'].replace(contributory_cause_remap)

array(['Improper TurningImproper Overtaking',
       'Improper OvertakingUnknown', 'UnknownTailgating',
       'TailgatingFailing to Yield Right-of-Way',
       'Ignoring Traffic SignInexperience', 'Improper Lane UsageWeather',
       'Failing to Yield Right-of-WayVehicle Condition',
       'Driving Under the Influence (Arrest)Speeding',
       'SpeedingDriver Physical Condition',
       'InexperienceImproper Lane Usage', 'WeatherAggressive Driving',
       'Improper BackingImproper Backing',
       'Aggressive DrivingIgnoring Traffic Sign',
       'Turning on RedDriving Under the Influence (Arrest)',
       'Vehicle ConditionImproper Turning',
       'Driver Physical ConditionRoad Construction',
       'Driving Wrong WayDriving Wrong Way',
       'Evasive ManeuverEvasive Maneuver',
       'Road DefectsDistracted Driver', 'Vision ObscuredVision Obscured',
       'Distracted DriverRoad Defects', 'Driver TextingDriver Texting',
       'Road ConstructionTurning on Red',
       'Driving Under the Influence (No Arrest)Related to Bus Stop',
       'AnimalAnimal',
       'Related to Bus StopDriving Under the Influence (No Arrest)',
       'ObstaclePassing Stopped School Bus',
       'Passing Stopped School Bus2-Wheel Legally Advancing',
       '2-Wheel Legally AdvancingObstacle'], dtype=object)

In [ ]:
x = pd.Series(df_cp4['PRIM_CONTRIBUTORY_CAUSE'].unique() + df_cp4['SEC_CONTRIBUTORY_CAUSE'].unique())
x.unique()

array(['DAYLIGHT', 'UNKNOWN', 'DARKNESS, LIGHTED ROAD', 'DARKNESS',
       'DUSK', 'DAWN'], dtype=object)

In [ ]:
df_cp4['LIGHTING_CONDITION'].unique()

In [ ]:
df_cp4['LIGHTING_CONDITION'] = df_cp4['LIGHTING_CONDITION'].replace(
    {
        'DAYLIGHT': "Day",
        'DAWN': "Day",
        'DARKNESS, LIGHTED ROAD': "Night",
        'DARKNESS': "Night",
        'DUSK': "Night",
        'UNKNOWN': "NA"
    }
)

### Renaming a few more columns

In [ ]:
df_cp4 = df_cp4.rename({'ALIGNMENT': 'ROAD_LEVEL', 'DAMAGE': 'DAMAGE_AMT', 'ROADWAY_SURFACE_COND': 'ROAD_CONDITION'}, axis=1)

### Checking street columns

In [ ]:
# 'STREET_NAME',
# 'STREET_NO',
# 'STREET_DIRECTION',

street_names = []

for idx, item in df_cp4['STREET_NAME'].items():
    street_names.append(f'{df_cp4.loc[idx, "STREET_NO"]} {df_cp4.loc[idx, "STREET_NAME"]}')

df_cp4.loc[:, 'STREET_NAME'] = street_names
df_cp4['STREET_NAME'] = df_cp4['STREET_NAME'].str.title()

0             6352 Sheridan Rd
1             3555 Western Ave
2               1005 Drake Ave
3             2901 Division St
4                4001 111Th St
                  ...
1020440    3231 Cumberland Ave
1020441      898 Lake Shore Dr
1020442         2416 Damen Ave
1020443          3700 Broadway
1020444        6799 Kedzie Ave
Name: STREET_NAME, Length: 1020445, dtype: object

In [ ]:
df_cp4['STREET_NAME']

In [ ]:
df_cp4 = df_cp4.drop('STREET_NO', axis=1)

### Ensuring correct datatypes

In [ ]:
df_cp4.info()

01/18/26|07:52 - Chicago Traffic Analysis - ERROR - ON_SCENE

In [ ]:
types = {
    'CRASH_DATE': None,
     'POSTED_SPEED_LIMIT': int,
     'TRAFFIC_CONTROL_DEVICE': None,
     'TRAFFIC_DEVICE_FUNCTIONING': bool,
     'WEATHER_CONDITION': None,
     'LIGHTING_CONDITION': None,
     'CRASH_TYPE': None,
     'TRAFFICWAY_TYPE': None,
     'ROAD_LEVEL': None,
     'ROAD_CONDITION': None,
     'ROAD_DEFECT': bool,
     'ON_SCENE': int,
     'CRASH_SEVERE': bool,
     'HIT_AND_RUN': bool,
     'DAMAGE_AMT': None,
     'DATE_POLICE_NOTIFIED': None,
     'PRIM_CONTRIBUTORY_CAUSE': None,
     'SEC_CONTRIBUTORY_CAUSE': None,
     'INJURIES_TOTAL': None,
     'INJURIES_FATAL': None,
     'INJURIES_INCAPACITATING': None,
     'INJURIES_NON_INCAPACITATING': None,
     'INJURIES_REPORTED_NOT_EVIDENT': None,
     'INJURIES_NO_INDICATION': None,
     'INJURIES_UNKNOWN': int,
     'LATITUDE': None,
     'LONGITUDE': None,
}

for col, typ in types.items():
    if typ is not None:
        try:
            df_cp4[col] = df_cp4[col].astype(dtype=typ)
        except:
            log.error(col)

Prettifying the text

In [ ]:
df_cp4['ROAD_CONDITION'] = df_cp4['ROAD_CONDITION'].str.title()
df_cp4['ROAD_LEVEL'] = df_cp4['ROAD_LEVEL'].str.title()

## Final Cleaned Dataset

In [ ]:
df_CLEANED = df_cp4.copy()

### Reorder columns

In [ ]:
# reordered_columns = [
#     'CRASH_DATE',
#     'DATE_POLICE_NOTIFIED',
#
#     'ON_SCENE',
#     'HIT_AND_RUN',
#
#     'POSTED_SPEED_LIMIT',
#
#     'TRAFFIC_CONTROL_DEVICE',
#     'TRAFFIC_DEVICE_FUNCTIONING',
#     'TRAFFICWAY_TYPE',
#
#     'WEATHER_CONDITION',
#     'LIGHTING_CONDITION',
#     'ROAD_DEFECT',
#     'ROAD_LEVEL',
#     'ROAD_CONDITION',
#
#     'CRASH_TYPE',
#     'CRASH_SEVERE',
#
#     'PRIM_CONTRIBUTORY_CAUSE',
#     'SEC_CONTRIBUTORY_CAUSE',
#
#     'INJURIES_TOTAL',
#     'INJURIES_FATAL',
#     'INJURIES_INCAPACITATING',
#     'INJURIES_NON_INCAPACITATING',
#     'INJURIES_REPORTED_NOT_EVIDENT',
#     'INJURIES_NO_INDICATION',
#     'INJURIES_UNKNOWN',
#
#     'DAMAGE_AMT',
#
#     'STREET_NAME',
#     'STREET_DIRECTION',
#
#     'LATITUDE',
#     'LONGITUDE',
# ]
# df_cpdf_CLEANED5 = df_CLEANED[reordered_columns]
reordered_columns = df_CLEANED.columns.tolist()
reordered_columns.append(reordered_columns.pop(0))
reordered_columns

,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,TRAFFIC_DEVICE_FUNCTIONING,WEATHER_CONDITION,LIGHTING_CONDITION,CRASH_TYPE,TRAFFICWAY_TYPE,ROAD_LEVEL,ROAD_CONDITION,...,INJURIES_TOTAL,INJURIES_FATAL,INJURIES_INCAPACITATING,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,LATITUDE,LONGITUDE,CRASH_RECORD_ID
0,2025-01-14 12:25:00,30,Traffic Signal,True,Snow,Day,Collision,Divided,Straight And Level,Snow,...,0,0,0,0,0,2,0,41.997808,-87.655770,000c4307d8e9b39075cffdd0aade3603e0f96f14e41da9...
1,2025-05-23 09:30:00,30,Stop Sign,False,Unknown,Day,Collision,Divided,Straight And Level,Unknown,...,0,0,0,0,0,2,0,41.946529,-87.688106,027b0b4c21460d3441fd83929abb9673c6fc0c7d575675...
2,2025-04-05 20:00:00,30,No Controls,False,Clear,NA,Fixed,Not Divided,Straight And Level,Dry,...,0,0,0,0,0,1,0,41.899325,-87.715074,04d91dffc94f677358ca47056921ba5c4224320df27ed4...
3,2025-05-23 09:15:00,30,No Controls,False,Clear,Day,Pedestrian,Not Divided,Straight And Level,Dry,...,1,0,0,1,0,2,0,41.902793,-87.699412,0b5603954d84b7341c7cad4f570ea039e85919f3750ccb...
4,2025-01-14 08:00:00,30,Traffic Signal,True,Snow,Day,Collision,Four-Way,Straight And Level,Wet,...,0,0,0,0,0,2,0,41.691207,-87.720555,00bce77960c2faa2a8782a8cac1d6e5715802d6c072a08...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020440,2025-10-18 11:42:00,35,Traffic Signal,True,Cloudy,Day,Collision,Not Divided,Straight And Level,Unknown,...,2,0,0,0,2,1,0,41.938537,-87.835965,5ff5b050ae2079df6addca8431c1bd6e381432ff72ff43...
1020441,2025-10-18 03:50:00,35,No Controls,False,Rain,Night,Fixed,Not Divided,Straight And Level,Wet,...,0,0,0,0,0,1,0,41.899200,-87.618841,7a7963ac15a38f3cf7549397dd053fd7612dd5194de280...
1020442,2025-10-18 17:08:00,30,No Controls,False,Clear,Day,Collision,Not Divided,Straight And Level,Dry,...,0,0,0,0,0,5,0,41.848081,-87.675881,84e546c12fd8fd78ae4e2dc26fdb02d6e8f6c4c92be450...
1020443,2025-10-19 01:50:00,30,Unknown,False,Unknown,NA,Collision,Not Divided,Straight And Level,Unknown,...,0,0,0,0,0,5,0,41.949157,-87.648527,8237045757e7fed5adfb450bd7c8472e28a61d322f86bb...
1020444,2023-06-23 16:30:00,30,Unknown,False,Unknown,Day,Collision,Not Divided,Straight And Level,Unknown,...,1,0,1,0,0,1,0,42.004564,-87.709200,ede74fa6fd507334cd0415d3d53deb535d27d23523cd38...

In [ ]:
df_CLEANED = df_CLEANED[reordered_columns]
df_CLEANED

### Export to CSV

In [ ]:
df_CLEANED.to_csv(path_export)