# Cleaning Messy Employee Dataset
Source https://www.kaggle.com/datasets/desolution01/messy-employee-dataset

In [22]:
import pandas as pd
import importlib

import lib

importlib.reload(lib)

log = lib.getLogger('messy_employee_dataset')

# Reading dataset

In [23]:
filename = '/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/messy_employee_dataset/messy_employee_dataset.csv'
df = lib.read_data(filename, sep=',')

PortfolioLogger.lib.tools: INFO: Encoding: ascii
PortfolioLogger.lib.tools: INFO: Stripping whitespaces from messy_employee_dataset.csv
PortfolioLogger.lib.performance: DEBUG: "<function read_data at 0x10f81c2c0>" took 0.026 secs to complete.

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(8)
memory usage: 88.8+ KB

In [25]:
lib.info(df)

PortfolioLogger.lib.tools: DEBUG: Null INFO ********************************************
PortfolioLogger.lib.tools: INFO: 2/12 columns contain null values
PortfolioLogger.lib.tools: INFO: 235 total null values
PortfolioLogger.lib.tools: INFO: 0 row(s) contain ALL null values
PortfolioLogger.lib.tools: INFO: 0 column(s) contain ALL null values
PortfolioLogger.lib.tools: DEBUG: Risk Rate INFO ***************************************
PortfolioLogger.lib.tools: INFO:
                  error_percent error_count
Employee_ID               0.00%           0
First_Name                0.00%           0
Last_Name                 0.00%           0
Age                      20.69%         211
Department_Region         0.00%           0
Status                    0.00%           0
Join_Date                 0.00%           0
Salary                    2.35%          24
Email                     0.00%           0
Phone                     0.00%           0
Performance_Score         0.00%           0
Remote_Work               0.00%           0
PortfolioLogger.lib.tools: DEBUG: Data Types INFO **************************************
PortfolioLogger.lib.tools: INFO:
                  has_different_types has_<NA>
Employee_ID                     False        0
First_Name                      False        0
Last_Name                       False        0
Age                             False      211
Department_Region               False        0
Status                          False        0
Join_Date                       False        0
Salary                          False       24
Email                           False        0
Phone                           False        0
Performance_Score               False        0
Remote_Work                     False        0
PortfolioLogger.lib.tools: DEBUG:  *****************************************************
/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/lib/tools.py:678: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  result = result.fillna(0)
PortfolioLogger.lib.tools: INFO:
                 Employee_ID  First_Name  Last_Name  Age  Department_Region  \
<NA>                       0           0          0  211                  0
<class 'float'>            0           0          0  809                  0
<class 'str'>           1020        1020       1020    0               1020
<class 'bool'>             0           0          0    0                  0
<class 'int'>              0           0          0    0                  0

                 Status  Join_Date  Salary  Email  Phone  Performance_Score  \
<NA>                  0          0      24      0      0                  0
<class 'float'>       0          0     996      0      0                  0
<class 'str'>      1020       1020       0   1020      0               1020
<class 'bool'>        0          0       0      0      0                  0
<class 'int'>         0          0       0      0   1020                  0

                 Remote_Work
<NA>                       0
<class 'float'>            0
<class 'str'>              0
<class 'bool'>          1020
<class 'int'>              0
PortfolioLogger.lib.tools: DEBUG: Values Counter INFO **********************************
PortfolioLogger.lib.tools: INFO: First_Name: <object> BEGIN
PortfolioLogger.lib.tools: INFO: 	Bob: 133
PortfolioLogger.lib.tools: INFO: 	Alice: 117
PortfolioLogger.lib.tools: INFO: 	Eva: 136
PortfolioLogger.lib.tools: INFO: 	Frank: 142
PortfolioLogger.lib.tools: INFO: 	Charlie: 125
PortfolioLogger.lib.tools: INFO: 	David: 116
PortfolioLogger.lib.tools: INFO: 	Heidi: 111
PortfolioLogger.lib.tools: INFO: 	Grace: 140
PortfolioLogger.lib.tools: INFO: First_Name: <object> END

PortfolioLogger.lib.tools: INFO: Last_Name: <object> BEGIN
PortfolioLogger.lib.tools: INFO: 	Davis: 120
PortfolioLogger.lib.tools: INFO: 	Brown: 148
PortfolioLogger.lib.tools: INFO: 	Jones: 131
PortfolioLogger.lib.tools: INFO: 	Williams: 115
PortfolioLogger.lib.tools: INFO: 	Garcia: 136
PortfolioLogger.lib.tools: INFO: 	Johnson: 118
PortfolioLogger.lib.tools: INFO: 	Miller: 116
PortfolioLogger.lib.tools: INFO: 	Smith: 136
PortfolioLogger.lib.tools: INFO: Last_Name: <object> END

PortfolioLogger.lib.tools: INFO: Status: <object> BEGIN
PortfolioLogger.lib.tools: INFO: 	Active: 352
PortfolioLogger.lib.tools: INFO: 	Pending: 356
PortfolioLogger.lib.tools: INFO: 	Inactive: 312
PortfolioLogger.lib.tools: INFO: Status: <object> END

PortfolioLogger.lib.tools: INFO: Performance_Score: <object> BEGIN
PortfolioLogger.lib.tools: INFO: 	Average: 267
PortfolioLogger.lib.tools: INFO: 	Excellent: 267
PortfolioLogger.lib.tools: INFO: 	Good: 270
PortfolioLogger.lib.tools: INFO: 	Poor: 216
PortfolioLogger.lib.tools: INFO: Performance_Score: <object> END

PortfolioLogger.lib.tools: INFO: Remote_Work: <bool> BEGIN
PortfolioLogger.lib.tools: INFO: 	True: 513
PortfolioLogger.lib.tools: INFO: 	False: 507
PortfolioLogger.lib.tools: INFO: Remote_Work: <bool> END

PortfolioLogger.lib.tools: INFO: Columns ['Employee_ID', 'Age', 'Department_Region', 'Join_Date', 'Salary', 'Email', 'Phone'] exceeded maximum values of 20
PortfolioLogger.lib.performance: DEBUG: "<function info at 0x10f721440>" took 0.085 secs to complete.

## Creating Backup

In [26]:
df_cp1 = df.copy()

# Beginning Cleaning Process

## Set index to column 'Employee_ID'

In [27]:
df_cp1 = df_cp1.set_index('Employee_ID')

In [28]:
df_cp1

,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
Employee_ID,,,,,,,,,,,
EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False
...,...,...,...,...,...,...,...,...,...,...,...
EMP2015,David,Miller,30.0,HR-California,Active,8/19/2023,NaN,david.miller@example.com,-3546212759,Good,True
EMP2016,David,Johnson,30.0,Cloud Tech-Texas,Inactive,11/7/2021,100215.06,david.johnson@example.com,-2508261122,Good,True
EMP2017,Charlie,Williams,40.0,Finance-New York,Active,10/4/2023,114587.11,charlie.williams@example.com,-1261632487,Average,False
EMP2018,Alice,Garcia,30.0,HR-Florida,Inactive,12/16/2024,71318.79,alice.garcia@example.com,-8995729892,Good,True
EMP2019,Heidi,Jones,30.0,DevOps-Illinois,Pending,2/22/2021,77764.24,heidi.jones@example.com,-7629745492,Average,False

## Checking for different dtypes

In [29]:
lib.has_different_dtypes(df_cp1)

                  has_different_types has_<NA>
First_Name                      False        0
Last_Name                       False        0
Age                             False      211
Department_Region               False        0
Status                          False        0
Join_Date                       False        0
Salary                          False       24
Email                           False        0
Phone                           False        0
Performance_Score               False        0
Remote_Work                     False        0

## Checking for NaN values

In [30]:
lib.null_info(df_cp1)

PortfolioLogger.lib.tools: DEBUG: Null INFO ********************************************
PortfolioLogger.lib.tools: INFO: 2/11 columns contain null values
PortfolioLogger.lib.tools: INFO: 235 total null values
PortfolioLogger.lib.tools: INFO: 0 row(s) contain ALL null values
PortfolioLogger.lib.tools: INFO: 0 column(s) contain ALL null values
PortfolioLogger.lib.tools: DEBUG: Risk Rate INFO ***************************************
PortfolioLogger.lib.tools: INFO:
                  error_percent error_count
First_Name                0.00%           0
Last_Name                 0.00%           0
Age                      20.69%         211
Department_Region         0.00%           0
Status                    0.00%           0
Join_Date                 0.00%           0
Salary                    2.35%          24
Email                     0.00%           0
Phone                     0.00%           0
Performance_Score         0.00%           0
Remote_Work               0.00%           0

(              Age     Salary
 Employee_ID
 EMP1001       NaN   65304.66
 EMP1002       NaN   88145.90
 EMP1006       NaN   96288.43
 EMP1009       NaN   76561.88
 EMP1011       NaN   84946.19
 ...           ...        ...
 EMP2006       NaN   77821.79
 EMP2009       NaN   62603.98
 EMP2012      35.0        NaN
 EMP2013       NaN  116680.63
 EMP2015      30.0        NaN

 [233 rows x 2 columns],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [])

In [31]:
df_cp1['Age']

Employee_ID
EMP1000    25.0
EMP1001     NaN
EMP1002     NaN
EMP1003    25.0
EMP1004    25.0
           ...
EMP2015    30.0
EMP2016    30.0
EMP2017    40.0
EMP2018    30.0
EMP2019    30.0
Name: Age, Length: 1020, dtype: float64

### Filling NaN values with filler values

In [32]:
df_cp1['Age'] = lib.fillnull(df_cp1['Age'], default=0)[0].astype(int)

In [33]:
df_cp1['Salary'], filler_values = lib.fillnull(df_cp1['Salary'])

### Verifying we have no more null values

In [34]:
lib.hasnull(df_cp1)

Empty DataFrame
Columns: []
Index: []

## Continuing with Cleaning Process

In [35]:
df_cp1.columns

Index(['First_Name', 'Last_Name', 'Age', 'Department_Region', 'Status',
       'Join_Date', 'Salary', 'Email', 'Phone', 'Performance_Score',
       'Remote_Work'],
      dtype='object')

## Checking for messy string data

In [36]:
for col, series in df_cp1.items():
    log.info(f'{col}: {lib.messy_strings(series)}')

PortfolioLogger.messy_employee_dataset: INFO: First_Name: set()
PortfolioLogger.messy_employee_dataset: INFO: Last_Name: set()
PortfolioLogger.messy_employee_dataset: INFO: Age: set()
PortfolioLogger.messy_employee_dataset: INFO: Department_Region: set()
PortfolioLogger.messy_employee_dataset: INFO: Status: set()
PortfolioLogger.messy_employee_dataset: INFO: Join_Date: {'4/30/2020', '1/29/2023', '1/2/2024', '5/31/2022', '2/24/2022', '10/24/2023', '7/21/2024', '11/7/2021', '10/30/2023', '10/15/2023', '5/2/2024', '3/7/2020', '7/6/2024', '10/10/2023', '3/29/2021', '7/1/2021', '11/21/2024', '8/11/2024', '10/24/2022', '2/3/2021', '2/20/2020', '1/1/2024', '3/7/2021', '12/7/2022', '9/28/2023', '4/24/2022', '9/29/2024', '11/30/2024', '3/17/2023', '1/21/2023', '7/16/2020', '10/5/2021', '8/21/2022', '5/26/2021', '7/8/2020', '8/23/2023', '8/13/2024', '12/12/2024', '10/16/2020', '5/18/2022', '8/17/2023', '7/5/2024', '7/25/2023', '12/31/2023', '9/16/2020', '6/6/2020', '7/17/2023', '3/16/2024', '12/25/2024', '1/2/2021', '1/11/2022', '12/28/2021', '2/3/2022', '5/10/2022', '7/17/2021', '7/7/2020', '10/19/2023', '3/26/2023', '5/23/2023', '7/14/2021', '12/24/2023', '2/8/2022', '1/3/2021', '6/27/2024', '1/30/2020', '9/7/2022', '4/24/2023', '3/25/2024', '1/21/2020', '3/28/2023', '8/21/2023', '7/24/2024', '7/29/2022', '10/10/2020', '7/4/2023', '5/25/2023', '9/19/2024', '3/21/2023', '11/17/2023', '12/13/2023', '4/27/2024', '9/17/2024', '12/21/2022', '7/5/2023', '4/27/2023', '6/26/2024', '7/14/2024', '1/9/2022', '2/3/2023', '7/20/2021', '7/20/2020', '1/20/2021', '8/6/2023', '4/27/2022', '10/11/2021', '2/15/2020', '9/23/2020', '12/14/2023', '3/10/2021', '2/10/2024', '12/2/2024', '8/19/2020', '10/23/2024', '1/30/2023', '12/13/2021', '7/14/2020', '8/16/2023', '4/30/2024', '9/4/2024', '6/2/2023', '10/2/2022', '7/29/2023', '10/9/2023', '8/4/2022', '8/4/2021', '11/21/2020', '12/14/2022', '9/19/2020', '1/28/2023', '11/10/2021', '7/31/2022', '6/8/2024', '7/31/2020', '11/29/2023', '1/5/2022', '4/16/2023', '12/29/2022', '8/24/2023', '10/5/2020', '12/3/2024', '3/31/2024', '6/10/2023', '6/22/2020', '7/19/2020', '7/5/2021', '2/2/2024', '9/28/2020', '1/31/2021', '4/13/2020', '11/19/2021', '4/13/2023', '11/6/2023', '6/21/2022', '5/12/2023', '2/17/2021', '12/15/2020', '11/3/2023', '12/6/2023', '10/26/2021', '11/4/2024', '10/4/2020', '11/1/2022', '1/2/2020', '9/22/2020', '11/21/2023', '12/12/2020', '6/12/2022', '4/28/2024', '5/8/2023', '10/25/2022', '8/11/2020', '2/8/2020', '10/2/2023', '12/3/2022', '5/17/2022', '4/22/2023', '12/5/2022', '11/2/2021', '5/3/2022', '5/21/2022', '6/13/2020', '5/3/2024', '8/19/2022', '9/14/2021', '3/10/2023', '11/14/2024', '11/20/2022', '8/20/2020', '10/24/2024', '6/29/2023', '6/17/2022', '10/14/2020', '11/25/2024', '10/2/2021', '2/12/2024', '9/5/2022', '7/25/2024', '12/9/2020', '8/24/2021', '8/5/2020', '4/19/2024', '8/23/2020', '12/23/2024', '3/25/2023', '5/13/2024', '4/26/2023', '12/2/2021', '8/23/2021', '9/24/2024', '1/16/2023', '2/29/2024', '5/21/2021', '5/4/2021', '4/13/2024', '8/14/2022', '10/1/2020', '12/29/2024', '3/9/2024', '7/2/2022', '4/8/2020', '11/10/2023', '9/8/2023', '7/2/2021', '3/20/2023', '4/19/2020', '5/9/2020', '4/16/2021', '10/31/2023', '6/13/2023', '2/4/2022', '5/24/2021', '1/12/2021', '8/23/2022', '4/14/2024', '10/25/2024', '5/13/2020', '10/22/2021', '11/13/2022', '8/2/2020', '6/3/2022', '1/28/2021', '2/18/2023', '8/5/2024', '6/6/2023', '4/9/2023', '11/26/2021', '9/8/2024', '11/7/2022', '6/13/2022', '7/14/2023', '8/25/2023', '4/17/2022', '3/12/2020', '12/8/2023', '7/13/2021', '2/20/2022', '4/8/2024', '10/25/2021', '1/12/2020', '1/11/2024', '1/7/2021', '8/10/2020', '3/21/2022', '9/7/2021', '2/19/2024', '10/28/2024', '7/8/2024', '10/2/2024', '6/28/2022', '11/30/2023', '11/26/2020', '6/13/2021', '12/9/2022', '1/16/2020', '9/11/2024', '5/4/2020', '12/22/2020', '1/17/2023', '7/12/2020', '5/10/2021', '11/27/2021', '9/8/2022', '10/15/2022', '9/25/2020', '6/26/2021', '7/20/2022', '2/10/2021', '4/21/2020', '1/5/2021', '12/18/2024', '2/2/2021', '9/5/2021', '6/17/2020', '9/6/2022', '3/21/2020', '1/3/2023', '12/7/2023', '8/3/2024', '7/1/2022', '2/11/2023', '12/24/2022', '5/13/2021', '12/6/2022', '2/28/2023', '8/1/2022', '9/11/2020', '4/15/2020', '9/27/2023', '3/4/2020', '11/18/2021', '7/4/2021', '12/23/2022', '6/15/2022', '5/5/2021', '4/19/2023', '3/26/2022', '9/14/2023', '7/22/2024', '3/19/2023', '12/11/2021', '2/5/2024', '9/29/2021', '2/24/2023', '10/26/2024', '2/21/2024', '10/18/2020', '11/26/2022', '1/10/2020', '1/16/2022', '3/31/2023', '5/1/2020', '7/30/2021', '8/10/2021', '3/9/2023', '7/7/2021', '10/18/2021', '10/26/2022', '3/14/2020', '9/16/2021', '2/13/2021', '6/10/2021', '10/11/2024', '3/19/2021', '9/2/2020', '2/18/2022', '5/12/2020', '6/7/2020', '7/6/2023', '9/10/2021', '4/21/2023', '11/23/2020', '1/29/2020', '9/20/2023', '10/29/2022', '5/14/2024', '11/2/2023', '11/19/2020', '3/11/2020', '10/12/2024', '2/26/2024', '3/26/2024', '2/1/2023', '11/23/2021', '5/2/2023', '1/21/2024', '12/26/2024', '1/15/2022', '12/19/2020', '7/9/2021', '6/18/2024', '8/12/2021', '7/30/2022', '7/9/2022', '2/16/2022', '9/17/2022', '2/28/2021', '5/29/2021', '9/5/2024', '10/10/2021', '4/19/2022', '8/26/2024', '3/14/2023', '6/29/2021', '6/16/2020', '11/25/2021', '2/15/2024', '7/16/2024', '10/4/2023', '2/21/2021', '3/13/2022', '4/29/2020', '11/20/2023', '12/10/2024', '8/12/2022', '9/26/2021', '12/13/2022', '2/10/2022', '5/14/2023', '6/5/2020', '1/9/2020', '11/27/2023', '10/4/2024', '7/18/2022', '12/5/2023', '10/8/2020', '8/13/2023', '7/29/2021', '4/2/2021', '6/25/2023', '9/28/2022', '9/24/2020', '1/1/2021', '10/31/2022', '12/25/2023', '10/7/2024', '3/9/2021', '10/5/2024', '3/22/2023', '11/6/2024', '9/25/2021', '5/15/2020', '1/7/2023', '4/15/2024', '10/20/2022', '7/4/2022', '3/3/2022', '11/24/2024', '2/25/2020', '7/31/2024', '8/7/2024', '11/5/2020', '9/19/2023', '3/15/2022', '11/22/2022', '1/9/2021', '10/23/2023', '10/21/2024', '8/7/2022', '1/30/2022', '4/4/2021', '8/20/2022', '5/5/2022', '3/18/2021', '2/13/2023', '2/14/2021', '11/4/2023', '12/28/2022', '11/11/2021', '1/22/2022', '11/11/2024', '2/13/2022', '2/7/2022', '4/1/2022', '9/18/2024', '4/20/2020', '5/24/2020', '8/10/2024', '9/4/2023', '9/5/2020', '1/15/2023', '7/27/2023', '8/18/2024', '5/8/2024', '5/2/2021', '1/14/2020', '6/9/2022', '3/20/2024', '7/28/2024', '7/12/2023', '11/23/2022', '3/29/2023', '2/17/2024', '11/11/2022', '7/27/2024', '3/1/2020', '5/19/2020', '2/22/2020', '11/15/2021', '3/11/2022', '7/22/2022', '11/7/2024', '5/13/2022', '11/15/2023', '4/3/2020', '9/6/2020', '1/13/2021', '4/17/2021', '10/26/2023', '2/13/2020', '8/28/2021', '2/2/2022', '6/23/2020', '5/31/2020', '11/24/2021', '10/28/2022', '4/28/2020', '9/10/2023', '8/27/2024', '1/2/2022', '2/5/2021', '3/13/2023', '4/17/2023', '4/11/2022', '9/21/2022', '3/27/2021', '11/4/2020', '11/28/2024', '8/1/2024', '8/28/2023', '1/26/2024', '2/11/2024', '8/1/2021', '10/31/2021', '3/6/2024', '4/15/2021', '7/1/2020', '6/16/2022', '4/5/2024', '10/22/2023', '5/25/2021', '1/30/2024', '3/4/2023', '3/27/2020', '8/27/2023', '9/18/2023', '8/30/2023', '3/5/2022', '4/18/2021', '12/29/2023', '3/31/2022', '9/29/2023', '6/10/2020', '5/18/2024', '11/28/2023', '6/9/2021', '3/5/2024', '7/17/2022', '4/9/2020', '7/15/2023', '11/22/2021', '6/1/2024', '1/23/2023', '10/10/2022', '7/28/2023', '11/9/2021', '12/19/2024', '10/11/2022', '1/31/2023', '6/15/2024', '9/30/2022', '3/29/2024', '2/28/2024', '11/5/2024', '4/17/2020', '8/3/2022', '1/25/2021', '2/2/2020', '4/11/2020', '2/28/2022', '4/25/2021', '10/30/2020', '4/16/2022', '11/8/2021', '1/29/2021', '5/28/2024', '10/1/2022', '10/23/2021', '3/9/2020', '5/30/2022', '7/23/2024', '11/15/2022', '8/31/2022', '4/23/2021', '2/27/2022', '9/11/2021', '11/17/2021', '5/18/2023', '4/11/2024', '8/20/2021', '8/26/2021', '7/23/2020', '6/5/2023', '11/8/2020', '11/14/2023', '10/9/2024', '11/7/2023', '2/9/2023', '8/4/2023', '12/11/2023', '7/20/2023', '5/2/2020', '10/21/2020', '7/27/2022', '1/24/2022', '8/28/2020', '4/6/2023', '8/18/2022', '1/23/2024', '11/12/2023', '7/3/2021', '12/7/2020', '9/14/2024', '1/8/2022', '9/21/2020', '7/24/2022', '9/4/2021', '8/7/2021', '10/3/2020', '12/12/2023', '3/1/2022', '4/1/2020', '5/5/2023', '2/22/2022', '7/23/2022', '5/3/2023', '11/18/2020', '10/15/2020', '9/1/2021', '7/13/2022', '3/6/2022', '5/27/2021', '10/14/2023', '1/3/2022', '5/29/2020', '8/21/2021', '10/28/2021', '4/22/2020', '8/14/2021', '7/13/2024', '2/14/2024', '1/17/2024', '3/13/2021', '11/10/2024', '11/12/2022', '5/19/2021', '6/5/2024', '8/24/2022', '11/30/2021', '4/30/2023', '10/14/2024', '11/25/2020', '4/23/2023', '5/5/2020', '10/20/2024', '5/10/2020', '3/31/2021', '10/12/2021', '9/27/2022', '3/2/2024'}
PortfolioLogger.messy_employee_dataset: INFO: Salary: set()
PortfolioLogger.messy_employee_dataset: INFO: Email: set()
PortfolioLogger.messy_employee_dataset: INFO: Phone: set()
PortfolioLogger.messy_employee_dataset: INFO: Performance_Score: set()
PortfolioLogger.messy_employee_dataset: INFO: Remote_Work: set()

## Converting 'Join_Date' to Timestamp

In [37]:
pd.to_datetime(df_cp1['Join_Date'])

Employee_ID
EMP1000   2021-04-02
EMP1001   2020-07-10
EMP1002   2023-12-07
EMP1003   2021-11-27
EMP1004   2022-01-05
             ...
EMP2015   2023-08-19
EMP2016   2021-11-07
EMP2017   2023-10-04
EMP2018   2024-12-16
EMP2019   2021-02-22
Name: Join_Date, Length: 1020, dtype: datetime64[ns]

In [38]:
df_cp1['Join_Date'] = pd.to_datetime(df_cp1['Join_Date'])

In [39]:
df_cp1

,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
Employee_ID,,,,,,,,,,,
EMP1000,Bob,Davis,25,DevOps-California,Active,2021-04-02,59767.650000,bob.davis@example.com,-1651623197,Average,True
EMP1001,Bob,Brown,0,Finance-Texas,Active,2020-07-10,65304.660000,bob.brown@example.com,-1898471390,Excellent,True
EMP1002,Alice,Jones,0,Admin-Nevada,Pending,2023-12-07,88145.900000,alice.jones@example.com,-5596363211,Good,True
EMP1003,Eva,Davis,25,Admin-Nevada,Inactive,2021-11-27,69450.990000,eva.davis@example.com,-3476490784,Good,True
EMP1004,Frank,Williams,25,Cloud Tech-Florida,Active,2022-01-05,109324.610000,frank.williams@example.com,-1586734256,Poor,False
...,...,...,...,...,...,...,...,...,...,...,...
EMP2015,David,Miller,30,HR-California,Active,2023-08-19,85155.056396,david.miller@example.com,-3546212759,Good,True
EMP2016,David,Johnson,30,Cloud Tech-Texas,Inactive,2021-11-07,100215.060000,david.johnson@example.com,-2508261122,Good,True
EMP2017,Charlie,Williams,40,Finance-New York,Active,2023-10-04,114587.110000,charlie.williams@example.com,-1261632487,Average,False
EMP2018,Alice,Garcia,30,HR-Florida,Inactive,2024-12-16,71318.790000,alice.garcia@example.com,-8995729892,Good,True
EMP2019,Heidi,Jones,30,DevOps-Illinois,Pending,2021-02-22,77764.240000,heidi.jones@example.com,-7629745492,Average,False

In [40]:
df_cp1['Performance_Score'].unique()

array(['Average', 'Excellent', 'Good', 'Poor'], dtype=object)

# Final Cleaned Dataset

In [41]:
df_clean_data = df_cp1.copy()

## Exporting Dataset

In [42]:
lib.export_data(filename, df_clean_data)

PortfolioLogger.lib.tools: INFO: Exporting 11220 elements (0.46 MB) to /Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/messy_employee_dataset/messy_employee_dataset_CLEAN.csv
PortfolioLogger.lib.performance: DEBUG: "<function export_data at 0x10f81c400>" took 0.007 secs to complete.

PosixPath('/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/messy_employee_dataset/messy_employee_dataset_CLEAN.csv')