# Cleaning Messy IMDB Dataset

In [55]:
import numpy as np
import pandas as pd
from pathlib import Path
import datetime
import logging
import importlib
import chardet

import library

importlib.reload(library)

log = library.logger.getLogger(__name__)
log.setLevel(logging.DEBUG)

In [56]:
library.tools.set_display_options()

## Get the path to the CSV dataset

In [57]:
path = Path().cwd().joinpath('imdb', 'messy_imdb_dataset.csv')

Get the encoding of the CSV file (non UTF-8)

In [58]:
encoding = library.path.detect_encoding(path)
log.debug(f'Detecting Encoding {encoding}')

Detecting Encoding Windows-1252

Read the CSV into a Pandas Dataframe

In [59]:
df = pd.read_csv(path, sep=';', encoding=encoding)
df

,IMBD title ID,Original titlÊ,Release year,Genrë¨,Duration,Country,Content Rating,Director,Unnamed: 8,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,NaN,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,NaN,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,NaN,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,NaN,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,NaN,$ 222831817,1.780.147,"8,9f"
5,tt0167260,The Lord of the Rings: The Return of the King,22 Feb 04,"Action, Adventure, Drama",201,New Zealand,PG-13,Peter Jackson,NaN,$ 1142271098,1.604.280,08.9
6,tt0108052,Schindler's List,1994-03-11,"Biography, Drama, History",Nan,USA,R,Steven Spielberg,NaN,$ 322287794,1.183.248,8.9
7,tt0050083,12 Angry Men,1957-09-04,"Crime, Drama",96,USA,Not Rated,Sidney Lumet,NaN,$ 576,668.473,8.9
8,tt1375666,Inception,2010-09-24,"Action, Adventure, Sci-Fi",148,USA,PG-13,Christopher Nolan,NaN,$ 869784991,2.002.816,8..8
9,tt0137523,Fight Club,10-29-99,Drama,Inf,UK,R,David Fincher,NaN,$ 101218804,1.807.440,8.8
10,tt0109830,Forrest Gump,1994-10-06,"Drama, Romance",142,USA,PG-13,Robert Zemeckis,NaN,$ 678229452,1.755.490,8:8
11,tt0120737,The Lord of the Rings: The Fellowship of the Ring,2002-01-18,"Action, Adventure, Drama",178c,New Zesland,PG-13,Peter Jackson,NaN,$ 887934303,1.619.920,8.8
12,tt0060196,"Il buono, il brutto, il cattivo",23rd December of 1966,Western,161,Italy,Approved,Sergio Leone,NaN,$ 25252481,672.499,8.8
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,tt0133093,The Matrix,1999-05-07,"Action, Sci-Fi",NaN,USA,R,"Lana Wachowski, Lilly Wachowski",NaN,$ 465718588,1.632.315,++8.7
15,tt0167261,The Lord of the Rings: The Two Towers,01/16-03,"Action, Adventure, Drama",179,New Zeland,PG-13,Peter Jackson,NaN,$ 951227416,1.449.778,8.7.
16,tt0080684,Star Wars: Episode V - The Empire Strikes Back,1980-09-19,"Action, Adventure, Fantasy",Not Applicable,USA,PG,Irvin Kershner,NaN,$ 549265501,1.132.073,"8,7e-0"
17,tt0099685,Goodfellas,1990-09-20,"Biography, Crime, Drama",146,USA,R,Martin Scorsese,NaN,$ 46879633,991.505,8.7
18,tt0073486,One Flew Over the Cuckoo's Nest,18/11/1976,Drama,-,USA,R,Milos Forman,NaN,$ 108997629,891.071,8.7
19,tt0816692,Interstellar,2014-11-06,"Adventure, Drama, Sci-Fi",169,USA,PG-13,Christopher Nolan,NaN,$ 696742056,1.449.256,8.6
20,tt0114369,Se7en,1995-12-15,"Crime, Drama, Mystery",127,USA,R,David Fincher,NaN,$ 327333559,1.402.015,8.6
21,tt0102926,The Silence of the Lambs,1991-03-05,"Crime, Drama, Thriller",118,USA,R,Jonathan Demme,NaN,$ 272753884,1.234.134,"8,6"
22,tt0076759,Star Wars,1977-10-20,"Action, Adventure, Fantasy",121,USA,PG,George Lucas,NaN,$ 775768912,1.204.107,8.6
23,tt0120815,Saving Private Ryan,1998-10-30,"Drama, War",169,USA,R,Steven Spielberg,NaN,$ 482349603,1.203.825,8.6
24,tt0120689,The Green Mile,2000-10-03,"Crime, Drama, Fantasy",189,US.,R,Frank Darabont,NaN,$ 286801374,1.112.336,8.6
25,tt0317248,Cidade de Deus,2003-05-09,"Crime, Drama",130,Brazil,R,"Fernando Meirelles, KÃ¡tia Lund",NaN,$ 30680793,685.856,8.6
26,tt0245429,Sen to Chihiro no kamikakushi,2003-04-18,"Animation, Adventure, Family",125,Japan,PG,Hayao Miyazaki,NaN,$ 355467056,626.693,8.6
27,tt0118799,La vita B9 bella,1997-12-20,"Comedy, Drama, Romance",116,Italy1,NaN,Roberto Benigni,NaN,$ 230098753,605.648,8.6
28,tt6751668,Gisaengchung,2019-11-07,"Comedy, Drama, Thriller",132,South Korea,NaN,Bong Joon Ho,NaN,$ 257604912,470.931,8.6
29,tt0038650,It's a Wonderful Life,1948-03-11,"Drama, Family, Fantasy",130,USA,PG,Frank Capra,NaN,$ 6130720,388.310,8.6
30,tt0047478,Shichinin no samurai,1955-08-19,"Action, Adventure, Drama",207,Japan,Unrated,Akira Kurosawa,NaN,$ 322773,307.958,8.6
31,tt0172495,Gladiator,2000-05-19,"Action, Adventure, Drama",155,USA,R,Ridley Scott,NaN,$ 465361176,1.308.193,8.5
32,tt0407887,The Departed,2006-10-27,"Crime, Drama, Thriller",151,USA,R,Martin Scorsese,NaN,$ 291465034,1.159.703,8.5
33,tt0482571,The Prestige,2006-12-22,"Drama, Mystery, Sci-Fi",130,UK,PG-13,Christopher Nolan,NaN,$ 109676311,1.155.723,8.5
34,tt0088763,Back to the Future,1985-10-18,"Adventure, Comedy, Sci-Fi",116,USA,PG,Robert Zemeckis,NaN,$ 388774684,1.027.330,8.5
35,tt0120586,American History X,1999-08-27,Drama,119,USA,R,Tony Kaye,NaN,$ 23875127,1.014.218,8.5
36,tt0110413,LÃ©on,1995-04-07,"Action, Crime, Drama",110,France,NaN,Luc Besson,NaN,$ 19552639,1.007.598,8.5
37,tt0103064,Terminator 2: Judgment Day,1991-12-19,"Action, Sci-Fi",137,USA,R,James Cameron,NaN,$ 520884847,974.970,8.4
38,tt0114814,The Usual Suspects,1995-11-30,"Crime, Mystery, Thriller",106,USA,R,Bryan Singer,NaN,$ 23341568,968.947,8.4
39,tt0110357,The Lion King,1994-11-25,"Animation, Adventure, Drama",88,USA,G,"Roger Allers, Rob Minkoff",NaN,$ 968511805,917.248,8.4
40,tt7286456,Joker,2019-10-03,"Crime, Drama, Thriller",122,USA,NaN,Todd Phillips,NaN,$ 1074251311,855.097,8.4
41,tt1675434,Intouchables,2012-02-24,"Biography, Comedy, Drama",112,France,NaN,"Olivier Nakache, Ã‰ric Toledano",NaN,$ 426588510,736.691,8.4
42,tt0253474,The Pianist,2002-10-25,"Biography, Drama, Music",150,UK,R,Roman Polanski,NaN,$ 120072577,707.942,8.4
43,tt2582802,Whiplash,2015-02-12,"Drama, Music",106,USA,R,Damien Chazelle,NaN,$ 48983260,690.732,8.4
44,tt0054215,Psycho,1960-10-28,"Horror, Mystery, Thriller",109,USA,R,Alfred Hitchcock,NaN,$ 32008644,586.765,8.3
45,tt0034583,Casablanca,21-11-46,"Drama, Romance, War",102,USA,PG,Michael Curtiz,NaN,$ 4374761,509.953,8.3
46,tt0064116,C'era una volta il West,1968-12-21,Western,165,Italy,PG-13,Sergio Leone,NaN,$ 112911,295.220,8.3
47,tt0095327,Hotaru no haka,2015-10-11,"Animation, Drama, War",89,Japan,NaN,Isao Takahata,NaN,$ 516962,225.438,8.3
48,tt0095765,Nuovo Cinema Paradiso,1988-11-17,Drama,155,Italy,NaN,Giuseppe Tornatore,NaN,$ 13826605,223.050,8.3
49,tt0027977,Modern Times,1937-03-12,"Comedy, Drama, Family",87,USA,G,Charles Chaplin,NaN,$ 457688,211.250,8.3
50,tt1345836,The Dark Knight Rises,2012-08-29,"Action, Adventure",164,UK,PG-13,Christopher Nolan,NaN,$ 1081133191,1.480.582,8.3
51,tt1853728,Django Unchained,2013-01-17,"Drama, Western",165,USA,R,Quentin Tarantino,NaN,$ 425368238,1.317.856,8.3
52,tt0209144,Memento,2001-01-19,"Mystery, Thriller",113,USA,R,Christopher Nolan,NaN,$ 39970386,1.098.879,8.2
53,tt0910970,WALLÂ·E,2008-10-17,"Animation, Adventure, Family",98,USA,G,Andrew Stanton,NaN,$ 521311860,974.734,8.2
54,tt0081505,The Shining,1980-12-22,"Drama, Horror",146,UK,R,Stanley Kubrick,NaN,$ 46520613,869.480,8.2
55,tt0082971,Raiders of the Lost Ark,1981-06-12,"Action, Adventure",115,USA,PG,Steven Spielberg,NaN,$ 390133212,865.510,8.2
56,tt4154756,Avengers: Infinity War,2018-04-25,"Action, Adventure, Sci-Fi",149,USA,NaN,"Anthony Russo, Joe Russo",NaN,$ 2048359754,796.486,8.2
57,tt0078748,Alien,1979-10-25,"Horror, Sci-Fi",117,UK,R,Ridley Scott,NaN,$ 108110316,768.874,8.2
58,tt4154796,Avengers: Endgame,2019-04-24,"Action, Adventure, Drama",181,USA,NaN,"Anthony Russo, Joe Russo",NaN,$ 2797800564,754.786,8.2
59,tt0078788,Apocalypse Now,1979-12-18,"Drama, Mystery, War",147,USA,R,Francis Ford Coppola,NaN,$ 91968688,591.251,8.2
60,tt0364569,Oldeuboi,2005-05-06,"Action, Drama, Mystery",120,South Korea,R,Chan-wook Park,NaN,$ 15002116,501.082,8.1
61,tt0057012,Dr. Strangelove or: How I Learned to Stop Worr...,1964-04-03,Comedy,95,UK,PG,Stanley Kubrick,NaN,$ 9443876,441.115,8.1
62,tt0047396,Rear Window,1955-04-14,"Mystery, Thriller",112,USA,NaN,Alfred Hitchcock,NaN,$ 37032034,432.390,8.1
63,tt2380307,Coco,2017-12-28,"Animation, Adventure, Family",105,USA,NaN,"Lee Unkrich, Adrian Molina",NaN,$ 807083670,352.455,8.1
64,tt0405094,Das Leben der Anderen,2007-04-06,"Drama, Mystery, Thriller",137,Germany,R,Florian Henckel von Donnersmarck,NaN,$ 77356942,349.642,8.1
65,tt4633694,Spider-Man: Into the Spider-Verse,2018-12-25,"Animation, Action, Adventure",117,USA,NaN,"Bob Persichetti, Peter Ramsey",NaN,$ 375540831,335.892,8.1
66,tt1187043,3 Idiots,2009-12-25,"Comedy, Drama",170,India,NaN,Rajkumar Hirani,NaN,$ 60262836,332.217,8.1
67,tt0119698,Mononoke-hime,2000-05-19,"Animation, Adventure, Fantasy",134,Japan,PG-13,Hayao Miyazaki,NaN,$ 169785629,331.045,8.0
68,tt0087843,Once Upon a Time in America,1984-09-28,"Crime, Drama",229,USA,R,Sergio Leone,NaN,$ 5472914,302.317,8.0
69,tt0032553,The Great Dictator,1945-06-25,"Comedy, Drama, War",125,USA,NaN,Charles Chaplin,NaN,$ 969879,197.381,8.0
70,tt0043014,Sunset Blvd.,"The 6th of marzo, year 1951","Drama, Film-Noir",110,USA,NaN,Billy Wilder,NaN,$ 299645,195.789,8.0
71,tt0361748,Inglourious Basterds,2009-10-02,"Adventure, Drama, War",153,Germany,R,Quentin Tarantino,NaN,$ 321455689,1.229.958,8.0
72,tt0169547,American Beauty,2000-01-21,Drama,122,USA,R,Sam Mendes,NaN,$ 356296601,1.049.009,8.0
73,tt0112573,Braveheart,1995-12-01,"Biography, Drama, History",178,USA,R,Mel Gibson,NaN,$ 213216216,941.683,7.9
74,tt0086190,Star Wars: Episode VI - Return of the Jedi,1983-10-21,"Action, Adventure, Fantasy",131,USA,PG,Richard Marquand,NaN,$ 475347111,928.036,7.9
75,tt0105236,Reservoir Dogs,1992-10-09,"Crime, Drama, Thriller",99,USA,R,Quentin Tarantino,NaN,$ 2889963,896.551,7.9
76,tt0338013,Eternal Sunshine of the Spotless Mind,2004-10-22,"Drama, Romance, Sci-Fi",108,USA,R,Michel Gondry,NaN,$ 74036715,889.875,7.9
77,tt0114709,Toy Story,1996-03-22,"Animation, Adventure, Comedy",81,USA,G,John Lasseter,NaN,$ 404265438,864.461,7.9
78,tt0119217,Good Will Hunting,1998-03-06,"Drama, Romance",126,USA,R,Gus Van Sant,NaN,$ 225933435,837.379,7.8
79,tt0208092,Snatch,2001-03-16,"Comedy, Crime",104,UK,R,Guy Ritchie,NaN,$ 83557872,766.589,7.8
80,tt0180093,Requiem for a Dream,2000-12-15,Drama,102,USA,R,Darren Aronofsky,NaN,$ 7390108,748.291,7.8
81,tt0066921,A Clockwork Orange,1972-09-07,"Crime, Drama, Sci-Fi",136,UK,NaN,Stanley Kubrick,NaN,$ 26903440,740.301,7.8
82,tt0435761,Toy Story 3,2010-07-07,"Animation, Adventure, Comedy",103,USA,G,Lee Unkrich,NaN,$ 1066969703,739.717,7.8
83,tt0086250,Scarface,1984-02-34,"Crime, Drama",170,USA,R,Brian De Palma,NaN,$ 66023585,721.343,7.8
84,tt0075314,Taxi Driver,1976-13-24,"Crime, Drama",114,USA,R,Martin Scorsese,NaN,$ 28441292,703.264,7.7
85,tt0211915,Le fabuleux destin d'AmÃ©lie Poulain,2002-01-25,"Comedy, Romance",122,France,R,Jean-Pierre Jeunet,NaN,$ 173924742,690.480,7.7
86,tt0093058,Full Metal Jacket,1987-10-09,"Drama, War",116,UK,NaN,Stanley Kubrick,NaN,$ 46357676,658.175,7.7
87,tt0090605,Aliens,1986-09-24,"Action, Adventure, Sci-Fi",137,USA,R,James Cameron,NaN,$ 131384634,639.500,7.7
88,tt0062622,2001: A Space Odyssey,1968-12-12,"Adventure, Sci-Fi",149,UK,G,Stanley Kubrick,NaN,$ 68989547,587.866,7.6
89,tt0033467,Citizen Kane,1948-11-25,"Drama, Mystery",119,USA,NaN,Orson Welles,NaN,$ 1594107,389.322,7.6
90,tt8579674,1917,2020-01-23,"Drama, War",119,USA,NaN,Sam Mendes,NaN,$ 384857224,362.897,7.6
91,tt0086879,Amadeus,1985-02-15,"Biography, Drama, History",160,USA,R,Milos Forman,NaN,$ 52066791,361.028,7.6
92,tt0052357,Vertigo,1958-11-18,"Mystery, Romance, Thriller",128,USA,NaN,Alfred Hitchcock,NaN,$ 7796389,352.786,7.5
93,tt0053125,North by Northwest,1959-10-28,"Adventure, Mystery, Thriller",136,USA,NaN,Alfred Hitchcock,NaN,$ 73446,291.628,7.5
94,tt2106476,Jagten,2012-11-22,Drama,115,Denmark,R,Thomas Vinterberg,NaN,$ 15843274,269.616,7.5
95,tt0056172,Lawrence of Arabia,1963-10-29,"Adventure, Biography, Drama",228,UK,PG,David Lean,NaN,$ 45710874,261.504,7.5
96,tt0070735,The Sting,1974-03-21,"Comedy, Crime, Drama",129,USA,PG,George Roy Hill,NaN,$ 156000000,236.285,7.5
97,tt0082096,Das Boot,1982-03-18,"Adventure, Drama, Thriller",149,West Germany,R,Wolfgang Petersen,NaN,$ 11487676,226.427,7.5
98,tt0059578,Per qualche dollaro in piÃ¹,1965-12-20,Western,132,Italy,NaN,Sergio Leone,NaN,$ 15000000,226.039,7.4
99,tt1832382,Jodaeiye Nader az Simin,2011-10-21,Drama,123,Iran,PG-13,Asghar Farhadi,NaN,$ 22926076,214.165,7.4
100,tt0045152,Singin' in the Rain,1953-02-05,"Comedy, Musical, Romance",103,USA,NaN,Stanley Donen,NaN,$ 1864182,213.152,7.4

## Getting the general info to see what we're working with

In [60]:
log.info(f'General Info {df.info()}')
log.info(f'General Info {df.shape}')

General Info None
General Info (101, 12)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   IMBD title ID   100 non-null    object
 1   Original titlÊ  100 non-null    object
 2   Release year    100 non-null    object
 3   Genrë¨          100 non-null    object
 4   Duration        99 non-null     object
 5   Country         100 non-null    object
 6   Content Rating  77 non-null     object
 7   Director        100 non-null    object
 8   Unnamed: 8      0 non-null      float64
 9   Income          100 non-null    object
 10   Votes          100 non-null    object
 11  Score           100 non-null    object
dtypes: float64(1), object(11)
memory usage: 9.6+ KB

### Checking for null indices and rows

In [61]:
na_items = pd.isnull(df).sum()
log.debug(f'na_items {na_items}')
null_indices = library.tools.get_null_indices(df)
null_columns, null_rows = library.tools.get_all_nulls(df)
log.info(f'Null indices {len(df.columns)}/{len(null_indices)}\n{null_indices}')
log.info(f'Null columns {null_columns}')
log.info(f'Null rows {null_rows}')

na_items IMBD title ID       1
Original titlÊ      1
Release year        1
Genrë¨              1
Duration            2
Country             1
Content Rating     24
Director            1
Unnamed: 8        101
Income              1
 Votes              1
Score               1
dtype: int64
Null indices 12/12
{'IMBD title ID': Index([13], dtype='int64'), 'Original titlÊ': Index([13], dtype='int64'), 'Release year': Index([13], dtype='int64'), 'Genrë¨': Index([13], dtype='int64'), 'Duration': Index([13, 14], dtype='int64'), 'Country': Index([13], dtype='int64'), 'Content Rating': Index([ 13,  27,  28,  36,  40,  41,  47,  48,  56,  58,  62,  63,  65,  66,
        69,  70,  81,  86,  89,  90,  92,  93,  98, 100],
      dtype='int64'), 'Director': Index([13], dtype='int64'), 'Unnamed: 8': Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
      dtype='int64', length=101), 'Income': Index([13], dtype='int64'), ' Votes ': Index([13], dtype='int64'), 'Score': Index([13], dtype='int64')}
Null columns Index(['Unnamed: 8'], dtype='object')
Null rows Index([13], dtype='int64')

## Creating a copy of the data before modifying it

In [62]:
df_checkpoint1 = df.copy()

In [63]:
df_checkpoint1.shape

(101, 12)

### Row 13 and Column 'Unnamed: 8:' are null - dropping them

In [64]:
if not null_columns.empty:
    df_checkpoint1 = df_checkpoint1.drop(columns=null_columns)
if not null_rows.empty:
    df_checkpoint1 = df_checkpoint1.drop(index=null_rows)
# Comparing to make sure it's dropped
log.debug(f'{df.equals(df_checkpoint1)}: {df.shape}/{df_checkpoint1.shape}')

False: (101, 12)/(100, 11)

Ensuring we have no more null values

In [65]:
null_indices = library.tools.get_null_indices(df_checkpoint1)
log.debug(f'null_indices: {null_indices}')

null_indices: {'Duration': Index([14], dtype='int64'), 'Content Rating': Index([ 27,  28,  36,  40,  41,  47,  48,  56,  58,  62,  63,  65,  66,  69,
        70,  81,  86,  89,  90,  92,  93,  98, 100],
      dtype='int64')}

## Dropping the 'IMDB title ID' because we don't need it

In [66]:
df_checkpoint1 = df_checkpoint1.drop('IMBD title ID', axis=1)

# If I wanted to rename the misspelled column
# df_checkpoint1 = df_checkpoint1.rename({'IMBD title ID': 'IMDB title ID'}, axis=1)

In [67]:
df_checkpoint1.columns

Index(['Original titlÊ', 'Release year', 'Genrë¨', 'Duration', 'Country',
       'Content Rating', 'Director', 'Income', ' Votes ', 'Score'],
      dtype='object')

## Cleaning 'Original Title' column

In [68]:
df_checkpoint1 = df_checkpoint1.rename({'Original titlÊ': 'Original Title'}, axis=1)
df_checkpoint1.columns

Index(['Original Title', 'Release year', 'Genrë¨', 'Duration', 'Country',
       'Content Rating', 'Director', 'Income', ' Votes ', 'Score'],
      dtype='object')

## Converting 'Release year' column to DateTime

In [69]:
df_checkpoint1['Release year']

0                       1995-02-10
1                       09 21 1972
2                      23 -07-2008
3                       1975-09-25
4                       1994-10-28
5                        22 Feb 04
6                       1994-03-11
7                       1957-09-04
8                       2010-09-24
9                         10-29-99
10                      1994-10-06
11                      2002-01-18
12          23rd December of 1966
14                      1999-05-07
15                        01/16-03
16                      1980-09-19
17                      1990-09-20
18                      18/11/1976
19                      2014-11-06
20                      1995-12-15
21                      1991-03-05
22                      1977-10-20
23                      1998-10-30
24                      2000-10-03
25                      2003-05-09
26                      2003-04-18
27                      1997-12-20
28                      2019-11-07
29                      1948-03-11
30                      1955-08-19
31                      2000-05-19
32                      2006-10-27
33                      2006-12-22
34                      1985-10-18
35                      1999-08-27
36                      1995-04-07
37                      1991-12-19
38                      1995-11-30
39                      1994-11-25
40                      2019-10-03
41                      2012-02-24
42                      2002-10-25
43                      2015-02-12
44                      1960-10-28
45                        21-11-46
46                      1968-12-21
47                      2015-10-11
48                      1988-11-17
49                      1937-03-12
50                      2012-08-29
51                      2013-01-17
52                      2001-01-19
53                      2008-10-17
54                      1980-12-22
55                      1981-06-12
56                      2018-04-25
57                      1979-10-25
58                      2019-04-24
59                      1979-12-18
60                      2005-05-06
61                      1964-04-03
62                      1955-04-14
63                      2017-12-28
64                      2007-04-06
65                      2018-12-25
66                      2009-12-25
67                      2000-05-19
68                      1984-09-28
69                      1945-06-25
70     The 6th of marzo, year 1951
71                      2009-10-02
72                      2000-01-21
73                      1995-12-01
74                      1983-10-21
75                      1992-10-09
76                      2004-10-22
77                      1996-03-22
78                      1998-03-06
79                      2001-03-16
80                      2000-12-15
81                      1972-09-07
82                      2010-07-07
83                      1984-02-34
84                      1976-13-24
85                      2002-01-25
86                      1987-10-09
87                      1986-09-24
88                      1968-12-12
89                      1948-11-25
90                      2020-01-23
91                      1985-02-15
92                      1958-11-18
93                      1959-10-28
94                      2012-11-22
95                      1963-10-29
96                      1974-03-21
97                      1982-03-18
98                      1965-12-20
99                      2011-10-21
100                     1953-02-05
Name: Release year, dtype: object

Convert to Timestamp

In [70]:
df_checkpoint1.loc[:, 'Release year'] = pd.to_datetime(df_checkpoint1.loc[:, 'Release year'], yearfirst=True, format='mixed', errors='coerce')
df_checkpoint1.loc[:, 'Release year']

0      1995-02-10 00:00:00
1      1972-09-21 00:00:00
2      2008-07-23 00:00:00
3      1975-09-25 00:00:00
4      1994-10-28 00:00:00
5      2022-02-04 00:00:00
6      1994-03-11 00:00:00
7      1957-09-04 00:00:00
8      2010-09-24 00:00:00
9      1999-10-29 00:00:00
10     1994-10-06 00:00:00
11     2002-01-18 00:00:00
12     1966-12-23 00:00:00
14     1999-05-07 00:00:00
15     2003-01-16 00:00:00
16     1980-09-19 00:00:00
17     1990-09-20 00:00:00
18     1976-11-18 00:00:00
19     2014-11-06 00:00:00
20     1995-12-15 00:00:00
21     1991-03-05 00:00:00
22     1977-10-20 00:00:00
23     1998-10-30 00:00:00
24     2000-10-03 00:00:00
25     2003-05-09 00:00:00
26     2003-04-18 00:00:00
27     1997-12-20 00:00:00
28     2019-11-07 00:00:00
29     1948-03-11 00:00:00
30     1955-08-19 00:00:00
31     2000-05-19 00:00:00
32     2006-10-27 00:00:00
33     2006-12-22 00:00:00
34     1985-10-18 00:00:00
35     1999-08-27 00:00:00
36     1995-04-07 00:00:00
37     1991-12-19 00:00:00
38     1995-11-30 00:00:00
39     1994-11-25 00:00:00
40     2019-10-03 00:00:00
41     2012-02-24 00:00:00
42     2002-10-25 00:00:00
43     2015-02-12 00:00:00
44     1960-10-28 00:00:00
45     2046-11-21 00:00:00
46     1968-12-21 00:00:00
47     2015-10-11 00:00:00
48     1988-11-17 00:00:00
49     1937-03-12 00:00:00
50     2012-08-29 00:00:00
51     2013-01-17 00:00:00
52     2001-01-19 00:00:00
53     2008-10-17 00:00:00
54     1980-12-22 00:00:00
55     1981-06-12 00:00:00
56     2018-04-25 00:00:00
57     1979-10-25 00:00:00
58     2019-04-24 00:00:00
59     1979-12-18 00:00:00
60     2005-05-06 00:00:00
61     1964-04-03 00:00:00
62     1955-04-14 00:00:00
63     2017-12-28 00:00:00
64     2007-04-06 00:00:00
65     2018-12-25 00:00:00
66     2009-12-25 00:00:00
67     2000-05-19 00:00:00
68     1984-09-28 00:00:00
69     1945-06-25 00:00:00
70                     NaT
71     2009-10-02 00:00:00
72     2000-01-21 00:00:00
73     1995-12-01 00:00:00
74     1983-10-21 00:00:00
75     1992-10-09 00:00:00
76     2004-10-22 00:00:00
77     1996-03-22 00:00:00
78     1998-03-06 00:00:00
79     2001-03-16 00:00:00
80     2000-12-15 00:00:00
81     1972-09-07 00:00:00
82     2010-07-07 00:00:00
83                     NaT
84                     NaT
85     2002-01-25 00:00:00
86     1987-10-09 00:00:00
87     1986-09-24 00:00:00
88     1968-12-12 00:00:00
89     1948-11-25 00:00:00
90     2020-01-23 00:00:00
91     1985-02-15 00:00:00
92     1958-11-18 00:00:00
93     1959-10-28 00:00:00
94     2012-11-22 00:00:00
95     1963-10-29 00:00:00
96     1974-03-21 00:00:00
97     1982-03-18 00:00:00
98     1965-12-20 00:00:00
99     2011-10-21 00:00:00
100    1953-02-05 00:00:00
Name: Release year, dtype: object

Check NaT/null values in conversion

In [71]:
x = df_checkpoint1['Release year'].isnull()
null_indices = df_checkpoint1.loc[:, 'Release year'][x].index
df.loc[null_indices, 'Release year']

70    The 6th of marzo, year 1951
83                     1984-02-34
84                     1976-13-24
Name: Release year, dtype: object

Fix index 70

In [72]:
df_checkpoint1.loc[70, 'Release year'] = pd.Timestamp(1951, 3, 6)
df_checkpoint1.loc[70, 'Release year']

Timestamp('1951-03-06 00:00:00')

Fix index 83 and 84 as 0 Timestamps

In [73]:
filler_release_year = pd.Timestamp.min

In [74]:
# df_checkpoint1.loc[83, 'Release year'] = filler_release_year
# df_checkpoint1.loc[84, 'Release year'] = filler_release_year
df_checkpoint1['Release year']

0      1995-02-10 00:00:00
1      1972-09-21 00:00:00
2      2008-07-23 00:00:00
3      1975-09-25 00:00:00
4      1994-10-28 00:00:00
5      2022-02-04 00:00:00
6      1994-03-11 00:00:00
7      1957-09-04 00:00:00
8      2010-09-24 00:00:00
9      1999-10-29 00:00:00
10     1994-10-06 00:00:00
11     2002-01-18 00:00:00
12     1966-12-23 00:00:00
14     1999-05-07 00:00:00
15     2003-01-16 00:00:00
16     1980-09-19 00:00:00
17     1990-09-20 00:00:00
18     1976-11-18 00:00:00
19     2014-11-06 00:00:00
20     1995-12-15 00:00:00
21     1991-03-05 00:00:00
22     1977-10-20 00:00:00
23     1998-10-30 00:00:00
24     2000-10-03 00:00:00
25     2003-05-09 00:00:00
26     2003-04-18 00:00:00
27     1997-12-20 00:00:00
28     2019-11-07 00:00:00
29     1948-03-11 00:00:00
30     1955-08-19 00:00:00
31     2000-05-19 00:00:00
32     2006-10-27 00:00:00
33     2006-12-22 00:00:00
34     1985-10-18 00:00:00
35     1999-08-27 00:00:00
36     1995-04-07 00:00:00
37     1991-12-19 00:00:00
38     1995-11-30 00:00:00
39     1994-11-25 00:00:00
40     2019-10-03 00:00:00
41     2012-02-24 00:00:00
42     2002-10-25 00:00:00
43     2015-02-12 00:00:00
44     1960-10-28 00:00:00
45     2046-11-21 00:00:00
46     1968-12-21 00:00:00
47     2015-10-11 00:00:00
48     1988-11-17 00:00:00
49     1937-03-12 00:00:00
50     2012-08-29 00:00:00
51     2013-01-17 00:00:00
52     2001-01-19 00:00:00
53     2008-10-17 00:00:00
54     1980-12-22 00:00:00
55     1981-06-12 00:00:00
56     2018-04-25 00:00:00
57     1979-10-25 00:00:00
58     2019-04-24 00:00:00
59     1979-12-18 00:00:00
60     2005-05-06 00:00:00
61     1964-04-03 00:00:00
62     1955-04-14 00:00:00
63     2017-12-28 00:00:00
64     2007-04-06 00:00:00
65     2018-12-25 00:00:00
66     2009-12-25 00:00:00
67     2000-05-19 00:00:00
68     1984-09-28 00:00:00
69     1945-06-25 00:00:00
70     1951-03-06 00:00:00
71     2009-10-02 00:00:00
72     2000-01-21 00:00:00
73     1995-12-01 00:00:00
74     1983-10-21 00:00:00
75     1992-10-09 00:00:00
76     2004-10-22 00:00:00
77     1996-03-22 00:00:00
78     1998-03-06 00:00:00
79     2001-03-16 00:00:00
80     2000-12-15 00:00:00
81     1972-09-07 00:00:00
82     2010-07-07 00:00:00
83                     NaT
84                     NaT
85     2002-01-25 00:00:00
86     1987-10-09 00:00:00
87     1986-09-24 00:00:00
88     1968-12-12 00:00:00
89     1948-11-25 00:00:00
90     2020-01-23 00:00:00
91     1985-02-15 00:00:00
92     1958-11-18 00:00:00
93     1959-10-28 00:00:00
94     2012-11-22 00:00:00
95     1963-10-29 00:00:00
96     1974-03-21 00:00:00
97     1982-03-18 00:00:00
98     1965-12-20 00:00:00
99     2011-10-21 00:00:00
100    1953-02-05 00:00:00
Name: Release year, dtype: object

In [75]:
df_checkpoint1.columns

Index(['Original Title', 'Release year', 'Genrë¨', 'Duration', 'Country',
       'Content Rating', 'Director', 'Income', ' Votes ', 'Score'],
      dtype='object')

## Cleaning 'Genre' column

Renaming the 'Genrë¨' column to Genre

In [76]:
df_checkpoint1 = df_checkpoint1.rename({'Genrë¨': 'Genre'}, axis=1)

Checking for any odd values

In [77]:
result = ''
for each in df_checkpoint1.loc[:, 'Genre'].unique():
    # log.debug(f'{each}')
    result += each + ', '
set(result.split(', ')[:-1])

{'Action',
 'Adventure',
 'Animation',
 'Biography',
 'Comedy',
 'Crime',
 'Drama',
 'Family',
 'Fantasy',
 'Film-Noir',
 'History',
 'Horror',
 'Music',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western'}

In [78]:
df_checkpoint1.columns

Index(['Original Title', 'Release year', 'Genre', 'Duration', 'Country',
       'Content Rating', 'Director', 'Income', ' Votes ', 'Score'],
      dtype='object')

## Cleaning 'Duration' column

In [79]:
df_checkpoint1.loc[:, 'Duration']

0                 142
1                 175
2                 152
3                 220
4
5                 201
6                 Nan
7                  96
8                 148
9                 Inf
10                142
11               178c
12                161
14                NaN
15                179
16     Not Applicable
17                146
18                  -
19                169
20                127
21                118
22                121
23                169
24                189
25                130
26                125
27                116
28                132
29                130
30                207
31                155
32                151
33                130
34                116
35                119
36                110
37                137
38                106
39                 88
40                122
41                112
42                150
43                106
44                109
45                102
46                165
47                 89
48                155
49                 87
50                164
51                165
52                113
53                 98
54                146
55                115
56                149
57                117
58                181
59                147
60                120
61                 95
62                112
63                105
64                137
65                117
66                170
67                134
68                229
69                125
70                110
71                153
72                122
73                178
74                131
75                 99
76                108
77                 81
78                126
79                104
80                102
81                136
82                103
83                170
84                114
85                122
86                116
87                137
88                149
89                119
90                119
91                160
92                128
93                136
94                115
95                228
96                129
97                149
98                132
99                123
100               103
Name: Duration, dtype: object

Filler value for duration

In [80]:
filler_duration = 0

In [81]:
df_checkpoint1.loc[:, 'Duration'] = pd.to_numeric(df_checkpoint1['Duration'], errors='coerce', downcast='integer')

In [82]:
df_checkpoint1.loc[:, 'Duration'] = df_checkpoint1.loc[:, 'Duration'].infer_objects().fillna(filler_duration)
df_checkpoint1.loc[:, 'Duration']

0      142.0
1      175.0
2      152.0
3      220.0
4        0.0
5      201.0
6        0.0
7       96.0
8      148.0
9        inf
10     142.0
11       0.0
12     161.0
14       0.0
15     179.0
16       0.0
17     146.0
18       0.0
19     169.0
20     127.0
21     118.0
22     121.0
23     169.0
24     189.0
25     130.0
26     125.0
27     116.0
28     132.0
29     130.0
30     207.0
31     155.0
32     151.0
33     130.0
34     116.0
35     119.0
36     110.0
37     137.0
38     106.0
39      88.0
40     122.0
41     112.0
42     150.0
43     106.0
44     109.0
45     102.0
46     165.0
47      89.0
48     155.0
49      87.0
50     164.0
51     165.0
52     113.0
53      98.0
54     146.0
55     115.0
56     149.0
57     117.0
58     181.0
59     147.0
60     120.0
61      95.0
62     112.0
63     105.0
64     137.0
65     117.0
66     170.0
67     134.0
68     229.0
69     125.0
70     110.0
71     153.0
72     122.0
73     178.0
74     131.0
75      99.0
76     108.0
77      81.0
78     126.0
79     104.0
80     102.0
81     136.0
82     103.0
83     170.0
84     114.0
85     122.0
86     116.0
87     137.0
88     149.0
89     119.0
90     119.0
91     160.0
92     128.0
93     136.0
94     115.0
95     228.0
96     129.0
97     149.0
98     132.0
99     123.0
100    103.0
Name: Duration, dtype: object

In [83]:
df_checkpoint1.loc[9, 'Duration'] = filler_duration
df_checkpoint1.loc[:, 'Duration'] = df_checkpoint1.loc[:, 'Duration'].astype(int)
df_checkpoint1.loc[:, 'Duration']

0      142
1      175
2      152
3      220
4        0
5      201
6        0
7       96
8      148
9        0
10     142
11       0
12     161
14       0
15     179
16       0
17     146
18       0
19     169
20     127
21     118
22     121
23     169
24     189
25     130
26     125
27     116
28     132
29     130
30     207
31     155
32     151
33     130
34     116
35     119
36     110
37     137
38     106
39      88
40     122
41     112
42     150
43     106
44     109
45     102
46     165
47      89
48     155
49      87
50     164
51     165
52     113
53      98
54     146
55     115
56     149
57     117
58     181
59     147
60     120
61      95
62     112
63     105
64     137
65     117
66     170
67     134
68     229
69     125
70     110
71     153
72     122
73     178
74     131
75      99
76     108
77      81
78     126
79     104
80     102
81     136
82     103
83     170
84     114
85     122
86     116
87     137
88     149
89     119
90     119
91     160
92     128
93     136
94     115
95     228
96     129
97     149
98     132
99     123
100    103
Name: Duration, dtype: object

## Creating a backup

In [84]:
df_checkpoint2 = df_checkpoint1.copy()

## Cleaning 'Country' column

In [85]:
df_checkpoint2.loc[:, 'Country'].unique()

array(['USA', 'US', 'New Zealand', 'UK', 'New Zesland', 'Italy',
       'New Zeland', 'US.', 'Brazil', 'Japan', 'Italy1', 'South Korea',
       'France', 'Germany', 'India', 'Denmark', 'West Germany', 'Iran'],
      dtype=object)

Need to fix 'New Zealand',
 'New Zeland',
 'New Zesland', and 'US',
 'US.',
 'USA',

In [86]:
# x = df_checkpoint2.loc[:, 'Country'].replace(['New Zeland', 'New Zesland'], 'New Zealand')
replace_values = {
    'New Zeland': 'New Zealand',
    'New Zesland': 'New Zealand',
    'US': 'USA',
    'US.': 'USA'
}
df_checkpoint2.loc[:, 'Country'] = df_checkpoint2.loc[:, 'Country'].replace(replace_values)
df_checkpoint2.loc[:, 'Country']

0               USA
1               USA
2               USA
3               USA
4               USA
5       New Zealand
6               USA
7               USA
8               USA
9                UK
10              USA
11      New Zealand
12            Italy
14              USA
15      New Zealand
16              USA
17              USA
18              USA
19              USA
20              USA
21              USA
22              USA
23              USA
24              USA
25           Brazil
26            Japan
27           Italy1
28      South Korea
29              USA
30            Japan
31              USA
32              USA
33               UK
34              USA
35              USA
36           France
37              USA
38              USA
39              USA
40              USA
41           France
42               UK
43              USA
44              USA
45              USA
46            Italy
47            Japan
48            Italy
49              USA
50               UK
51              USA
52              USA
53              USA
54               UK
55              USA
56              USA
57               UK
58              USA
59              USA
60      South Korea
61               UK
62              USA
63              USA
64          Germany
65              USA
66            India
67            Japan
68              USA
69              USA
70              USA
71          Germany
72              USA
73              USA
74              USA
75              USA
76              USA
77              USA
78              USA
79               UK
80              USA
81               UK
82              USA
83              USA
84              USA
85           France
86               UK
87              USA
88               UK
89              USA
90              USA
91              USA
92              USA
93              USA
94          Denmark
95               UK
96              USA
97     West Germany
98            Italy
99             Iran
100             USA
Name: Country, dtype: object

## Cleaning 'Content Rating' column

In [87]:
df_checkpoint2.loc[:, 'Content Rating'].unique()

array(['R', 'PG-13', 'Not Rated', 'Approved', 'PG', nan, 'Unrated', 'G'],
      dtype=object)

Filler variable for null 'Content Rating' values

In [88]:
filler_content_rating = 'Not Rated'

In [89]:
df_checkpoint2.loc[:, 'Content Rating'] = df_checkpoint2['Content Rating'].fillna(filler_content_rating)
df_checkpoint2.loc[:, 'Content Rating']

0              R
1              R
2          PG-13
3              R
4              R
5          PG-13
6              R
7      Not Rated
8          PG-13
9              R
10         PG-13
11         PG-13
12      Approved
14             R
15         PG-13
16            PG
17             R
18             R
19         PG-13
20             R
21             R
22            PG
23             R
24             R
25             R
26            PG
27     Not Rated
28     Not Rated
29            PG
30       Unrated
31             R
32             R
33         PG-13
34            PG
35             R
36     Not Rated
37             R
38             R
39             G
40     Not Rated
41     Not Rated
42             R
43             R
44             R
45            PG
46         PG-13
47     Not Rated
48     Not Rated
49             G
50         PG-13
51             R
52             R
53             G
54             R
55            PG
56     Not Rated
57             R
58     Not Rated
59             R
60             R
61            PG
62     Not Rated
63     Not Rated
64             R
65     Not Rated
66     Not Rated
67         PG-13
68             R
69     Not Rated
70     Not Rated
71             R
72             R
73             R
74            PG
75             R
76             R
77             G
78             R
79             R
80             R
81     Not Rated
82             G
83             R
84             R
85             R
86     Not Rated
87             R
88             G
89     Not Rated
90     Not Rated
91             R
92     Not Rated
93     Not Rated
94             R
95            PG
96            PG
97             R
98     Not Rated
99         PG-13
100    Not Rated
Name: Content Rating, dtype: object

In [90]:
df_checkpoint2.loc[:, 'Content Rating'].unique()

array(['R', 'PG-13', 'Not Rated', 'Approved', 'PG', 'Unrated', 'G'],
      dtype=object)

In [91]:
df_checkpoint2.columns

Index(['Original Title', 'Release year', 'Genre', 'Duration', 'Country',
       'Content Rating', 'Director', 'Income', ' Votes ', 'Score'],
      dtype='object')

## Cleaning 'Director' column

In [92]:
df_checkpoint2.loc[:, 'Director'].unique()

array(['Frank Darabont', 'Francis Ford Coppola', 'Christopher Nolan',
       'Quentin Tarantino', 'Peter Jackson', 'Steven Spielberg',
       'Sidney Lumet', 'David Fincher', 'Robert Zemeckis', 'Sergio Leone',
       'Lana Wachowski, Lilly Wachowski', 'Irvin Kershner',
       'Martin Scorsese', 'Milos Forman', 'Jonathan Demme',
       'George Lucas', 'Fernando Meirelles, KÃ¡tia Lund',
       'Hayao Miyazaki', 'Roberto Benigni', 'Bong Joon Ho', 'Frank Capra',
       'Akira Kurosawa', 'Ridley Scott', 'Tony Kaye', 'Luc Besson',
       'James Cameron', 'Bryan Singer', 'Roger Allers, Rob Minkoff',
       'Todd Phillips', 'Olivier Nakache, Ã‰ric Toledano',
       'Roman Polanski', 'Damien Chazelle', 'Alfred Hitchcock',
       'Michael Curtiz', 'Isao Takahata', 'Giuseppe Tornatore',
       'Charles Chaplin', 'Andrew Stanton', 'Stanley Kubrick',
       'Anthony Russo, Joe Russo', 'Chan-wook Park',
       'Lee Unkrich, Adrian Molina', 'Florian Henckel von Donnersmarck',
       'Bob Persichetti, Peter Ramsey', 'Rajkumar Hirani', 'Billy Wilder',
       'Sam Mendes', 'Mel Gibson', 'Richard Marquand', 'Michel Gondry',
       'John Lasseter', 'Gus Van Sant', 'Guy Ritchie', 'Darren Aronofsky',
       'Lee Unkrich', 'Brian De Palma', 'Jean-Pierre Jeunet',
       'Orson Welles', 'Thomas Vinterberg', 'David Lean',
       'George Roy Hill', 'Wolfgang Petersen', 'Asghar Farhadi',
       'Stanley Donen'], dtype=object)

In [93]:
df_checkpoint2.columns

Index(['Original Title', 'Release year', 'Genre', 'Duration', 'Country',
       'Content Rating', 'Director', 'Income', ' Votes ', 'Score'],
      dtype='object')

## Cleaning 'Income' column

In [94]:
df_checkpoint2.loc[:, 'Income'] = df_checkpoint2.loc[:, 'Income'].str.replace('$ ', '')
df_checkpoint2.loc[:, 'Income']

0         28815245
1        246120974
2       1005455211
3      4o8,035,783
4        222831817
5       1142271098
6        322287794
7              576
8        869784991
9        101218804
10       678229452
11       887934303
12        25252481
14       465718588
15       951227416
16       549265501
17        46879633
18       108997629
19       696742056
20       327333559
21       272753884
22       775768912
23       482349603
24       286801374
25        30680793
26       355467056
27       230098753
28       257604912
29         6130720
30          322773
31       465361176
32       291465034
33       109676311
34       388774684
35        23875127
36        19552639
37       520884847
38        23341568
39       968511805
40      1074251311
41       426588510
42       120072577
43        48983260
44        32008644
45         4374761
46          112911
47          516962
48        13826605
49          457688
50      1081133191
51       425368238
52        39970386
53       521311860
54        46520613
55       390133212
56      2048359754
57       108110316
58      2797800564
59        91968688
60        15002116
61         9443876
62        37032034
63       807083670
64        77356942
65       375540831
66        60262836
67       169785629
68         5472914
69          969879
70          299645
71       321455689
72       356296601
73       213216216
74       475347111
75         2889963
76        74036715
77       404265438
78       225933435
79        83557872
80         7390108
81        26903440
82      1066969703
83        66023585
84        28441292
85       173924742
86        46357676
87       131384634
88        68989547
89         1594107
90       384857224
91        52066791
92         7796389
93           73446
94        15843274
95        45710874
96       156000000
97        11487676
98        15000000
99        22926076
100        1864182
Name: Income, dtype: object

Manually fix bad value

In [95]:
df_checkpoint2.loc[3, 'Income'] = 408035783

Cast to int

In [96]:
df_checkpoint2.loc[:, 'Income'] = df_checkpoint2.loc[:, 'Income'].astype(int)

In [97]:
df_checkpoint2.columns

Index(['Original Title', 'Release year', 'Genre', 'Duration', 'Country',
       'Content Rating', 'Director', 'Income', ' Votes ', 'Score'],
      dtype='object')

## Creating a backup

In [98]:
df_checkpoint3 = df_checkpoint2.copy()

## Cleaning 'Votes' column

In [99]:
df_checkpoint3.loc[:, ' Votes ']

0      2.278.845
1      1.572.674
2      2.241.615
3      1.098.714
4      1.780.147
5      1.604.280
6      1.183.248
7        668.473
8      2.002.816
9      1.807.440
10     1.755.490
11     1.619.920
12       672.499
14     1.632.315
15     1.449.778
16     1.132.073
17       991.505
18       891.071
19     1.449.256
20     1.402.015
21     1.234.134
22     1.204.107
23     1.203.825
24     1.112.336
25       685.856
26       626.693
27       605.648
28       470.931
29       388.310
30       307.958
31     1.308.193
32     1.159.703
33     1.155.723
34     1.027.330
35     1.014.218
36     1.007.598
37       974.970
38       968.947
39       917.248
40       855.097
41       736.691
42       707.942
43       690.732
44       586.765
45       509.953
46       295.220
47       225.438
48       223.050
49       211.250
50     1.480.582
51     1.317.856
52     1.098.879
53       974.734
54       869.480
55       865.510
56       796.486
57       768.874
58       754.786
59       591.251
60       501.082
61       441.115
62       432.390
63       352.455
64       349.642
65       335.892
66       332.217
67       331.045
68       302.317
69       197.381
70       195.789
71     1.229.958
72     1.049.009
73       941.683
74       928.036
75       896.551
76       889.875
77       864.461
78       837.379
79       766.589
80       748.291
81       740.301
82       739.717
83       721.343
84       703.264
85       690.480
86       658.175
87       639.500
88       587.866
89       389.322
90       362.897
91       361.028
92       352.786
93       291.628
94       269.616
95       261.504
96       236.285
97       226.427
98       226.039
99       214.165
100      213.152
Name:  Votes , dtype: object

Rename ' Votes ' column to 'Votes'

In [100]:
df_checkpoint3 = df_checkpoint3.rename({' Votes ': 'Votes'}, axis=1)

In [101]:
df_checkpoint3.loc[:, 'Votes']

0      2.278.845
1      1.572.674
2      2.241.615
3      1.098.714
4      1.780.147
5      1.604.280
6      1.183.248
7        668.473
8      2.002.816
9      1.807.440
10     1.755.490
11     1.619.920
12       672.499
14     1.632.315
15     1.449.778
16     1.132.073
17       991.505
18       891.071
19     1.449.256
20     1.402.015
21     1.234.134
22     1.204.107
23     1.203.825
24     1.112.336
25       685.856
26       626.693
27       605.648
28       470.931
29       388.310
30       307.958
31     1.308.193
32     1.159.703
33     1.155.723
34     1.027.330
35     1.014.218
36     1.007.598
37       974.970
38       968.947
39       917.248
40       855.097
41       736.691
42       707.942
43       690.732
44       586.765
45       509.953
46       295.220
47       225.438
48       223.050
49       211.250
50     1.480.582
51     1.317.856
52     1.098.879
53       974.734
54       869.480
55       865.510
56       796.486
57       768.874
58       754.786
59       591.251
60       501.082
61       441.115
62       432.390
63       352.455
64       349.642
65       335.892
66       332.217
67       331.045
68       302.317
69       197.381
70       195.789
71     1.229.958
72     1.049.009
73       941.683
74       928.036
75       896.551
76       889.875
77       864.461
78       837.379
79       766.589
80       748.291
81       740.301
82       739.717
83       721.343
84       703.264
85       690.480
86       658.175
87       639.500
88       587.866
89       389.322
90       362.897
91       361.028
92       352.786
93       291.628
94       269.616
95       261.504
96       236.285
97       226.427
98       226.039
99       214.165
100      213.152
Name: Votes, dtype: object

## Cleaning 'Score' column

In [102]:
df_checkpoint3.loc[:, 'Score']

0         9.3
1         9.2
2          9.
3        9,.0
4        8,9f
5        08.9
6         8.9
7         8.9
8        8..8
9         8.8
10        8:8
11        8.8
12        8.8
14      ++8.7
15       8.7.
16     8,7e-0
17        8.7
18        8.7
19        8.6
20        8.6
21        8,6
22        8.6
23        8.6
24        8.6
25        8.6
26        8.6
27        8.6
28        8.6
29        8.6
30        8.6
31        8.5
32        8.5
33        8.5
34        8.5
35        8.5
36        8.5
37        8.4
38        8.4
39        8.4
40        8.4
41        8.4
42        8.4
43        8.4
44        8.3
45        8.3
46        8.3
47        8.3
48        8.3
49        8.3
50        8.3
51        8.3
52        8.2
53        8.2
54        8.2
55        8.2
56        8.2
57        8.2
58        8.2
59        8.2
60        8.1
61        8.1
62        8.1
63        8.1
64        8.1
65        8.1
66        8.1
67        8.0
68        8.0
69        8.0
70        8.0
71        8.0
72        8.0
73        7.9
74        7.9
75        7.9
76        7.9
77        7.9
78        7.8
79        7.8
80        7.8
81        7.8
82        7.8
83        7.8
84        7.7
85        7.7
86        7.7
87        7.7
88        7.6
89        7.6
90        7.6
91        7.6
92        7.5
93        7.5
94        7.5
95        7.5
96        7.5
97        7.5
98        7.4
99        7.4
100       7.4
Name: Score, dtype: object

In [103]:
bad_values = {}
for idx, value in df_checkpoint3.loc[:, 'Score'].items():
    try:
        df_checkpoint3.loc[idx, 'Score'] = float(value)
    except ValueError:
        log.debug(f'{idx}: {value}')
        bad_values[idx] = value
bad_values

3: 9,.0
4: 8,9f
8: 8..8
10: 8:8
14: ++8.7
15: 8.7.
16: 8,7e-0
21: 8,6

{3: '9,.0',
 4: '8,9f',
 8: '8..8',
 10: '8:8',
 14: '++8.7',
 15: '8.7.',
 16: '8,7e-0',
 21: '8,6'}

In [104]:
replace_values = {
    ',.': '.',
    ',': '.',
    'f': '',
    '..': '.',
    ':': '.',
    '++': '',
}

# Strip values
df_checkpoint3.loc[bad_values.keys(), 'Score'] = df_checkpoint3.loc[bad_values.keys(), 'Score'].str.strip('++f.')
for to, value in replace_values.items():
    df_checkpoint3.loc[bad_values.keys(), 'Score'] = df_checkpoint3.loc[bad_values.keys(), 'Score'].str.replace(to, value)
df_checkpoint3.loc[:, 'Score'] = pd.to_numeric(df_checkpoint3.loc[:, 'Score'])
df_checkpoint3.loc[:, 'Score']

0      9.3
1      9.2
2      9.0
3      9.0
4      8.9
5      8.9
6      8.9
7      8.9
8      8.8
9      8.8
10     8.8
11     8.8
12     8.8
14     8.7
15     8.7
16     8.7
17     8.7
18     8.7
19     8.6
20     8.6
21     8.6
22     8.6
23     8.6
24     8.6
25     8.6
26     8.6
27     8.6
28     8.6
29     8.6
30     8.6
31     8.5
32     8.5
33     8.5
34     8.5
35     8.5
36     8.5
37     8.4
38     8.4
39     8.4
40     8.4
41     8.4
42     8.4
43     8.4
44     8.3
45     8.3
46     8.3
47     8.3
48     8.3
49     8.3
50     8.3
51     8.3
52     8.2
53     8.2
54     8.2
55     8.2
56     8.2
57     8.2
58     8.2
59     8.2
60     8.1
61     8.1
62     8.1
63     8.1
64     8.1
65     8.1
66     8.1
67     8.0
68     8.0
69     8.0
70     8.0
71     8.0
72     8.0
73     7.9
74     7.9
75     7.9
76     7.9
77     7.9
78     7.8
79     7.8
80     7.8
81     7.8
82     7.8
83     7.8
84     7.7
85     7.7
86     7.7
87     7.7
88     7.6
89     7.6
90     7.6
91     7.6
92     7.5
93     7.5
94     7.5
95     7.5
96     7.5
97     7.5
98     7.4
99     7.4
100    7.4
Name: Score, dtype: object

In [105]:
df_checkpoint3.columns

Index(['Original Title', 'Release year', 'Genre', 'Duration', 'Country',
       'Content Rating', 'Director', 'Income', 'Votes', 'Score'],
      dtype='object')

# Finished Cleaning Data

In [106]:
df_clean_data = df_checkpoint3.copy()
df_clean_data_styled = df_clean_data.style.format({'Income': '$'}, precision=2, thousands=',')
df_clean_data_styled

## Export data

In [107]:
path_cleaned = library.path.get_cleaned_path(path)
df_clean_data.to_csv(path_cleaned)

In [108]:
df_clean_data

,Original Title,Release year,Genre,Duration,Country,Content Rating,Director,Income,Votes,Score
0,The Shawshank Redemption,1995-02-10 00:00:00,Drama,142,USA,R,Frank Darabont,28815245,2.278.845,9.3
1,The Godfather,1972-09-21 00:00:00,"Crime, Drama",175,USA,R,Francis Ford Coppola,246120974,1.572.674,9.2
2,The Dark Knight,2008-07-23 00:00:00,"Action, Crime, Drama",152,USA,PG-13,Christopher Nolan,1005455211,2.241.615,9.0
3,The Godfather: Part II,1975-09-25 00:00:00,"Crime, Drama",220,USA,R,Francis Ford Coppola,408035783,1.098.714,9.0
4,Pulp Fiction,1994-10-28 00:00:00,"Crime, Drama",0,USA,R,Quentin Tarantino,222831817,1.780.147,8.9
5,The Lord of the Rings: The Return of the King,2022-02-04 00:00:00,"Action, Adventure, Drama",201,New Zealand,PG-13,Peter Jackson,1142271098,1.604.280,8.9
6,Schindler's List,1994-03-11 00:00:00,"Biography, Drama, History",0,USA,R,Steven Spielberg,322287794,1.183.248,8.9
7,12 Angry Men,1957-09-04 00:00:00,"Crime, Drama",96,USA,Not Rated,Sidney Lumet,576,668.473,8.9
8,Inception,2010-09-24 00:00:00,"Action, Adventure, Sci-Fi",148,USA,PG-13,Christopher Nolan,869784991,2.002.816,8.8
9,Fight Club,1999-10-29 00:00:00,Drama,0,UK,R,David Fincher,101218804,1.807.440,8.8
10,Forrest Gump,1994-10-06 00:00:00,"Drama, Romance",142,USA,PG-13,Robert Zemeckis,678229452,1.755.490,8.8
11,The Lord of the Rings: The Fellowship of the Ring,2002-01-18 00:00:00,"Action, Adventure, Drama",0,New Zealand,PG-13,Peter Jackson,887934303,1.619.920,8.8
12,"Il buono, il brutto, il cattivo",1966-12-23 00:00:00,Western,161,Italy,Approved,Sergio Leone,25252481,672.499,8.8
14,The Matrix,1999-05-07 00:00:00,"Action, Sci-Fi",0,USA,R,"Lana Wachowski, Lilly Wachowski",465718588,1.632.315,8.7
15,The Lord of the Rings: The Two Towers,2003-01-16 00:00:00,"Action, Adventure, Drama",179,New Zealand,PG-13,Peter Jackson,951227416,1.449.778,8.7
16,Star Wars: Episode V - The Empire Strikes Back,1980-09-19 00:00:00,"Action, Adventure, Fantasy",0,USA,PG,Irvin Kershner,549265501,1.132.073,8.7
17,Goodfellas,1990-09-20 00:00:00,"Biography, Crime, Drama",146,USA,R,Martin Scorsese,46879633,991.505,8.7
18,One Flew Over the Cuckoo's Nest,1976-11-18 00:00:00,Drama,0,USA,R,Milos Forman,108997629,891.071,8.7
19,Interstellar,2014-11-06 00:00:00,"Adventure, Drama, Sci-Fi",169,USA,PG-13,Christopher Nolan,696742056,1.449.256,8.6
20,Se7en,1995-12-15 00:00:00,"Crime, Drama, Mystery",127,USA,R,David Fincher,327333559,1.402.015,8.6
21,The Silence of the Lambs,1991-03-05 00:00:00,"Crime, Drama, Thriller",118,USA,R,Jonathan Demme,272753884,1.234.134,8.6
22,Star Wars,1977-10-20 00:00:00,"Action, Adventure, Fantasy",121,USA,PG,George Lucas,775768912,1.204.107,8.6
23,Saving Private Ryan,1998-10-30 00:00:00,"Drama, War",169,USA,R,Steven Spielberg,482349603,1.203.825,8.6
24,The Green Mile,2000-10-03 00:00:00,"Crime, Drama, Fantasy",189,USA,R,Frank Darabont,286801374,1.112.336,8.6
25,Cidade de Deus,2003-05-09 00:00:00,"Crime, Drama",130,Brazil,R,"Fernando Meirelles, KÃ¡tia Lund",30680793,685.856,8.6
26,Sen to Chihiro no kamikakushi,2003-04-18 00:00:00,"Animation, Adventure, Family",125,Japan,PG,Hayao Miyazaki,355467056,626.693,8.6
27,La vita B9 bella,1997-12-20 00:00:00,"Comedy, Drama, Romance",116,Italy1,Not Rated,Roberto Benigni,230098753,605.648,8.6
28,Gisaengchung,2019-11-07 00:00:00,"Comedy, Drama, Thriller",132,South Korea,Not Rated,Bong Joon Ho,257604912,470.931,8.6
29,It's a Wonderful Life,1948-03-11 00:00:00,"Drama, Family, Fantasy",130,USA,PG,Frank Capra,6130720,388.310,8.6
30,Shichinin no samurai,1955-08-19 00:00:00,"Action, Adventure, Drama",207,Japan,Unrated,Akira Kurosawa,322773,307.958,8.6
31,Gladiator,2000-05-19 00:00:00,"Action, Adventure, Drama",155,USA,R,Ridley Scott,465361176,1.308.193,8.5
32,The Departed,2006-10-27 00:00:00,"Crime, Drama, Thriller",151,USA,R,Martin Scorsese,291465034,1.159.703,8.5
33,The Prestige,2006-12-22 00:00:00,"Drama, Mystery, Sci-Fi",130,UK,PG-13,Christopher Nolan,109676311,1.155.723,8.5
34,Back to the Future,1985-10-18 00:00:00,"Adventure, Comedy, Sci-Fi",116,USA,PG,Robert Zemeckis,388774684,1.027.330,8.5
35,American History X,1999-08-27 00:00:00,Drama,119,USA,R,Tony Kaye,23875127,1.014.218,8.5
36,LÃ©on,1995-04-07 00:00:00,"Action, Crime, Drama",110,France,Not Rated,Luc Besson,19552639,1.007.598,8.5
37,Terminator 2: Judgment Day,1991-12-19 00:00:00,"Action, Sci-Fi",137,USA,R,James Cameron,520884847,974.970,8.4
38,The Usual Suspects,1995-11-30 00:00:00,"Crime, Mystery, Thriller",106,USA,R,Bryan Singer,23341568,968.947,8.4
39,The Lion King,1994-11-25 00:00:00,"Animation, Adventure, Drama",88,USA,G,"Roger Allers, Rob Minkoff",968511805,917.248,8.4
40,Joker,2019-10-03 00:00:00,"Crime, Drama, Thriller",122,USA,Not Rated,Todd Phillips,1074251311,855.097,8.4
41,Intouchables,2012-02-24 00:00:00,"Biography, Comedy, Drama",112,France,Not Rated,"Olivier Nakache, Ã‰ric Toledano",426588510,736.691,8.4
42,The Pianist,2002-10-25 00:00:00,"Biography, Drama, Music",150,UK,R,Roman Polanski,120072577,707.942,8.4
43,Whiplash,2015-02-12 00:00:00,"Drama, Music",106,USA,R,Damien Chazelle,48983260,690.732,8.4
44,Psycho,1960-10-28 00:00:00,"Horror, Mystery, Thriller",109,USA,R,Alfred Hitchcock,32008644,586.765,8.3
45,Casablanca,2046-11-21 00:00:00,"Drama, Romance, War",102,USA,PG,Michael Curtiz,4374761,509.953,8.3
46,C'era una volta il West,1968-12-21 00:00:00,Western,165,Italy,PG-13,Sergio Leone,112911,295.220,8.3
47,Hotaru no haka,2015-10-11 00:00:00,"Animation, Drama, War",89,Japan,Not Rated,Isao Takahata,516962,225.438,8.3
48,Nuovo Cinema Paradiso,1988-11-17 00:00:00,Drama,155,Italy,Not Rated,Giuseppe Tornatore,13826605,223.050,8.3
49,Modern Times,1937-03-12 00:00:00,"Comedy, Drama, Family",87,USA,G,Charles Chaplin,457688,211.250,8.3
50,The Dark Knight Rises,2012-08-29 00:00:00,"Action, Adventure",164,UK,PG-13,Christopher Nolan,1081133191,1.480.582,8.3
51,Django Unchained,2013-01-17 00:00:00,"Drama, Western",165,USA,R,Quentin Tarantino,425368238,1.317.856,8.3
52,Memento,2001-01-19 00:00:00,"Mystery, Thriller",113,USA,R,Christopher Nolan,39970386,1.098.879,8.2
53,WALLÂ·E,2008-10-17 00:00:00,"Animation, Adventure, Family",98,USA,G,Andrew Stanton,521311860,974.734,8.2
54,The Shining,1980-12-22 00:00:00,"Drama, Horror",146,UK,R,Stanley Kubrick,46520613,869.480,8.2
55,Raiders of the Lost Ark,1981-06-12 00:00:00,"Action, Adventure",115,USA,PG,Steven Spielberg,390133212,865.510,8.2
56,Avengers: Infinity War,2018-04-25 00:00:00,"Action, Adventure, Sci-Fi",149,USA,Not Rated,"Anthony Russo, Joe Russo",2048359754,796.486,8.2
57,Alien,1979-10-25 00:00:00,"Horror, Sci-Fi",117,UK,R,Ridley Scott,108110316,768.874,8.2
58,Avengers: Endgame,2019-04-24 00:00:00,"Action, Adventure, Drama",181,USA,Not Rated,"Anthony Russo, Joe Russo",2797800564,754.786,8.2
59,Apocalypse Now,1979-12-18 00:00:00,"Drama, Mystery, War",147,USA,R,Francis Ford Coppola,91968688,591.251,8.2
60,Oldeuboi,2005-05-06 00:00:00,"Action, Drama, Mystery",120,South Korea,R,Chan-wook Park,15002116,501.082,8.1
61,Dr. Strangelove or: How I Learned to Stop Worr...,1964-04-03 00:00:00,Comedy,95,UK,PG,Stanley Kubrick,9443876,441.115,8.1
62,Rear Window,1955-04-14 00:00:00,"Mystery, Thriller",112,USA,Not Rated,Alfred Hitchcock,37032034,432.390,8.1
63,Coco,2017-12-28 00:00:00,"Animation, Adventure, Family",105,USA,Not Rated,"Lee Unkrich, Adrian Molina",807083670,352.455,8.1
64,Das Leben der Anderen,2007-04-06 00:00:00,"Drama, Mystery, Thriller",137,Germany,R,Florian Henckel von Donnersmarck,77356942,349.642,8.1
65,Spider-Man: Into the Spider-Verse,2018-12-25 00:00:00,"Animation, Action, Adventure",117,USA,Not Rated,"Bob Persichetti, Peter Ramsey",375540831,335.892,8.1
66,3 Idiots,2009-12-25 00:00:00,"Comedy, Drama",170,India,Not Rated,Rajkumar Hirani,60262836,332.217,8.1
67,Mononoke-hime,2000-05-19 00:00:00,"Animation, Adventure, Fantasy",134,Japan,PG-13,Hayao Miyazaki,169785629,331.045,8.0
68,Once Upon a Time in America,1984-09-28 00:00:00,"Crime, Drama",229,USA,R,Sergio Leone,5472914,302.317,8.0
69,The Great Dictator,1945-06-25 00:00:00,"Comedy, Drama, War",125,USA,Not Rated,Charles Chaplin,969879,197.381,8.0
70,Sunset Blvd.,1951-03-06 00:00:00,"Drama, Film-Noir",110,USA,Not Rated,Billy Wilder,299645,195.789,8.0
71,Inglourious Basterds,2009-10-02 00:00:00,"Adventure, Drama, War",153,Germany,R,Quentin Tarantino,321455689,1.229.958,8.0
72,American Beauty,2000-01-21 00:00:00,Drama,122,USA,R,Sam Mendes,356296601,1.049.009,8.0
73,Braveheart,1995-12-01 00:00:00,"Biography, Drama, History",178,USA,R,Mel Gibson,213216216,941.683,7.9
74,Star Wars: Episode VI - Return of the Jedi,1983-10-21 00:00:00,"Action, Adventure, Fantasy",131,USA,PG,Richard Marquand,475347111,928.036,7.9
75,Reservoir Dogs,1992-10-09 00:00:00,"Crime, Drama, Thriller",99,USA,R,Quentin Tarantino,2889963,896.551,7.9
76,Eternal Sunshine of the Spotless Mind,2004-10-22 00:00:00,"Drama, Romance, Sci-Fi",108,USA,R,Michel Gondry,74036715,889.875,7.9
77,Toy Story,1996-03-22 00:00:00,"Animation, Adventure, Comedy",81,USA,G,John Lasseter,404265438,864.461,7.9
78,Good Will Hunting,1998-03-06 00:00:00,"Drama, Romance",126,USA,R,Gus Van Sant,225933435,837.379,7.8
79,Snatch,2001-03-16 00:00:00,"Comedy, Crime",104,UK,R,Guy Ritchie,83557872,766.589,7.8
80,Requiem for a Dream,2000-12-15 00:00:00,Drama,102,USA,R,Darren Aronofsky,7390108,748.291,7.8
81,A Clockwork Orange,1972-09-07 00:00:00,"Crime, Drama, Sci-Fi",136,UK,Not Rated,Stanley Kubrick,26903440,740.301,7.8
82,Toy Story 3,2010-07-07 00:00:00,"Animation, Adventure, Comedy",103,USA,G,Lee Unkrich,1066969703,739.717,7.8
83,Scarface,NaT,"Crime, Drama",170,USA,R,Brian De Palma,66023585,721.343,7.8
84,Taxi Driver,NaT,"Crime, Drama",114,USA,R,Martin Scorsese,28441292,703.264,7.7
85,Le fabuleux destin d'AmÃ©lie Poulain,2002-01-25 00:00:00,"Comedy, Romance",122,France,R,Jean-Pierre Jeunet,173924742,690.480,7.7
86,Full Metal Jacket,1987-10-09 00:00:00,"Drama, War",116,UK,Not Rated,Stanley Kubrick,46357676,658.175,7.7
87,Aliens,1986-09-24 00:00:00,"Action, Adventure, Sci-Fi",137,USA,R,James Cameron,131384634,639.500,7.7
88,2001: A Space Odyssey,1968-12-12 00:00:00,"Adventure, Sci-Fi",149,UK,G,Stanley Kubrick,68989547,587.866,7.6
89,Citizen Kane,1948-11-25 00:00:00,"Drama, Mystery",119,USA,Not Rated,Orson Welles,1594107,389.322,7.6
90,1917,2020-01-23 00:00:00,"Drama, War",119,USA,Not Rated,Sam Mendes,384857224,362.897,7.6
91,Amadeus,1985-02-15 00:00:00,"Biography, Drama, History",160,USA,R,Milos Forman,52066791,361.028,7.6
92,Vertigo,1958-11-18 00:00:00,"Mystery, Romance, Thriller",128,USA,Not Rated,Alfred Hitchcock,7796389,352.786,7.5
93,North by Northwest,1959-10-28 00:00:00,"Adventure, Mystery, Thriller",136,USA,Not Rated,Alfred Hitchcock,73446,291.628,7.5
94,Jagten,2012-11-22 00:00:00,Drama,115,Denmark,R,Thomas Vinterberg,15843274,269.616,7.5
95,Lawrence of Arabia,1963-10-29 00:00:00,"Adventure, Biography, Drama",228,UK,PG,David Lean,45710874,261.504,7.5
96,The Sting,1974-03-21 00:00:00,"Comedy, Crime, Drama",129,USA,PG,George Roy Hill,156000000,236.285,7.5
97,Das Boot,1982-03-18 00:00:00,"Adventure, Drama, Thriller",149,West Germany,R,Wolfgang Petersen,11487676,226.427,7.5
98,Per qualche dollaro in piÃ¹,1965-12-20 00:00:00,Western,132,Italy,Not Rated,Sergio Leone,15000000,226.039,7.4
99,Jodaeiye Nader az Simin,2011-10-21 00:00:00,Drama,123,Iran,PG-13,Asghar Farhadi,22926076,214.165,7.4
100,Singin' in the Rain,1953-02-05 00:00:00,"Comedy, Musical, Romance",103,USA,Not Rated,Stanley Donen,1864182,213.152,7.4