# Cleaning Messy Chicago Traffic Crashes Dataset
Dataset from https://catalog.data.gov/dataset/traffic-crashes-crashes

In [1]:
import pandas as pd
import importlib

import lib

importlib.reload(lib)

log = lib.getLogger('chicago_traffic_crashes')

# Read dataset

In [2]:
filename = 'chicago_traffic_crashes.csv'
df = lib.read_data(filename, sep=',', encoding='ascii')

PortfolioLogger.lib.tools: INFO: Encoding: ascii
PortfolioLogger.lib.tools: INFO: Stripping whitespaces from chicago_traffic_crashes.csv

## Getting the general info to see what we're working with

In [3]:
log.info(f'DataFrame shape {df.shape}')

PortfolioLogger.chicago_traffic_crashes: INFO: DataFrame shape (984012, 48)

In [4]:
lib.info(df)

PortfolioLogger.lib.tools: INFO: INFO
PortfolioLogger.lib.tools: INFO: -------------------------------------------------------------------------------
PortfolioLogger.lib.tools: INFO: Null INFO
PortfolioLogger.lib.tools: INFO: 26/48 columns contain null values
PortfolioLogger.lib.tools: INFO: 9994606 total null values
PortfolioLogger.lib.tools: INFO: -------------------------------------------------------------------------------
PortfolioLogger.lib.tools: INFO: Column "CRASH_RECORD_ID" has no null values
PortfolioLogger.lib.tools: INFO: Column "CRASH_DATE" has no null values
PortfolioLogger.lib.tools: INFO: Column "POSTED_SPEED_LIMIT" has no null values
PortfolioLogger.lib.tools: INFO: Column "TRAFFIC_CONTROL_DEVICE" has no null values
PortfolioLogger.lib.tools: INFO: Column "DEVICE_CONDITION" has no null values
PortfolioLogger.lib.tools: INFO: Column "WEATHER_CONDITION" has no null values
PortfolioLogger.lib.tools: INFO: Column "LIGHTING_CONDITION" has no null values
PortfolioLogger.lib.tools: INFO: Column "FIRST_CRASH_TYPE" has no null values
PortfolioLogger.lib.tools: INFO: Column "TRAFFICWAY_TYPE" has no null values
PortfolioLogger.lib.tools: INFO: Column "ALIGNMENT" has no null values
PortfolioLogger.lib.tools: INFO: Column "ROADWAY_SURFACE_COND" has no null values
PortfolioLogger.lib.tools: INFO: Column "ROAD_DEFECT" has no null values
PortfolioLogger.lib.tools: INFO: Column "CRASH_TYPE" has no null values
PortfolioLogger.lib.tools: INFO: Column "DAMAGE" has no null values
PortfolioLogger.lib.tools: INFO: Column "DATE_POLICE_NOTIFIED" has no null values
PortfolioLogger.lib.tools: INFO: Column "PRIM_CONTRIBUTORY_CAUSE" has no null values
PortfolioLogger.lib.tools: INFO: Column "SEC_CONTRIBUTORY_CAUSE" has no null values
PortfolioLogger.lib.tools: INFO: Column "STREET_NO" has no null values
PortfolioLogger.lib.tools: INFO: Column "NUM_UNITS" has no null values
PortfolioLogger.lib.tools: INFO: Column "CRASH_HOUR" has no null values
PortfolioLogger.lib.tools: INFO: Column "CRASH_DAY_OF_WEEK" has no null values
PortfolioLogger.lib.tools: INFO: Column "CRASH_MONTH" has no null values
PortfolioLogger.lib.tools: INFO: Column "CRASH_DATE_EST_I" has 912297 null values
PortfolioLogger.lib.tools: INFO: Column "LANE_CNT" has 784983 null values
PortfolioLogger.lib.tools: INFO: Column "REPORT_TYPE" has 32224 null values
PortfolioLogger.lib.tools: INFO: Column "INTERSECTION_RELATED_I" has 757867 null values
PortfolioLogger.lib.tools: INFO: Column "NOT_RIGHT_OF_WAY_I" has 939693 null values
PortfolioLogger.lib.tools: INFO: Column "HIT_AND_RUN_I" has 675242 null values
PortfolioLogger.lib.tools: INFO: Column "STREET_DIRECTION" has 4 null values
PortfolioLogger.lib.tools: INFO: Column "STREET_NAME" has 1 null values
PortfolioLogger.lib.tools: INFO: Column "BEAT_OF_OCCURRENCE" has 5 null values
PortfolioLogger.lib.tools: INFO: Column "PHOTOS_TAKEN_I" has 970138 null values
PortfolioLogger.lib.tools: INFO: Column "STATEMENTS_TAKEN_I" has 960800 null values
PortfolioLogger.lib.tools: INFO: Column "DOORING_I" has 980878 null values
PortfolioLogger.lib.tools: INFO: Column "WORK_ZONE_I" has 978635 null values
PortfolioLogger.lib.tools: INFO: Column "WORK_ZONE_TYPE" has 979898 null values
PortfolioLogger.lib.tools: INFO: Column "WORKERS_PRESENT_I" has 982631 null values
PortfolioLogger.lib.tools: INFO: Column "MOST_SEVERE_INJURY" has 2151 null values
PortfolioLogger.lib.tools: INFO: Column "INJURIES_TOTAL" has 2137 null values
PortfolioLogger.lib.tools: INFO: Column "INJURIES_FATAL" has 2137 null values
PortfolioLogger.lib.tools: INFO: Column "INJURIES_INCAPACITATING" has 2137 null values
PortfolioLogger.lib.tools: INFO: Column "INJURIES_NON_INCAPACITATING" has 2137 null values
PortfolioLogger.lib.tools: INFO: Column "INJURIES_REPORTED_NOT_EVIDENT" has 2137 null values
PortfolioLogger.lib.tools: INFO: Column "INJURIES_NO_INDICATION" has 2137 null values
PortfolioLogger.lib.tools: INFO: Column "INJURIES_UNKNOWN" has 2137 null values
PortfolioLogger.lib.tools: INFO: Column "LATITUDE" has 7400 null values
PortfolioLogger.lib.tools: INFO: Column "LONGITUDE" has 7400 null values
PortfolioLogger.lib.tools: INFO: Column "LOCATION" has 7400 null values
PortfolioLogger.lib.tools: INFO:
PortfolioLogger.lib.tools: INFO: Risk Rate ---------------------------------------------------------------------
PortfolioLogger.lib.tools: INFO: CRASH_RECORD_ID                  0.000000
CRASH_DATE_EST_I                 0.927120
CRASH_DATE                       0.000000
POSTED_SPEED_LIMIT               0.000000
TRAFFIC_CONTROL_DEVICE           0.000000
DEVICE_CONDITION                 0.000000
WEATHER_CONDITION                0.000000
LIGHTING_CONDITION               0.000000
FIRST_CRASH_TYPE                 0.000000
TRAFFICWAY_TYPE                  0.000000
LANE_CNT                         0.797737
ALIGNMENT                        0.000000
ROADWAY_SURFACE_COND             0.000000
ROAD_DEFECT                      0.000000
REPORT_TYPE                      0.032748
CRASH_TYPE                       0.000000
INTERSECTION_RELATED_I           0.770181
NOT_RIGHT_OF_WAY_I               0.954961
HIT_AND_RUN_I                    0.686213
DAMAGE                           0.000000
DATE_POLICE_NOTIFIED             0.000000
PRIM_CONTRIBUTORY_CAUSE          0.000000
SEC_CONTRIBUTORY_CAUSE           0.000000
STREET_NO                        0.000000
STREET_DIRECTION                 0.000004
STREET_NAME                      0.000001
BEAT_OF_OCCURRENCE               0.000005
PHOTOS_TAKEN_I                   0.985901
STATEMENTS_TAKEN_I               0.976411
DOORING_I                        0.996815
WORK_ZONE_I                      0.994536
WORK_ZONE_TYPE                   0.995819
WORKERS_PRESENT_I                0.998597
NUM_UNITS                        0.000000
MOST_SEVERE_INJURY               0.002186
INJURIES_TOTAL                   0.002172
INJURIES_FATAL                   0.002172
INJURIES_INCAPACITATING          0.002172
INJURIES_NON_INCAPACITATING      0.002172
INJURIES_REPORTED_NOT_EVIDENT    0.002172
INJURIES_NO_INDICATION           0.002172
INJURIES_UNKNOWN                 0.002172
CRASH_HOUR                       0.000000
CRASH_DAY_OF_WEEK                0.000000
CRASH_MONTH                      0.000000
LATITUDE                         0.007520
LONGITUDE                        0.007520
LOCATION                         0.007520
dtype: float64
PortfolioLogger.lib.tools: INFO: Column Risk Rates
PortfolioLogger.lib.tools: INFO: CRASH_RECORD_ID                  0.000000
CRASH_DATE_EST_I                 0.927120
CRASH_DATE                       0.000000
POSTED_SPEED_LIMIT               0.000000
TRAFFIC_CONTROL_DEVICE           0.000000
DEVICE_CONDITION                 0.000000
WEATHER_CONDITION                0.000000
LIGHTING_CONDITION               0.000000
FIRST_CRASH_TYPE                 0.000000
TRAFFICWAY_TYPE                  0.000000
LANE_CNT                         0.797737
ALIGNMENT                        0.000000
ROADWAY_SURFACE_COND             0.000000
ROAD_DEFECT                      0.000000
REPORT_TYPE                      0.032748
CRASH_TYPE                       0.000000
INTERSECTION_RELATED_I           0.770181
NOT_RIGHT_OF_WAY_I               0.954961
HIT_AND_RUN_I                    0.686213
DAMAGE                           0.000000
DATE_POLICE_NOTIFIED             0.000000
PRIM_CONTRIBUTORY_CAUSE          0.000000
SEC_CONTRIBUTORY_CAUSE           0.000000
STREET_NO                        0.000000
STREET_DIRECTION                 0.000004
STREET_NAME                      0.000001
BEAT_OF_OCCURRENCE               0.000005
PHOTOS_TAKEN_I                   0.985901
STATEMENTS_TAKEN_I               0.976411
DOORING_I                        0.996815
WORK_ZONE_I                      0.994536
WORK_ZONE_TYPE                   0.995819
WORKERS_PRESENT_I                0.998597
NUM_UNITS                        0.000000
MOST_SEVERE_INJURY               0.002186
INJURIES_TOTAL                   0.002172
INJURIES_FATAL                   0.002172
INJURIES_INCAPACITATING          0.002172
INJURIES_NON_INCAPACITATING      0.002172
INJURIES_REPORTED_NOT_EVIDENT    0.002172
INJURIES_NO_INDICATION           0.002172
INJURIES_UNKNOWN                 0.002172
CRASH_HOUR                       0.000000
CRASH_DAY_OF_WEEK                0.000000
CRASH_MONTH                      0.000000
LATITUDE                         0.007520
LONGITUDE                        0.007520
LOCATION                         0.007520
dtype: float64
PortfolioLogger.lib.tools: INFO:
-------------------------------------------------------------------------------
PortfolioLogger.lib.tools: INFO: Data Types Info
PortfolioLogger.lib.tools: INFO: -------------------------------------------------------------------------------
PortfolioLogger.lib.tools: INFO:                               has_different_types has_<NA>
CRASH_RECORD_ID                             False        0
CRASH_DATE_EST_I                            False   912297
CRASH_DATE                                  False        0
POSTED_SPEED_LIMIT                          False        0
TRAFFIC_CONTROL_DEVICE                      False        0
DEVICE_CONDITION                            False        0
WEATHER_CONDITION                           False        0
LIGHTING_CONDITION                          False        0
FIRST_CRASH_TYPE                            False        0
TRAFFICWAY_TYPE                             False        0
LANE_CNT                                    False   784983
ALIGNMENT                                   False        0
ROADWAY_SURFACE_COND                        False        0
ROAD_DEFECT                                 False        0
REPORT_TYPE                                 False    32224
CRASH_TYPE                                  False        0
INTERSECTION_RELATED_I                      False   757867
NOT_RIGHT_OF_WAY_I                          False   939693
HIT_AND_RUN_I                               False   675242
DAMAGE                                      False        0
DATE_POLICE_NOTIFIED                        False        0
PRIM_CONTRIBUTORY_CAUSE                     False        0
SEC_CONTRIBUTORY_CAUSE                      False        0
STREET_NO                                   False        0
STREET_DIRECTION                            False        4
STREET_NAME                                 False        1
BEAT_OF_OCCURRENCE                          False        5
PHOTOS_TAKEN_I                              False   970138
STATEMENTS_TAKEN_I                          False   960800
DOORING_I                                   False   980878
WORK_ZONE_I                                 False   978635
WORK_ZONE_TYPE                              False   979898
WORKERS_PRESENT_I                           False   982631
NUM_UNITS                                   False        0
MOST_SEVERE_INJURY                          False     2151
INJURIES_TOTAL                              False     2137
INJURIES_FATAL                              False     2137
INJURIES_INCAPACITATING                     False     2137
INJURIES_NON_INCAPACITATING                 False     2137
INJURIES_REPORTED_NOT_EVIDENT               False     2137
INJURIES_NO_INDICATION                      False     2137
INJURIES_UNKNOWN                            False     2137
CRASH_HOUR                                  False        0
CRASH_DAY_OF_WEEK                           False        0
CRASH_MONTH                                 False        0
LATITUDE                                    False     7400
LONGITUDE                                   False     7400
LOCATION                                    False     7400
PortfolioLogger.lib.tools: INFO: -------------------------------------------------------------------------------
/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/lib/tools.py:618: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  result = result.fillna(0)
PortfolioLogger.lib.tools: INFO:                  CRASH_RECORD_ID  CRASH_DATE_EST_I  CRASH_DATE  \
<NA>                           0            912297           0
<class 'float'>                0                 0           0
<class 'int'>                  0                 0           0
<class 'str'>             984012             71715      984012

                 POSTED_SPEED_LIMIT  TRAFFIC_CONTROL_DEVICE  DEVICE_CONDITION  \
<NA>                              0                       0                 0
<class 'float'>                   0                       0                 0
<class 'int'>                984012                       0                 0
<class 'str'>                     0                  984012            984012

                 WEATHER_CONDITION  LIGHTING_CONDITION  FIRST_CRASH_TYPE  \
<NA>                             0                   0                 0
<class 'float'>                  0                   0                 0
<class 'int'>                    0                   0                 0
<class 'str'>               984012              984012            984012

                 TRAFFICWAY_TYPE  ...  INJURIES_NON_INCAPACITATING  \
<NA>                           0  ...                         2137
<class 'float'>                0  ...                       981875
<class 'int'>                  0  ...                            0
<class 'str'>             984012  ...                            0

                 INJURIES_REPORTED_NOT_EVIDENT  INJURIES_NO_INDICATION  \
<NA>                                      2137                    2137
<class 'float'>                         981875                  981875
<class 'int'>                                0                       0
<class 'str'>                                0                       0

                 INJURIES_UNKNOWN  CRASH_HOUR  CRASH_DAY_OF_WEEK  CRASH_MONTH  \
<NA>                         2137           0                  0            0
<class 'float'>            981875           0                  0            0
<class 'int'>                   0      984012             984012       984012
<class 'str'>                   0           0                  0            0

                 LATITUDE  LONGITUDE  LOCATION
<NA>                 7400       7400      7400
<class 'float'>    976612     976612         0
<class 'int'>           0          0         0
<class 'str'>           0          0    976612

[4 rows x 48 columns]
PortfolioLogger.lib.tools: INFO:
-------------------------------------------------------------------------------
PortfolioLogger.lib.tools: INFO: Values Counter
PortfolioLogger.lib.tools: INFO: -------------------------------------------------------------------------------
PortfolioLogger.lib.tools: INFO: CRASH_RECORD_ID: <object> BEGIN
PortfolioLogger.lib.tools: INFO: CRASH_RECORD_ID: Has more than 20 values (984012 values)

PortfolioLogger.lib.tools: INFO: CRASH_DATE_EST_I: <object> BEGIN
PortfolioLogger.lib.tools: INFO: 	nan: 912297
PortfolioLogger.lib.tools: INFO: 	Y: 62551
PortfolioLogger.lib.tools: INFO: 	N: 9164
PortfolioLogger.lib.tools: INFO: CRASH_DATE_EST_I: <object> END

PortfolioLogger.lib.tools: INFO: CRASH_DATE: <object> BEGIN
PortfolioLogger.lib.tools: INFO: CRASH_DATE: Has more than 20 values (649476 values)

PortfolioLogger.lib.tools: INFO: POSTED_SPEED_LIMIT: <int64> BEGIN
PortfolioLogger.lib.tools: INFO: POSTED_SPEED_LIMIT: Has more than 20 values (46 values)

PortfolioLogger.lib.tools: INFO: TRAFFIC_CONTROL_DEVICE: <object> BEGIN
PortfolioLogger.lib.tools: INFO: 	TRAFFIC SIGNAL: 272546
PortfolioLogger.lib.tools: INFO: 	STOP SIGN/FLASHER: 97577
PortfolioLogger.lib.tools: INFO: 	NO CONTROLS: 554877
PortfolioLogger.lib.tools: INFO: 	UNKNOWN: 44121
PortfolioLogger.lib.tools: INFO: 	OTHER: 6739
PortfolioLogger.lib.tools: INFO: 	LANE USE MARKING: 1226
PortfolioLogger.lib.tools: INFO: 	PEDESTRIAN CROSSING SIGN: 772
PortfolioLogger.lib.tools: INFO: 	OTHER REG. SIGN: 1183
PortfolioLogger.lib.tools: INFO: 	OTHER WARNING SIGN: 765
PortfolioLogger.lib.tools: INFO: 	YIELD: 1517
PortfolioLogger.lib.tools: INFO: 	SCHOOL ZONE: 393
PortfolioLogger.lib.tools: INFO: 	FLASHING CONTROL SIGNAL: 432
PortfolioLogger.lib.tools: INFO: 	DELINEATORS: 363
PortfolioLogger.lib.tools: INFO: 	NO PASSING: 69
PortfolioLogger.lib.tools: INFO: 	RAILROAD CROSSING GATE: 632
PortfolioLogger.lib.tools: INFO: 	POLICE/FLAGMAN: 335
PortfolioLogger.lib.tools: INFO: 	RR CROSSING SIGN: 219
PortfolioLogger.lib.tools: INFO: 	BICYCLE CROSSING SIGN: 38
PortfolioLogger.lib.tools: INFO: 	OTHER RAILROAD CROSSING: 208
PortfolioLogger.lib.tools: INFO: TRAFFIC_CONTROL_DEVICE: <object> END

PortfolioLogger.lib.tools: INFO: DEVICE_CONDITION: <object> BEGIN
PortfolioLogger.lib.tools: INFO: 	FUNCTIONING PROPERLY: 335128
PortfolioLogger.lib.tools: INFO: 	UNKNOWN: 72156
PortfolioLogger.lib.tools: INFO: 	NO CONTROLS: 561849
PortfolioLogger.lib.tools: INFO: 	FUNCTIONING IMPROPERLY: 4364
PortfolioLogger.lib.tools: INFO: 	OTHER: 7421
PortfolioLogger.lib.tools: INFO: 	NOT FUNCTIONING: 2683
PortfolioLogger.lib.tools: INFO: 	WORN REFLECTIVE MATERIAL: 307
PortfolioLogger.lib.tools: INFO: 	MISSING: 104
PortfolioLogger.lib.tools: INFO: DEVICE_CONDITION: <object> END

PortfolioLogger.lib.tools: INFO: WEATHER_CONDITION: <object> BEGIN
PortfolioLogger.lib.tools: INFO: 	SNOW: 30717
PortfolioLogger.lib.tools: INFO: 	UNKNOWN: 58079
PortfolioLogger.lib.tools: INFO: 	CLEAR: 774065
PortfolioLogger.lib.tools: INFO: 	RAIN: 83841
PortfolioLogger.lib.tools: INFO: 	CLOUDY/OVERCAST: 28641
PortfolioLogger.lib.tools: INFO: 	FREEZING RAIN/DRIZZLE: 2335
PortfolioLogger.lib.tools: INFO: 	SLEET/HAIL: 1113
PortfolioLogger.lib.tools: INFO: 	OTHER: 3128
PortfolioLogger.lib.tools: INFO: 	BLOWING SNOW: 488
PortfolioLogger.lib.tools: INFO: 	SEVERE CROSS WIND GATE: 165
PortfolioLogger.lib.tools: INFO: 	FOG/SMOKE/HAZE: 1420
PortfolioLogger.lib.tools: INFO: 	BLOWING SAND, SOIL, DIRT: 20
PortfolioLogger.lib.tools: INFO: WEATHER_CONDITION: <object> END

PortfolioLogger.lib.tools: INFO: LIGHTING_CONDITION: <object> BEGIN
PortfolioLogger.lib.tools: INFO: 	DAYLIGHT: 633188
PortfolioLogger.lib.tools: INFO: 	UNKNOWN: 47554
PortfolioLogger.lib.tools: INFO: 	DARKNESS, LIGHTED ROAD: 213604
PortfolioLogger.lib.tools: INFO: 	DARKNESS: 45658
PortfolioLogger.lib.tools: INFO: 	DUSK: 27754
PortfolioLogger.lib.tools: INFO: 	DAWN: 16254
PortfolioLogger.lib.tools: INFO: LIGHTING_CONDITION: <object> END

PortfolioLogger.lib.tools: INFO: FIRST_CRASH_TYPE: <object> BEGIN
PortfolioLogger.lib.tools: INFO: 	SIDESWIPE SAME DIRECTION: 152392
PortfolioLogger.lib.tools: INFO: 	TURNING: 142049
PortfolioLogger.lib.tools: INFO: 	PARKED MOTOR VEHICLE: 227264
PortfolioLogger.lib.tools: INFO: 	PEDALCYCLIST: 16156
PortfolioLogger.lib.tools: INFO: 	REAR END: 215361
PortfolioLogger.lib.tools: INFO: 	ANGLE: 106885
PortfolioLogger.lib.tools: INFO: 	SIDESWIPE OPPOSITE DIRECTION: 13580
PortfolioLogger.lib.tools: INFO: 	FIXED OBJECT: 45249
PortfolioLogger.lib.tools: INFO: 	PEDESTRIAN: 23492
PortfolioLogger.lib.tools: INFO: 	REAR TO SIDE: 6331
PortfolioLogger.lib.tools: INFO: 	HEAD ON: 8243
PortfolioLogger.lib.tools: INFO: 	REAR TO FRONT: 10630
PortfolioLogger.lib.tools: INFO: 	OTHER OBJECT: 9910
PortfolioLogger.lib.tools: INFO: 	OTHER NONCOLLISION: 2915
PortfolioLogger.lib.tools: INFO: 	REAR TO REAR: 2185
PortfolioLogger.lib.tools: INFO: 	OVERTURNED: 584
PortfolioLogger.lib.tools: INFO: 	ANIMAL: 732
PortfolioLogger.lib.tools: INFO: 	TRAIN: 54
PortfolioLogger.lib.tools: INFO: FIRST_CRASH_TYPE: <object> END

PortfolioLogger.lib.tools: INFO: TRAFFICWAY_TYPE: <object> BEGIN
PortfolioLogger.lib.tools: INFO: TRAFFICWAY_TYPE: Has more than 20 values (20 values)

PortfolioLogger.lib.tools: INFO: LANE_CNT: <float64> BEGIN

### Checking for null indices and rows

In [5]:
null_columns, null_rows, null_columns = lib.null_info(df)

PortfolioLogger.lib.tools: INFO: 26/48 columns contain null values
PortfolioLogger.lib.tools: INFO: 9994606 total null values
PortfolioLogger.lib.tools: INFO: -------------------------------------------------------------------------------
PortfolioLogger.lib.tools: INFO: Column "CRASH_RECORD_ID" has no null values
PortfolioLogger.lib.tools: INFO: Column "CRASH_DATE" has no null values
PortfolioLogger.lib.tools: INFO: Column "POSTED_SPEED_LIMIT" has no null values
PortfolioLogger.lib.tools: INFO: Column "TRAFFIC_CONTROL_DEVICE" has no null values
PortfolioLogger.lib.tools: INFO: Column "DEVICE_CONDITION" has no null values
PortfolioLogger.lib.tools: INFO: Column "WEATHER_CONDITION" has no null values
PortfolioLogger.lib.tools: INFO: Column "LIGHTING_CONDITION" has no null values
PortfolioLogger.lib.tools: INFO: Column "FIRST_CRASH_TYPE" has no null values
PortfolioLogger.lib.tools: INFO: Column "TRAFFICWAY_TYPE" has no null values
PortfolioLogger.lib.tools: INFO: Column "ALIGNMENT" has no null values
PortfolioLogger.lib.tools: INFO: Column "ROADWAY_SURFACE_COND" has no null values
PortfolioLogger.lib.tools: INFO: Column "ROAD_DEFECT" has no null values
PortfolioLogger.lib.tools: INFO: Column "CRASH_TYPE" has no null values
PortfolioLogger.lib.tools: INFO: Column "DAMAGE" has no null values
PortfolioLogger.lib.tools: INFO: Column "DATE_POLICE_NOTIFIED" has no null values
PortfolioLogger.lib.tools: INFO: Column "PRIM_CONTRIBUTORY_CAUSE" has no null values
PortfolioLogger.lib.tools: INFO: Column "SEC_CONTRIBUTORY_CAUSE" has no null values
PortfolioLogger.lib.tools: INFO: Column "STREET_NO" has no null values
PortfolioLogger.lib.tools: INFO: Column "NUM_UNITS" has no null values
PortfolioLogger.lib.tools: INFO: Column "CRASH_HOUR" has no null values
PortfolioLogger.lib.tools: INFO: Column "CRASH_DAY_OF_WEEK" has no null values
PortfolioLogger.lib.tools: INFO: Column "CRASH_MONTH" has no null values
PortfolioLogger.lib.tools: INFO: Column "CRASH_DATE_EST_I" has 912297 null values
PortfolioLogger.lib.tools: INFO: Column "LANE_CNT" has 784983 null values
PortfolioLogger.lib.tools: INFO: Column "REPORT_TYPE" has 32224 null values
PortfolioLogger.lib.tools: INFO: Column "INTERSECTION_RELATED_I" has 757867 null values
PortfolioLogger.lib.tools: INFO: Column "NOT_RIGHT_OF_WAY_I" has 939693 null values
PortfolioLogger.lib.tools: INFO: Column "HIT_AND_RUN_I" has 675242 null values
PortfolioLogger.lib.tools: INFO: Column "STREET_DIRECTION" has 4 null values
PortfolioLogger.lib.tools: INFO: Column "STREET_NAME" has 1 null values
PortfolioLogger.lib.tools: INFO: Column "BEAT_OF_OCCURRENCE" has 5 null values
PortfolioLogger.lib.tools: INFO: Column "PHOTOS_TAKEN_I" has 970138 null values
PortfolioLogger.lib.tools: INFO: Column "STATEMENTS_TAKEN_I" has 960800 null values
PortfolioLogger.lib.tools: INFO: Column "DOORING_I" has 980878 null values
PortfolioLogger.lib.tools: INFO: Column "WORK_ZONE_I" has 978635 null values
PortfolioLogger.lib.tools: INFO: Column "WORK_ZONE_TYPE" has 979898 null values
PortfolioLogger.lib.tools: INFO: Column "WORKERS_PRESENT_I" has 982631 null values
PortfolioLogger.lib.tools: INFO: Column "MOST_SEVERE_INJURY" has 2151 null values
PortfolioLogger.lib.tools: INFO: Column "INJURIES_TOTAL" has 2137 null values
PortfolioLogger.lib.tools: INFO: Column "INJURIES_FATAL" has 2137 null values
PortfolioLogger.lib.tools: INFO: Column "INJURIES_INCAPACITATING" has 2137 null values
PortfolioLogger.lib.tools: INFO: Column "INJURIES_NON_INCAPACITATING" has 2137 null values
PortfolioLogger.lib.tools: INFO: Column "INJURIES_REPORTED_NOT_EVIDENT" has 2137 null values
PortfolioLogger.lib.tools: INFO: Column "INJURIES_NO_INDICATION" has 2137 null values
PortfolioLogger.lib.tools: INFO: Column "INJURIES_UNKNOWN" has 2137 null values
PortfolioLogger.lib.tools: INFO: Column "LATITUDE" has 7400 null values
PortfolioLogger.lib.tools: INFO: Column "LONGITUDE" has 7400 null values
PortfolioLogger.lib.tools: INFO: Column "LOCATION" has 7400 null values
PortfolioLogger.lib.tools: INFO:
PortfolioLogger.lib.tools: INFO: Risk Rate ---------------------------------------------------------------------
PortfolioLogger.lib.tools: INFO: CRASH_RECORD_ID                  0.000000
CRASH_DATE_EST_I                 0.927120
CRASH_DATE                       0.000000
POSTED_SPEED_LIMIT               0.000000
TRAFFIC_CONTROL_DEVICE           0.000000
DEVICE_CONDITION                 0.000000
WEATHER_CONDITION                0.000000
LIGHTING_CONDITION               0.000000
FIRST_CRASH_TYPE                 0.000000
TRAFFICWAY_TYPE                  0.000000
LANE_CNT                         0.797737
ALIGNMENT                        0.000000
ROADWAY_SURFACE_COND             0.000000
ROAD_DEFECT                      0.000000
REPORT_TYPE                      0.032748
CRASH_TYPE                       0.000000
INTERSECTION_RELATED_I           0.770181
NOT_RIGHT_OF_WAY_I               0.954961
HIT_AND_RUN_I                    0.686213
DAMAGE                           0.000000
DATE_POLICE_NOTIFIED             0.000000
PRIM_CONTRIBUTORY_CAUSE          0.000000
SEC_CONTRIBUTORY_CAUSE           0.000000
STREET_NO                        0.000000
STREET_DIRECTION                 0.000004
STREET_NAME                      0.000001
BEAT_OF_OCCURRENCE               0.000005
PHOTOS_TAKEN_I                   0.985901
STATEMENTS_TAKEN_I               0.976411
DOORING_I                        0.996815
WORK_ZONE_I                      0.994536
WORK_ZONE_TYPE                   0.995819
WORKERS_PRESENT_I                0.998597
NUM_UNITS                        0.000000
MOST_SEVERE_INJURY               0.002186
INJURIES_TOTAL                   0.002172
INJURIES_FATAL                   0.002172
INJURIES_INCAPACITATING          0.002172
INJURIES_NON_INCAPACITATING      0.002172
INJURIES_REPORTED_NOT_EVIDENT    0.002172
INJURIES_NO_INDICATION           0.002172
INJURIES_UNKNOWN                 0.002172
CRASH_HOUR                       0.000000
CRASH_DAY_OF_WEEK                0.000000
CRASH_MONTH                      0.000000
LATITUDE                         0.007520
LONGITUDE                        0.007520
LOCATION                         0.007520
dtype: float64

## No rows or columns that are ALL null. Moving onto cleaning columns.

## Creating a backup

In [6]:
df_cp1 = df.copy()

# Processing NaN Values

In [7]:
df_cp1.columns

Index(['CRASH_RECORD_ID', 'CRASH_DATE_EST_I', 'CRASH_DATE',
       'POSTED_SPEED_LIMIT', 'TRAFFIC_CONTROL_DEVICE', 'DEVICE_CONDITION',
       'WEATHER_CONDITION', 'LIGHTING_CONDITION', 'FIRST_CRASH_TYPE',
       'TRAFFICWAY_TYPE', 'LANE_CNT', 'ALIGNMENT', 'ROADWAY_SURFACE_COND',
       'ROAD_DEFECT', 'REPORT_TYPE', 'CRASH_TYPE', 'INTERSECTION_RELATED_I',
       'NOT_RIGHT_OF_WAY_I', 'HIT_AND_RUN_I', 'DAMAGE', 'DATE_POLICE_NOTIFIED',
       'PRIM_CONTRIBUTORY_CAUSE', 'SEC_CONTRIBUTORY_CAUSE', 'STREET_NO',
       'STREET_DIRECTION', 'STREET_NAME', 'BEAT_OF_OCCURRENCE',
       'PHOTOS_TAKEN_I', 'STATEMENTS_TAKEN_I', 'DOORING_I', 'WORK_ZONE_I',
       'WORK_ZONE_TYPE', 'WORKERS_PRESENT_I', 'NUM_UNITS',
       'MOST_SEVERE_INJURY', 'INJURIES_TOTAL', 'INJURIES_FATAL',
       'INJURIES_INCAPACITATING', 'INJURIES_NON_INCAPACITATING',
       'INJURIES_REPORTED_NOT_EVIDENT', 'INJURIES_NO_INDICATION',
       'INJURIES_UNKNOWN', 'CRASH_HOUR', 'CRASH_DAY_OF_WEEK', 'CRASH_MONTH',
       'LATITUDE', 'LONGITUDE', 'LOCATION'],
      dtype='object')

## Checking for NaN and Non-NaN columns

In [8]:
# Create a null and non_null columns list
non_null_columns = lib.notnull(df_cp1).columns

log.info(non_null_columns)
log.info(null_columns)

PortfolioLogger.chicago_traffic_crashes: INFO: Index(['CRASH_RECORD_ID', 'CRASH_DATE', 'POSTED_SPEED_LIMIT',
       'TRAFFIC_CONTROL_DEVICE', 'DEVICE_CONDITION', 'WEATHER_CONDITION',
       'LIGHTING_CONDITION', 'FIRST_CRASH_TYPE', 'TRAFFICWAY_TYPE',
       'ALIGNMENT', 'ROADWAY_SURFACE_COND', 'ROAD_DEFECT', 'CRASH_TYPE',
       'DAMAGE', 'DATE_POLICE_NOTIFIED', 'PRIM_CONTRIBUTORY_CAUSE',
       'SEC_CONTRIBUTORY_CAUSE', 'STREET_NO', 'NUM_UNITS', 'CRASH_HOUR',
       'CRASH_DAY_OF_WEEK', 'CRASH_MONTH'],
      dtype='object')
PortfolioLogger.chicago_traffic_crashes: INFO: Index(['CRASH_DATE_EST_I', 'LANE_CNT', 'REPORT_TYPE', 'INTERSECTION_RELATED_I',
       'NOT_RIGHT_OF_WAY_I', 'HIT_AND_RUN_I', 'STREET_DIRECTION',
       'STREET_NAME', 'BEAT_OF_OCCURRENCE', 'PHOTOS_TAKEN_I',
       'STATEMENTS_TAKEN_I', 'DOORING_I', 'WORK_ZONE_I', 'WORK_ZONE_TYPE',
       'WORKERS_PRESENT_I', 'MOST_SEVERE_INJURY', 'INJURIES_TOTAL',
       'INJURIES_FATAL', 'INJURIES_INCAPACITATING',
       'INJURIES_NON_INCAPACITATING', 'INJURIES_REPORTED_NOT_EVIDENT',
       'INJURIES_NO_INDICATION', 'INJURIES_UNKNOWN', 'LATITUDE', 'LONGITUDE',
       'LOCATION'],
      dtype='object')

## Checking for columns whose values are 75% or more NaN

In [9]:
# Get columns that mostly have NaN values. Will need to look at these closer.
high_risk = lib.data_err_rates(df_cp1, err_rate=.75)

Taking a look at the high risk columns

In [10]:
high_risk

CRASH_DATE_EST_I          0.927120
LANE_CNT                  0.797737
INTERSECTION_RELATED_I    0.770181
NOT_RIGHT_OF_WAY_I        0.954961
PHOTOS_TAKEN_I            0.985901
STATEMENTS_TAKEN_I        0.976411
DOORING_I                 0.996815
WORK_ZONE_I               0.994536
WORK_ZONE_TYPE            0.995819
WORKERS_PRESENT_I         0.998597
dtype: float64

## Removing data that is not useable

In [11]:
df_cp1 = df_cp1.drop(high_risk.keys(), axis=1)

## Filling the rest of the NaN values with filler values

In [12]:
df_cp1, filler_values = lib.fillnull(df_cp1)

In [92]:
df_cp1

,CRASH_RECORD_ID,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
0,000c4307d8e9b39075cffdd0aade3603e0f96f14e41da9...,01/14/2025 12:25:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,SNOW,DAYLIGHT,SIDESWIPE SAME DIRECTION,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,12,3,1,41.997808,-87.655770,POINT (-87.655770494712 41.997807727633)
1,027b0b4c21460d3441fd83929abb9673c6fc0c7d575675...,05/23/2025 09:30:00 AM,30,STOP SIGN/FLASHER,UNKNOWN,UNKNOWN,DAYLIGHT,TURNING,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,9,6,5,41.946529,-87.688106,POINT (-87.688106391039 41.946529480518)
2,04d91dffc94f677358ca47056921ba5c4224320df27ed4...,04/05/2025 08:00:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,UNKNOWN,PARKED MOTOR VEHICLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,20,7,4,41.899325,-87.715074,POINT (-87.715074373867 41.899324573751)
3,0b5603954d84b7341c7cad4f570ea039e85919f3750ccb...,05/23/2025 09:15:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PEDALCYCLIST,NOT DIVIDED,STRAIGHT AND LEVEL,...,1.0,0.0,2.0,0.0,9,6,5,41.902793,-87.699412,POINT (-87.699412181285 41.902792968177)
4,00bce77960c2faa2a8782a8cac1d6e5715802d6c072a08...,01/14/2025 08:00:00 AM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,SNOW,DAYLIGHT,REAR END,FOUR WAY,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,8,3,1,41.691207,-87.720555,POINT (-87.720554863466 41.691206664451)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984007,74e09beb0f06ce78bf40d93a4f9f95ce642840ce8b494f...,08/07/2025 06:40:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,18,5,8,42.012120,-87.690100,POINT (-87.690099690923 42.012120373394)
984008,fca94c41825b3c63cca216b3187a67bc0ae13f06eaa54f...,08/16/2025 11:50:00 PM,30,NO CONTROLS,NO CONTROLS,UNKNOWN,"DARKNESS, LIGHTED ROAD",SIDESWIPE OPPOSITE DIRECTION,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,23,7,8,41.778225,-87.747206,POINT (-87.747206294662 41.778224612839)
984009,fd38884c12b125e32a573636e90e7f9250f9ffb783b35b...,08/17/2025 02:00:00 PM,30,STOP SIGN/FLASHER,NOT FUNCTIONING,CLEAR,DAYLIGHT,TURNING,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,14,1,8,41.838002,-87.641182,POINT (-87.641182383332 41.838001538617)
984010,0139b4c5805211169bb2794826b44b725ad58e935139bb...,08/18/2025 12:08:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",PARKED MOTOR VEHICLE,ONE-WAY,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,0,2,8,41.904205,-87.678698,POINT (-87.678698087004 41.904205053083)
984011,5a51307d8d8ae05db31500943a14ed5bb786886d87f7fa...,08/18/2025 12:24:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",TURNING,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,0,2,8,41.720684,-87.536644,POINT (-87.536644107447 41.720683731954)

## Creating a backup

In [13]:
df_cp2 = df_cp1.copy()

In [14]:
df_cp2.columns

Index(['CRASH_RECORD_ID', 'CRASH_DATE', 'POSTED_SPEED_LIMIT',
       'TRAFFIC_CONTROL_DEVICE', 'DEVICE_CONDITION', 'WEATHER_CONDITION',
       'LIGHTING_CONDITION', 'FIRST_CRASH_TYPE', 'TRAFFICWAY_TYPE',
       'ALIGNMENT', 'ROADWAY_SURFACE_COND', 'ROAD_DEFECT', 'REPORT_TYPE',
       'CRASH_TYPE', 'HIT_AND_RUN_I', 'DAMAGE', 'DATE_POLICE_NOTIFIED',
       'PRIM_CONTRIBUTORY_CAUSE', 'SEC_CONTRIBUTORY_CAUSE', 'STREET_NO',
       'STREET_DIRECTION', 'STREET_NAME', 'BEAT_OF_OCCURRENCE', 'NUM_UNITS',
       'MOST_SEVERE_INJURY', 'INJURIES_TOTAL', 'INJURIES_FATAL',
       'INJURIES_INCAPACITATING', 'INJURIES_NON_INCAPACITATING',
       'INJURIES_REPORTED_NOT_EVIDENT', 'INJURIES_NO_INDICATION',
       'INJURIES_UNKNOWN', 'CRASH_HOUR', 'CRASH_DAY_OF_WEEK', 'CRASH_MONTH',
       'LATITUDE', 'LONGITUDE', 'LOCATION'],
      dtype='object')

# Checking and Validating data

In [15]:
df_cp2.loc[:, 'CRASH_DATE']

0         01/14/2025 12:25:00 PM
1         05/23/2025 09:30:00 AM
2         04/05/2025 08:00:00 PM
3         05/23/2025 09:15:00 AM
4         01/14/2025 08:00:00 AM
                   ...
984007    08/07/2025 06:40:00 PM
984008    08/16/2025 11:50:00 PM
984009    08/17/2025 02:00:00 PM
984010    08/18/2025 12:08:00 AM
984011    08/18/2025 12:24:00 AM
Name: CRASH_DATE, Length: 984012, dtype: object

Unifying proper formatting for pd.Timestamp data type

In [16]:
df_cp2.loc[:, 'POSTED_SPEED_LIMIT']

0         30
1         30
2         30
3         30
4         30
          ..
984007    30
984008    30
984009    30
984010    30
984011    30
Name: POSTED_SPEED_LIMIT, Length: 984012, dtype: int64

Quick check of values

In [17]:
minimum = df_cp2.loc[:, 'POSTED_SPEED_LIMIT'].min()
maximum = df_cp2.loc[:, 'POSTED_SPEED_LIMIT'].max()
average = df_cp2.loc[:, 'POSTED_SPEED_LIMIT'].mean()
log.info(f'Min/Max/Avg POSTED_SPEED_LIMIT {minimum}/{maximum}/{average}')

PortfolioLogger.chicago_traffic_crashes: INFO: Min/Max/Avg POSTED_SPEED_LIMIT 0/99/28.423204188566807

Valid values, no need to clean this column

Checking for categories

In [18]:
df_cp2.loc[:, 'DEVICE_CONDITION'].unique()

array(['FUNCTIONING PROPERLY', 'UNKNOWN', 'NO CONTROLS',
       'FUNCTIONING IMPROPERLY', 'OTHER', 'NOT FUNCTIONING',
       'WORN REFLECTIVE MATERIAL', 'MISSING'], dtype=object)

In [19]:
df_cp2.loc[:, 'WEATHER_CONDITION'].unique()

array(['SNOW', 'UNKNOWN', 'CLEAR', 'RAIN', 'CLOUDY/OVERCAST',
       'FREEZING RAIN/DRIZZLE', 'SLEET/HAIL', 'OTHER', 'BLOWING SNOW',
       'SEVERE CROSS WIND GATE', 'FOG/SMOKE/HAZE',
       'BLOWING SAND, SOIL, DIRT'], dtype=object)

To keep with current formatting, switching 'BLOWING SAND, SOIL, DIRT' to '/'

In [20]:
df_cp2.loc[:, 'WEATHER_CONDITION'] = df_cp2.loc[:, 'WEATHER_CONDITION'].str.replace(', ', '/')
df_cp2.loc[:, 'WEATHER_CONDITION'].unique()

array(['SNOW', 'UNKNOWN', 'CLEAR', 'RAIN', 'CLOUDY/OVERCAST',
       'FREEZING RAIN/DRIZZLE', 'SLEET/HAIL', 'OTHER', 'BLOWING SNOW',
       'SEVERE CROSS WIND GATE', 'FOG/SMOKE/HAZE',
       'BLOWING SAND/SOIL/DIRT'], dtype=object)

In [21]:
df_cp2.loc[:, 'LIGHTING_CONDITION'].unique()

array(['DAYLIGHT', 'UNKNOWN', 'DARKNESS, LIGHTED ROAD', 'DARKNESS',
       'DUSK', 'DAWN'], dtype=object)

In [22]:
df_cp2.loc[:, 'FIRST_CRASH_TYPE'].unique()

array(['SIDESWIPE SAME DIRECTION', 'TURNING', 'PARKED MOTOR VEHICLE',
       'PEDALCYCLIST', 'REAR END', 'ANGLE',
       'SIDESWIPE OPPOSITE DIRECTION', 'FIXED OBJECT', 'PEDESTRIAN',
       'REAR TO SIDE', 'HEAD ON', 'REAR TO FRONT', 'OTHER OBJECT',
       'OTHER NONCOLLISION', 'REAR TO REAR', 'OVERTURNED', 'ANIMAL',
       'TRAIN'], dtype=object)

In [23]:
df_cp2['TRAFFICWAY_TYPE'].unique()

array(['DIVIDED - W/MEDIAN (NOT RAISED)', 'NOT DIVIDED', 'FOUR WAY',
       'DIVIDED - W/MEDIAN BARRIER', 'ONE-WAY', 'PARKING LOT', 'UNKNOWN',
       'T-INTERSECTION', 'OTHER', 'TRAFFIC ROUTE', 'DRIVEWAY',
       'UNKNOWN INTERSECTION TYPE', 'ALLEY', 'Y-INTERSECTION',
       'FIVE POINT, OR MORE', 'L-INTERSECTION', 'RAMP',
       'CENTER TURN LANE', 'NOT REPORTED', 'ROUNDABOUT'], dtype=object)

In [24]:
df_cp2['ALIGNMENT'].unique()

array(['STRAIGHT AND LEVEL', 'STRAIGHT ON GRADE', 'STRAIGHT ON HILLCREST',
       'CURVE, LEVEL', 'CURVE ON GRADE', 'CURVE ON HILLCREST'],
      dtype=object)

In [25]:
df_cp2['ROADWAY_SURFACE_COND'].unique()

array(['SNOW OR SLUSH', 'UNKNOWN', 'DRY', 'WET', 'ICE', 'OTHER',
       'SAND, MUD, DIRT'], dtype=object)

In [26]:
df_cp2['ROAD_DEFECT'].unique()

array(['NO DEFECTS', 'UNKNOWN', 'SHOULDER DEFECT', 'WORN SURFACE',
       'RUT, HOLES', 'OTHER', 'DEBRIS ON ROADWAY'], dtype=object)

In [27]:
df_cp2.columns

Index(['CRASH_RECORD_ID', 'CRASH_DATE', 'POSTED_SPEED_LIMIT',
       'TRAFFIC_CONTROL_DEVICE', 'DEVICE_CONDITION', 'WEATHER_CONDITION',
       'LIGHTING_CONDITION', 'FIRST_CRASH_TYPE', 'TRAFFICWAY_TYPE',
       'ALIGNMENT', 'ROADWAY_SURFACE_COND', 'ROAD_DEFECT', 'REPORT_TYPE',
       'CRASH_TYPE', 'HIT_AND_RUN_I', 'DAMAGE', 'DATE_POLICE_NOTIFIED',
       'PRIM_CONTRIBUTORY_CAUSE', 'SEC_CONTRIBUTORY_CAUSE', 'STREET_NO',
       'STREET_DIRECTION', 'STREET_NAME', 'BEAT_OF_OCCURRENCE', 'NUM_UNITS',
       'MOST_SEVERE_INJURY', 'INJURIES_TOTAL', 'INJURIES_FATAL',
       'INJURIES_INCAPACITATING', 'INJURIES_NON_INCAPACITATING',
       'INJURIES_REPORTED_NOT_EVIDENT', 'INJURIES_NO_INDICATION',
       'INJURIES_UNKNOWN', 'CRASH_HOUR', 'CRASH_DAY_OF_WEEK', 'CRASH_MONTH',
       'LATITUDE', 'LONGITUDE', 'LOCATION'],
      dtype='object')

In [28]:
df_cp2['REPORT_TYPE'].unique()

array(['ON SCENE', 'NOT ON SCENE (DESK REPORT)', 'Not Available',
       'AMENDED'], dtype=object)

In [29]:
df_cp2['CRASH_TYPE'].unique()

array(['NO INJURY / DRIVE AWAY', 'INJURY AND / OR TOW DUE TO CRASH'],
      dtype=object)

In [30]:
df_cp2['HIT_AND_RUN_I'].unique()

array(['Y', 'Not Available', 'N'], dtype=object)

In [31]:
df_cp2['DAMAGE'].unique()

array(['$501 - $1,500', 'OVER $1,500', '$500 OR LESS'], dtype=object)

In [32]:
df_cp2['DATE_POLICE_NOTIFIED'].unique()

array(['01/14/2025 12:38:00 PM', '05/27/2025 10:40:00 AM',
       '04/05/2025 09:23:00 PM', ..., '08/16/2025 11:55:00 PM',
       '08/18/2025 12:09:00 AM', '08/18/2025 12:28:00 AM'],
      shape=(744929,), dtype=object)

In [33]:
df_cp2['PRIM_CONTRIBUTORY_CAUSE'].unique()

array(['IMPROPER TURNING/NO SIGNAL', 'IMPROPER OVERTAKING/PASSING',
       'UNABLE TO DETERMINE', 'FOLLOWING TOO CLOSELY',
       'DISREGARDING TRAFFIC SIGNALS', 'IMPROPER LANE USAGE',
       'FAILING TO YIELD RIGHT-OF-WAY', 'NOT APPLICABLE',
       'UNDER THE INFLUENCE OF ALCOHOL/DRUGS (USE WHEN ARREST IS EFFECTED)',
       'FAILING TO REDUCE SPEED TO AVOID CRASH',
       'DRIVING SKILLS/KNOWLEDGE/EXPERIENCE', 'WEATHER',
       'DISREGARDING STOP SIGN', 'IMPROPER BACKING',
       'OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELESS, NEGLIGENT OR AGGRESSIVE MANNER',
       'TURNING RIGHT ON RED', 'PHYSICAL CONDITION OF DRIVER',
       'EQUIPMENT - VEHICLE CONDITION', 'DRIVING ON WRONG SIDE/WRONG WAY',
       'DISREGARDING ROAD MARKINGS',
       'EVASIVE ACTION DUE TO ANIMAL, OBJECT, NONMOTORIST',
       'ROAD ENGINEERING/SURFACE/MARKING DEFECTS',
       'VISION OBSCURED (SIGNS, TREE LIMBS, BUILDINGS, ETC.)',
       'DISTRACTION - FROM OUTSIDE VEHICLE',
       'DISTRACTION - OTHER ELECTRONIC DEVICE (NAVIGATION DEVICE, DVD PLAYER, ETC.)',
       'TEXTING', 'ROAD CONSTRUCTION/MAINTENANCE',
       'HAD BEEN DRINKING (USE WHEN ARREST IS NOT MADE)',
       'DISTRACTION - FROM INSIDE VEHICLE',
       'CELL PHONE USE OTHER THAN TEXTING', 'ANIMAL',
       'DISREGARDING OTHER TRAFFIC SIGNS', 'RELATED TO BUS STOP',
       'OBSTRUCTED CROSSWALKS', 'DISREGARDING YIELD SIGN',
       'PASSING STOPPED SCHOOL BUS',
       'BICYCLE ADVANCING LEGALLY ON RED LIGHT',
       'MOTORCYCLE ADVANCING LEGALLY ON RED LIGHT',
       'EXCEEDING AUTHORIZED SPEED LIMIT',
       'EXCEEDING SAFE SPEED FOR CONDITIONS'], dtype=object)

In [34]:
df_cp2['SEC_CONTRIBUTORY_CAUSE'].unique()

array(['IMPROPER OVERTAKING/PASSING', 'UNABLE TO DETERMINE',
       'FOLLOWING TOO CLOSELY', 'NOT APPLICABLE',
       'FAILING TO YIELD RIGHT-OF-WAY',
       'DRIVING SKILLS/KNOWLEDGE/EXPERIENCE', 'WEATHER',
       'FAILING TO REDUCE SPEED TO AVOID CRASH',
       'PHYSICAL CONDITION OF DRIVER', 'IMPROPER LANE USAGE',
       'OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELESS, NEGLIGENT OR AGGRESSIVE MANNER',
       'IMPROPER BACKING', 'DISREGARDING STOP SIGN',
       'UNDER THE INFLUENCE OF ALCOHOL/DRUGS (USE WHEN ARREST IS EFFECTED)',
       'IMPROPER TURNING/NO SIGNAL', 'ROAD CONSTRUCTION/MAINTENANCE',
       'DRIVING ON WRONG SIDE/WRONG WAY', 'DISREGARDING TRAFFIC SIGNALS',
       'EVASIVE ACTION DUE TO ANIMAL, OBJECT, NONMOTORIST',
       'EQUIPMENT - VEHICLE CONDITION',
       'CELL PHONE USE OTHER THAN TEXTING',
       'VISION OBSCURED (SIGNS, TREE LIMBS, BUILDINGS, ETC.)',
       'DISTRACTION - FROM OUTSIDE VEHICLE',
       'ROAD ENGINEERING/SURFACE/MARKING DEFECTS', 'TEXTING',
       'TURNING RIGHT ON RED', 'RELATED TO BUS STOP', 'ANIMAL',
       'DISTRACTION - FROM INSIDE VEHICLE',
       'DISREGARDING OTHER TRAFFIC SIGNS', 'DISREGARDING YIELD SIGN',
       'HAD BEEN DRINKING (USE WHEN ARREST IS NOT MADE)',
       'DISTRACTION - OTHER ELECTRONIC DEVICE (NAVIGATION DEVICE, DVD PLAYER, ETC.)',
       'PASSING STOPPED SCHOOL BUS', 'DISREGARDING ROAD MARKINGS',
       'OBSTRUCTED CROSSWALKS',
       'MOTORCYCLE ADVANCING LEGALLY ON RED LIGHT',
       'EXCEEDING SAFE SPEED FOR CONDITIONS',
       'BICYCLE ADVANCING LEGALLY ON RED LIGHT',
       'EXCEEDING AUTHORIZED SPEED LIMIT'], dtype=object)

In [35]:
df_cp2['STREET_NO']

0         6352
1         3555
2         1005
3         2901
4         4001
          ...
984007    7137
984008    5001
984009     555
984010    2034
984011    9620
Name: STREET_NO, Length: 984012, dtype: int64

In [36]:
df_cp2['STREET_DIRECTION'].unique()

array(['N', 'W', 'S', 'E', 'Not Available'], dtype=object)

In [37]:
df_cp2['STREET_DIRECTION'].value_counts()['Not Available']

np.int64(4)

In [38]:
df_cp2['BEAT_OF_OCCURRENCE']

0         2433.0
1         1921.0
2         1121.0
3         1211.0
4         2211.0
           ...
984007    2411.0
984008     813.0
984009     915.0
984010    1424.0
984011     432.0
Name: BEAT_OF_OCCURRENCE, Length: 984012, dtype: float64

In [39]:
df_cp2['NUM_UNITS'].unique()

array([ 2,  1,  5,  3,  4,  6,  7, 10,  8, 14, 12, 18, 11,  9, 16, 13, 15])

In [40]:
df_cp2['MOST_SEVERE_INJURY'].unique()

array(['NO INDICATION OF INJURY', 'NONINCAPACITATING INJURY',
       'REPORTED, NOT EVIDENT', 'INCAPACITATING INJURY', 'FATAL',
       'Not Available'], dtype=object)

In [41]:
df_cp2['INJURIES_TOTAL'].unique()

array([ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ,
        6.        ,  4.        ,  0.19713507,  7.        , 11.        ,
        8.        ,  9.        , 19.        , 15.        , 10.        ,
       21.        , 17.        , 12.        , 14.        , 13.        ,
       16.        ])

In [42]:
df_cp2['INJURIES_FATAL'].unique()

array([0.00000000e+00, 1.00000000e+00, 1.15697008e-03, 2.00000000e+00,
       3.00000000e+00, 4.00000000e+00])

In [43]:
df_cp2['INJURIES_INCAPACITATING'].unique()

array([ 0.        ,  1.        ,  2.        ,  0.01936397,  3.        ,
        5.        ,  4.        ,  6.        ,  7.        , 10.        ,
        8.        ])

In [44]:
sorted(df_cp2['INJURIES_NON_INCAPACITATING'].astype(int).unique())

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(18),
 np.int64(19),
 np.int64(21)]

In [45]:
sorted(df_cp2['INJURIES_REPORTED_NOT_EVIDENT'].astype(int).unique())

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(15),
 np.int64(19)]

In [46]:
sorted(df_cp2['INJURIES_NO_INDICATION'].astype(int).unique())

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(19),
 np.int64(20),
 np.int64(21),
 np.int64(22),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(26),
 np.int64(27),
 np.int64(28),
 np.int64(29),
 np.int64(30),
 np.int64(31),
 np.int64(32),
 np.int64(33),
 np.int64(34),
 np.int64(35),
 np.int64(36),
 np.int64(37),
 np.int64(38),
 np.int64(39),
 np.int64(40),
 np.int64(41),
 np.int64(42),
 np.int64(43),
 np.int64(45),
 np.int64(46),
 np.int64(48),
 np.int64(49),
 np.int64(50),
 np.int64(61)]

In [47]:
sorted(df_cp2['INJURIES_UNKNOWN'].astype(int).unique())

[np.int64(0)]

In [48]:
df_cp2['CRASH_HOUR'].unique() > 24

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [49]:
df_cp2['CRASH_DAY_OF_WEEK'].unique() > 7

array([False, False, False, False, False, False, False])

In [50]:
df_cp2['CRASH_MONTH'].unique() > 12

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [51]:
df_cp2['LATITUDE']

0         41.997808
1         41.946529
2         41.899325
3         41.902793
4         41.691207
            ...
984007    42.012120
984008    41.778225
984009    41.838002
984010    41.904205
984011    41.720684
Name: LATITUDE, Length: 984012, dtype: float64

In [52]:
df_cp2['LONGITUDE']

0        -87.655770
1        -87.688106
2        -87.715074
3        -87.699412
4        -87.720555
            ...
984007   -87.690100
984008   -87.747206
984009   -87.641182
984010   -87.678698
984011   -87.536644
Name: LONGITUDE, Length: 984012, dtype: float64

In [53]:
df_cp2['LOCATION']

0         POINT (-87.655770494712 41.997807727633)
1         POINT (-87.688106391039 41.946529480518)
2         POINT (-87.715074373867 41.899324573751)
3         POINT (-87.699412181285 41.902792968177)
4         POINT (-87.720554863466 41.691206664451)
                            ...
984007    POINT (-87.690099690923 42.012120373394)
984008    POINT (-87.747206294662 41.778224612839)
984009    POINT (-87.641182383332 41.838001538617)
984010    POINT (-87.678698087004 41.904205053083)
984011    POINT (-87.536644107447 41.720683731954)
Name: LOCATION, Length: 984012, dtype: object

## Creating lists to process

In [54]:
to_drop = [
    'CRASH_RECORD_ID',
    'STREET_NAME',
    'STREET_NO',
    'STREET_DIRECTION',
    'BEAT_OF_OCCURRENCE',
    'MOST_SEVERE_INJURY', # Repeated in other INJURY_* columns
    'CRASH_HOUR',  # repeated in CRASH_DATE
    'CRASH_DAY_OF_WEEK',  # repeated in CRASH_DATE
    'CRASH_MONTH',  # repeated in CRASH_DATE
    'NUM_UNITS', # Would need clarification what this means
    'LOCATION'
]

# Convert to Timestamp
to_datetime = [
    'CRASH_DATE',
    'DATE_POLICE_NOTIFIED',
]

to_consolidate = [
    'WEATHER_CONDITION',
    'TRAFFIC_CONTROL_DEVICE',
    'DEVICE_CONDITION',
    'FIRST_CRASH_TYPE', #?
    'ALIGNMENT,'
    'TRAFFICWAY_TYPE',
    'ROADWAY_SURFACE_COND',
    'ROAD_DEFECT',
    'PRIM_CONTRIBUTORY_CAUSE',
    'SEC_CONTRIBUTORY_CAUSE',
    'ROADWAY_SURFACE_COND'

]

to_bools_manual = [
    'REPORT_TYPE', # Change to ON_SCENE
    'CRASH_TYPE', # Change to REPORTABLE
    'HIT_AND_RUN_I'
]

to_ints_manual = [
    'DAMAGE'
]

to_ints = [
    'INJURIES_TOTAL',
    'INJURIES_FATAL',
    'INJURIES_INCAPACITATING',
    'INJURIES_NON_INCAPACITATING',
    'INJURIES_REPORTED_NOT_EVIDENT',
    'INJURIES_NO_INDICATION'
]

# No need to check these
valid = [
    'POSTED_SPEED_LIMIT',
    'LIGHTING_CONDITION',
    'LATITUDE',
    'LONGITUDE',
]

keys2 = to_consolidate + to_bools_manual + to_ints_manual + to_ints + to_datetime + to_drop + valid
diff = set(df_cp2.columns).difference(set(keys2))
log.debug(f'Diff {diff}: {df_cp2.shape[1]}/{len(keys2)}')

PortfolioLogger.chicago_traffic_crashes: DEBUG: Diff {'INJURIES_UNKNOWN', 'TRAFFICWAY_TYPE', 'ALIGNMENT'}: 38/37

## Creating a backup

In [55]:
df_cp3 = df_cp2.copy()

## Dropping unneeded Columns

In [56]:
df_cp3 = df_cp3.drop(to_drop, axis=1)

# Begin Cleaning Process

## Stripping whitespaces from DataFrame

In [57]:
df_cp3 = lib.str_strip(df_cp3)

## Converting Datetime columns

In [58]:
for column in to_datetime:
    df_cp3[column] = pd.to_datetime(df_cp3.loc[:, column], format='%m/%d/%Y %I:%M:%S %p')

In [59]:
df_cp3[to_datetime]

                CRASH_DATE DATE_POLICE_NOTIFIED
0      2025-01-14 12:25:00  2025-01-14 12:38:00
1      2025-05-23 09:30:00  2025-05-27 10:40:00
2      2025-04-05 20:00:00  2025-04-05 21:23:00
3      2025-05-23 09:15:00  2025-05-23 09:16:00
4      2025-01-14 08:00:00  2025-01-14 08:45:00
...                    ...                  ...
984007 2025-08-07 18:40:00  2025-08-08 15:30:00
984008 2025-08-16 23:50:00  2025-08-16 23:55:00
984009 2025-08-17 14:00:00  2025-08-18 15:30:00
984010 2025-08-18 00:08:00  2025-08-18 00:09:00
984011 2025-08-18 00:24:00  2025-08-18 00:28:00

[984012 rows x 2 columns]

## Converting Ints columns

In [60]:
df_cp3['DAMAGE']

0         $501 - $1,500
1           OVER $1,500
2           OVER $1,500
3          $500 OR LESS
4           OVER $1,500
              ...
984007    $501 - $1,500
984008      OVER $1,500
984009     $500 OR LESS
984010      OVER $1,500
984011      OVER $1,500
Name: DAMAGE, Length: 984012, dtype: object

In [61]:
# Converting to ints
df_cp3['DAMAGE'] = df_cp3['DAMAGE'].replace('$500 OR LESS', 0)
df_cp3['DAMAGE'] = df_cp3['DAMAGE'].replace('$501 - $1,500', 1)
df_cp3['DAMAGE'] = df_cp3['DAMAGE'].replace('OVER $1,500', 2)
df_cp3['DAMAGE'].astype(int)

/var/folders/_9/nyjys43x4nv6dxyk3y75vzh80000gn/T/ipykernel_2458/2964060824.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_cp3['DAMAGE'] = df_cp3['DAMAGE'].replace('OVER $1,500', 2)

0         1
1         2
2         2
3         0
4         2
         ..
984007    1
984008    2
984009    0
984010    2
984011    2
Name: DAMAGE, Length: 984012, dtype: int64

In [62]:
for column in to_ints:
    df_cp3[column] = df_cp3[column].astype(int)

## Converting Bools columns
-1 for Not Available
0 for False
1 for True

Renaming 'REPORT_TYPE' to 'ON_SCENE'

In [63]:
df_cp3['REPORT_TYPE'].unique()

array(['ON SCENE', 'NOT ON SCENE (DESK REPORT)', 'Not Available',
       'AMENDED'], dtype=object)

Change to ON_SCENE

In [64]:
df_cp3.loc[:, 'REPORT_TYPE'] = df_cp3['REPORT_TYPE'].replace(
    {
        'ON SCENE': 1,
        'NOT ON SCENE (DESK REPORT)': 0,
        'Not Available': -1,
     }
)

In [65]:
df_cp3 = df_cp3.rename({'REPORT_TYPE': 'ON_SCENE'}, axis=1)
df_cp3.loc[:, 'ON_SCENE']

0          1
1          0
2          1
3          1
4          0
          ..
984007     0
984008     1
984009     0
984010    -1
984011     1
Name: ON_SCENE, Length: 984012, dtype: object

In [66]:
df_cp3.columns

Index(['CRASH_DATE', 'POSTED_SPEED_LIMIT', 'TRAFFIC_CONTROL_DEVICE',
       'DEVICE_CONDITION', 'WEATHER_CONDITION', 'LIGHTING_CONDITION',
       'FIRST_CRASH_TYPE', 'TRAFFICWAY_TYPE', 'ALIGNMENT',
       'ROADWAY_SURFACE_COND', 'ROAD_DEFECT', 'ON_SCENE', 'CRASH_TYPE',
       'HIT_AND_RUN_I', 'DAMAGE', 'DATE_POLICE_NOTIFIED',
       'PRIM_CONTRIBUTORY_CAUSE', 'SEC_CONTRIBUTORY_CAUSE', 'INJURIES_TOTAL',
       'INJURIES_FATAL', 'INJURIES_INCAPACITATING',
       'INJURIES_NON_INCAPACITATING', 'INJURIES_REPORTED_NOT_EVIDENT',
       'INJURIES_NO_INDICATION', 'INJURIES_UNKNOWN', 'LATITUDE', 'LONGITUDE'],
      dtype='object')

Renaming to REPORTABLE

In [67]:
df_cp3['CRASH_TYPE'].unique()

array(['NO INJURY / DRIVE AWAY', 'INJURY AND / OR TOW DUE TO CRASH'],
      dtype=object)

In [68]:
df_cp3.loc[:, 'CRASH_TYPE'] = df_cp3['CRASH_TYPE'].replace(
    {
        'NO INJURY / DRIVE AWAY': False,
        'INJURY AND / OR TOW DUE TO CRASH': True,
     }
)

/var/folders/_9/nyjys43x4nv6dxyk3y75vzh80000gn/T/ipykernel_2458/3714322767.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_cp3.loc[:, 'CRASH_TYPE'] = df_cp3['CRASH_TYPE'].replace(

In [69]:
df_cp3 = df_cp3.rename({'CRASH_TYPE': 'REPORTABLE'}, axis=1)
df_cp3.loc[:, 'REPORTABLE']

0         False
1         False
2         False
3          True
4         False
          ...
984007    False
984008     True
984009    False
984010     True
984011     True
Name: REPORTABLE, Length: 984012, dtype: object

Renaming to HIT_AND_RUN

In [70]:
df_cp3['HIT_AND_RUN_I'].unique()

array(['Y', 'Not Available', 'N'], dtype=object)

In [71]:
df_cp3.loc[:, 'HIT_AND_RUN_I'] = df_cp3['HIT_AND_RUN_I'].replace(
    {
        'Not Available': -1,
        'N': 0,
        'Y': 1,
     }
)
df_cp3 = df_cp3.rename({'HIT_AND_RUN_I': 'HIT_AND_RUN'}, axis=1)
df_cp3.loc[:, 'HIT_AND_RUN']

/var/folders/_9/nyjys43x4nv6dxyk3y75vzh80000gn/T/ipykernel_2458/3292695733.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_cp3.loc[:, 'HIT_AND_RUN_I'] = df_cp3['HIT_AND_RUN_I'].replace(

0          1
1          1
2          1
3         -1
4         -1
          ..
984007    -1
984008     1
984009    -1
984010    -1
984011    -1
Name: HIT_AND_RUN, Length: 984012, dtype: object

## Creating a backup

In [72]:
df_cp4 = df_cp3.copy()

## Converting Consolidate column
A manual process

In [73]:
df_cp4['WEATHER_CONDITION'].unique()

array(['SNOW', 'UNKNOWN', 'CLEAR', 'RAIN', 'CLOUDY/OVERCAST',
       'FREEZING RAIN/DRIZZLE', 'SLEET/HAIL', 'OTHER', 'BLOWING SNOW',
       'SEVERE CROSS WIND GATE', 'FOG/SMOKE/HAZE',
       'BLOWING SAND/SOIL/DIRT'], dtype=object)

In [74]:
df_cp4['TRAFFIC_CONTROL_DEVICE'].unique()

array(['TRAFFIC SIGNAL', 'STOP SIGN/FLASHER', 'NO CONTROLS', 'UNKNOWN',
       'OTHER', 'LANE USE MARKING', 'PEDESTRIAN CROSSING SIGN',
       'OTHER REG. SIGN', 'OTHER WARNING SIGN', 'YIELD', 'SCHOOL ZONE',
       'FLASHING CONTROL SIGNAL', 'DELINEATORS', 'NO PASSING',
       'RAILROAD CROSSING GATE', 'POLICE/FLAGMAN', 'RR CROSSING SIGN',
       'BICYCLE CROSSING SIGN', 'OTHER RAILROAD CROSSING'], dtype=object)

In [75]:
df_cp4['DEVICE_CONDITION'].unique()

array(['FUNCTIONING PROPERLY', 'UNKNOWN', 'NO CONTROLS',
       'FUNCTIONING IMPROPERLY', 'OTHER', 'NOT FUNCTIONING',
       'WORN REFLECTIVE MATERIAL', 'MISSING'], dtype=object)

In [76]:
df_cp4['DEVICE_CONDITION'] = df_cp4['DEVICE_CONDITION'].replace(
    {
        'FUNCTIONING PROPERLY': True,
        'UNKNOWN': False,
        'NO CONTROLS': False,
        'FUNCTIONING IMPROPERLY': False,
        'OTHER': False,
        'NOT FUNCTIONING': False,
        'WORN REFLECTIVE MATERIAL': False,
        'MISSING': False,
    }
)
df_cp4 = df_cp4.rename({'DEVICE_CONDITION': 'TRAFFIC_DEVICE_FUNCTIONING'}, axis=1)
df_cp4.loc[:, 'TRAFFIC_DEVICE_FUNCTIONING']

/var/folders/_9/nyjys43x4nv6dxyk3y75vzh80000gn/T/ipykernel_2458/1568383276.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_cp4['DEVICE_CONDITION'] = df_cp4['DEVICE_CONDITION'].replace(

0          True
1         False
2         False
3         False
4          True
          ...
984007     True
984008    False
984009    False
984010    False
984011    False
Name: TRAFFIC_DEVICE_FUNCTIONING, Length: 984012, dtype: bool

In [77]:
df_cp4['FIRST_CRASH_TYPE'].unique()

array(['SIDESWIPE SAME DIRECTION', 'TURNING', 'PARKED MOTOR VEHICLE',
       'PEDALCYCLIST', 'REAR END', 'ANGLE',
       'SIDESWIPE OPPOSITE DIRECTION', 'FIXED OBJECT', 'PEDESTRIAN',
       'REAR TO SIDE', 'HEAD ON', 'REAR TO FRONT', 'OTHER OBJECT',
       'OTHER NONCOLLISION', 'REAR TO REAR', 'OVERTURNED', 'ANIMAL',
       'TRAIN'], dtype=object)

In [78]:
# collision, fixed, movement, nonmotorist
df_cp4['FIRST_CRASH_TYPE'] = df_cp4['FIRST_CRASH_TYPE'].replace(
    {
        'SIDESWIPE SAME DIRECTION': 'Collision',
        'SIDESWIPE OPPOSITE DIRECTION': 'Collision',
        'REAR END': 'Collision',
        'REAR TO SIDE': 'Collision',
        'HEAD ON': 'Collision',
        'REAR TO FRONT': 'Collision',
        'OTHER OBJECT': 'Collision',
        'REAR TO REAR': 'Collision',

        'PARKED MOTOR VEHICLE': 'Fixed',
        'FIXED OBJECT': 'Fixed',
        'TRAIN': 'Fixed',

        'TURNING': 'Movement',
        'ANGLE': 'Movement',
        'OVERTURNED': 'Movement',

        'PEDALCYCLIST': 'Non-motorist',
        'PEDESTRIAN': 'Non-motorist',
        'ANIMAL': 'Non-motorist',

        'OTHER NONCOLLISION': 'OTHER NONCOLLISION',
    }
)
df_cp4 = df_cp4.rename({'FIRST_CRASH_TYPE': 'CRASH_TYPE'}, axis=1)
df_cp4.loc[:, 'CRASH_TYPE']

0            Collision
1             Movement
2                Fixed
3         Non-motorist
4            Collision
              ...
984007       Collision
984008       Collision
984009        Movement
984010           Fixed
984011        Movement
Name: CRASH_TYPE, Length: 984012, dtype: object

In [79]:
df_cp4['TRAFFICWAY_TYPE'].unique()

array(['DIVIDED - W/MEDIAN (NOT RAISED)', 'NOT DIVIDED', 'FOUR WAY',
       'DIVIDED - W/MEDIAN BARRIER', 'ONE-WAY', 'PARKING LOT', 'UNKNOWN',
       'T-INTERSECTION', 'OTHER', 'TRAFFIC ROUTE', 'DRIVEWAY',
       'UNKNOWN INTERSECTION TYPE', 'ALLEY', 'Y-INTERSECTION',
       'FIVE POINT, OR MORE', 'L-INTERSECTION', 'RAMP',
       'CENTER TURN LANE', 'NOT REPORTED', 'ROUNDABOUT'], dtype=object)

In [80]:
df_cp4['ROADWAY_SURFACE_COND'].unique()

array(['SNOW OR SLUSH', 'UNKNOWN', 'DRY', 'WET', 'ICE', 'OTHER',
       'SAND, MUD, DIRT'], dtype=object)

In [81]:
df_cp4['ROAD_DEFECT'].unique()

array(['NO DEFECTS', 'UNKNOWN', 'SHOULDER DEFECT', 'WORN SURFACE',
       'RUT, HOLES', 'OTHER', 'DEBRIS ON ROADWAY'], dtype=object)

In [82]:
df_cp4['ROAD_DEFECT'] = df_cp3['ROAD_DEFECT']

In [83]:
df_cp4['ROAD_DEFECT'] = df_cp4['ROAD_DEFECT'].replace(
    {
        'NO DEFECTS': False,
        'UNKNOWN': True,
        'SHOULDER DEFECT': True,
        'WORN SURFACE': True,
        'RUT, HOLES': True,
        'OTHER': True,
        'DEBRIS ON ROADWAY': True
    }
)

/var/folders/_9/nyjys43x4nv6dxyk3y75vzh80000gn/T/ipykernel_2458/2626659515.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_cp4['ROAD_DEFECT'] = df_cp4['ROAD_DEFECT'].replace(

In [84]:
df_cp4['PRIM_CONTRIBUTORY_CAUSE'].unique()

array(['IMPROPER TURNING/NO SIGNAL', 'IMPROPER OVERTAKING/PASSING',
       'UNABLE TO DETERMINE', 'FOLLOWING TOO CLOSELY',
       'DISREGARDING TRAFFIC SIGNALS', 'IMPROPER LANE USAGE',
       'FAILING TO YIELD RIGHT-OF-WAY', 'NOT APPLICABLE',
       'UNDER THE INFLUENCE OF ALCOHOL/DRUGS (USE WHEN ARREST IS EFFECTED)',
       'FAILING TO REDUCE SPEED TO AVOID CRASH',
       'DRIVING SKILLS/KNOWLEDGE/EXPERIENCE', 'WEATHER',
       'DISREGARDING STOP SIGN', 'IMPROPER BACKING',
       'OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELESS, NEGLIGENT OR AGGRESSIVE MANNER',
       'TURNING RIGHT ON RED', 'PHYSICAL CONDITION OF DRIVER',
       'EQUIPMENT - VEHICLE CONDITION', 'DRIVING ON WRONG SIDE/WRONG WAY',
       'DISREGARDING ROAD MARKINGS',
       'EVASIVE ACTION DUE TO ANIMAL, OBJECT, NONMOTORIST',
       'ROAD ENGINEERING/SURFACE/MARKING DEFECTS',
       'VISION OBSCURED (SIGNS, TREE LIMBS, BUILDINGS, ETC.)',
       'DISTRACTION - FROM OUTSIDE VEHICLE',
       'DISTRACTION - OTHER ELECTRONIC DEVICE (NAVIGATION DEVICE, DVD PLAYER, ETC.)',
       'TEXTING', 'ROAD CONSTRUCTION/MAINTENANCE',
       'HAD BEEN DRINKING (USE WHEN ARREST IS NOT MADE)',
       'DISTRACTION - FROM INSIDE VEHICLE',
       'CELL PHONE USE OTHER THAN TEXTING', 'ANIMAL',
       'DISREGARDING OTHER TRAFFIC SIGNS', 'RELATED TO BUS STOP',
       'OBSTRUCTED CROSSWALKS', 'DISREGARDING YIELD SIGN',
       'PASSING STOPPED SCHOOL BUS',
       'BICYCLE ADVANCING LEGALLY ON RED LIGHT',
       'MOTORCYCLE ADVANCING LEGALLY ON RED LIGHT',
       'EXCEEDING AUTHORIZED SPEED LIMIT',
       'EXCEEDING SAFE SPEED FOR CONDITIONS'], dtype=object)

In [85]:
df_cp4['SEC_CONTRIBUTORY_CAUSE'].unique()

array(['IMPROPER OVERTAKING/PASSING', 'UNABLE TO DETERMINE',
       'FOLLOWING TOO CLOSELY', 'NOT APPLICABLE',
       'FAILING TO YIELD RIGHT-OF-WAY',
       'DRIVING SKILLS/KNOWLEDGE/EXPERIENCE', 'WEATHER',
       'FAILING TO REDUCE SPEED TO AVOID CRASH',
       'PHYSICAL CONDITION OF DRIVER', 'IMPROPER LANE USAGE',
       'OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELESS, NEGLIGENT OR AGGRESSIVE MANNER',
       'IMPROPER BACKING', 'DISREGARDING STOP SIGN',
       'UNDER THE INFLUENCE OF ALCOHOL/DRUGS (USE WHEN ARREST IS EFFECTED)',
       'IMPROPER TURNING/NO SIGNAL', 'ROAD CONSTRUCTION/MAINTENANCE',
       'DRIVING ON WRONG SIDE/WRONG WAY', 'DISREGARDING TRAFFIC SIGNALS',
       'EVASIVE ACTION DUE TO ANIMAL, OBJECT, NONMOTORIST',
       'EQUIPMENT - VEHICLE CONDITION',
       'CELL PHONE USE OTHER THAN TEXTING',
       'VISION OBSCURED (SIGNS, TREE LIMBS, BUILDINGS, ETC.)',
       'DISTRACTION - FROM OUTSIDE VEHICLE',
       'ROAD ENGINEERING/SURFACE/MARKING DEFECTS', 'TEXTING',
       'TURNING RIGHT ON RED', 'RELATED TO BUS STOP', 'ANIMAL',
       'DISTRACTION - FROM INSIDE VEHICLE',
       'DISREGARDING OTHER TRAFFIC SIGNS', 'DISREGARDING YIELD SIGN',
       'HAD BEEN DRINKING (USE WHEN ARREST IS NOT MADE)',
       'DISTRACTION - OTHER ELECTRONIC DEVICE (NAVIGATION DEVICE, DVD PLAYER, ETC.)',
       'PASSING STOPPED SCHOOL BUS', 'DISREGARDING ROAD MARKINGS',
       'OBSTRUCTED CROSSWALKS',
       'MOTORCYCLE ADVANCING LEGALLY ON RED LIGHT',
       'EXCEEDING SAFE SPEED FOR CONDITIONS',
       'BICYCLE ADVANCING LEGALLY ON RED LIGHT',
       'EXCEEDING AUTHORIZED SPEED LIMIT'], dtype=object)

In [86]:
x = pd.Series(df_cp4['PRIM_CONTRIBUTORY_CAUSE'].unique() + df_cp4['SEC_CONTRIBUTORY_CAUSE'].unique())
x.unique()

array(['IMPROPER TURNING/NO SIGNALIMPROPER OVERTAKING/PASSING',
       'IMPROPER OVERTAKING/PASSINGUNABLE TO DETERMINE',
       'UNABLE TO DETERMINEFOLLOWING TOO CLOSELY',
       'FOLLOWING TOO CLOSELYNOT APPLICABLE',
       'DISREGARDING TRAFFIC SIGNALSFAILING TO YIELD RIGHT-OF-WAY',
       'IMPROPER LANE USAGEDRIVING SKILLS/KNOWLEDGE/EXPERIENCE',
       'FAILING TO YIELD RIGHT-OF-WAYWEATHER',
       'NOT APPLICABLEFAILING TO REDUCE SPEED TO AVOID CRASH',
       'UNDER THE INFLUENCE OF ALCOHOL/DRUGS (USE WHEN ARREST IS EFFECTED)PHYSICAL CONDITION OF DRIVER',
       'FAILING TO REDUCE SPEED TO AVOID CRASHIMPROPER LANE USAGE',
       'DRIVING SKILLS/KNOWLEDGE/EXPERIENCEOPERATING VEHICLE IN ERRATIC, RECKLESS, CARELESS, NEGLIGENT OR AGGRESSIVE MANNER',
       'WEATHERIMPROPER BACKING',
       'DISREGARDING STOP SIGNDISREGARDING STOP SIGN',
       'IMPROPER BACKINGUNDER THE INFLUENCE OF ALCOHOL/DRUGS (USE WHEN ARREST IS EFFECTED)',
       'OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELESS, NEGLIGENT OR AGGRESSIVE MANNERIMPROPER TURNING/NO SIGNAL',
       'TURNING RIGHT ON REDROAD CONSTRUCTION/MAINTENANCE',
       'PHYSICAL CONDITION OF DRIVERDRIVING ON WRONG SIDE/WRONG WAY',
       'EQUIPMENT - VEHICLE CONDITIONDISREGARDING TRAFFIC SIGNALS',
       'DRIVING ON WRONG SIDE/WRONG WAYEVASIVE ACTION DUE TO ANIMAL, OBJECT, NONMOTORIST',
       'DISREGARDING ROAD MARKINGSEQUIPMENT - VEHICLE CONDITION',
       'EVASIVE ACTION DUE TO ANIMAL, OBJECT, NONMOTORISTCELL PHONE USE OTHER THAN TEXTING',
       'ROAD ENGINEERING/SURFACE/MARKING DEFECTSVISION OBSCURED (SIGNS, TREE LIMBS, BUILDINGS, ETC.)',
       'VISION OBSCURED (SIGNS, TREE LIMBS, BUILDINGS, ETC.)DISTRACTION - FROM OUTSIDE VEHICLE',
       'DISTRACTION - FROM OUTSIDE VEHICLEROAD ENGINEERING/SURFACE/MARKING DEFECTS',
       'DISTRACTION - OTHER ELECTRONIC DEVICE (NAVIGATION DEVICE, DVD PLAYER, ETC.)TEXTING',
       'TEXTINGTURNING RIGHT ON RED',
       'ROAD CONSTRUCTION/MAINTENANCERELATED TO BUS STOP',
       'HAD BEEN DRINKING (USE WHEN ARREST IS NOT MADE)ANIMAL',
       'DISTRACTION - FROM INSIDE VEHICLEDISTRACTION - FROM INSIDE VEHICLE',
       'CELL PHONE USE OTHER THAN TEXTINGDISREGARDING OTHER TRAFFIC SIGNS',
       'ANIMALDISREGARDING YIELD SIGN',
       'DISREGARDING OTHER TRAFFIC SIGNSHAD BEEN DRINKING (USE WHEN ARREST IS NOT MADE)',
       'RELATED TO BUS STOPDISTRACTION - OTHER ELECTRONIC DEVICE (NAVIGATION DEVICE, DVD PLAYER, ETC.)',
       'OBSTRUCTED CROSSWALKSPASSING STOPPED SCHOOL BUS',
       'DISREGARDING YIELD SIGNDISREGARDING ROAD MARKINGS',
       'PASSING STOPPED SCHOOL BUSOBSTRUCTED CROSSWALKS',
       'BICYCLE ADVANCING LEGALLY ON RED LIGHTMOTORCYCLE ADVANCING LEGALLY ON RED LIGHT',
       'MOTORCYCLE ADVANCING LEGALLY ON RED LIGHTEXCEEDING SAFE SPEED FOR CONDITIONS',
       'EXCEEDING AUTHORIZED SPEED LIMITBICYCLE ADVANCING LEGALLY ON RED LIGHT',
       'EXCEEDING SAFE SPEED FOR CONDITIONSEXCEEDING AUTHORIZED SPEED LIMIT'],
      dtype=object)

## Renaming a few more columns

In [87]:
df_cp4 = df_cp4.rename({'ALIGNMENT': 'ROAD_LEVEL', 'DAMAGE': 'DAMAGE_AMT'}, axis=1)

# Final Cleaned Dataset

In [88]:
df_clean_data = df_cp4.copy()

## Reorder columns

In [89]:
reordered_columns = [
    'CRASH_DATE',
    'DATE_POLICE_NOTIFIED',

    'ON_SCENE',
    'HIT_AND_RUN',

    'POSTED_SPEED_LIMIT',

    'TRAFFIC_CONTROL_DEVICE',
    'TRAFFIC_DEVICE_FUNCTIONING',

    'WEATHER_CONDITION',
    'LIGHTING_CONDITION',
    'ROADWAY_SURFACE_COND',
    'ROAD_DEFECT',

    'TRAFFICWAY_TYPE',
    'ROAD_LEVEL',

    'DAMAGE_AMT',

    'CRASH_TYPE',

    'PRIM_CONTRIBUTORY_CAUSE',
    'SEC_CONTRIBUTORY_CAUSE',

    'REPORTABLE',
    'INJURIES_TOTAL',
    'INJURIES_FATAL',
    'INJURIES_INCAPACITATING',
    'INJURIES_NON_INCAPACITATING',
    'INJURIES_REPORTED_NOT_EVIDENT',
    'INJURIES_NO_INDICATION',
    'INJURIES_UNKNOWN',

    'LATITUDE',
    'LONGITUDE',
]
df_clean_data = df_clean_data[reordered_columns]

In [90]:
df_clean_data

,CRASH_DATE,DATE_POLICE_NOTIFIED,ON_SCENE,HIT_AND_RUN,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,TRAFFIC_DEVICE_FUNCTIONING,WEATHER_CONDITION,LIGHTING_CONDITION,ROADWAY_SURFACE_COND,...,REPORTABLE,INJURIES_TOTAL,INJURIES_FATAL,INJURIES_INCAPACITATING,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,LATITUDE,LONGITUDE
0,2025-01-14 12:25:00,2025-01-14 12:38:00,1,1,30,TRAFFIC SIGNAL,True,SNOW,DAYLIGHT,SNOW OR SLUSH,...,False,0,0,0,0,0,2,0.0,41.997808,-87.655770
1,2025-05-23 09:30:00,2025-05-27 10:40:00,0,1,30,STOP SIGN/FLASHER,False,UNKNOWN,DAYLIGHT,UNKNOWN,...,False,0,0,0,0,0,2,0.0,41.946529,-87.688106
2,2025-04-05 20:00:00,2025-04-05 21:23:00,1,1,30,NO CONTROLS,False,CLEAR,UNKNOWN,DRY,...,False,0,0,0,0,0,1,0.0,41.899325,-87.715074
3,2025-05-23 09:15:00,2025-05-23 09:16:00,1,-1,30,NO CONTROLS,False,CLEAR,DAYLIGHT,DRY,...,True,1,0,0,1,0,2,0.0,41.902793,-87.699412
4,2025-01-14 08:00:00,2025-01-14 08:45:00,0,-1,30,TRAFFIC SIGNAL,True,SNOW,DAYLIGHT,WET,...,False,0,0,0,0,0,2,0.0,41.691207,-87.720555
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984007,2025-08-07 18:40:00,2025-08-08 15:30:00,0,-1,30,TRAFFIC SIGNAL,True,CLEAR,DAYLIGHT,DRY,...,False,0,0,0,0,0,2,0.0,42.012120,-87.690100
984008,2025-08-16 23:50:00,2025-08-16 23:55:00,1,1,30,NO CONTROLS,False,UNKNOWN,"DARKNESS, LIGHTED ROAD",UNKNOWN,...,True,0,0,0,0,0,2,0.0,41.778225,-87.747206
984009,2025-08-17 14:00:00,2025-08-18 15:30:00,0,-1,30,STOP SIGN/FLASHER,False,CLEAR,DAYLIGHT,DRY,...,False,0,0,0,0,0,2,0.0,41.838002,-87.641182
984010,2025-08-18 00:08:00,2025-08-18 00:09:00,-1,-1,30,NO CONTROLS,False,CLEAR,"DARKNESS, LIGHTED ROAD",DRY,...,True,0,0,0,0,0,1,0.0,41.904205,-87.678698
984011,2025-08-18 00:24:00,2025-08-18 00:28:00,1,-1,30,NO CONTROLS,False,CLEAR,"DARKNESS, LIGHTED ROAD",DRY,...,True,0,0,0,0,0,2,0.0,41.720684,-87.536644

## Export to CSV

In [91]:
lib.export_data(filename, df_clean_data)

PortfolioLogger.lib.tools: INFO: Exporting 26568324 elements (722.62 MB) to chicago_traffic_crashes_CLEAN.csv

PosixPath('chicago_traffic_crashes_CLEAN.csv')