# Yelp Data Exploration

[<img  alt="image" src="images/banner.png">](https://public.tableau.com/app/profile/christopher.magno/viz/YelpAnalysis_17653606827830/YelpAnalysis)

For this project, I selected a dataset composed of relational tables connected through primary and foreign keys. The
goal was to focus on data wrangling, exploratory analysis, and visualization in Tableau. The data comes from the Yelp
Open Dataset, which is available [here](https://business.yelp.com/data/resources/open-dataset/). The dataset is provided
across five separate JSON files.

| Files                               | Shape (row x columns) | Size     |
|-------------------------------------|-----------------------|----------|
| yelp_academic_dataset_business.json | 150,346 x 60          | 118.9 MB |
| yelp_academic_dataset_checkin.json  | 131,930 x 2           | 287 MB   |
| yelp_academic_dataset_review.json   | 6,990,280 x 9         | 5.34 GB  |
| yelp_academic_dataset_tip.json      | 908,915 x 5           | 180.6 MB |
| yelp_academic_dataset_user.json     | 1,987,897 x 22        | 3.36 GB  |

## Dataset Modeling
<img width="1000" alt="image" src="images/img1.png">


## The goal of this project
* Get total businesses, total review count, and average rating for the regions provided per category overtime (spark lines)
* Get total business, total review count, and average rating per price tiers ($, $$, $$$, $$$$)
* Get user engagement by hour/day of week by checkins
* Get top categories
* Get top 10 businesses (per region)
* Evaluate market share distribution to determine which segment dominates


## Stretch goals
* Sentiment Analysis and word cloud or negative and positive keywords on the 6.9M rows of customer reviews and tips
  * Sentiment trends over time


## ⚒️ Tools Used
* Python
  * Pandas
* Tableau


To view the Tableau visualization, please click [here](https://public.tableau.com/app/profile/christopher.magno/viz/YelpAnalysis_17653606827830/YelpAnalysis)
<img width="1000" alt="image" src="images/img2.png">

In [2]:
import importlib
import datetime
import json
from pathlib import Path

import pandas as pd
import numpy as np

import lib
importlib.reload(lib)

PROJECT_DIRECTORY = lib.get_project_dir()
PROJECT_NAME = lib.get_project_name()
log = lib.getLogger(PROJECT_NAME)

EXPORT_DIRECTORY = PROJECT_DIRECTORY / 'clean'

In [2]:
path_dataset_business = '/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/yelp_academic_dataset_business.json'  # 118.9 MB

In [3]:
df_business = lib.read_json(path_dataset_business)

In [4]:
df_business.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150346 entries, 0 to 150345
Data columns (total 60 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   business_id                            150346 non-null  object
 1   name                                   150346 non-null  object
 2   address                                150346 non-null  object
 3   city                                   150346 non-null  object
 4   state                                  150346 non-null  object
 5   postal_code                            150346 non-null  object
 6   latitude                               150346 non-null  float64
 7   longitude                              150346 non-null  float64
 8   stars                                  150346 non-null  float64
 9   review_count                           150346 non-null  int64
 10  is_open                                150346 non-null  int64
 11  categories                             150243 non-null  object
 12  hours                                  0 non-null       float64
 13  attributes.ByAppointmentOnly           42339 non-null   object
 14  attributes.BusinessAcceptsCreditCards  119765 non-null  object
 15  hours.Monday                           114474 non-null  object
 16  hours.Tuesday                          120631 non-null  object
 17  hours.Wednesday                        123771 non-null  object
 18  hours.Thursday                         125198 non-null  object
 19  hours.Friday                           124999 non-null  object
 20  hours.Saturday                         110770 non-null  object
 21  attributes.BikeParking                 72638 non-null   object
 22  attributes.RestaurantsPriceRange2      85314 non-null   object
 23  attributes.CoatCheck                   5584 non-null    object
 24  attributes.RestaurantsTakeOut          59857 non-null   object
 25  attributes.RestaurantsDelivery         56282 non-null   object
 26  attributes.Caters                      40127 non-null   object
 27  attributes.WiFi                        56914 non-null   object
 28  attributes.BusinessParking             91085 non-null   object
 29  attributes.WheelchairAccessible        28953 non-null   object
 30  attributes.HappyHour                   15171 non-null   object
 31  attributes.OutdoorSeating              48802 non-null   object
 32  attributes.HasTV                       45084 non-null   object
 33  attributes.RestaurantsReservations     45247 non-null   object
 34  attributes.DogsAllowed                 18284 non-null   object
 35  hours.Sunday                           81172 non-null   object
 36  attributes.Alcohol                     43189 non-null   object
 37  attributes.GoodForKids                 53375 non-null   object
 38  attributes.RestaurantsAttire           39255 non-null   object
 39  attributes.Ambience                    44279 non-null   object
 40  attributes.RestaurantsTableService     19982 non-null   object
 41  attributes.RestaurantsGoodForGroups    44170 non-null   object
 42  attributes.DriveThru                   7760 non-null    object
 43  attributes                             0 non-null       float64
 44  attributes.NoiseLevel                  37993 non-null   object
 45  attributes.GoodForMeal                 29087 non-null   object
 46  attributes.BusinessAcceptsBitcoin      17430 non-null   object
 47  attributes.Smoking                     4567 non-null    object
 48  attributes.Music                       7521 non-null    object
 49  attributes.GoodForDancing              4628 non-null    object
 50  attributes.AcceptsInsurance            5713 non-null    object
 51  attributes.BestNights                  5694 non-null    object
 52  attributes.BYOB                        4451 non-null    object
 53  attributes.Corkage                     3553 non-null    object
 54  attributes.BYOBCorkage                 1444 non-null    object
 55  attributes.HairSpecializesIn           1065 non-null    object
 56  attributes.Open24Hours                 39 non-null      object
 57  attributes.RestaurantsCounterService   19 non-null      object
 58  attributes.AgesAllowed                 129 non-null     object
 59  attributes.DietaryRestrictions         31 non-null      object
dtypes: float64(5), int64(2), object(53)
memory usage: 68.8+ MB

In [5]:
df_business.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,attributes.AcceptsInsurance,attributes.BestNights,attributes.BYOB,attributes.Corkage,attributes.BYOBCorkage,attributes.HairSpecializesIn,attributes.Open24Hours,attributes.RestaurantsCounterService,attributes.AgesAllowed,attributes.DietaryRestrictions
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_business_cp1 = df_business.copy()

### Creating backup

In [7]:
df_business_cp1 = df_business.copy()

### Looking for Risky columns to potentially drop

In [8]:
risky_columns = lib.risky_columns(df_business_cp1, err_rate=.9)
risky_columns

                                     error_percent error_count
hours                                      100.00%      150346
attributes.CoatCheck                        96.29%      144762
attributes.DriveThru                        94.84%      142586
attributes                                 100.00%      150346
attributes.Smoking                          96.96%      145779
attributes.Music                            95.00%      142825
attributes.GoodForDancing                   96.92%      145718
attributes.AcceptsInsurance                 96.20%      144633
attributes.BestNights                       96.21%      144652
attributes.BYOB                             97.04%      145895
attributes.Corkage                          97.64%      146793
attributes.BYOBCorkage                      99.04%      148902
attributes.HairSpecializesIn                99.29%      149281
attributes.Open24Hours                      99.97%      150307
attributes.RestaurantsCounterService        99.99%      150327
attributes.AgesAllowed                      99.91%      150217
attributes.DietaryRestrictions              99.98%      150315

In [9]:
df_business_cp1 = df_business_cp1.drop(risky_columns.index, axis=1)
df_business_cp1.columns

Index(['business_id', 'name', 'address', 'city', 'state', 'postal_code',
       'latitude', 'longitude', 'stars', 'review_count', 'is_open',
       'categories', 'attributes.ByAppointmentOnly',
       'attributes.BusinessAcceptsCreditCards', 'hours.Monday',
       'hours.Tuesday', 'hours.Wednesday', 'hours.Thursday', 'hours.Friday',
       'hours.Saturday', 'attributes.BikeParking',
       'attributes.RestaurantsPriceRange2', 'attributes.RestaurantsTakeOut',
       'attributes.RestaurantsDelivery', 'attributes.Caters',
       'attributes.WiFi', 'attributes.BusinessParking',
       'attributes.WheelchairAccessible', 'attributes.HappyHour',
       'attributes.OutdoorSeating', 'attributes.HasTV',
       'attributes.RestaurantsReservations', 'attributes.DogsAllowed',
       'hours.Sunday', 'attributes.Alcohol', 'attributes.GoodForKids',
       'attributes.RestaurantsAttire', 'attributes.Ambience',
       'attributes.RestaurantsTableService',
       'attributes.RestaurantsGoodForGroups', 'attributes.NoiseLevel',
       'attributes.GoodForMeal', 'attributes.BusinessAcceptsBitcoin'],
      dtype='object')

### Creating backup

In [10]:
df_business_cp2 = df_business_cp1.copy()

### Fixing Categories
Going to store into multiple datasets (categories table, business/categories table [build relationship between the two])

In [11]:
df_business_cp2['categories'].value_counts()

categories
Beauty & Spas, Nail Salons                                                                                       1012
Restaurants, Pizza                                                                                                935
Nail Salons, Beauty & Spas                                                                                        934
Pizza, Restaurants                                                                                                823
Restaurants, Mexican                                                                                              728
                                                                                                                 ...
Dermatologists, Health & Medical, Cosmetic Surgeons, Doctors, Acne Treatment, Skin Care, Beauty & Spas              1
Home Services, Home & Garden, Nurseries & Gardening, Hardware Stores, Shopping, Building Supplies, Appliances       1
Food Trucks, Smokehouse, Restaurants, Food, Barbeque, Soul Food, Food Stands                                        1
Assisted Living Facilities, Memory Care, Health & Medical, Hospice                                                  1
Beauty & Spas, Permanent Makeup, Piercing, Tattoo                                                                   1
Name: count, Length: 83160, dtype: int64

Building out the data for the categories

In [12]:
# Holds data per index/business_id/associated categories
categories_dict = {}
# Holds all categories
categories_set = set()
for idx, row in df_business_cp2.iterrows():
    if row['categories']:
        categories_dict[idx] = {'business_id': row['business_id'], 'categories': row['categories'].split(', ')}
    else:
        categories_dict[idx] = {'business_id': row['business_id'], 'categories': []}

    # Update the full list of categories
    categories_set.update(categories_dict[idx]['categories'])

categories_set = sorted(list(categories_set))
categories_dict

{0: {'business_id': 'Pns2l4eNsfO8kk83dixA6A',
  'categories': ['Doctors',
   'Traditional Chinese Medicine',
   'Naturopathic/Holistic',
   'Acupuncture',
   'Health & Medical',
   'Nutritionists']},
 1: {'business_id': 'mpf3x-BjTdTEA3yCZrAYPw',
  'categories': ['Shipping Centers',
   'Local Services',
   'Notaries',
   'Mailbox Centers',
   'Printing Services']},
 2: {'business_id': 'tUFrWirKiKi_TAnsVWINQQ',
  'categories': ['Department Stores',
   'Shopping',
   'Fashion',
   'Home & Garden',
   'Electronics',
   'Furniture Stores']},
 3: {'business_id': 'MTSW4McQd7CbVtyjqoe9mw',
  'categories': ['Restaurants',
   'Food',
   'Bubble Tea',
   'Coffee & Tea',
   'Bakeries']},
 4: {'business_id': 'mWMc6_wTdE0EUBKIGXDVfA',
  'categories': ['Brewpubs', 'Breweries', 'Food']},
 5: {'business_id': 'CF33F8-E6oudUQ46HnavjQ',
  'categories': ['Burgers',
   'Fast Food',
   'Sandwiches',
   'Food',
   'Ice Cream & Frozen Yogurt',
   'Restaurants']},
 6: {'business_id': 'n_0UpQx1hsNbnPUSlodU8w',
  'categories': ['Sporting Goods',
   'Fashion',
   'Shoe Stores',
   'Shopping',
   'Sports Wear',
   'Accessories']},
 7: {'business_id': 'qkRM_2X51Yqxk3btlwAQIg',
  'categories': ['Synagogues', 'Religious Organizations']},
 8: {'business_id': 'k0hlBqXX-Bt0vf1op7Jr1w',
  'categories': ['Pubs',
   'Restaurants',
   'Italian',
   'Bars',
   'American (Traditional)',
   'Nightlife',
   'Greek']},
 9: {'business_id': 'bBDDEgkFA1Otx9Lfe7BZUQ',
  'categories': ['Ice Cream & Frozen Yogurt',
   'Fast Food',
   'Burgers',
   'Restaurants',
   'Food']},
 10: {'business_id': 'UJsufbvfyfONHeWdvAHKjA',
  'categories': ['Department Stores', 'Shopping', 'Fashion']},
 11: {'business_id': 'eEOYSgkmpB90uNA7lDOMRA',
  'categories': ['Vietnamese', 'Food', 'Restaurants', 'Food Trucks']},
 12: {'business_id': 'il_Ro8jwPlHresjw9EGmBg',
  'categories': ['American (Traditional)',
   'Restaurants',
   'Diners',
   'Breakfast & Brunch']},
 13: {'business_id': 'jaxMSoInw8Poo3XeMJt8lQ',
  'categories': ['General Dentistry',
   'Dentists',
   'Health & Medical',
   'Cosmetic Dentists']},
 14: {'business_id': '0bPLkL0QhhPO5kt1_EXmNQ',
  'categories': ['Food', 'Delis', 'Italian', 'Bakeries', 'Restaurants']},
 15: {'business_id': 'MUTTqe8uqyMdBl186RmNeA',
  'categories': ['Sushi Bars', 'Restaurants', 'Japanese']},
 16: {'business_id': 'rBmpy_Y1UbBx8ggHlyb7hA',
  'categories': ['Automotive', 'Auto Parts & Supplies', 'Auto Customization']},
 17: {'business_id': 'M0XSSHqrASOnhgbWDJIpQA',
  'categories': ['Vape Shops',
   'Tobacco Shops',
   'Personal Shopping',
   'Vitamins & Supplements',
   'Shopping']},
 18: {'business_id': '8wGISYjYkE2tSqn3cDMu8A',
  'categories': ['Automotive',
   'Car Rental',
   'Hotels & Travel',
   'Truck Rental']},
 19: {'business_id': 'ROeacJQwBeh05Rqg7F6TCg',
  'categories': ['Korean', 'Restaurants']},
 20: {'business_id': 'WKMJwqnfZKsAae75RMP6jA',
  'categories': ['Coffee & Tea',
   'Food',
   'Cafes',
   'Bars',
   'Wine Bars',
   'Restaurants',
   'Nightlife']},
 21: {'business_id': 'qhDdDeI3K4jy2KyzwFN53w',
  'categories': ['Shopping', 'Books', 'Mags', 'Music & Video', 'Bookstores']},
 22: {'business_id': 'kfNv-JZpuN6TVNSO6hHdkw',
  'categories': ['Steakhouses', 'Asian Fusion', 'Restaurants']},
 23: {'business_id': '9OG5YkX1g2GReZM0AskizA',
  'categories': ['Restaurants', 'Italian']},
 24: {'business_id': '4iRzR7OaS-QaSXuvYxEGKA',
  'categories': ['Hot Dogs', 'Restaurants']},
 25: {'business_id': 'PSo_C1Sfa13JHjzVNW6ziQ',
  'categories': ['Pet Services', 'Pet Groomers', 'Pets', 'Veterinarians']},
 26: {'business_id': 'noByYNtDLQAra9ccqxdfDw',
  'categories': ["Women's Clothing",
   'Accessories',
   "Children's Clothing",
   "Men's Clothing",
   'Adult',
   'Shopping',
   'Fashion']},
 27: {'business_id': 'tMkwHmWFUEXrC9ZduonpTg',
  'categories': ['Restaurants', 'Japanese', 'Seafood']},
 28: {'business_id': 'QdN72BWoyFypdGJhhI5r7g',
  'categories': ['Cocktail Bars',
   'Bars',
   'Italian',
   'Nightlife',
   'Restaurants']},
 29: {'business_id': 'sqSqqLy0sN8n2IZrAbzidQ',
  'categories': ['Pizza', 'Chicken Wings', 'Sandwiches', 'Restaurants']},
 30: {'business_id': 'fvWn8oXXwbj2l79cochZyw',
  'categories': ['Trampoline Parks', 'Active Life']},
 31: {'business_id': 'Mjboz24M9NlBeiOJKLEd_Q',
  'categories': ['Pizza', 'Restaurants', 'Salad', 'Soup']},
 32: {'business_id': '8sshLb4UU7emeUDvtJWnpA',
  'categories': ['Dance Wear',
   'Sports Wear',
   "Children's Clothing",
   'Arts & Entertainment',
   'Social Clubs',
   'Performing Arts',
   'Sporting Goods',
   'Shoe Stores',
   'Fashion',
   'Shopping']},
 33: {'business_id': 'kV_Q1oqis8Qli8dUoGpTyQ',
  'categories': ['Pizza', 'Restaurants']},
 34: {'business_id': 'w_AMNoI1iG9eay7ncmc67w',
  'categories': ['Event Planning & Services', 'Hotels', 'Hotels & Travel']},
 35: {'business_id': 'aPNXGTDkf-4bjhyMBQxqpQ',
  'categories': ['Eatertainment',
   'Arts & Entertainment',
   'Brewpubs',
   'American (Traditional)',
   'Bakeries',
   'Breweries',
   'Food',
   'Restaurants']},
 36: {'business_id': '2xVsWBNFwZOxIOdd9Mwnww',
  'categories': ['Restaurants', 'Burgers']},
 37: {'business_id': 'mGFsPRHdE6SMV1gYQ6GzgQ',
  'categories': ['Mobile Phones',
   'Telecommunications',
   'Electronics',
   'Mobile Phone Accessories',
   'Local Services',
   'Shopping',
   'IT Services & Computer Repair']},
 38: {'business_id': 'LcAozWCMLGjwRbokaJAKMg',
  'categories': ['Museums',
   'Kids Activities',
   'Arts & Entertainment',
   'Education',
   'Active Life',
   'Playgrounds',
   "Children's Museums"]},
 39: {'business_id': 'fSCNwMtNNQY9QT69Cj9fiA',
  'categories': ['Musicians',
   'DJs',
   'Karaoke',
   'Event Planning & Services',
   'Nightlife']},
 40: {'business_id': 'x1mhq4IpWctQOBM06dU8vg',
  'categories': ['Hair Salons',
   'Hair Extensions',
   'Beauty & Spas',
   'Wigs',
   'Shopping']},
 41: {'business_id': 'ljxNT9p0y7YMPx0fcNBGig',
  'categories': ['Restaurants',
   'Specialty Food',
   'Steakhouses',
   'Food',
   'Italian',
   'Pizza',
   'Pasta Shops']},
 42: {'business_id': 'lwItZ1Ck3KtpCgG4CPFmpQ',
  'categories': ['DUI Law',
   'Professional Services',
   'Lawyers',
   'Criminal Defense Law']},
 43: {'business_id': 'Kq51_lGAgAigqmENITTr-A',
  'categories': ['Health & Medical',
   'Beauty & Spas',
   'Laser Hair Removal',
   'Doctors',
   'Hair Removal',
   'Chiropractors',
   'Weight Loss Centers',
   'Sports Medicine',
   'Medical Spas',
   'Skin Care']},
 44: {'business_id': 'mglME3E7esPSpIF5bias8w',
  'categories': ['Fashion',
   'Shopping',
   'Department Stores',
   'Furniture Stores',
   'Candle Stores',
   'Home & Garden',
   'Home Decor']},
 45: {'business_id': 'wghnIlMb_i5U46HMBGx9ig',
  'categories': ['Restaurants', 'Chinese']},
 46: {'business_id': 'JX4tUpd09YFchLBuI43lGw',
  'categories': ['Arts & Entertainment',
   'Music Venues',
   'Internet Service Providers',
   'Nightlife',
   'Food',
   'Coffee & Tea',
   'Jazz & Blues',
   'Professional Services',
   'Internet Cafes']},
 47: {'business_id': 'lk9IwjZXqUMqqOhM774DtQ',
  'categories': ['Coffee & Tea',
   'Restaurants',
   'Wine Bars',
   'Bars',
   'Nightlife',
   'American (Traditional)',
   'Event Planning & Services',
   'Food',
   'Caterers',
   'Breakfast & Brunch',
   'Cafes',
   'Diners']},
 48: {'business_id': 'bCBPXIVfVzBZBEpFu29dcg',
  'categories': ['Shipping Centers', 'Local Services']},
 49: {'business_id': 'ABxoFuzZy5mqQ8C5FJJajQ',
  'categories': ['Restaurants', 'Italian']},
 50: {'business_id': 'Hwt3_mOEmU-t--ywcemnMg',
  'categories': ['Active Life',
   'Fitness & Instruction',
   'Trainers',
   'Gyms',
   'Yoga']},
 51: {'business_id': 'REwfwz-_-CMQ7Np5UVi9Qg',
  'categories': ['Real Estate Agents', 'Home Services', 'Real Estate']},
 52: {'business_id': '5BmQX4UVJY19mMtafMg7JA',
  'categories': ['Specialty Food', 'Bakeries', 'Food', 'Health Markets']},
 53: {'business_id': 'cVBxfMC4lp3DnocjYA3FHQ',
  'categories': ['Coffee & Tea',
   'Cafes',
   'Pets',
   'Restaurants',
   'Pet Adoption',
   'Food']},
 54: {'business_id': '0qNpTGTcqPwOLi2hADx4Xw',
  'categories': ['Food', 'Grocery', 'Convenience Stores']},
 55: {'business_id': 'xM6LoUcnpDpMBzXs_7dXAg',
  'categories': ['Hotels', 'Hotels & Travel', 'Event Planning & Services']},
 56: {'business_id': 'txyXRytGjwOXvS8s4sc-WA',
  'categories': ['Vitamins & Supplements',
   'Ice Cream & Frozen Yogurt',
   'Food',
   'Juice Bars & Smoothies',
   'Shopping']},
 57: {'business_id': 'DQ7PyYlp2bX96WZa7TcaWQ',
  'categories': ['Ophthalmologists',
   'Eyewear & Opticians',
   'Health & Medical',
   'Shopping',
   'Doctors',
   'Optometrists']},
 58: {'business_id': 'uI9XODGY_2_ieTE6xJ0myw',
  'categories': ['Restaurants', 'American (New)', 'Italian']},
 59: {'business_id': 'JgpnXv_0XhV3SfbfB50nxw',
  'categories': ['Restaurants', 'Pizza']},
 60: {'business_id': 'Si6LXSR9gvAbmgO5DzV2cw',
  'categories': ['Restaurants', 'Soup', 'Seafood', 'Burgers']},
 61: {'business_id': 'seKihQKpGGnCeLuELRQPSQ',
  'categories': ['Sports Bars',
   'American (New)',
   'American (Traditional)',
   'Nightlife',
   'Bars',
   'Restaurants']},
 62: {'business_id': 'L_TT0BFmFwORAMaA83K54A',
  'categories': ['Gastropubs',
   'Cocktail Bars',
   'Beer Bar',
   'Bars',
   'Restaurants',
   'Nightlife']},
 63: {'business_id': 'mjWvAkNqoA6Y5P03sDSzfA',
  'categories': ['Uniforms', 'Shopping']},
 64: {'business_id': 'qfWJmJ0g96eM_fWma3ja0g',
  'categories': ['Seafood',
   'Restaurants',
   'Bars',
   'Nightlife',
   'Cocktail Bars',
   'American (New)',
   'Pubs']},
 65: {'business_id': 'uczmbBk5O3tYhGue13dCDg',
  'categories': ['Hotels & Travel', 'Tours', 'Local Flavor']},
 66: {'business_id': 'n7AQvGvNHlmun3kqXeBKVQ',
  'categories': ['Local Services', 'Appliances & Repair']},
 67: {'business_id': 'eYxGFkxo6m3SYGVTh5m2nQ',
  'categories': ['Towing',
   'Hotels & Travel',
   'Automotive',
   'Motorcycle Rental',
   'Motorcycle Gear',
   'Shopping']},
 68: {'business_id': 'lOP3HxdUTaq0eXhwR_KC-w',
  'categories': ['Chocolatiers & Shops',
   'Specialty Food',
   'Candy Stores',
   'Food']},
 69: {'business_id': 'KWA2qtdwVEkMpd5soSKaGA',
  'categories': ['Food', 'Grocery']},
 70: {'business_id': 'gbN4RuUiiBxQ2GBFQ2p3Cw',
  'categories': ['Food Trucks', 'Food']},
 71: {'business_id': 'B2qqjCl_BNNnXvWWfpFiLA',
  'categories': ['Shopping',
   'Baby Gear & Furniture',
   'Home Decor',
   'Furniture Stores',
   'Home & Garden']},
 72: {'business_id': '7PDi_iyik3jraDAzWwwR4Q',
  'categories': ['Banks & Credit Unions', 'Financial Services']},
 73: {'business_id': '8rb-3VYXE37IZix4yOdskw',
  'categories': ['American (Traditional)',
   'Bars',
   'Nightlife',
   'Sports Bars',
   'Restaurants']},
 74: {'business_id': '9Rww8yE6Dm4dSMEq09nwXg',
  'categories': ['Health & Medical',
   'Personal Care Services',
   'Beauty & Spas',
   'Massage',
   'Nail Salons']},
 75: {'business_id': 'aCDY7vXYMs54EbYuQScsnQ',
  'categories': ['American (Traditional)',
   'Sports Bars',
   'Restaurants',
   'Bars',
   'Nightlife',
   'Steakhouses',
   'Salad',
   'Beer Bar']},
 76: {'business_id': '-4dYswJy7SPcbcERvitmIg',
  'categories': ['Food', 'Grocery']},
 77: {'business_id': 'mFTaYsRDyeFaY2NDLfSaAA',
  'categories': ['Tabletop Games', 'Shopping', 'Sporting Goods']},
 78: {'business_id': 'x9K0RfZaT_zlw6DklBDzjw',
  'categories': ['Italian', 'Restaurants']},
 79: {'business_id': 'pJfh3Ct8iL58NZa8ta-a5w',
  'categories': ['Burgers',
   'Sports Bars',
   'Bars',
   'Lounges',
   'Restaurants',
   'Salad',
   'Wraps',
   'Nightlife',
   'American (New)']},
 80: {'business_id': 'cvP_vh_bOLbCY3eoY1Xw-A',
  'categories': ['Festivals', 'Arts & Entertainment']},
 81: {'business_id': '7clCBgNbd-x2Wj96lZ6Mjw',
  'categories': ['Food', 'Beer', 'Wine & Spirits', 'Breweries']},
 82: {'business_id': 'ppFCk9aQkM338Rgwpl2F5A',
  'categories': ['Restaurants',
   'Automotive',
   'Delis',
   'Gas Stations',
   'Food',
   'Coffee & Tea',
   'Sandwiches',
   'Convenience Stores']},
 83: {'business_id': 'NZ_bFJma7brQUfln5h1UAg',
  'categories': ['Restaurants', 'Japanese', 'Sushi Bars', 'Asian Fusion']},
 84: {'business_id': 'eMjnw_7wp-CscyNh6Lu0ZA',
  'categories': ['Keys & Locksmiths', 'Home Services', 'Local Services']},
 85: {'business_id': 'IDtLPgUrqorrpqSLdfMhZQ',
  'categories': ['Food',
   'Restaurants',
   'Salad',
   'Coffee & Tea',
   'Breakfast & Brunch',
   'Sandwiches',
   'Bakeries']},
 86: {'business_id': 'sE6jSnvMts_MAn-b4OkMAw',
  'categories': ['Pet Groomers', 'Pet Sitting', 'Pets', 'Pet Services']},
 87: {'business_id': 'YNjyv0gfOr2g8lbmUpTnKg',
  'categories': ['Nightlife',
   'Pubs',
   'Event Planning & Services',
   'Wine Bars',
   'Bars',
   'Gastropubs',
   'Restaurants',
   'Venues & Event Spaces']},
 88: {'business_id': 'LhpPSrulqVeTyJeK2xydvQ',
  'categories': ['Juice Bars & Smoothies',
   'Restaurants',
   'Fruits & Veggies',
   'Salad',
   'Specialty Food',
   'Food']},
 89: {'business_id': 'oaboaRBUgGjbo2kfUIKDLQ',
  'categories': ['Ice Cream & Frozen Yogurt',
   'Coffee & Tea',
   'Restaurants',
   'Sandwiches',
   'Food']},
 90: {'business_id': '-ZXYcCyDjj1QimnJyGtYtg',
  'categories': ['Home Decor',
   'Shopping',
   'Antiques',
   'Books',
   'Mags',
   'Music & Video',
   'Home & Garden']},
 91: {'business_id': 'nUqrF-h9S7myCcvNDecOvw',
  'categories': ['Towing', 'Automotive', 'Body Shops']},
 92: {'business_id': 'vR9_bhoszcpXbB_APv6Xlw',
  'categories': ['Fashion', 'Shopping', "Men's Clothing"]},
 93: {'business_id': 'RK6-cJ9hj53RzOlCBmpT-g',
  'categories': ['Restaurants', 'Italian', 'Food Trucks', 'Food']},
 94: {'business_id': 'ZM46RDLXaFNo_z6t-j_L4w',
  'categories': ['Masonry/Concrete',
   'Gardeners',
   'Lawn Services',
   'Tree Services',
   'Landscape Architects',
   'Home Services',
   'Contractors',
   'Landscaping']},
 95: {'business_id': 'pEm4xNCk8d0TF6A1gi-WDQ',
  'categories': ['Karaoke',
   'DJs',
   'Event Planning & Services',
   'Party & Event Planning',
   'Nightlife']},
 96: {'business_id': 'J_ksUDPpzPwfTGtI4zTRnQ',
  'categories': ['Event Planning & Services',
   'Caterers',
   'Party & Event Planning']},
 97: {'business_id': 'knQ4vIgx-r85kjlWVVjcpQ',
  'categories': ['Sporting Goods',
   'Sports Wear',
   'Fashion',
   'Restaurants',
   'Fast Food',
   'Sandwiches',
   'Shopping']},
 98: {'business_id': 'U2Tzy6J9aAAg9pzXsgdkvg',
  'categories': ['Real Estate',
   'Home Services',
   'Financial Services',
   'Mortgage Brokers',
   'Mortgage Lenders']},
 99: {'business_id': '1MeIwdbTnZOBFCKOrgaxuw',
  'categories': ['American (New)',
   'Restaurants',
   'Cafes',
   'Italian',
   'American (Traditional)']},
 100: {'business_id': '8KMIT0NXu30Jz5Ojo5uxaw',
  'categories': ['Fitness & Instruction',
   'Physical Therapy',
   'Health & Medical',
   'Active Life',
   'Trainers']},
 101: {'business_id': 'jiLGdnf42eYftkqfU2ze1w',
  'categories': ["Women's Clothing",
   "Men's Clothing",
   'Accessories',
   'Fashion',
   'Jewelry',
   'Department Stores',
   'Shopping',
   'Shoe Stores']},
 102: {'business_id': 'EuRGgOwJ0g1vTj2R04j37Q',
  'categories': ['Seafood', 'Restaurants']},
 103: {'business_id': 'TLZ3-eDPLhUzfsWO4ad6Ug',
  'categories': ['Restaurants', 'Seafood', 'Cajun/Creole']},
 104: {'business_id': 'Dy91wdWkwtI_qgjAIZ0Niw',
  'categories': ['Mexican', 'Restaurants']},
 105: {'business_id': '2Bi3ef7c0CrLxHD_-yy_tw',
  'categories': ['Printing Services',
   'Local Services',
   'Shipping Centers',
   'Couriers & Delivery Services',
   'Notaries']},
 106: {'business_id': 'vje0KIiE7vtpx7JzmBx5LQ',
  'categories': ['Restaurants',
   'French',
   'Moroccan',
   'Seafood',
   'Mediterranean']},
 107: {'business_id': '2n9HHBxG7yAyAUwXXa49aw',
  'categories': ['Flooring', 'Handyman', 'Contractors', 'Home Services']},
 108: {'business_id': 'kK2i5Xyd9SOpF5pCFilbcg',
  'categories': ['Pest Control', 'Local Services']},
 109: {'business_id': 'I6DCYks9lqZeoZiVzW7PmA',
  'categories': ['Shopping', 'Auction Houses', 'Active Life']},
 110: {'business_id': 'VrGxoSNZfSiT-G4OqRRGIw',
  'categories': ['Bars',
   'Lounges',
   'American (New)',
   'Restaurants',
   'Nightlife',
   'Wine Bars']},
 111: {'business_id': 'H0NEOp4e3Zu598u6kO3y0g',
  'categories': ['Eyewear & Opticians',
   'Health & Medical',
   'Shopping',
   'Doctors',
   'Optometrists',
   'Ophthalmologists']},
 112: {'business_id': 'sB45WFgysT617bKWP_WJwA',
  'categories': ['Bars',
   'Beer Gardens',
   'Food',
   'Breweries',
   'Nightlife',
   'Tours',
   'Pubs',
   'Wine Tours',
   'Beer Tours',
   'Hotels & Travel']},
 113: {'business_id': 'Fk1xpM7fjqEJ4paqk5ZFSg',
  'categories': ['Juice Bars & Smoothies', 'Food']},
 114: {'business_id': '4dVrWc4Nhuw9apfk9BWEcA',
  'categories': ['Grocery',
   'Food',
   'Shopping',
   'Fashion',
   'Drugstores',
   'Department Stores',
   'Discount Store',
   'Electronics']},
 115: {'business_id': 'xfmkEGiIERBaBMLhw-dTCg',
  'categories': ['Eyewear & Opticians', 'Shopping']},
 116: {'business_id': 'NTf_U8kYu9PAE2cZGJqtJg',
  'categories': ['Public Services & Government', 'Libraries']},
 117: {'business_id': 'kk_oEw1j3xQ-cJaAII8A0Q',
  'categories': ['Grocery', 'Food']},
 118: {'business_id': 'RXpADfOCZBGi82-CGxYdsw',
  'categories': ['Flowers & Gifts',
   'Embroidery & Crochet',
   'Uniforms',
   'Arts & Crafts',
   'Home & Garden',
   'Shopping',
   'Gift Shops',
   'Home Decor']},
 119: {'business_id': 'qFX8IdomeBVhDPCSyz2aRg',
  'categories': ['Couriers & Delivery Services',
   'Local Services',
   'Food',
   'Food Delivery Services']},
 120: {'business_id': 'bYjnX_J1bHZob10DoSFkqQ',
  'categories': ['Parenting Classes',
   'Maternity Wear',
   'Fashion',
   'Education',
   'Specialty Schools',
   'Local Services',
   'Home Services',
   'Laundry Services',
   'Child Care & Day Care',
   'Shopping',
   'Baby Gear & Furniture']},
 121: {'business_id': 'luGY5CJlb4CJ3LrBcSXMPA',
  'categories': ['Furniture Stores', 'Shopping', 'Home & Garden']},
 122: {'business_id': 'VZzivJEbmHItOxNXJB3SpA',
  'categories': ['Sandwiches', 'Fast Food', 'Restaurants']},
 123: {'business_id': 'iPSPcprSnkLOuL1Ns8UZZA',
  'categories': ['Barbers', 'Beauty & Spas']},
 124: {'business_id': 'Q3kQYhkYxSRyYyeBgtk--A',
  'categories': ['Home Services',
   'Glass & Mirrors',
   'Door Sales/Installation']},
 125: {'business_id': 'wEfK2HIYNzkA1QYfUjHBaw',
  'categories': ['Hardware Stores',
   'Home Services',
   'Hot Tub & Pool',
   'Pool & Hot Tub Service',
   'Home & Garden',
   'Shopping']},
 126: {'business_id': 'anLQj9AM8vjbcLSIE0iUgg',
  'categories': ['Pizza', 'Restaurants']},
 127: {'business_id': 'BVo_36t3z7vfXp3XGgJkOg',
  'categories': ['Tires', 'Auto Repair', 'Oil Change Stations', 'Automotive']},
 128: {'business_id': 'P8brGDYVWjeW9GrKixH0yQ',
  'categories': ['Medical Centers',
   'Doctors',
   'Diagnostic Services',
   'Health & Medical',
   'Orthopedists',
   'Spine Surgeons',
   'Diagnostic Imaging']},
 129: {'business_id': 'Cdytv_YhJO0W0Ab8t2xLtg',
  'categories': ['Nightlife',
   'Chicken Wings',
   'Pubs',
   'Bars',
   'American (Traditional)',
   'Restaurants']},
 130: {'business_id': '3BJxm-HnvzdwD1zjmSbmyQ',
  'categories': ['Restaurants', 'Chinese']},
 131: {'business_id': 'FRYkg_JvsWU9xIXZsEZcVA',
  'categories': ['Cocktail Bars',
   'Italian',
   'Nightlife',
   'Seafood',
   'Bars',
   'Restaurants']},
 132: {'business_id': '9C2rpb56aQvW0ViZHK9sPw',
  'categories': ['Bars', 'Restaurants', 'Sports Bars', 'Nightlife']},
 133: {'business_id': 'k0yyD71s2F2eEKWRdkZ6jA',
  'categories': ['Custom Cakes',
   'Food',
   'Desserts',
   'Cupcakes',
   'Ice Cream & Frozen Yogurt']},
 134: {'business_id': 'dM5OKNzk9AL2aiq-fV-SYg',
  'categories': ['Discount Store',
   'Department Stores',
   'Food',
   'Drugstores',
   'Shopping',
   'Grocery',
   'Fashion',
   'Mobile Phones']},
 135: {'business_id': 'qdYfHRsZdcz4Bun4f9Ijaw',
  'categories': ['Car Wash', 'Auto Detailing', 'Automotive']},
 136: {'business_id': 'Y6t4pnKm5LF8y5ChHA27ow',
  'categories': ['Auto Repair', 'Automotive', 'Tires', 'Oil Change Stations']},
 137: {'business_id': 'E_kLUlU60fzoZYAOxbH_3w',
  'categories': ['Pain Management',

In [13]:
categories_set

['& Probates',
 '3D Printing',
 'ATV Rentals/Tours',
 'Acai Bowls',
 'Accessories',
 'Accountants',
 'Acne Treatment',
 'Active Life',
 'Acupuncture',
 'Addiction Medicine',
 'Adoption Services',
 'Adult',
 'Adult Education',
 'Adult Entertainment',
 'Advertising',
 'Aerial Fitness',
 'Aerial Tours',
 'Aestheticians',
 'Afghan',
 'African',
 'Air Duct Cleaning',
 'Aircraft Dealers',
 'Aircraft Repairs',
 'Airlines',
 'Airport Lounges',
 'Airport Shuttles',
 'Airport Terminals',
 'Airports',
 'Airsoft',
 'Allergists',
 'Alternative Medicine',
 'Amateur Sports Teams',
 'American (New)',
 'American (Traditional)',
 'Amusement Parks',
 'Anesthesiologists',
 'Animal Assisted Therapy',
 'Animal Physical Therapy',
 'Animal Shelters',
 'Antiques',
 'Apartment Agents',
 'Apartments',
 'Appliances',
 'Appliances & Repair',
 'Appraisal Services',
 'Aquarium Services',
 'Aquariums',
 'Arabic',
 'Arcades',
 'Archery',
 'Architects',
 'Architectural Tours',
 'Argentine',
 'Armenian',
 'Art Classes',
 'Art Consultants',
 'Art Galleries',
 'Art Installation',
 'Art Museums',
 'Art Restoration',
 'Art Schools',
 'Art Space Rentals',
 'Art Supplies',
 'Art Tours',
 'Artificial Turf',
 'Arts & Crafts',
 'Arts & Entertainment',
 'Asian Fusion',
 'Assisted Living Facilities',
 'Astrologers',
 'Attraction Farms',
 'Auction Houses',
 'Audio/Visual Equipment Rental',
 'Audiologist',
 'Australian',
 'Austrian',
 'Auto Customization',
 'Auto Detailing',
 'Auto Glass Services',
 'Auto Insurance',
 'Auto Loan Providers',
 'Auto Parts & Supplies',
 'Auto Repair',
 'Auto Security',
 'Auto Upholstery',
 'Automotive',
 'Aviation Services',
 'Awnings',
 'Axe Throwing',
 'Ayurveda',
 'Baby Gear & Furniture',
 'Backflow Services',
 'Badminton',
 'Bagels',
 'Bail Bondsmen',
 'Bakeries',
 'Balloon Services',
 'Bangladeshi',
 'Bankruptcy Law',
 'Banks & Credit Unions',
 'Bar Crawl',
 'Barbeque',
 'Barbers',
 'Barre Classes',
 'Bars',
 'Bartenders',
 'Bartending Schools',
 'Baseball Fields',
 'Basketball Courts',
 'Basque',
 'Battery Stores',
 'Batting Cages',
 'Beach Bars',
 'Beach Equipment Rentals',
 'Beaches',
 'Beauty & Spas',
 'Bed & Breakfast',
 'Beer',
 'Beer Bar',
 'Beer Gardens',
 'Beer Hall',
 'Beer Tours',
 'Behavior Analysts',
 'Belgian',
 'Bespoke Clothing',
 'Beverage Store',
 'Bicycle Paths',
 'Bicycles',
 'Bike Parking',
 'Bike Rentals',
 'Bike Repair',
 'Bike Repair/Maintenance',
 'Bike Sharing',
 'Bike Shop',
 'Bike tours',
 'Bikes',
 'Billing Services',
 'Bingo Halls',
 'Biohazard Cleanup',
 'Bird Shops',
 'Bistros',
 'Blood & Plasma Donation Centers',
 'Blow Dry/Out Services',
 'Boat Charters',
 'Boat Dealers',
 'Boat Parts & Supplies',
 'Boat Repair',
 'Boat Tours',
 'Boating',
 'Bocce Ball',
 'Body Contouring',
 'Body Shops',
 'Bookbinding',
 'Bookkeepers',
 'Books',
 'Bookstores',
 'Boot Camps',
 'Botanical Gardens',
 'Boudoir Photography',
 'Bounce House Rentals',
 'Bowling',
 'Boxing',
 'Brasseries',
 'Brazilian',
 'Brazilian Jiu-jitsu',
 'Breakfast & Brunch',
 'Breweries',
 'Brewing Supplies',
 'Brewpubs',
 'Bridal',
 'British',
 'Bubble Soccer',
 'Bubble Tea',
 'Buddhist Temples',
 'Buffets',
 'Building Supplies',
 'Burgers',
 'Burmese',
 'Bus Rental',
 'Bus Stations',
 'Bus Tours',
 'Buses',
 'Business Consulting',
 'Business Financing',
 'Business Law',
 'Butcher',
 'CPR Classes',
 'CSA',
 'Cabaret',
 'Cabinetry',
 'Cafes',
 'Cafeteria',
 'Cajun/Creole',
 'Calabrian',
 'Calligraphy',
 'Cambodian',
 'Campgrounds',
 'Canadian (New)',
 'Candle Stores',
 'Candy Stores',
 'Cannabis Clinics',
 'Cannabis Collective',
 'Cannabis Dispensaries',
 'Cannabis Tours',
 'Cantonese',
 'Car Auctions',
 'Car Brokers',
 'Car Buyers',
 'Car Dealers',
 'Car Inspectors',
 'Car Rental',
 'Car Share Services',
 'Car Stereo Installation',
 'Car Wash',
 'Car Window Tinting',
 'Cardio Classes',
 'Cardiologists',
 'Cards & Stationery',
 'Career Counseling',
 'Caribbean',
 'Caricatures',
 'Carousels',
 'Carpenters',
 'Carpet Cleaning',
 'Carpet Dyeing',
 'Carpet Installation',
 'Carpeting',
 'Casinos',
 'Caterers',
 'Ceremonial Clothing',
 'Challenge Courses',
 'Champagne Bars',
 'Check Cashing/Pay-day Loans',
 'Cheerleading',
 'Cheese Shops',
 'Cheese Tasting Classes',
 'Cheesesteaks',
 'Chicken Shop',
 'Chicken Wings',
 'Child Care & Day Care',
 'Childbirth Education',
 'Childproofing',
 "Children's Clothing",
 "Children's Museums",
 'Chimney Sweeps',
 'Chinese',
 'Chinese Martial Arts',
 'Chiropractors',
 'Chocolatiers & Shops',
 'Christmas Trees',
 'Churches',
 'Cideries',
 'Cigar Bars',
 'Cinema',
 'Circuit Training Gyms',
 'Circus Schools',
 'Climbing',
 'Clock Repair',
 'Clothing Rental',
 'Clowns',
 'Club Crawl',
 'Cocktail Bars',
 'Coffee & Tea',
 'Coffee & Tea Supplies',
 'Coffee Roasteries',
 'Coffeeshops',
 'College Counseling',
 'Colleges & Universities',
 'Colombian',
 'Colonics',
 'Comedy Clubs',
 'Comfort Food',
 'Comic Books',
 'Commercial Real Estate',
 'Commercial Truck Dealers',
 'Commercial Truck Repair',
 'Commissioned Artists',
 'Community Centers',
 'Community Gardens',
 'Community Service/Non-Profit',
 'Computers',
 'Concept Shops',
 'Concierge Medicine',
 'Condominiums',
 'Consumer Law',
 'Contract Law',
 'Contractors',
 'Convenience Stores',
 'Conveyor Belt Sushi',
 'Cooking Classes',
 'Cooking Schools',
 'Cosmetic Dentists',
 'Cosmetic Surgeons',
 'Cosmetics & Beauty Supply',
 'Cosmetology Schools',
 'Costumes',
 'Counseling & Mental Health',
 'Countertop Installation',
 'Country Clubs',
 'Country Dance Halls',
 'Couriers & Delivery Services',
 'Courthouses',
 'Crane Services',
 'Cremation Services',
 'Creperies',
 'Criminal Defense Law',
 'Crisis Pregnancy Centers',
 'Cryotherapy',
 'Cuban',
 'Cucina campana',
 'Cultural Center',
 'Cupcakes',
 'Currency Exchange',
 'Custom Cakes',
 'Customized Merchandise',
 'Cycling Classes',
 'Czech',
 'DIY Auto Shop',
 'DJs',
 'DUI Law',
 'DUI Schools',
 'Damage Restoration',
 'Dance Clubs',
 'Dance Schools',
 'Dance Studios',
 'Dance Wear',
 'Dart Arenas',
 'Data Recovery',
 'Day Camps',
 'Day Spas',
 'Debt Relief Services',
 'Decks & Railing',
 'Delicatessen',
 'Delis',
 'Demolition Services',
 'Dental Hygienists',
 'Dentists',
 'Department Stores',
 'Departments of Motor Vehicles',
 'Dermatologists',
 'Desserts',
 'Diagnostic Imaging',
 'Diagnostic Services',
 'Dialysis Clinics',
 'Diamond Buyers',
 'Dietitians',
 'Digitizing Services',
 'Dim Sum',
 'Diners',
 'Dinner Theater',
 'Disability Law',
 'Disc Golf',
 'Discount Store',
 'Distilleries',
 'Dive Bars',
 'Dive Shops',
 'Diving',
 'Divorce & Family Law',
 'Do-It-Yourself Food',
 'Doctors',
 'Dog Parks',
 'Dog Walkers',
 'Dominican',
 'Donairs',
 'Donation Center',
 'Donburi',
 'Donuts',
 'Door Sales/Installation',
 'Doulas',
 'Drama Schools',
 'Drive-In Theater',
 'Drive-Thru Bars',
 'Driving Schools',
 'Drones',
 'Drugstores',
 'Dry Cleaning',
 'Dry Cleaning & Laundry',
 'Drywall Installation & Repair',
 'Dumplings',
 'Dumpster Rental',
 'Duplication Services',
 'EV Charging Stations',
 'Ear Nose & Throat',
 'Eastern European',
 'Eatertainment',
 'Editorial Services',
 'Education',
 'Educational Services',
 'Egyptian',
 'Elder Care Planning',
 'Elder Law',
 'Electricians',
 'Electricity Suppliers',
 'Electronics',
 'Electronics Repair',
 'Elementary Schools',
 'Elevator Services',
 'Embassy',
 'Embroidery & Crochet',
 'Emergency Medicine',
 'Emergency Pet Hospital',
 'Emergency Rooms',
 'Empanadas',
 'Employment Agencies',
 'Employment Law',
 'Endocrinologists',
 'Endodontists',
 'Engraving',
 'Environmental Abatement',
 'Environmental Testing',
 'Escape Games',
 'Estate Liquidation',
 'Estate Planning Law',
 'Estheticians',
 'Ethical Grocery',
 'Ethiopian',
 'Ethnic Food',
 'Ethnic Grocery',
 'Event Photography',
 'Event Planning & Services',
 'Excavation Services',
 'Experiences',
 'Eyebrow Services',
 'Eyelash Service',
 'Eyewear & Opticians',
 'Fabric Stores',
 'Face Painting',
 'Faith-based Crisis Pregnancy Centers',
 'Falafel',
 'Family Practice',
 'Farm Equipment Repair',
 'Farmers Market',
 'Farming Equipment',
 'Farms',
 'Fashion',
 'Fast Food',
 'Fences & Gates',
 'Fencing Clubs',
 'Ferries',
 'Fertility',
 'Festivals',
 'Filipino',
 'Financial Advising',
 'Financial Services',
 'Fingerprinting',
 'Fire Departments',
 'Fire Protection Services',
 'Firearm Training',
 'Fireplace Services',
 'Firewood',
 'Fireworks',
 'First Aid Classes',
 'Fish & Chips',
 'Fishing',
 'Fitness & Instruction',
 'Fitness/Exercise Equipment',
 'Flea Markets',
 'Flight Instruction',
 'Float Spa',
 'Flooring',
 'Floral Designers',
 'Florists',
 'Flowers',
 'Flowers & Gifts',
 'Flyboarding',
 'Fondue',
 'Food',
 'Food Banks',
 'Food Court',
 'Food Delivery Services',
 'Food Stands',
 'Food Tours',
 'Food Trucks',
 'Foot Care',
 'Formal Wear',
 'Foundation Repair',
 'Framing',
 'Free Diving',
 'French',
 'Fruits & Veggies',
 'Fuel Docks',
 'Funeral Services & Cemeteries',
 'Fur Clothing',
 'Furniture Assembly',
 'Furniture Rental',
 'Furniture Repair',
 'Furniture Reupholstery',
 'Furniture Stores',
 'Fuzhou',
 'Game Truck Rental',
 'Garage Door Services',
 'Gardeners',
 'Gas Stations',
 'Gastroenterologist',
 'Gastropubs',
 'Gay Bars',
 'Gelato',
 'Gemstones & Minerals',
 'General Dentistry',
 'General Festivals',
 'General Litigation',
 'Generator Installation/Repair',
 'Georgian',
 'German',
 'Gerontologists',
 'Gift Shops',
 'Glass & Mirrors',
 'Glass Blowing',
 'Gluten-Free',
 'Go Karts',
 'Gold Buyers',
 'Golf',
 'Golf Cart Dealers',
 'Golf Cart Rentals',
 'Golf Equipment',
 'Golf Equipment Shops',
 'Golf Lessons',
 'Graphic Design',
 'Greek',
 'Grill Services',
 'Grilling Equipment',
 'Grocery',
 'Grout Services',
 'Guamanian',
 'Guest Houses',
 'Guitar Stores',
 'Gun/Rifle Ranges',
 'Guns & Ammo',
 'Gunsmith',
 'Gutter Services',
 'Gymnastics',
 'Gyms',
 'Hainan',
 'Hair Extensions',
 'Hair Loss Centers',
 'Hair Removal',
 'Hair Salons',
 'Hair Stylists',
 'Haitian',
 'Hakka',
 'Halal',
 'Halfway Houses',
 'Halotherapy',
 'Handyman',
 'Hang Gliding',
 'Hardware Stores',
 'Hats',
 'Haunted Houses',
 'Hawaiian',
 'Hazardous Waste Disposal',
 'Head Shops',
 'Health & Medical',
 'Health Coach',
 'Health Insurance Offices',
 'Health Markets',
 'Health Retreats',
 'Hearing Aid Providers',
 'Heating & Air Conditioning/HVAC',
 'Henna Artists',
 'Hepatologists',
 'Herbal Shops',
 'Herbs & Spices',
 'High Fidelity Audio Equipment',
 'Hiking',
 'Himalayan/Nepalese',
 'Hindu Temples',
 'Historical Tours',
 'Hobby Shops',
 'Hockey Equipment',
 'Holiday Decorating Services',
 'Holiday Decorations',
 'Holistic Animal Care',
 'Home & Garden',
 'Home & Rental Insurance',
 'Home Automation',
 'Home Cleaning',
 'Home Decor',
 'Home Developers',
 'Home Energy Auditors',
 'Home Health Care',
 'Home Inspectors',
 'Home Network Installation',
 'Home Organization',
 'Home Services',
 'Home Staging',
 'Home Theatre Installation',
 'Home Window Tinting',
 'Homeless Shelters',
 'Homeowner Association',
 'Honduran',
 'Honey',
 'Hong Kong Style Cafe',
 'Hookah Bars',
 'Horse Boarding',
 'Horse Equipment Shops',
 'Horse Racing',
 'Horseback Riding',
 'Hospice',
 'Hospitalists',
 'Hospitals',
 'Hostels',
 'Hot Air Balloons',
 'Hot Dogs',
 'Hot Pot',
 'Hot Tub & Pool',
 'Hotel bar',
 'Hotels',
 'Hotels & Travel',
 'House Sitters',
 'Housing Cooperatives',
 'Hungarian',
 'Hunting & Fishing Supplies',
 'Hybrid Car Repair',
 'Hydro-jetting',
 'Hydroponics',
 'Hydrotherapy',
 'Hypnosis/Hypnotherapy',
 'IP & Internet Law',
 'IT Services & Computer Repair',
 'IV Hydration',
 'Iberian',
 'Ice Cream & Frozen Yogurt',
 'Ice Delivery',
 'Immigration Law',
 'Immunodermatologists',
 'Imported Food',
 'Indian',
 'Indonesian',
 'Indoor Landscaping',
 'Indoor Playcentre',
 'Infectious Disease Specialists',
 'Installment Loans',
 'Insulation Installation',
 'Insurance',
 'Interior Design',
 'Interlock Systems',
 'Internal Medicine',
 'International',
 'International Grocery',
 'Internet Cafes',
 'Internet Service Providers',
 'Interval Training Gyms',
 'Investing',
 'Irish',
 'Irish Pub',
 'Irrigation',
 'Israeli',
 'Italian',
 'Izakaya',
 'Jails & Prisons',
 'Japanese',
 'Japanese Curry',
 'Jazz & Blues',
 'Jet Skis',
 'Jewelry',
 'Jewelry Repair',
 'Juice Bars & Smoothies',
 'Junk Removal & Hauling',
 'Junkyards',
 'Karaoke',
 'Karaoke Rental',
 'Karate',
 'Kebab',
 'Keys & Locksmiths',
 'Kickboxing',
 'Kids Activities',
 'Kids Hair Salons',
 'Kiosk',
 'Kitchen & Bath',
 'Kitchen Incubators',
 'Kitchen Supplies',
 'Kiteboarding',
 'Knife Sharpening',
 'Knitting Supplies',
 'Kombucha',
 'Korean',
 'Kosher',
 'LAN Centers',
 'Laboratory Testing',
 'Lactation Services',
 'Lahmacun',
 'Lakes',
 'Land Surveying',
 'Landmarks & Historical Buildings',
 'Landscape Architects',
 'Landscaping',
 'Language Schools',
 'Laotian',
 'Laser Eye Surgery/Lasik',
 'Laser Hair Removal',
 'Laser Tag',
 'Latin American',
 'Laundromat',
 'Laundry Services',
 'Lawn Services',
 'Lawyers',
 'Leather Goods',
 'Lebanese',
 'Legal Services',
 'Leisure Centers',
 'Libraries',
 'Lice Services',
 'Life Coach',
 'Life Insurance',
 'Lighting Fixtures & Equipment',
 'Lighting Stores',
 'Limos',
 'Lingerie',
 'Live/Raw Food',
 'Livestock Feed & Supply',
 'Local Fish Stores',
 'Local Flavor',
 'Local Services',
 'Lounges',
 'Luggage',
 'Luggage Storage',
 'Macarons',
 'Machine & Tool Rental',
 'Machine Shops',
 'Magicians',
 'Mags',
 'Mailbox Centers',
 'Makerspaces',
 'Makeup Artists',
 'Malaysian',
 'Marinas',
 'Marketing',
 'Martial Arts',
 'Masonry/Concrete',
 'Mass Media',
 'Massage',
 'Massage Schools',
 'Massage Therapy',
 'Matchmakers',
 'Maternity Wear',
 'Mattresses',
 'Meaderies',
 'Meat Shops',
 'Mediators',
 'Medical Cannabis Referrals',
 'Medical Centers',
 'Medical Law',
 'Medical Spas',
 'Medical Supplies',
 'Medical Transportation',
 'Meditation Centers',
 'Mediterranean',
 'Memory Care',
 "Men's Clothing",
 "Men's Hair Salons",
 'Metal Detector Services',
 'Metal Fabricators',
 'Mexican',
 'Middle Eastern',
 'Middle Schools & High Schools',
 'Midwives',
 'Military Surplus',
 'Mini Golf',
 'Mobile Dent Repair',
 'Mobile Home Dealers',
 'Mobile Home Parks',
 'Mobile Home Repair',
 'Mobile Phone Accessories',
 'Mobile Phone Repair',
 'Mobile Phones',
 'Mobility Equipment Sales & Services',
 'Modern European',
 'Mohels',
 'Mongolian',
 'Montessori Schools',
 'Moroccan',
 'Mortgage Brokers',
 'Mortgage Lenders',
 'Mortuary Services',
 'Mosques',
 'Motorcycle Dealers',
 'Motorcycle Gear',
 'Motorcycle Parts & Supplies',
 'Motorcycle Rental',
 'Motorcycle Repair',
 'Motorsport Vehicle Dealers',
 'Motorsport Vehicle Repairs',
 'Mountain Biking',
 'Movers',
 'Muay Thai',
 'Municipality',
 'Museums',
 'Music & DVDs',
 'Music & Video',
 'Music Production Services',
 'Music Venues',
 'Musical Instrument Services',
 'Musical Instruments & Teachers',
 'Musicians',
 'Nail Salons',
 'Nail Technicians',
 'Nanny Services',
 'Natural Gas Suppliers',
 'Naturopathic/Holistic',
 'Nephrologists',
 'Neurologist',
 'Neuropathologists',
 'Neurotologists',
 'New Mexican Cuisine',
 'Newspapers & Magazines',
 'Nicaraguan',
 'Nightlife',
 'Noodles',
 'Notaries',
 'Nudist',
 'Nurse Practitioner',
 'Nurseries & Gardening',
 'Nursing Schools',
 'Nutritionists',
 'Observatories',
 'Obstetricians & Gynecologists',
 'Occupational Therapy',
 'Office Cleaning',
 'Office Equipment',
 'Officiants',
 'Oil Change Stations',
 'Olive Oil',
 'Oncologist',
 'Opera & Ballet',
 'Ophthalmologists',
 'Optometrists',
 'Oral Surgeons',
 'Organic Stores',
 'Oriental',
 'Orthodontists',
 'Orthopedists',
 'Orthotics',
 'Osteopathic Physicians',
 'Osteopaths',
 'Otologists',
 'Outdoor Furniture Stores',
 'Outdoor Gear',
 'Outdoor Movies',
 'Outdoor Power Equipment Services',
 'Outlet Stores',
 'Oxygen Bars',
 'Packing Services',
 'Packing Supplies',
 'Paddleboarding',
 'Pain Management',
 'Paint & Sip',
 'Paint Stores',
 'Paint-Your-Own Pottery',
 'Paintball',
 'Painters',
 'Pakistani',
 'Pan Asian',
 'Pancakes',
 'Paragliding',
 'Parasailing',
 'Parent Cafes',
 'Parenting Classes',
 'Parking',
 'Parklets',
 'Parks',
 'Party & Event Planning',
 'Party Bike Rentals',
 'Party Bus Rentals',
 'Party Characters',
 'Party Equipment Rentals',
 'Party Supplies',
 'Passport & Visa Services',
 'Pasta Shops',
 'Patent Law',
 'Pathologists',
 'Patio Coverings',
 'Patisserie/Cake Shop',
 'Pawn Shops',
 'Payroll Services',
 'Pediatric Dentists',
 'Pediatricians',
 'Pedicabs',
 'Performing Arts',
 'Perfume',
 'Periodontists',
 'Permanent Makeup',
 'Persian/Iranian',
 'Personal Assistants',
 'Personal Care Services',
 'Personal Chefs',
 'Personal Injury Law',
 'Personal Shopping',
 'Peruvian',
 'Pest Control',
 'Pet Adoption',
 'Pet Boarding',
 'Pet Breeders',
 'Pet Cremation Services',
 'Pet Groomers',
 'Pet Hospice',
 'Pet Insurance',
 'Pet Photography',
 'Pet Services',
 'Pet Sitting',
 'Pet Stores',
 'Pet Training',
 'Pet Transportation',
 'Pet Waste Removal',
 'Pets',
 'Petting Zoos',
 'Pharmacy',
 'Phlebologists',
 'Photo Booth Rentals',
 'Photographers',
 'Photography Classes',
 'Photography Stores & Services',
 'Physical Therapy',
 'Piano Bars',
 'Piano Services',
 'Piano Stores',
 'Pick Your Own Farms',
 'Pickleball',
 'Piercing',
 'Pilates',
 'Pita',
 'Pizza',
 'Placenta Encapsulations',
 'Planetarium',
 'Plastic Surgeons',
 'Playgrounds',
 'Playsets',
 'Plumbing',
 'Plus Size Fashion',
 'Podiatrists',
 'Poke',
 'Pole Dancing Classes',
 'Police Departments',
 'Polish',
 'Pool & Billiards',
 'Pool & Hot Tub Service',
 'Pool Cleaners',
 'Pool Halls',
 'Pop-Up Restaurants',
 'Pop-up Shops',
 'Popcorn Shops',
 'Portable Toilet Services',
 'Portuguese',
 'Post Offices',
 'Poutineries',
 'Powder Coating',
 'Prenatal/Perinatal Care',
 'Preschools',
 'Pressure Washers',
 'Pretzels',
 'Preventive Medicine',
 'Print Media',
 'Printing Services',
 'Private Investigation',
 'Private Jet Charter',
 'Private Schools',
 'Private Tutors',
 'Process Servers',
 'Proctologists',
 'Product Design',
 'Professional Services',
 'Professional Sports Teams',
 'Propane',
 'Property Management',
 'Props',
 'Prosthetics',
 'Prosthodontists',
 'Psychiatrists',
 'Psychic Mediums',
 'Psychics',
 'Psychologists',
 'Public Adjusters',
 'Public Art',
 'Public Markets',
 'Public Relations',
 'Public Services & Government',
 'Public Transportation',
 'Pubs',
 'Puerto Rican',
 'Pulmonologist',
 'Pumpkin Patches',
 'Qi Gong',
 'RV Dealers',
 'RV Parks',
 'RV Rental',
 'RV Repair',
 'Race Tracks',
 'Races & Competitions',
 'Racing Experience',
 'Radio Stations',
 'Radiologists',
 'Rafting/Kayaking',
 'Ramen',
 'Ranches',
 'Real Estate',
 'Real Estate Agents',
 'Real Estate Law',
 'Real Estate Photography',
 'Real Estate Services',
 'Recording & Rehearsal Studios',
 'Recreation Centers',
 ...]

#### Creating the categories dataset

In [14]:
df_business_categories_id = pd.DataFrame(enumerate(categories_set), columns=['category_id', 'category_name']).set_index('category_id')
df_business_categories_id

                 category_name
category_id
0                   & Probates
1                  3D Printing
2            ATV Rentals/Tours
3                   Acai Bowls
4                  Accessories
...                        ...
1306                     Wraps
1307               Yelp Events
1308                      Yoga
1309                 Ziplining
1310                      Zoos

[1311 rows x 1 columns]

#### [DONT RUN THIS SECTION] Grouping categories though ML (these are actually more like tags...)
- Food & Dining
- Shopping
- Beauty / Personal Care
- Health & Wellness
- Professional Services
- Home Services
- Automotive
- Fitness
- Pets
- Entertainment
- Financial Services
- Real Estate

##### Build the embeddings model
##### TODO: Need to refine the grouping or take care of some edge cases

In [15]:
group_name_mapping = {
    0: 'Pets',
    1: 'Shopping',
    2: 'Professional Services',
    3: 'Beauty / Personal Care',
    4: 'Education',
    5: 'Food & Dining',
    6: 'Financial Services',
    7: 'Entertainment',
    8: 'Fitness',
    9: 'Health & Wellness',
    10: 'Home Services',
    11: 'Transportation',
}

In [16]:
from sentence_transformers import SentenceTransformer

model_name = 'all-MiniLM-L6-v2'
# model_name = 'multi-qa-mpnet-base-dot-v1'
model = SentenceTransformer(model_name)
embeddings = model.encode(df_business_categories_id['category_name'], show_progress_bar=True)
# df_business_categories_id.to_pickle(export_clean_directory / 'categories_with_embeddings.pkl')

/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
sentence_transformers.SentenceTransformer: INFO: Use pytorch device_name: mps
sentence_transformers.SentenceTransformer: INFO: Load pretrained SentenceTransformer: all-MiniLM-L6-v2
Batches: 100%|██████████| 41/41 [00:00<00:00, 56.22it/s]

##### With hdbscan

In [17]:
# import hdbscan
# x = np.vstack(embeddings.tolist())
# clusterer = hdbscan.HDBSCAN(min_cluster_size=3, min_samples=3, metric='euclidean')
# df_business_categories_id['group_id'] = clusterer.fit_predict(x)
# len(df_business_categories_id['group_id'].value_counts())

##### With sklean clustering

In [18]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import normalize

embeddings = normalize(embeddings)
num_clusters = 12

kmeans = KMeans(
    n_clusters=num_clusters,
    random_state=2,
    n_init='auto',
    max_iter=500,
)
group_ids = kmeans.fit_predict(embeddings)
group_ids

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

array([ 6,  2, 11, ...,  8,  2,  0], shape=(1311,), dtype=int32)

##### Create DataFrame for groups

In [19]:
df_business_groups_id = pd.DataFrame(
    {'group_id': group_name_mapping.keys(),
     'group_name': group_name_mapping.values()}
).set_index('group_id')
df_business_groups_id

                      group_name
group_id
0                           Pets
1                       Shopping
2          Professional Services
3         Beauty / Personal Care
4                      Education
5                  Food & Dining
6             Financial Services
7                  Entertainment
8                        Fitness
9              Health & Wellness
10                 Home Services
11                Transportation

#### Creating the business/categories key dataset

In [20]:
business_categories_data = []
for idx, business_data in categories_dict.items():
    business_id = business_data['business_id']
    for category in business_data['categories']:
        category_id = categories_set.index(category)
        business_categories_data.append({'business_id': business_id, 'category_id': category_id})
business_categories_data

[{'business_id': 'Pns2l4eNsfO8kk83dixA6A', 'category_id': 359},
 {'business_id': 'Pns2l4eNsfO8kk83dixA6A', 'category_id': 1200},
 {'business_id': 'Pns2l4eNsfO8kk83dixA6A', 'category_id': 798},
 {'business_id': 'Pns2l4eNsfO8kk83dixA6A', 'category_id': 8},
 {'business_id': 'Pns2l4eNsfO8kk83dixA6A', 'category_id': 551},
 {'business_id': 'Pns2l4eNsfO8kk83dixA6A', 'category_id': 813},
 {'business_id': 'mpf3x-BjTdTEA3yCZrAYPw', 'category_id': 1065},
 {'business_id': 'mpf3x-BjTdTEA3yCZrAYPw', 'category_id': 712},
 {'business_id': 'mpf3x-BjTdTEA3yCZrAYPw', 'category_id': 808},
 {'business_id': 'mpf3x-BjTdTEA3yCZrAYPw', 'category_id': 721},
 {'business_id': 'mpf3x-BjTdTEA3yCZrAYPw', 'category_id': 951},
 {'business_id': 'tUFrWirKiKi_TAnsVWINQQ', 'category_id': 337},
 {'business_id': 'tUFrWirKiKi_TAnsVWINQQ', 'category_id': 1069},
 {'business_id': 'tUFrWirKiKi_TAnsVWINQQ', 'category_id': 434},
 {'business_id': 'tUFrWirKiKi_TAnsVWINQQ', 'category_id': 572},
 {'business_id': 'tUFrWirKiKi_TAnsVWINQQ', 'category_id': 393},
 {'business_id': 'tUFrWirKiKi_TAnsVWINQQ', 'category_id': 487},
 {'business_id': 'MTSW4McQd7CbVtyjqoe9mw', 'category_id': 1014},
 {'business_id': 'MTSW4McQd7CbVtyjqoe9mw', 'category_id': 466},
 {'business_id': 'MTSW4McQd7CbVtyjqoe9mw', 'category_id': 172},
 {'business_id': 'MTSW4McQd7CbVtyjqoe9mw', 'category_id': 262},
 {'business_id': 'MTSW4McQd7CbVtyjqoe9mw', 'category_id': 95},
 {'business_id': 'mWMc6_wTdE0EUBKIGXDVfA', 'category_id': 168},
 {'business_id': 'mWMc6_wTdE0EUBKIGXDVfA', 'category_id': 166},
 {'business_id': 'mWMc6_wTdE0EUBKIGXDVfA', 'category_id': 466},
 {'business_id': 'CF33F8-E6oudUQ46HnavjQ', 'category_id': 176},
 {'business_id': 'CF33F8-E6oudUQ46HnavjQ', 'category_id': 435},
 {'business_id': 'CF33F8-E6oudUQ46HnavjQ', 'category_id': 1033},
 {'business_id': 'CF33F8-E6oudUQ46HnavjQ', 'category_id': 466},
 {'business_id': 'CF33F8-E6oudUQ46HnavjQ', 'category_id': 621},
 {'business_id': 'CF33F8-E6oudUQ46HnavjQ', 'category_id': 1014},
 {'business_id': 'n_0UpQx1hsNbnPUSlodU8w', 'category_id': 1117},
 {'business_id': 'n_0UpQx1hsNbnPUSlodU8w', 'category_id': 434},
 {'business_id': 'n_0UpQx1hsNbnPUSlodU8w', 'category_id': 1068},
 {'business_id': 'n_0UpQx1hsNbnPUSlodU8w', 'category_id': 1069},
 {'business_id': 'n_0UpQx1hsNbnPUSlodU8w', 'category_id': 1123},
 {'business_id': 'n_0UpQx1hsNbnPUSlodU8w', 'category_id': 4},
 {'business_id': 'qkRM_2X51Yqxk3btlwAQIg', 'category_id': 1149},
 {'business_id': 'qkRM_2X51Yqxk3btlwAQIg', 'category_id': 1007},
 {'business_id': 'k0hlBqXX-Bt0vf1op7Jr1w', 'category_id': 976},
 {'business_id': 'k0hlBqXX-Bt0vf1op7Jr1w', 'category_id': 1014},
 {'business_id': 'k0hlBqXX-Bt0vf1op7Jr1w', 'category_id': 647},
 {'business_id': 'k0hlBqXX-Bt0vf1op7Jr1w', 'category_id': 104},
 {'business_id': 'k0hlBqXX-Bt0vf1op7Jr1w', 'category_id': 33},
 {'business_id': 'k0hlBqXX-Bt0vf1op7Jr1w', 'category_id': 806},
 {'business_id': 'k0hlBqXX-Bt0vf1op7Jr1w', 'category_id': 518},
 {'business_id': 'bBDDEgkFA1Otx9Lfe7BZUQ', 'category_id': 621},
 {'business_id': 'bBDDEgkFA1Otx9Lfe7BZUQ', 'category_id': 435},
 {'business_id': 'bBDDEgkFA1Otx9Lfe7BZUQ', 'category_id': 176},
 {'business_id': 'bBDDEgkFA1Otx9Lfe7BZUQ', 'category_id': 1014},
 {'business_id': 'bBDDEgkFA1Otx9Lfe7BZUQ', 'category_id': 466},
 {'business_id': 'UJsufbvfyfONHeWdvAHKjA', 'category_id': 337},
 {'business_id': 'UJsufbvfyfONHeWdvAHKjA', 'category_id': 1069},
 {'business_id': 'UJsufbvfyfONHeWdvAHKjA', 'category_id': 434},
 {'business_id': 'eEOYSgkmpB90uNA7lDOMRA', 'category_id': 1258},
 {'business_id': 'eEOYSgkmpB90uNA7lDOMRA', 'category_id': 466},
 {'business_id': 'eEOYSgkmpB90uNA7lDOMRA', 'category_id': 1014},
 {'business_id': 'eEOYSgkmpB90uNA7lDOMRA', 'category_id': 472},
 {'business_id': 'il_Ro8jwPlHresjw9EGmBg', 'category_id': 33},
 {'business_id': 'il_Ro8jwPlHresjw9EGmBg', 'category_id': 1014},
 {'business_id': 'il_Ro8jwPlHresjw9EGmBg', 'category_id': 348},
 {'business_id': 'il_Ro8jwPlHresjw9EGmBg', 'category_id': 165},
 {'business_id': 'jaxMSoInw8Poo3XeMJt8lQ', 'category_id': 498},
 {'business_id': 'jaxMSoInw8Poo3XeMJt8lQ', 'category_id': 336},
 {'business_id': 'jaxMSoInw8Poo3XeMJt8lQ', 'category_id': 551},
 {'business_id': 'jaxMSoInw8Poo3XeMJt8lQ', 'category_id': 291},
 {'business_id': '0bPLkL0QhhPO5kt1_EXmNQ', 'category_id': 466},
 {'business_id': '0bPLkL0QhhPO5kt1_EXmNQ', 'category_id': 333},
 {'business_id': '0bPLkL0QhhPO5kt1_EXmNQ', 'category_id': 647},
 {'business_id': '0bPLkL0QhhPO5kt1_EXmNQ', 'category_id': 95},
 {'business_id': '0bPLkL0QhhPO5kt1_EXmNQ', 'category_id': 1014},
 {'business_id': 'MUTTqe8uqyMdBl186RmNeA', 'category_id': 1145},
 {'business_id': 'MUTTqe8uqyMdBl186RmNeA', 'category_id': 1014},
 {'business_id': 'MUTTqe8uqyMdBl186RmNeA', 'category_id': 650},
 {'business_id': 'rBmpy_Y1UbBx8ggHlyb7hA', 'category_id': 85},
 {'business_id': 'rBmpy_Y1UbBx8ggHlyb7hA', 'category_id': 81},
 {'business_id': 'rBmpy_Y1UbBx8ggHlyb7hA', 'category_id': 76},
 {'business_id': 'M0XSSHqrASOnhgbWDJIpQA', 'category_id': 1243},
 {'business_id': 'M0XSSHqrASOnhgbWDJIpQA', 'category_id': 1192},
 {'business_id': 'M0XSSHqrASOnhgbWDJIpQA', 'category_id': 886},
 {'business_id': 'M0XSSHqrASOnhgbWDJIpQA', 'category_id': 1263},
 {'business_id': 'M0XSSHqrASOnhgbWDJIpQA', 'category_id': 1069},
 {'business_id': '8wGISYjYkE2tSqn3cDMu8A', 'category_id': 85},
 {'business_id': '8wGISYjYkE2tSqn3cDMu8A', 'category_id': 210},
 {'business_id': '8wGISYjYkE2tSqn3cDMu8A', 'category_id': 607},
 {'business_id': '8wGISYjYkE2tSqn3cDMu8A', 'category_id': 1220},
 {'business_id': 'ROeacJQwBeh05Rqg7F6TCg', 'category_id': 675},
 {'business_id': 'ROeacJQwBeh05Rqg7F6TCg', 'category_id': 1014},
 {'business_id': 'WKMJwqnfZKsAae75RMP6jA', 'category_id': 262},
 {'business_id': 'WKMJwqnfZKsAae75RMP6jA', 'category_id': 466},
 {'business_id': 'WKMJwqnfZKsAae75RMP6jA', 'category_id': 190},
 {'business_id': 'WKMJwqnfZKsAae75RMP6jA', 'category_id': 104},
 {'business_id': 'WKMJwqnfZKsAae75RMP6jA', 'category_id': 1299},
 {'business_id': 'WKMJwqnfZKsAae75RMP6jA', 'category_id': 1014},
 {'business_id': 'WKMJwqnfZKsAae75RMP6jA', 'category_id': 806},
 {'business_id': 'qhDdDeI3K4jy2KyzwFN53w', 'category_id': 1069},
 {'business_id': 'qhDdDeI3K4jy2KyzwFN53w', 'category_id': 154},
 {'business_id': 'qhDdDeI3K4jy2KyzwFN53w', 'category_id': 720},
 {'business_id': 'qhDdDeI3K4jy2KyzwFN53w', 'category_id': 788},
 {'business_id': 'qhDdDeI3K4jy2KyzwFN53w', 'category_id': 155},
 {'business_id': 'kfNv-JZpuN6TVNSO6hHdkw', 'category_id': 1128},
 {'business_id': 'kfNv-JZpuN6TVNSO6hHdkw', 'category_id': 67},
 {'business_id': 'kfNv-JZpuN6TVNSO6hHdkw', 'category_id': 1014},
 {'business_id': '9OG5YkX1g2GReZM0AskizA', 'category_id': 1014},
 {'business_id': '9OG5YkX1g2GReZM0AskizA', 'category_id': 647},
 {'business_id': '4iRzR7OaS-QaSXuvYxEGKA', 'category_id': 602},
 {'business_id': '4iRzR7OaS-QaSXuvYxEGKA', 'category_id': 1014},
 {'business_id': 'PSo_C1Sfa13JHjzVNW6ziQ', 'category_id': 897},
 {'business_id': 'PSo_C1Sfa13JHjzVNW6ziQ', 'category_id': 893},
 {'business_id': 'PSo_C1Sfa13JHjzVNW6ziQ', 'category_id': 903},
 {'business_id': 'PSo_C1Sfa13JHjzVNW6ziQ', 'category_id': 1253},
 {'business_id': 'noByYNtDLQAra9ccqxdfDw', 'category_id': 1304},
 {'business_id': 'noByYNtDLQAra9ccqxdfDw', 'category_id': 4},
 {'business_id': 'noByYNtDLQAra9ccqxdfDw', 'category_id': 242},
 {'business_id': 'noByYNtDLQAra9ccqxdfDw', 'category_id': 748},
 {'business_id': 'noByYNtDLQAra9ccqxdfDw', 'category_id': 11},
 {'business_id': 'noByYNtDLQAra9ccqxdfDw', 'category_id': 1069},
 {'business_id': 'noByYNtDLQAra9ccqxdfDw', 'category_id': 434},
 {'business_id': 'tMkwHmWFUEXrC9ZduonpTg', 'category_id': 1014},
 {'business_id': 'tMkwHmWFUEXrC9ZduonpTg', 'category_id': 650},
 {'business_id': 'tMkwHmWFUEXrC9ZduonpTg', 'category_id': 1045},
 {'business_id': 'QdN72BWoyFypdGJhhI5r7g', 'category_id': 261},
 {'business_id': 'QdN72BWoyFypdGJhhI5r7g', 'category_id': 104},
 {'business_id': 'QdN72BWoyFypdGJhhI5r7g', 'category_id': 647},
 {'business_id': 'QdN72BWoyFypdGJhhI5r7g', 'category_id': 806},
 {'business_id': 'QdN72BWoyFypdGJhhI5r7g', 'category_id': 1014},
 {'business_id': 'sqSqqLy0sN8n2IZrAbzidQ', 'category_id': 920},
 {'business_id': 'sqSqqLy0sN8n2IZrAbzidQ', 'category_id': 238},
 {'business_id': 'sqSqqLy0sN8n2IZrAbzidQ', 'category_id': 1033},
 {'business_id': 'sqSqqLy0sN8n2IZrAbzidQ', 'category_id': 1014},
 {'business_id': 'fvWn8oXXwbj2l79cochZyw', 'category_id': 1210},
 {'business_id': 'fvWn8oXXwbj2l79cochZyw', 'category_id': 7},
 {'business_id': 'Mjboz24M9NlBeiOJKLEd_Q', 'category_id': 920},
 {'business_id': 'Mjboz24M9NlBeiOJKLEd_Q', 'category_id': 1014},
 {'business_id': 'Mjboz24M9NlBeiOJKLEd_Q', 'category_id': 1030},
 {'business_id': 'Mjboz24M9NlBeiOJKLEd_Q', 'category_id': 1102},
 {'business_id': '8sshLb4UU7emeUDvtJWnpA', 'category_id': 325},
 {'business_id': '8sshLb4UU7emeUDvtJWnpA', 'category_id': 1123},
 {'business_id': '8sshLb4UU7emeUDvtJWnpA', 'category_id': 242},
 {'business_id': '8sshLb4UU7emeUDvtJWnpA', 'category_id': 66},
 {'business_id': '8sshLb4UU7emeUDvtJWnpA', 'category_id': 1095},
 {'business_id': '8sshLb4UU7emeUDvtJWnpA', 'category_id': 877},
 {'business_id': '8sshLb4UU7emeUDvtJWnpA', 'category_id': 1117},
 {'business_id': '8sshLb4UU7emeUDvtJWnpA', 'category_id': 1068},
 {'business_id': '8sshLb4UU7emeUDvtJWnpA', 'category_id': 434},
 {'business_id': '8sshLb4UU7emeUDvtJWnpA', 'category_id': 1069},
 {'business_id': 'kV_Q1oqis8Qli8dUoGpTyQ', 'category_id': 920},
 {'business_id': 'kV_Q1oqis8Qli8dUoGpTyQ', 'category_id': 1014},
 {'business_id': 'w_AMNoI1iG9eay7ncmc67w', 'category_id': 419},
 {'business_id': 'w_AMNoI1iG9eay7ncmc67w', 'category_id': 606},
 {'business_id': 'w_AMNoI1iG9eay7ncmc67w', 'category_id': 607},
 {'business_id': 'aPNXGTDkf-4bjhyMBQxqpQ', 'category_id': 384},
 {'business_id': 'aPNXGTDkf-4bjhyMBQxqpQ', 'category_id': 66},
 {'business_id': 'aPNXGTDkf-4bjhyMBQxqpQ', 'category_id': 168},
 {'business_id': 'aPNXGTDkf-4bjhyMBQxqpQ', 'category_id': 33},
 {'business_id': 'aPNXGTDkf-4bjhyMBQxqpQ', 'category_id': 95},
 {'business_id': 'aPNXGTDkf-4bjhyMBQxqpQ', 'category_id': 166},
 {'business_id': 'aPNXGTDkf-4bjhyMBQxqpQ', 'category_id': 466},
 {'business_id': 'aPNXGTDkf-4bjhyMBQxqpQ', 'category_id': 1014},
 {'business_id': '2xVsWBNFwZOxIOdd9Mwnww', 'category_id': 1014},
 {'business_id': '2xVsWBNFwZOxIOdd9Mwnww', 'category_id': 176},
 {'business_id': 'mGFsPRHdE6SMV1gYQ6GzgQ', 'category_id': 764},
 {'business_id': 'mGFsPRHdE6SMV1gYQ6GzgQ', 'category_id': 1175},
 {'business_id': 'mGFsPRHdE6SMV1gYQ6GzgQ', 'category_id': 393},
 {'business_id': 'mGFsPRHdE6SMV1gYQ6GzgQ', 'category_id': 762},
 {'business_id': 'mGFsPRHdE6SMV1gYQ6GzgQ', 'category_id': 712},
 {'business_id': 'mGFsPRHdE6SMV1gYQ6GzgQ', 'category_id': 1069},
 {'business_id': 'mGFsPRHdE6SMV1gYQ6GzgQ', 'category_id': 618},
 {'business_id': 'LcAozWCMLGjwRbokaJAKMg', 'category_id': 786},
 {'business_id': 'LcAozWCMLGjwRbokaJAKMg', 'category_id': 665},
 {'business_id': 'LcAozWCMLGjwRbokaJAKMg', 'category_id': 66},
 {'business_id': 'LcAozWCMLGjwRbokaJAKMg', 'category_id': 386},
 {'business_id': 'LcAozWCMLGjwRbokaJAKMg', 'category_id': 7},
 {'business_id': 'LcAozWCMLGjwRbokaJAKMg', 'category_id': 924},
 {'business_id': 'LcAozWCMLGjwRbokaJAKMg', 'category_id': 243},
 {'business_id': 'fSCNwMtNNQY9QT69Cj9fiA', 'category_id': 793},
 {'business_id': 'fSCNwMtNNQY9QT69Cj9fiA', 'category_id': 318},
 {'business_id': 'fSCNwMtNNQY9QT69Cj9fiA', 'category_id': 659},
 {'business_id': 'fSCNwMtNNQY9QT69Cj9fiA', 'category_id': 419},
 {'business_id': 'fSCNwMtNNQY9QT69Cj9fiA', 'category_id': 806},
 {'business_id': 'x1mhq4IpWctQOBM06dU8vg', 'category_id': 536},
 {'business_id': 'x1mhq4IpWctQOBM06dU8vg', 'category_id': 533},
 {'business_id': 'x1mhq4IpWctQOBM06dU8vg', 'category_id': 115},
 {'business_id': 'x1mhq4IpWctQOBM06dU8vg', 'category_id': 1291},
 {'business_id': 'x1mhq4IpWctQOBM06dU8vg', 'category_id': 1069},
 {'business_id': 'ljxNT9p0y7YMPx0fcNBGig', 'category_id': 1014},
 {'business_id': 'ljxNT9p0y7YMPx0fcNBGig', 'category_id': 1109},
 {'business_id': 'ljxNT9p0y7YMPx0fcNBGig', 'category_id': 1128},
 {'business_id': 'ljxNT9p0y7YMPx0fcNBGig', 'category_id': 466},
 {'business_id': 'ljxNT9p0y7YMPx0fcNBGig', 'category_id': 647},
 {'business_id': 'ljxNT9p0y7YMPx0fcNBGig', 'category_id': 920},
 {'business_id': 'ljxNT9p0y7YMPx0fcNBGig', 'category_id': 867},
 {'business_id': 'lwItZ1Ck3KtpCgG4CPFmpQ', 'category_id': 319},
 {'business_id': 'lwItZ1Ck3KtpCgG4CPFmpQ', 'category_id': 959},
 {'business_id': 'lwItZ1Ck3KtpCgG4CPFmpQ', 'category_id': 695},
 {'business_id': 'lwItZ1Ck3KtpCgG4CPFmpQ', 'category_id': 305},
 {'business_id': 'Kq51_lGAgAigqmENITTr-A', 'category_id': 551},
 {'business_id': 'Kq51_lGAgAigqmENITTr-A', 'category_id': 115},
 {'business_id': 'Kq51_lGAgAigqmENITTr-A', 'category_id': 689},
 {'business_id': 'Kq51_lGAgAigqmENITTr-A', 'category_id': 359},
 {'business_id': 'Kq51_lGAgAigqmENITTr-A', 'category_id': 535},
 {'business_id': 'Kq51_lGAgAigqmENITTr-A', 'category_id': 247},
 {'business_id': 'Kq51_lGAgAigqmENITTr-A', 'category_id': 1284},
 {'business_id': 'Kq51_lGAgAigqmENITTr-A', 'category_id': 1121},
 {'business_id': 'Kq51_lGAgAigqmENITTr-A', 'category_id': 742},
 {'business_id': 'Kq51_lGAgAigqmENITTr-A', 'category_id': 1086},
 {'business_id': 'mglME3E7esPSpIF5bias8w', 'category_id': 434},
 {'business_id': 'mglME3E7esPSpIF5bias8w', 'category_id': 1069},
 {'business_id': 'mglME3E7esPSpIF5bias8w', 'category_id': 337},
 {'business_id': 'mglME3E7esPSpIF5bias8w', 'category_id': 487},
 {'business_id': 'mglME3E7esPSpIF5bias8w', 'category_id': 198},
 {'business_id': 'mglME3E7esPSpIF5bias8w', 'category_id': 572},
 {'business_id': 'mglME3E7esPSpIF5bias8w', 'category_id': 576},
 {'business_id': 'wghnIlMb_i5U46HMBGx9ig', 'category_id': 1014},
 {'business_id': 'wghnIlMb_i5U46HMBGx9ig', 'category_id': 245},
 {'business_id': 'JX4tUpd09YFchLBuI43lGw', 'category_id': 66},
 {'business_id': 'JX4tUpd09YFchLBuI43lGw', 'category_id': 790},
 {'business_id': 'JX4tUpd09YFchLBuI43lGw', 'category_id': 640},
 {'business_id': 'JX4tUpd09YFchLBuI43lGw', 'category_id': 806},
 {'business_id': 'JX4tUpd09YFchLBuI43lGw', 'category_id': 466},
 {'business_id': 'JX4tUpd09YFchLBuI43lGw', 'category_id': 262},
 {'business_id': 'JX4tUpd09YFchLBuI43lGw', 'category_id': 652},
 {'business_id': 'JX4tUpd09YFchLBuI43lGw', 'category_id': 959},
 {'business_id': 'JX4tUpd09YFchLBuI43lGw', 'category_id': 639},
 {'business_id': 'lk9IwjZXqUMqqOhM774DtQ', 'category_id': 262},
 {'business_id': 'lk9IwjZXqUMqqOhM774DtQ', 'category_id': 1014},
 {'business_id': 'lk9IwjZXqUMqqOhM774DtQ', 'category_id': 1299},
 {'business_id': 'lk9IwjZXqUMqqOhM774DtQ', 'category_id': 104},
 {'business_id': 'lk9IwjZXqUMqqOhM774DtQ', 'category_id': 806},
 {'business_id': 'lk9IwjZXqUMqqOhM774DtQ', 'category_id': 33},
 {'business_id': 'lk9IwjZXqUMqqOhM774DtQ', 'category_id': 419},
 {'business_id': 'lk9IwjZXqUMqqOhM774DtQ', 'category_id': 466},
 {'business_id': 'lk9IwjZXqUMqqOhM774DtQ', 'category_id': 228},
 {'business_id': 'lk9IwjZXqUMqqOhM774DtQ', 'category_id': 165},
 {'business_id': 'lk9IwjZXqUMqqOhM774DtQ', 'category_id': 190},
 {'business_id': 'lk9IwjZXqUMqqOhM774DtQ', 'category_id': 348},
 {'business_id': 'bCBPXIVfVzBZBEpFu29dcg', 'category_id': 1065},
 {'business_id': 'bCBPXIVfVzBZBEpFu29dcg', 'category_id': 712},
 {'business_id': 'ABxoFuzZy5mqQ8C5FJJajQ', 'category_id': 1014},
 {'business_id': 'ABxoFuzZy5mqQ8C5FJJajQ', 'category_id': 647},
 {'business_id': 'Hwt3_mOEmU-t--ywcemnMg', 'category_id': 7},
 {'business_id': 'Hwt3_mOEmU-t--ywcemnMg', 'category_id': 454},
 {'business_id': 'Hwt3_mOEmU-t--ywcemnMg', 'category_id': 1208},
 {'business_id': 'Hwt3_mOEmU-t--ywcemnMg', 'category_id': 531},
 {'business_id': 'Hwt3_mOEmU-t--ywcemnMg', 'category_id': 1308},
 {'business_id': 'REwfwz-_-CMQ7Np5UVi9Qg', 'category_id': 994},
 {'business_id': 'REwfwz-_-CMQ7Np5UVi9Qg', 'category_id': 583},
 {'business_id': 'REwfwz-_-CMQ7Np5UVi9Qg', 'category_id': 993},
 {'business_id': '5BmQX4UVJY19mMtafMg7JA', 'category_id': 1109},
 {'business_id': '5BmQX4UVJY19mMtafMg7JA', 'category_id': 95},
 {'business_id': '5BmQX4UVJY19mMtafMg7JA', 'category_id': 466},
 {'business_id': '5BmQX4UVJY19mMtafMg7JA', 'category_id': 554},
 {'business_id': 'cVBxfMC4lp3DnocjYA3FHQ', 'category_id': 262},
 {'business_id': 'cVBxfMC4lp3DnocjYA3FHQ', 'category_id': 190},
 {'business_id': 'cVBxfMC4lp3DnocjYA3FHQ', 'category_id': 903},
 {'business_id': 'cVBxfMC4lp3DnocjYA3FHQ', 'category_id': 1014},
 {'business_id': 'cVBxfMC4lp3DnocjYA3FHQ', 'category_id': 889},
 {'business_id': 'cVBxfMC4lp3DnocjYA3FHQ', 'category_id': 466},
 {'business_id': '0qNpTGTcqPwOLi2hADx4Xw', 'category_id': 466},
 {'business_id': '0qNpTGTcqPwOLi2hADx4Xw', 'category_id': 521},
 {'business_id': '0qNpTGTcqPwOLi2hADx4Xw', 'category_id': 287},
 {'business_id': 'xM6LoUcnpDpMBzXs_7dXAg', 'category_id': 606},
 {'business_id': 'xM6LoUcnpDpMBzXs_7dXAg', 'category_id': 607},
 {'business_id': 'xM6LoUcnpDpMBzXs_7dXAg', 'category_id': 419},
 {'business_id': 'txyXRytGjwOXvS8s4sc-WA', 'category_id': 1263},
 {'business_id': 'txyXRytGjwOXvS8s4sc-WA', 'category_id': 621},
 {'business_id': 'txyXRytGjwOXvS8s4sc-WA', 'category_id': 466},
 {'business_id': 'txyXRytGjwOXvS8s4sc-WA', 'category_id': 656},
 {'business_id': 'txyXRytGjwOXvS8s4sc-WA', 'category_id': 1069},
 {'business_id': 'DQ7PyYlp2bX96WZa7TcaWQ', 'category_id': 824},
 {'business_id': 'DQ7PyYlp2bX96WZa7TcaWQ', 'category_id': 424},
 {'business_id': 'DQ7PyYlp2bX96WZa7TcaWQ', 'category_id': 551},
 {'business_id': 'DQ7PyYlp2bX96WZa7TcaWQ', 'category_id': 1069},
 {'business_id': 'DQ7PyYlp2bX96WZa7TcaWQ', 'category_id': 359},
 {'business_id': 'DQ7PyYlp2bX96WZa7TcaWQ', 'category_id': 825},
 {'business_id': 'uI9XODGY_2_ieTE6xJ0myw', 'category_id': 1014},
 {'business_id': 'uI9XODGY_2_ieTE6xJ0myw', 'category_id': 32},
 {'business_id': 'uI9XODGY_2_ieTE6xJ0myw', 'category_id': 647},
 {'business_id': 'JgpnXv_0XhV3SfbfB50nxw', 'category_id': 1014},
 {'business_id': 'JgpnXv_0XhV3SfbfB50nxw', 'category_id': 920},
 {'business_id': 'Si6LXSR9gvAbmgO5DzV2cw', 'category_id': 1014},
 {'business_id': 'Si6LXSR9gvAbmgO5DzV2cw', 'category_id': 1102},
 {'business_id': 'Si6LXSR9gvAbmgO5DzV2cw', 'category_id': 1045},
 {'business_id': 'Si6LXSR9gvAbmgO5DzV2cw', 'category_id': 176},
 {'business_id': 'seKihQKpGGnCeLuELRQPSQ', 'category_id': 1118},
 {'business_id': 'seKihQKpGGnCeLuELRQPSQ', 'category_id': 32},
 {'business_id': 'seKihQKpGGnCeLuELRQPSQ', 'category_id': 33},
 {'business_id': 'seKihQKpGGnCeLuELRQPSQ', 'category_id': 806},
 {'business_id': 'seKihQKpGGnCeLuELRQPSQ', 'category_id': 104},
 {'business_id': 'seKihQKpGGnCeLuELRQPSQ', 'category_id': 1014},
 {'business_id': 'L_TT0BFmFwORAMaA83K54A', 'category_id': 494},
 {'business_id': 'L_TT0BFmFwORAMaA83K54A', 'category_id': 261},
 {'business_id': 'L_TT0BFmFwORAMaA83K54A', 'category_id': 118},
 {'business_id': 'L_TT0BFmFwORAMaA83K54A', 'category_id': 104},
 {'business_id': 'L_TT0BFmFwORAMaA83K54A', 'category_id': 1014},
 {'business_id': 'L_TT0BFmFwORAMaA83K54A', 'category_id': 806},
 {'business_id': 'mjWvAkNqoA6Y5P03sDSzfA', 'category_id': 1230},
 {'business_id': 'mjWvAkNqoA6Y5P03sDSzfA', 'category_id': 1069},
 {'business_id': 'qfWJmJ0g96eM_fWma3ja0g', 'category_id': 1045},
 {'business_id': 'qfWJmJ0g96eM_fWma3ja0g', 'category_id': 1014},
 {'business_id': 'qfWJmJ0g96eM_fWma3ja0g', 'category_id': 104},
 {'business_id': 'qfWJmJ0g96eM_fWma3ja0g', 'category_id': 806},
 {'business_id': 'qfWJmJ0g96eM_fWma3ja0g', 'category_id': 261},
 {'business_id': 'qfWJmJ0g96eM_fWma3ja0g', 'category_id': 32},
 {'business_id': 'qfWJmJ0g96eM_fWma3ja0g', 'category_id': 976},
 {'business_id': 'uczmbBk5O3tYhGue13dCDg', 'category_id': 607},
 {'business_id': 'uczmbBk5O3tYhGue13dCDg', 'category_id': 1194},
 {'business_id': 'uczmbBk5O3tYhGue13dCDg', 'category_id': 711},
 {'business_id': 'n7AQvGvNHlmun3kqXeBKVQ', 'category_id': 712},
 {'business_id': 'n7AQvGvNHlmun3kqXeBKVQ', 'category_id': 43},
 {'business_id': 'eYxGFkxo6m3SYGVTh5m2nQ', 'category_id': 1195},

In [21]:
df_business_categories_key = pd.DataFrame(business_categories_data)
df_business_categories_key

                   business_id  category_id
0       Pns2l4eNsfO8kk83dixA6A          359
1       Pns2l4eNsfO8kk83dixA6A         1200
2       Pns2l4eNsfO8kk83dixA6A          798
3       Pns2l4eNsfO8kk83dixA6A            8
4       Pns2l4eNsfO8kk83dixA6A          551
...                        ...          ...
668587  mtGm22y5c2UHNXDFAjaPNw          135
668588  jV_XOycEzSlTx-65W906pg          115
668589  jV_XOycEzSlTx-65W906pg          880
668590  jV_XOycEzSlTx-65W906pg          917
668591  jV_XOycEzSlTx-65W906pg         1165

[668592 rows x 2 columns]

In [22]:
sorted_group_ids = []
for idx, row in df_business_categories_id.iterrows():
    sorted_group_ids.append(int(group_ids[idx]))
sorted_group_ids

[6,
 2,
 11,
 3,
 2,
 6,
 2,
 8,
 9,
 9,
 6,
 5,
 4,
 7,
 7,
 8,
 7,
 2,
 5,
 5,
 10,
 1,
 10,
 8,
 11,
 11,
 11,
 11,
 8,
 9,
 9,
 8,
 5,
 5,
 11,
 9,
 0,
 0,
 0,
 2,
 6,
 11,
 3,
 10,
 6,
 6,
 8,
 5,
 8,
 8,
 6,
 7,
 5,
 5,
 4,
 7,
 7,
 7,
 7,
 2,
 4,
 7,
 1,
 7,
 8,
 2,
 7,
 5,
 11,
 2,
 11,
 1,
 7,
 9,
 5,
 5,
 2,
 10,
 10,
 6,
 6,
 10,
 10,
 6,
 2,
 6,
 6,
 2,
 8,
 9,
 2,
 6,
 8,
 3,
 6,
 3,
 6,
 5,
 6,
 6,
 3,
 3,
 2,
 4,
 3,
 3,
 4,
 8,
 8,
 5,
 1,
 8,
 3,
 11,
 8,
 11,
 3,
 3,
 3,
 11,
 11,
 7,
 4,
 5,
 2,
 1,
 8,
 8,
 11,
 11,
 10,
 10,
 8,
 1,
 7,
 8,
 6,
 11,
 10,
 1,
 3,
 9,
 6,
 8,
 1,
 1,
 10,
 7,
 8,
 8,
 2,
 1,
 2,
 6,
 7,
 1,
 11,
 11,
 2,
 11,
 8,
 8,
 3,
 5,
 8,
 3,
 3,
 3,
 3,
 2,
 5,
 8,
 3,
 11,
 3,
 1,
 3,
 5,
 11,
 11,
 7,
 11,
 6,
 6,
 6,
 3,
 4,
 6,
 7,
 6,
 11,
 3,
 5,
 5,
 2,
 5,
 11,
 5,
 1,
 1,
 11,
 11,
 3,
 7,
 5,
 6,
 6,
 1,
 1,
 6,
 11,
 6,
 10,
 2,
 2,
 4,
 9,
 2,
 4,
 5,
 2,
 7,
 2,
 2,
 2,
 2,
 2,
 7,
 3,
 2,
 4,
 3,
 6,
 8,
 1,
 3,
 3,
 1,
 3,
 6,
 4,
 2,
 2,
 7,
 2,
 5,
 4,
 9,
 1,
 2,
 11,
 3,
 3,
 7,
 4,
 4,
 8,
 10,
 1,
 7,
 8,
 3,
 3,
 3,
 3,
 1,
 4,
 4,
 5,
 3,
 7,
 3,
 2,
 6,
 1,
 10,
 7,
 11,
 11,
 6,
 2,
 1,
 9,
 11,
 6,
 6,
 6,
 1,
 3,
 4,
 4,
 9,
 9,
 1,
 4,
 2,
 4,
 10,
 11,
 7,
 6,
 6,
 6,
 6,
 3,
 6,
 11,
 2,
 5,
 3,
 11,
 3,
 6,
 3,
 1,
 4,
 5,
 1,
 7,
 6,
 4,
 10,
 7,
 4,
 7,
 2,
 8,
 10,
 11,
 11,
 6,
 8,
 2,
 3,
 6,
 9,
 9,
 1,
 6,
 9,
 3,
 9,
 6,
 9,
 1,
 9,
 6,
 2,
 3,
 7,
 6,
 8,
 1,
 3,
 8,
 1,
 8,
 6,
 3,
 9,
 0,
 0,
 5,
 3,
 11,
 5,
 3,
 10,
 3,
 4,
 7,
 3,
 4,
 8,
 1,
 2,
 2,
 10,
 3,
 11,
 6,
 11,
 9,
 5,
 3,
 6,
 4,
 4,
 5,
 6,
 6,
 9,
 1,
 2,
 10,
 4,
 6,
 5,
 2,
 9,
 0,
 11,
 3,
 6,
 6,
 9,
 9,
 2,
 6,
 6,
 8,
 6,
 6,
 9,
 3,
 5,
 5,
 5,
 7,
 7,
 6,
 7,
 2,
 6,
 9,
 1,
 2,
 6,
 3,
 9,
 10,
 1,
 8,
 3,
 2,
 3,
 11,
 8,
 8,
 2,
 7,
 5,
 6,
 6,
 2,
 6,
 6,
 4,
 6,
 11,
 2,
 4,
 3,
 8,
 4,
 8,
 1,
 8,
 8,
 2,
 2,
 2,
 2,
 2,
 8,
 3,
 3,
 3,
 3,
 6,
 3,
 3,
 3,
 9,
 2,
 10,
 2,
 8,
 5,
 3,
 11,
 6,
 2,
 2,
 11,
 10,
 2,
 1,
 5,
 11,
 6,
 11,
 11,
 9,
 3,
 3,
 3,
 2,
 9,
 7,
 6,
 10,
 5,
 5,
 9,
 1,
 2,
 2,
 3,
 8,
 1,
 8,
 1,
 11,
 8,
 1,
 8,
 2,
 5,
 3,
 3,
 3,
 3,
 5,
 11,
 1,
 11,
 2,
 2,
 6,
 8,
 8,
 5,
 2,
 2,
 2,
 2,
 2,
 5,
 5,
 3,
 11,
 9,
 6,
 8,
 1,
 2,
 11,
 5,
 2,
 1,
 9,
 9,
 6,
 6,
 11,
 9,
 6,
 7,
 9,
 1,
 3,
 2,
 8,
 5,
 11,
 7,
 1,
 8,
 11,
 2,
 0,
 11,
 6,
 6,
 2,
 2,
 6,
 6,
 9,
 6,
 10,
 6,
 6,
 7,
 7,
 2,
 11,
 6,
 5,
 3,
 11,
 3,
 8,
 1,
 8,
 8,
 9,
 9,
 9,
 11,
 8,
 3,
 3,
 8,
 11,
 11,
 11,
 2,
 11,
 5,
 1,
 10,
 8,
 3,
 9,
 9,
 6,
 10,
 9,
 5,
 3,
 3,
 5,
 9,
 3,
 5,
 5,
 11,
 11,
 9,
 6,
 10,
 6,
 2,
 6,
 9,
 5,
 1,
 11,
 6,
 4,
 8,
 5,
 11,
 6,
 5,
 5,
 5,
 11,
 5,
 5,
 7,
 8,
 2,
 10,
 3,
 10,
 1,
 7,
 7,
 8,
 3,
 6,
 8,
 4,
 2,
 3,
 3,
 3,
 1,
 8,
 2,
 1,
 5,
 5,
 3,
 11,
 9,
 6,
 5,
 8,
 6,
 11,
 11,
 11,
 4,
 5,
 9,
 2,
 2,
 5,
 2,
 6,
 6,
 6,
 1,
 5,
 6,
 11,
 7,
 6,
 4,
 6,
 2,
 1,
 3,
 2,
 3,
 6,
 1,
 3,
 6,
 11,
 8,
 1,
 3,
 6,
 1,
 7,
 2,
 11,
 11,
 2,
 5,
 3,
 6,
 4,
 11,
 7,
 9,
 4,
 9,
 2,
 2,
 2,
 2,
 1,
 7,
 9,
 9,
 9,
 9,
 9,
 9,
 11,
 5,
 9,
 2,
 2,
 6,
 2,
 5,
 5,
 4,
 9,
 6,
 8,
 10,
 1,
 11,
 10,
 2,
 10,
 2,
 6,
 5,
 3,
 5,
 4,
 5,
 6,
 6,
 6,
 11,
 1,
 8,
 1,
 11,
 10,
 8,
 10,
 8,
 8,
 5,
 11,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 2,
 9,
 6,
 1,
 9,
 9,
 9,
 9,
 9,
 3,
 6,
 5,
 7,
 3,
 6,
 2,
 9,
 11,
 4,
 9,
 7,
 9,
 9,
 2,
 2,
 8,
 11,
 3,
 9,
 7,
 9,
 9,
 9,
 1,
 5,
 9,
 9,
 9,
 9,
 9,
 9,
 1,
 8,
 7,
 6,
 1,
 3,
 6,
 1,
 8,
 9,
 2,
 1,
 2,
 8,
 2,
 5,
 5,
 3,
 8,
 8,
 11,
 4,
 11,
 11,
 11,
 7,
 11,
 11,
 2,
 11,
 1,
 6,
 1,
 6,
 9,
 2,
 1,
 1,
 6,
 9,
 9,
 2,
 7,
 2,
 9,
 2,
 5,
 6,
 6,
 3,
 6,
 1,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 9,
 9,
 11,
 7,
 4,
 1,
 9,
 3,
 7,
 1,
 3,
 8,
 2,
 8,
 5,
 3,
 2,
 7,
 9,
 8,
 8,
 9,
 2,
 9,
 8,
 4,
 6,
 5,
 8,
 6,
 8,
 11,
 3,
 1,
 1,
 6,
 5,
 11,
 3,
 2,
 9,
 4,
 2,
 3,
 9,
 2,
 6,
 6,
 6,
 4,
 4,
 6,
 9,
 2,
 6,
 8,
 3,
 6,
 2,
 9,
 9,
 9,
 2,
 2,
 9,
 6,
 7,
 6,
 6,
 6,
 6,
 11,
 5,
 9,
 2,
 5,
 1,
 11,
 11,
 10,
 8,
 8,
 8,
 7,
 9,
 8,
 3,
 3,
 6,
 6,
 6,
 7,
 6,
 7,
 11,
 ...]

#### Exporting the DataFrames

In [23]:
df_business_categories_id['group_id'] = sorted_group_ids
df_business_categories_id

                 category_name  group_id
category_id
0                   & Probates         6
1                  3D Printing         2
2            ATV Rentals/Tours        11
3                   Acai Bowls         3
4                  Accessories         2
...                        ...       ...
1306                     Wraps         2
1307               Yelp Events         7
1308                      Yoga         8
1309                 Ziplining         2
1310                      Zoos         0

[1311 rows x 2 columns]

In [24]:
lib.export_data(EXPORT_DIRECTORY / 'yelp_business_groups_id.csv', df_business_groups_id)
lib.export_data(EXPORT_DIRECTORY / 'yelp_business_categories_id.csv', df_business_categories_id)
lib.export_data(EXPORT_DIRECTORY / 'yelp_business_categories_key.csv', df_business_categories_key)

PortfolioLogger.lib.tools: INFO: Exporting 12 elements (0.00 MB) to /Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/clean/yelp_business_groups_id_CLEAN.csv
PortfolioLogger.lib.performance: INFO: <function export_data at 0x10f9a1940> took 0.003 secs to complete.
PortfolioLogger.lib.tools: INFO: Exporting 2622 elements (0.13 MB) to /Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/clean/yelp_business_categories_id_CLEAN.csv
PortfolioLogger.lib.performance: INFO: <function export_data at 0x10f9a1940> took 0.002 secs to complete.
PortfolioLogger.lib.tools: INFO: Exporting 1337184 elements (50.37 MB) to /Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/clean/yelp_business_categories_key_CLEAN.csv
PortfolioLogger.lib.performance: INFO: <function export_data at 0x10f9a1940> took 0.364 secs to complete.

PosixPath('/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/clean/yelp_business_categories_key_CLEAN.csv')

### Creating backup

In [25]:
df_business_cp3 = df_business_cp2.copy()

### Cleaning Hours columns
Going to create a new DataFrame for these columns

In [26]:
df_business_cp3['hours.Sunday']

0               NaN
1               NaN
2          8:0-22:0
3          7:0-21:0
4         12:0-18:0
            ...
150341    11:0-17:0
150342     0:0-16:0
150343          NaN
150344    10:0-17:0
150345          NaN
Name: hours.Sunday, Length: 150346, dtype: object

In [27]:
def convert_unit(u):
    timestamp = [int(item) for item in u.split(':')]
    t = datetime.time(*timestamp)
    return t.strftime('%H:%M:%S')

def convert_time(t):
    start, end = t.split('-')
    start = convert_unit(start)
    end = convert_unit(end)
    return start, end

Creating DataFrame

In [28]:
days = {
    'Sunday': 0,
    'Monday': 1,
    'Tuesday': 2,
    'Wednesday': 3,
    'Thursday': 4,
    'Friday': 5,
    'Saturday': 6
}
days_mapping = {
    'days_id': [0,1,2,3,4,5,6],
    'day_of_week': ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
}
days

{'Sunday': 0,
 'Monday': 1,
 'Tuesday': 2,
 'Wednesday': 3,
 'Thursday': 4,
 'Friday': 5,
 'Saturday': 6}

In [29]:
hours_data = {
    'business_id': [],
    'day_of_week': [],
    'open_time': [],
    'close_time': [],
    'is_closed': []
}
to_drop =set()

for col, series in df_business_cp3.items():
    if col.startswith('hours.'):
        to_drop.add(col)
        day = col.replace('hours.', '')
        print(day)
        for idx, item in series.items():
            business_id = df_business_cp3.loc[idx, 'business_id']
            hours_data['business_id'].append(business_id)
            hours_data['day_of_week'].append(days[day])
            try:
                if np.isnan(item) or pd.isna(item):
                    hours_data['open_time'].append(pd.NA)
                    hours_data['close_time'].append(pd.NA)
                    hours_data['is_closed'].append(True)
            except TypeError:
                try:
                    open_time, close_time = convert_time(item)
                    hours_data['open_time'].append(open_time)
                    hours_data['close_time'].append(close_time)
                    hours_data['is_closed'].append(False)
                except:
                    log.error(f'Error in parsing {idx}: ({business_id})')

hours_data

Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday

{'business_id': ['Pns2l4eNsfO8kk83dixA6A',
  'mpf3x-BjTdTEA3yCZrAYPw',
  'tUFrWirKiKi_TAnsVWINQQ',
  'MTSW4McQd7CbVtyjqoe9mw',
  'mWMc6_wTdE0EUBKIGXDVfA',
  'CF33F8-E6oudUQ46HnavjQ',
  'n_0UpQx1hsNbnPUSlodU8w',
  'qkRM_2X51Yqxk3btlwAQIg',
  'k0hlBqXX-Bt0vf1op7Jr1w',
  'bBDDEgkFA1Otx9Lfe7BZUQ',
  'UJsufbvfyfONHeWdvAHKjA',
  'eEOYSgkmpB90uNA7lDOMRA',
  'il_Ro8jwPlHresjw9EGmBg',
  'jaxMSoInw8Poo3XeMJt8lQ',
  '0bPLkL0QhhPO5kt1_EXmNQ',
  'MUTTqe8uqyMdBl186RmNeA',
  'rBmpy_Y1UbBx8ggHlyb7hA',
  'M0XSSHqrASOnhgbWDJIpQA',
  '8wGISYjYkE2tSqn3cDMu8A',
  'ROeacJQwBeh05Rqg7F6TCg',
  'WKMJwqnfZKsAae75RMP6jA',
  'qhDdDeI3K4jy2KyzwFN53w',
  'kfNv-JZpuN6TVNSO6hHdkw',
  '9OG5YkX1g2GReZM0AskizA',
  '4iRzR7OaS-QaSXuvYxEGKA',
  'PSo_C1Sfa13JHjzVNW6ziQ',
  'noByYNtDLQAra9ccqxdfDw',
  'tMkwHmWFUEXrC9ZduonpTg',
  'QdN72BWoyFypdGJhhI5r7g',
  'sqSqqLy0sN8n2IZrAbzidQ',
  'fvWn8oXXwbj2l79cochZyw',
  'Mjboz24M9NlBeiOJKLEd_Q',
  '8sshLb4UU7emeUDvtJWnpA',
  'kV_Q1oqis8Qli8dUoGpTyQ',
  'w_AMNoI1iG9eay7ncmc67w',
  'aPNXGTDkf-4bjhyMBQxqpQ',
  '2xVsWBNFwZOxIOdd9Mwnww',
  'mGFsPRHdE6SMV1gYQ6GzgQ',
  'LcAozWCMLGjwRbokaJAKMg',
  'fSCNwMtNNQY9QT69Cj9fiA',
  'x1mhq4IpWctQOBM06dU8vg',
  'ljxNT9p0y7YMPx0fcNBGig',
  'lwItZ1Ck3KtpCgG4CPFmpQ',
  'Kq51_lGAgAigqmENITTr-A',
  'mglME3E7esPSpIF5bias8w',
  'wghnIlMb_i5U46HMBGx9ig',
  'JX4tUpd09YFchLBuI43lGw',
  'lk9IwjZXqUMqqOhM774DtQ',
  'bCBPXIVfVzBZBEpFu29dcg',
  'ABxoFuzZy5mqQ8C5FJJajQ',
  'Hwt3_mOEmU-t--ywcemnMg',
  'REwfwz-_-CMQ7Np5UVi9Qg',
  '5BmQX4UVJY19mMtafMg7JA',
  'cVBxfMC4lp3DnocjYA3FHQ',
  '0qNpTGTcqPwOLi2hADx4Xw',
  'xM6LoUcnpDpMBzXs_7dXAg',
  'txyXRytGjwOXvS8s4sc-WA',
  'DQ7PyYlp2bX96WZa7TcaWQ',
  'uI9XODGY_2_ieTE6xJ0myw',
  'JgpnXv_0XhV3SfbfB50nxw',
  'Si6LXSR9gvAbmgO5DzV2cw',
  'seKihQKpGGnCeLuELRQPSQ',
  'L_TT0BFmFwORAMaA83K54A',
  'mjWvAkNqoA6Y5P03sDSzfA',
  'qfWJmJ0g96eM_fWma3ja0g',
  'uczmbBk5O3tYhGue13dCDg',
  'n7AQvGvNHlmun3kqXeBKVQ',
  'eYxGFkxo6m3SYGVTh5m2nQ',
  'lOP3HxdUTaq0eXhwR_KC-w',
  'KWA2qtdwVEkMpd5soSKaGA',
  'gbN4RuUiiBxQ2GBFQ2p3Cw',
  'B2qqjCl_BNNnXvWWfpFiLA',
  '7PDi_iyik3jraDAzWwwR4Q',
  '8rb-3VYXE37IZix4yOdskw',
  '9Rww8yE6Dm4dSMEq09nwXg',
  'aCDY7vXYMs54EbYuQScsnQ',
  '-4dYswJy7SPcbcERvitmIg',
  'mFTaYsRDyeFaY2NDLfSaAA',
  'x9K0RfZaT_zlw6DklBDzjw',
  'pJfh3Ct8iL58NZa8ta-a5w',
  'cvP_vh_bOLbCY3eoY1Xw-A',
  '7clCBgNbd-x2Wj96lZ6Mjw',
  'ppFCk9aQkM338Rgwpl2F5A',
  'NZ_bFJma7brQUfln5h1UAg',
  'eMjnw_7wp-CscyNh6Lu0ZA',
  'IDtLPgUrqorrpqSLdfMhZQ',
  'sE6jSnvMts_MAn-b4OkMAw',
  'YNjyv0gfOr2g8lbmUpTnKg',
  'LhpPSrulqVeTyJeK2xydvQ',
  'oaboaRBUgGjbo2kfUIKDLQ',
  '-ZXYcCyDjj1QimnJyGtYtg',
  'nUqrF-h9S7myCcvNDecOvw',
  'vR9_bhoszcpXbB_APv6Xlw',
  'RK6-cJ9hj53RzOlCBmpT-g',
  'ZM46RDLXaFNo_z6t-j_L4w',
  'pEm4xNCk8d0TF6A1gi-WDQ',
  'J_ksUDPpzPwfTGtI4zTRnQ',
  'knQ4vIgx-r85kjlWVVjcpQ',
  'U2Tzy6J9aAAg9pzXsgdkvg',
  '1MeIwdbTnZOBFCKOrgaxuw',
  '8KMIT0NXu30Jz5Ojo5uxaw',
  'jiLGdnf42eYftkqfU2ze1w',
  'EuRGgOwJ0g1vTj2R04j37Q',
  'TLZ3-eDPLhUzfsWO4ad6Ug',
  'Dy91wdWkwtI_qgjAIZ0Niw',
  '2Bi3ef7c0CrLxHD_-yy_tw',
  'vje0KIiE7vtpx7JzmBx5LQ',
  '2n9HHBxG7yAyAUwXXa49aw',
  'kK2i5Xyd9SOpF5pCFilbcg',
  'I6DCYks9lqZeoZiVzW7PmA',
  'VrGxoSNZfSiT-G4OqRRGIw',
  'H0NEOp4e3Zu598u6kO3y0g',
  'sB45WFgysT617bKWP_WJwA',
  'Fk1xpM7fjqEJ4paqk5ZFSg',
  '4dVrWc4Nhuw9apfk9BWEcA',
  'xfmkEGiIERBaBMLhw-dTCg',
  'NTf_U8kYu9PAE2cZGJqtJg',
  'kk_oEw1j3xQ-cJaAII8A0Q',
  'RXpADfOCZBGi82-CGxYdsw',
  'qFX8IdomeBVhDPCSyz2aRg',
  'bYjnX_J1bHZob10DoSFkqQ',
  'luGY5CJlb4CJ3LrBcSXMPA',
  'VZzivJEbmHItOxNXJB3SpA',
  'iPSPcprSnkLOuL1Ns8UZZA',
  'Q3kQYhkYxSRyYyeBgtk--A',
  'wEfK2HIYNzkA1QYfUjHBaw',
  'anLQj9AM8vjbcLSIE0iUgg',
  'BVo_36t3z7vfXp3XGgJkOg',
  'P8brGDYVWjeW9GrKixH0yQ',
  'Cdytv_YhJO0W0Ab8t2xLtg',
  '3BJxm-HnvzdwD1zjmSbmyQ',
  'FRYkg_JvsWU9xIXZsEZcVA',
  '9C2rpb56aQvW0ViZHK9sPw',
  'k0yyD71s2F2eEKWRdkZ6jA',
  'dM5OKNzk9AL2aiq-fV-SYg',
  'qdYfHRsZdcz4Bun4f9Ijaw',
  'Y6t4pnKm5LF8y5ChHA27ow',
  'E_kLUlU60fzoZYAOxbH_3w',
  'txiXR1YfMyk-5S4ZzOVIhQ',
  '0vCsslN-TYnDeOSNT4rIfg',
  'zFvqulgAYOpSG2t1v8AZ-w',
  'SZU9c8V2GuREDN5KgyHFJw',
  'GWGXTKR0Fhdvzf_isDqJug',
  '-aeZuatjCDMV1X4gCTz9Ug',
  'PYW8Buz8S8LpjIe6mZTAcw',
  'Lx8ZYUJ_-3Aa8N821mN1WQ',
  'M_THnNDHs29aylcK-JqS1A',
  'uCQqtYW_xc1EJRm7NyakdA',
  '9LLxOjEhLNcdx8i4lL6EUQ',
  'h-y5azB-VlQAT3m7Ff2g2Q',
  'XHTgtBSwLnwRHzKSbea2Fg',
  'WYYdQDjx-DsCanlP0DpImQ',
  'U2htB9qk4hOXCdkccvvW0Q',
  'aNtKyc2rr-uK5cqzY9TVQQ',
  'yv6kSKxDdZTsvHL25K-U2g',
  'hUQ9Z7kQeabvhPOAQOVV1A',
  't5tBd4p7BA7hNDitBUXxrw',
  'oCFcoyGx2VRZ8MHXEsV8tQ',
  'FC6ef4rMMZKNov_-A9M6iQ',
  'X_E7U2lVNEwbH_gpOBmAHQ',
  'EYA514FX4H8MwvFjv2ORQA',
  'G4lRmwDHdvhZAhmtlsYYBw',
  'DTUfAthScapCGnOnnLUhPA',
  'DcUDIlxFsvqPvFh8_lb4Sw',
  'zs4d4DqSp5zh3HGFh-PiiQ',
  'BxhkoR6cscJwwex8gx31OA',
  '2oxrOO3c9_mQmqM9kwEm9Q',
  'Ms5xG8i4p80KSMcF3tt4ug',
  'yswijv6wP2fKbMqAiEZ0vw',
  'm9ncuZp0nEVhIwu24G-HRw',
  'QZU7TcrztBb3tXaPbVCkXg',
  'l6VYP8AxIoW6U52aDo8fXg',
  'wMAxTyExktVtfyqKAfApbA',
  'E-nhxuu3zbt02oCj_1AFng',
  'vvE3HVfxlx9UYctKPr0dbw',
  'JnbSkfsl_j2dUoHncBTonA',
  '5BYQP7i7ckUlgSzX4Yhnmw',
  'xAAhPuZ8FG6OlvAw5m1BVQ',
  'DfGNZQsCe9k2BxazCf0p6g',
  '07JLsUInZr5OSiYH2XVi4g',
  'hPAmGKnDqummngSTOJN_8g',
  'ORL4JE6tz3rJxVqkdKfegA',
  '1GnJDrpp-jyDRCptavD9RQ',
  'jkY8aotwcAlSHCgoZrF49w',
  'YD_eZ4TaFrHYRrJVzOXHfw',
  'P10BsKUeoeCeVoK4BS2u0w',
  '7Du9oW73YcYFmXdtU5aiSg',
  'h_qlv6CIXGVurFOhFQ945w',
  'QjV4v7q_pt7tt3K1US7IHg',
  'LGqiubTmpJ-A1L5n7dmc6g',
  'FTFtoylMzkrzqNVSl-bkKw',
  '59jkCUm4yHciKL1KW_1HJA',
  'AzwiKZjVqHOxLaYtPAx8lA',
  'yM8LlTInbQH4FwWC97lz6w',
  'tVdJ7CgBGAQ_nLomYXbB-Q',
  'x8KYhsxbufQiYIK-4MRzHQ',
  '3S9GYtMOYhbZl4MMPOHT0Q',
  'znL4YrNbA2uwOQ3CchkmEA',
  'CtMEJxpVMlNzFpB4PtFjfA',
  'O1oZpbZNDMH_gz8DhsZCdA',
  'vPcfJ3rm3NpdqVDod2WxLA',
  'HI4_NqeHMJOnMoVFNxaFyA',
  'pmuuoDqNZp7518AUd-YmPA',
  'EDNYAyVc_WFhM3CD6QVD4A',
  'tyJwgMRwo21wLUsga_RkQw',
  '2dlQX5sP9X6Dlm1MmNOlSw',
  'IYlUaKC9nICjiWdk-ShPlg',
  '8oi1Gm7XLyK31Y3N3Wp2Ig',
  'hdRtVNk-G9Ep4eaHPKXmfA',
  'tSFXJ0GFl5iUdy021YgWLw',
  'UoKkgWmE9-c3wbWwO4VAVQ',
  'Nh1rc9aSeO-Y5lYmXVS6CA',
  'r_8FZXRkGoc5QNbTOAIftA',
  'ZU6NodDOWaabGkeNpOWdXw',
  'LVYAXWQB3t7tdwWteyjfhw',
  'mq5Z9X7yxgyApILQ11niNw',
  'X0V_PdBTS_SwNxMY2795ZA',
  'ONUZertKOOImiyQG66Z7Tg',
  'ULReFPrCIDRbGKwP3ZsHwg',
  '25Uww0C0wvF9CZ_3B6vWtA',
  'rCoWa-C7Os51GjFkCnFlVw',
  'Dtuf4vD0znzwJW9vk3iTNw',
  '8c0r7olQSYGcws0bTd3ikw',
  'QU-X2Pijwd4SitfYXoZWMQ',
  'Ucl9Vo5lwrUmYbV8Dv8X5g',
  'cSeA6pC9JUlGfz-RNfvnGw',
  'WdrpkH-q7FQY5nclmPfoDQ',
  'xF9r1XbMvEOsJeHlmFhIvw',
  '6BF3eaIzHtoNHSxKTFnTyg',
  'wjyUxHxkrvUvCOVqy4g_wg',
  'do6EpBc7ZUoaqdzuUuGFXA',
  '4IcB3QyMEA85UTWFKh9O9A',
  '_mf0QKI1Jlk8zRinr-56FA',
  'h_3oLlQ_CFohwlzsrSZ6xQ',
  'Y6heWJJ9AmEL58fZwgi9YQ',
  'bTve2mwLk5Zc01vRKqc2KQ',
  '7FHjj04Wy2aqXl22NA_C0g',
  'TF6QZYUR5atqBEFnHP5bOw',
  'WveinioyAZg3dtt0zHsyHA',
  'D9Xez9uOSM4DgSjSTywq7w',
  '6czqMScx8MRDirv7fxX7pw',
  'bi3SICnYEuFC7Cihyqz8Nw',
  'xbRbvXSAVZBEwaUUn3mzbg',
  'qb5pyP6XOS8K2uuC4eQHmQ',
  'CWE-NfyMgi28ePUiansSdQ',
  'uDQgmudYDKiB6n4vwbEeDg',
  'MyE_zdul_JO-dOHOug4GQQ',
  'v5kwdvmg-J8g-ll0nkc3Sw',
  '8p9euqoMCbT4AIL_Fgqb0g',
  'bqmX882_6AxVA_uHEQ70sQ',
  'my0bmPD5dgDFE1ia__LNlw',
  '8ThWgxiTB83nrIGbZQnNBg',
  'TzrA1TsKMKbrZBkw3q6DEQ',
  'Edg22x3CZkIv0GUib2oEFA',
  'VVvUBlc_WIEb8obKGq39dA',
  'FR5xx5YEzxAnoMdqGl7vRQ',
  'py5aKmlTB2NarfsfcOpHOQ',
  'jL_NufxqXi-BpW5uXKsPwQ',
  'wZhGuW7vQpfhxeEvLHkTrA',
  'vjLSYNGFkPu4Y5HKoJlzYg',
  'pIUQz-zGw-Nu_Pu-qoTGuw',
  'I3ZLcrGzj-QN5vFgaJFrAg',
  'Tm3QiAVLJAR2fEJK7APPPQ',
  'rJXa375PYt906DwptOOP3Q',
  'YR0nwxBOKk6DiLHNItfsBQ',
  'X4loIesbBkiTZLFstHv8Kw',
  'n8ecak12IF_jhnPNs37AZA',
  'jnyHs1ZXy9qIE2gORZBQMg',
  'xloFoRiYlH4IKGz3FhTDpA',
  's_lHc_CrkzOTY3k4VNtN8w',
  'zzUxvYE-8Fj_dWqsPcagNg',
  'jcL_qaGJiappzpnn-ifSoA',
  'rYOrSXy2I4BcxB7dhg29uA',
  's-A1_pxGRYL2x4gONVzvFA',
  '_T0cPZE2ZJOTTlYYKMP64Q',
  'dJfkfBbJz7wi0RgW-ph_Eg',
  'VbItL6RDULtnw4YvB6EhVg',
  'OIsLivxtTTqH7i1QISoUOQ',
  'W57cR9a7XP6RX56MSWHJJA',
  '35dqrE4z9qWCtCn749oorg',
  'gYMOrd8xnZF-B61lwGiFUw',
  '6bFx8j2KqPfmT0XEUS1RMg',
  'x7_p5O3ChQa7shdHCcLHZQ',
  'G2Byuh4EVeSnqqWBWtD7rg',
  'JF7iyI3wA_AKi_iXOKi0Qw',
  'vSE6lkp5FBcttPxEbQ9XCw',
  'iolaqx0v6g-fymksGWIU9A',
  'G89OuZ3sIEfOR5cXeDqNaA',
  'usv5G5cO314pPHRTGq2Eyw',
  'gRHd5bRosRWQBckzPawf-w',
  'xa6JYHDgVza7CuenKBJBHw',
  '1dSKEitDDgIkaApe6UNMSA',
  'rZw9O5lJ36m_mXeRKE4G9A',
  'dCITjr2RMTmrX33_eFaMKA',
  'CLEWowfkj-wKYJlQDqT1aw',
  'YG0OOMLP3MWYPKHpkA_mew',
  'Pr_Mlt9FqdcW7WCFGJmozA',
  '-7GDqSUaXrpC8Ql7nDBxWA',
  '6I_DA3uqOox50rBvjrQ_-g',
  'zn-WXkqHag5FSVc_LC9dEQ',
  'IYJOfQ6eFVHKCfJck59YIw',
  'e8pMCk4bE0U4qk7z59Lxkg',
  'qps-oF95uqPoV7fiXn-dpg',
  'Q2sKrIaEZsFN7VNjkibyfQ',
  'IAj1Lw3FAOY-yZn4IO7ElQ',
  'en_F2VgZPW1RCnWkPyCrhg',
  'cEqDvn5VuX8nQ_vqs6_xog',
  'aNLr1j_3CZ46rqiUeLaQ-A',
  'tuyCmcmm5Q-bc-9zV76xKA',
  '96qKAK06EdkG6GPVxKDdTw',
  'yZP6Z8sbDpkeXyjNMDiyDg',
  'kR4tXc1fLeR2QNu8cMZrEg',
  'V-96iACFgPmVjjKACGxd7Q',
  'p184f-Zvf4ToPwLba0VS4A',
  'WcSpc5mcfa7NUZ9GQgx0Tg',
  'zVlhs7BVaouutt-rles-YA',
  '1E9o1SNo7UTf1XHTFPv1_Q',
  '0CEUpFtaKhxbmrbSdP9MUQ',
  'CPor0p2hvvHJJN4L0U_zEg',
  'f82dhKNiUXsDVPMLqKYiIQ',
  'FF45pKN_lzqG8Bqk-_HQvw',
  'GrzCVNDTRODqNez4zb4RLw',
  'DeN5N6B78gysROm_Sq2kWA',
  'scychO44eMoosS9iEBV7xw',
  'IOZrqUQ2Jg6UeQ5CWpsmkg',
  'TEP-73fGvgSUmtQFaOTA_g',
  '28FfSlW07o8GTwOrbfNMHA',
  'Ir5Ts-NC7DDTL3XLizhV3g',
  'nSyOBxBRMugT3sKeT4YWBg',
  'I0gSLthWBsiUPzBft_CZ9Q',
  'NBgbL_KQTRRLQPQQtmUkYQ',
  'dhz3m3xUFy6-BrU9xTfkow',
  'bDAlJYMIzwOewIThe2IZjQ',
  'b7YJrFZWZdI2C5-9nZvVdw',
  '6WBHCXHfLAG26n0ALAkoPA',
  'xvFV3ENVa_9POy_grBs03Q',
  '2FR-xWttfR8qaODqcuExvw',
  'SGigkw0zqh4TTXferq3XGA',
  'x9xBKymj6CJ2WuCCFInb7g',
  'SRexiuEsx1d9-dZVUsssQA',
  'xJyp6RLqNRv3tSu6njPKxQ',
  'bwL2TymVrYekkkKztKyiwA',
  '-VBhLd8DAz2VyDF3YBMH4g',
  '1P_mGUY1PyPq7_ZabrzpBw',
  'mHDBZmEH0Er3184YS83_LQ',
  'XwoXi0M66RU6Gouq-DSDHw',
  '1vmx7_L210UBbOWLzrhepQ',
  'ZiJfb924ewMO9S2f-9W9Pw',
  'OfW-VK04qr7b7bPm5QbyLg',
  'dP_1jbKl47-9Ty83RyeJDA',
  'Qa1YQzo00sm9O0JUlwdCQw',
  '0DbIUh_Xuj6H5B_SF0RLCQ',
  'bSJczuohHVko33UT82hnfA',
  '7hSJSIBUP1UQncD4xWPDqg',
  'cSigjSbOfHR_mHGTCmJTaQ',
  'PCM-vL-vRLJ4HB2OE8Nnbg',
  'yooufdsf3eAVq_9RQNSDJA',
  '8YJtf5v76SIz-4udyF4YmA',
  'rmHgqdVkLsGN2byesWRo0w',
  '6zBCuzJwov08YisHZkfU2Q',
  'JfGfqCnk0-Tnf6PlahPUJQ',
  'aNXw3PkXVt8ANwLyCfcmpg',
  'gbetDRjllP5cOxaWxFjGHA',
  'RI8tdJy90bfApk836eF-ag',
  'vweEeZwiaRRWX2Cu9Iq66Q',
  'GVqXNt0HKJLpciN9ePxnWw',
  'KUx_q3nzqUINYgUTrZc9OA',
  'j-PaHu9iyJBlzKJZYN2smA',
  'Ot4bRWWO681vXZIgnLfjEA',
  'OURGUNuoVqPGxZTZsxZQ8w',
  'VeqkfRUzZAKlQer3npXPdQ',
  'JwBTq6IOFH97b9Hr6RT7pw',
  'dChRGpit9fM_kZK5pafNyA',
  'uyc-S7lauYjzouYQ2TM76A',
  'gRw-rxLFeNzyqa6hKPXD1w',
  'FJDvhCGIwKuohPOK7JfLuA',
  '2_gRg3_oWK3GoiB-OpcDHA',
  '7qDAeIsMVj1McNktlICETw',
  'YE2TePip0TxcdquF5hGauQ',
  'nIn0fMn-SEjLdJ44SG4CKw',
  '-Ijm5ICZUZffTo3iumczrw',
  'KdkMXzeoqpfNsZd-_axoTQ',
  '0Xsmy6HtVVBlCbbMjRyzcg',
  'iBRXLFWD7PeSYDbKsd_JTw',
  '3tX0CduxNIHgrxr6Toairw',
  'vFJIK-z3QWs-3XNjs1hcZQ',
  'od6skmfXz9twktEAuJHEmw',
  'sUQ-OfJYSNfz-cimEjoaXQ',
  '5gLjr0BZzm6EY07bp7_LSA',
  'cDekcTE1qwpz8ROlYixhqg',
  '5lcumCB7X0nH5PElagz1VA',
  'j9Kaj_6tSeXmVMYCgZithg',
  'EIlFs8kybcG-l60GJjNUIA',
  'SzHAnqwOuOmw0qh1d6ZAcQ',
  'z9wCTHYI2VZy9YIblwSsgg',
  'cl5NjtALgaX7E-WL2DtiYQ',
  'csJKpjAqZu42-pPhFLfPLw',
  'HsibLfc2XD7Gh7Hbd1WfJQ',
  '_7ks3u-qZsOTKBrXKcA1Ow',
  'nnHHPz4SKmDGxod16WxDxQ',
  '8t6mbhBNAT027aeDQ4mR3A',
  '4xhGQGdGqU60BIznBjqnuA',
  'gVh26yEPkXSoWbhs1p2kNA',
  'juVJO2kMrHwCYXwQQmv1Tg',
  'pYC5fKcpj8GKjSAc7Sl3RQ',
  'IFDNP-n9bBN1egOsGADYYg',
  'Rad7bl6MFOEemh41CdREMQ',
  'f55CXbSB-F8AZXNumZZlcA',
  'Rz0KfP7YAZV_yQE8uIB0fg',
  'QWqKTWQ2OiDgo3dzNkpung',
  'FAWhZ5nasogf2oG_9h7yjg',
  'HPpKVvBT-2EeWNdy9cIjqA',
  'JgORpZ2kB8DG2MECu7jvkQ',
  'CsjKkpApaYJDd5woO9sP4w',
  'gTwgRz52imtyggXCrH2Xng',
  'Wt1W6qwCvna1KzIuJRJbwA',
  'KNfqu3kNwn6eDMJjP0cNcg',
  'TO5-F6Rgt-_sYvRT9Cta-w',
  'L2TIgbnlsqRtqDU3FuW7lw',
  'REuCtUZ2MeehpDipAKBSmQ',
  'eJ77e9lGxY3ArzaoDbHhYw',
  '2M4pYfuivdluXyBOP7IDQw',
  'fNssGWMjae-SUzyyGblspQ',
  'c16lBET8GKbGZY6Aegm_2Q',
  'QU6xxKwHXR6xQ5oi2yIKLw',
  'Vk3Up8OlB8h2ygVlvm8tBQ',
  'TGr9-KKNk_o7HzqvtlKomQ',
  'kwQzVF5GP8DzdyBavvhIaQ',
  '9X1_a2DQwBtXza-U1CfA1g',
  '0Up4mOWP588Leb_dqoDiYQ',
  'wFXwmrlV8TiBS4Ac2-W_9g',
  'ifjluUv4VASwmFqEp8cWlQ',
  'bNJSy64VXxQ3RZ8tNpM-fA',
  '9RoAU2wAlH63Non9qrx3xQ',
  'MlEhwiOJpKe7VuO-IDCZqg',
  'bPPy7yNFfb-6N_bHkn1qAw',
  'i_cFU5_dQexbjJA9rmf_WA',
  'tUl_Lq8dM3T-NnM-u3szSg',
  'bTC3m_GPWBp92Y5TTReyTA',
  'Z3EIfrkSmOmE4hnc1BRo5w',
  'wQjhFPMKwN_z85aPEn6V4Q',
  '516L9-ZWyqVgzqjP5uW7Jg',
  'KDcHC6Es_jv4tloj0NP6gA',
  '7mpYTDb24SywNMRn3yeakQ',
  '_WRe3ql2DI_h3htr77Siew',
  'NpglDX_FUp3ybEzbBp4qhw',
  'iEC0VzHM2hQ13wM7c0QwgQ',
  '34YgAnnZAPOeu8E-6IESJQ',
  'dK_qONtd5z73i6fQ1BTrTA',
  '_raU4FUxWzx30V6DCDSKiA',
  'OlD8UoHqrKnLoZUFxuas_w',
  'C43IEVBroD_3YiumPPLLdQ',
  'xDEee0p41GueCDN0EAp-YA',
  'eq4xYdVExp3jLYAZ71uvPA',
  'LFPJXiuM357JZ-d0vv6yxw',
  'NIV7uxsE8rn8cB1t-FsJHg',
  'qsCLpTsXayYMJ3-lJj_fyA',
  'D7z_V6E8cxXghSRcHAmUPg',
  'u4cktT_mzitYexUsr_vKsw',
  'uW2oyOCEN3RgS7j2MfUIkg',
  'gb7JjRJtzWDsIWpJihZhBQ',
  'JPm93BlP-UHYPqFgK66JUw',
  'c9xE6CyePzE1gONFxpTJWw',
  'Xj0SIY3dprQ4ZZ0lz8YmGw',
  '-DXNvQLhKwunHzg8OjkwXA',
  '9kCutyCm1b8UuCRJF3Hw5A',
  'oy-n3wkXeK6NPPKf3uRDTQ',
  'YZuoaOzD49ffP10PNf72nA',
  '0WIlsDUUFuUKcDfJPaHRkA',
  'LdQUIP4_DPnJjq-Jf2_iNg',
  'VeFfrEZ4iWaecrQg6Eq4cg',
  '5LbiHS5xbeKUxd9ulIJz4w',
  '5iuo1kvv0XZMS0bUOoLz2Q',
  'wwHswDU1t8T-8DAuKI3WdQ',
  'Dl1alpHSJE4_iB0MGKRLXw',
  'hsyIDX4x4ndYEvPoJF6_1g',
  'dk9zGFRJD2RXkHqAmFHOOA',
  'GMVVFox3a0ROMdofd68mZw',
  'fCRGXD-TTLgNhaC4mVFFJQ',
  'rR30b1XWbxZFFgLyGbfNAw',
  'g736EKijhJTrQbqoQAo9Tw',
  '4QFqi8w3rlZTcc5LXKyPJw',
  'XTWGzxXdQN0DVVH2GPGwiA',
  'VKwPAl11iuM_YkEwm07sYQ',
  'iONfxRWQqA8pAPMZFNLaug',
  '0HpYaBbRqaG1df4JckJoUw',
  'Cyy0zZz5ixYjSX4o4sacpg',
  'p79UR4tdHoJzmhwKmiXa2A',
  'qTjsoi0FCv93wxzl0puQSQ',
  'jfz_-ngCCAbKUziluLAgiw',
  'Q9nC1l2V5wDyJpVb50OyLg',
  'wRBEBZ6TvMTuwosvBa72xQ',
  'hE1ouPLiGQiAkiOacnZVLw',
  'lJfxS6RMzAQ7oy8F2vU3Pg',
  'unkPNwxOxNQS5a5kPftLRA',
  'rrdSkNz4YG6eDgOq3ov0IQ',
  'RsTF2skxLcp6qo9FdnA5PA',
  'WZpCnvSQ-YGukju9r4Gd_A',
  'PXI7kvSV-NvWcqbI9jlmtg',
  'oBqjxbnNKILyCN1S8KKd_g',
  'qKcEyi0idj7cTQYzbhuKkg',
  'uYBx50Yl_Jc-UYwFzudBsQ',
  'bchZXVE4feVx4Q5rhIRCGg',
  'ith4RsN3YwQeE3WWQ3Af4w',
  '0Ze7pcwjyauf6steWfpV7g',
  '6MuGlWEZzKA2YtlY44Cksw',
  'GpFRwCHN0RI8yFbcfXjfUg',
  'cvrIE1rLPWk-Nxb_ZNv5lA',
  'MDP8K2NzEnCibFHa9XujWw',
  'QZLOM3T6xl7y1Q6zqoqHWg',
  'RZpEMG2ILk4bL3lH3ygRcw',
  'sXZGhglxCV7bO7mXe63A8Q',
  'PENtXTN19SYMMmFYYbA_Gw',
  'NNcqCDV6PHhDmKY8fO6S9g',
  '9qxMhGWjGsuPUoQB3Y74Wg',
  'AgbRp5NLsP1-J1fdg6Hdcw',
  'U8N-E8P9UOL_g0VxMCF3Mg',
  'EcP5_cCKZqtRv_HJiALMtA',
  'pJB63RaQpkTIKBhfTsLQQg',
  'ufvaaDCkJj5pW4f7_DSN5w',
  'yUEeh9nwaycI6fKLruD_rQ',
  '5XelZjHymGydI5qKE8BOrA',
  'Jov0PmO5g5lXGQyPiEZyXw',
  'ngvE1G9IckUO-ljZBFo23w',
  '46_2e1hnQ4csLrYnhn6bkw',
  'HqLOOpUax2dC8GYc0oqq2A',
  'TGfPJHImEq6AQL9a1laxlg',
  'xa28v84RtUPWQKuw_UQBXQ',
  'kxvOUehCtJAL2nYKkeiR-w',
  'CPgWuWGZ4v2sZr5_-1kluw',
  'uU9h_l5WSTY8fKVU2nx2Cw',
  'xvAkaDEOOUloROkX0j4C-w',
  '5SV2YI6MBSOWaEwB8pBHtQ',
  'gu2-TPPdyQyHl2CnPb7Xjg',
  'Eb8GseQXa1ZICrmCwbXmPQ',
  'O5Obr4roy3Fd-nQXkfk7TQ',
  'VCkSUsdL5P0p16DAPxVROA',
  'dIpTuL2T1L98GQGU17IeSw',
  'kKb00Oj96n5YYqMSDzx1IA',
  'Oy7rU9H76PN1hsDU9EUt5g',
  '2ahg0y3bmn8gRo0aGrFiEQ',
  'XRkzSBTroG7kIdI7Z8ic6g',
  'bf34LpGej_MZbOlAKB1beQ',
  '4pS7qnjJ7_DCoJB-Enl7KA',
  '5VYkn3vm4teAiLVeuT89Qw',
  'SoJwDKedR7SJh7-G69C38A',
  'sKdF_rwYyLa2NM1dlG0-Sg',
  'X7FQ5k29A_RRYep7TOfjtw',
  '8zsUZsQtRPHYW4gD5puiqQ',
  'FW1PXpUq-yOs-5O_gqz3AQ',
  'dgMuYzYRXji7PGFmnUs3aw',
  '1tLrjXG-I9hkOoZxlbwDqw',
  'SlLfWzeYOrVBxCd-0QILZQ',
  'adATTqggIQX5xxLDISkFTw',
  'pNu5bd9aL3jcJClfdQ86MQ',
  'bdfZdB2MTXlT6-RBjSIpQg',
  'vxrGNnuEef7YCfB7mN08rA',
  '1EokZOnCDkjv2VtPtplyHw',
  'yuangT-PWlF-YRbgN6M02A',
  'ZpmSEd9N042IJanBiKlKiQ',
  'OYmwoFmoEIA0rx7jd6ZWsg',
  '42OM20QndpmsOSY6ccudBA',
  'lAd7PwbmfpirUngbb6uCiA',
  'hx-qUirkgRqX2Bk8A2U0nA',
  'D5DBDShzSVx_gQtdIbOqZg',
  'TapXvuOEC3qGGmlf03INnA',
  'SwWfW3vBn5QkDE7T3urGAg',
  '1s-vqaaGLscl7h4XIDO7LQ',
  'W4rgF_1eKzFZiGUOsgbGMA',
  'yN6jZyG1G1FG_HCZQlJZ1g',
  '00szsg8vQy6yX5f-m9sI4A',
  'WmnPtMtY0elYVStooCTfng',
  'wCgIJhH_CTuwsSZPcafkng',
  'wOUJ-duIHPdRiV0af9s0xA',
  'PW5eZM5RAQEhy3wgovChhQ',
  'QTsscMMSMJbWGjGktvQwZA',
  'jGewGnIYcf9LFBcR8lMC5g',
  'quv6eMqyJ1NIkjPgIgS65g',
  '5whwQ1UnbkT2wwD8-08Rpw',
  'DwkUcTFaFhqcW-RDJ5rnNQ',
  'd45ejuYD188Yzyxz6cCu-g',
  '2TLNzc2WVzJMa-IRTYMINQ',
  'FLsMpCzvopg6vl3atsKVmQ',
  '-lVTNjVoTMOkD-eT--u0oA',
  'Jft1PUUQGH4DoC2S1zsABg',
  'BQkH3UGGtXzU4IfZewaw_w',
  'K0nNsUGPoE7ezIXiBwxrFQ',
  'jDCk9DEwSS_TamliID4QuQ',
  'FbGjCCc7bbJVWq3Kt5lamQ',
  'TCxvQgfBD6_JjOM3N1VPRA',
  '6_Zf2QsRHCH1RhbzA9inyw',
  'cAUe8LFnDjii_sx_4fRMaA',
  'lPPYZr1_jx0XeW-xR9WJtw',
  '0sr1EyOc6Td1C-962QW88w',
  'p3QzxYDXLs6AthCldH-_Og',
  'SFKjUQ1gmfwm7cJhMCFmkA',
  'GJpAeUSsPIsVK6_0Lfuekg',
  'frsWe9bmMOMIBOBNzsCTew',
  '-H6s1c2NRic5UKxXqi4FdQ',
  'NQhyMw8SOU1HB-V9X52CTg',
  'VEbHYioBfoPiIOWntE_DBA',
  'xwSWtJcQkzTF6HNm_IMgcg',
  'Rm6DNK_kpJ55mai3bL4qTA',
  'xY0jpu0zzGEBr-bGBdPs-w',
  'o9jFWOpK9ty5vZUQTE6z5w',
  '395jG1TlFKTf1t1d9PH6AQ',
  'ejEVU5o5F56e7XIO07xpcA',
  'yni7QxA0Hgw5PbgR4NxKHw',
  'yFqq66GxRjnhZXPgjA6hnw',
  'AaiXrV5sFYedDtx1hBbx7w',
  'IbndcMURguByburM72o3SA',
  '1oDLf788824qQh-8Shl3sw',
  'CrF8GhrF8KJikwugSci5lA',
  'Iipfa9Kaac9XH5Vo8GQwvg',
  'S_-UJCj3Q-69_q92k59XYA',
  '82suwumWp1MEq04QhiS9DQ',
  'diwwt5QBU3-Thig9SVlsOA',
  'u2Bh7ylWs9InI7WFk9N53A',
  '3uvFklejzRPwEPEZQ5vHYQ',
  'BFf44roOiEodYRu06Xq8cg',
  '0l_njS4wGMadAk1b4nZRUA',
  'lB6jIOb1UBATmdfot4KJew',
  'qQcAJDLelexcAZOcdPnsEA',
  'CC7YefPM9zc080JHOKfI1w',
  'cm0bhBDPM3bjBefmEXa3BQ',
  'MObScX791gFEwtkoFA9GQg',
  'zaaX5EzJDNxhzIFywyxYKg',
  '3c9TiufCFT2yXXj3R08Vwg',
  'TJe1ZGe-X0-GjOQd00kKxA',
  'dRqRBDrQZsNKo72JlEcejw',
  'FYzZd2mlMIPScy95UY2xkw',
  'V8uKFuHyHKSOWojuhcP-2A',
  'rh3C_JK4NAoUJ-HNStvHtw',
  'ObH_8KvD5McBFAZen0pp6g',
  'nHUJCK-Ek_lAVTSyEz9GEQ',
  'xHspDrdyq1g27yRDezB5yA',
  'HCbJPXWXvwN-C7XfmVy3gA',
  'XNBExNkAx5fjYM6fjqfzAA',
  '1p15mHF9dFRBYH_VKcdDRg',
  'jZoeTGRfhG9n_Jo6VMqwxw',
  'SBgr-5n-kV3EeZztYsstUQ',
  'wR8V8u3_wv-yjR-CIHyY0Q',
  '_CFqjUDwqpfKlsbl01KQ8Q',
  'v_C_FZW_rPsqHdBEY_O4kQ',
  'O4oK6A5wJuVWpYP4IMgUqw',
  'asmWFLd8yC96IdLEgfeYNg',
  'A1lAqN3SOaBLoo6NqVcy4Q',
  'EPDRXctqbR9fJRW881zSDA',
  '6XT6OcqGU-8BXKFp7zHoRA',
  'oSp8B87eQ8droCGiWUERZA',
  'O0YHVrUtxbsEhQ4qaWkVaw',
  'YKsZFlfTUNAzuDTTkArh0A',
  'kGjpBqAqG4mIuFSgU2KKEA',
  'VqK1bLVFmEpePL1Qhmz7ew',
  'nzIx3Wze25rr5k32sDCwaA',
  'jKb0H78PubnEMa5JoXdnvw',
  '-pgTW7620zWdXMOczX0www',
  '5yi5oPPf065CQjF5nOnFCw',
  'L9CKPOoI51LNnRW8B1M8CQ',
  'CNVapZiNGgqVrkEwmS8INQ',
  'kLSEk3qXY1KdtFjxHJ9pww',
  'WYVDN3VDDTiEUV0QR8D2Hg',
  'uKEabBQrn0gLzvTppOrKIA',
  'epGYbd0_OeSxsSkw-Kx5Rg',
  '3rh9S7pQWFf8WP1Vg67aaQ',
  'uHprVoxTV7CwKJdaEEf3aA',
  '8JEOmVGQffkr6xtn4vvplQ',
  'lq4bgjDiAYR6i63-ZDiBGg',
  '05f7LL_6d7DOw0hHR9tsqw',
  'W5tIz4sl1yRW_fOXHoGVzQ',
  'cogiJiOXN5fDu7jnkYEkfQ',
  'rF0xI_3jjlsEKp3N0Z0BuQ',
  'wcppVzRVOFwZp3-Qdwb_TQ',
  'YQxZzSbGJl_4Ul2EGXYAqQ',
  'oO3XXCAzBP4d-2klkkgEcw',
  'gp-DPUypvHZYyuDE55PHyA',
  'qma1sGQv7ArUtzuUTQElRg',
  '9W9pFoPdrwZAg1xxHhzp6Q',
  'zjQDk4tZyhEroyqtkgvx0g',
  'adb1hOYICrJ1Ix8M0sRpbw',
  'dujix6rWem5FD73MZSBF2w',
  'EEc3X2r94uNhCz_jOTSzHg',
  'j2oZyu8a5qa-LL-LZ5DBPw',
  'HxlFnUI9-RNKlKD2zUwzWQ',
  '5N8iDpDtjTbU0F1YD645xA',
  'iRLAkeK4PZGjKB1zmvRByw',
  'dGPwaWBjzKQiYJpGw73EHA',
  'Cc1HSkYiRiDUquHiz2vdIg',
  'kfGz2E7Y5FLXJyiKbQYfZg',
  'H3JjbID9Zhukpqr9uupHAA',
  'Dq7pbol4jb6RV4ozqGHLXw',
  '-kY_HDP7IMvGl-kBIZVU4A',
  'O5zuQH_YowDC-rsK8ZEXCA',
  'xpmcxoWG0w9HkqTo6AClUQ',
  'jsQQu9rVerR3OGxIa0hRQQ',
  'sSCTL4XvhBPZDdmnOYGmGA',
  'XkofFhXCXh6OUpWoG_ydWA',
  '5bCsL-Z3QnuBmJQtIt8qyw',
  '7fuFAkD_NqV5PQ7cA0Yzlg',
  'NHdjuuwzYCh0AWqWZgz-KA',
  'n2Va0mKydUWM-Y4fv1pOtA',
  'bJ7h_SLSrnxEj61E6Qv9tQ',
  'Hp3Ony7yW60VPuWHQFIIHA',
  'UX3eq0WsVva-cqlVrzyzFg',
  'QqNTFJdyPWpWAoO5ecw93w',
  'BP5zBLaUz8QPCNgPwgBoRg',
  'Yas-A9Jf07TJCIcgZny04w',
  '1o_M5JdOkJJFNj1rIDIlng',
  'n5rWjvJHmlEwr4rd13ZRqw',
  'aSJdDcspNCf-2oNF2E6SJQ',
  'ZuOtTcUKmthgvhKo7B_-sg',
  'q9dLguaNI58Rs5GJuJAWIg',
  'Q-a-DzqRufrPL6EcUDpyag',

In [30]:
hours_data['day_of_week']

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 ...]

In [31]:
to_drop

{'hours.Friday',
 'hours.Monday',
 'hours.Saturday',
 'hours.Sunday',
 'hours.Thursday',
 'hours.Tuesday',
 'hours.Wednesday'}

#### Creating hours DataFrame

In [32]:
df_business_hours = pd.DataFrame(hours_data, columns=hours_data.keys())  # Make keys as index
df_business_hours

                    business_id  day_of_week open_time close_time  is_closed
0        Pns2l4eNsfO8kk83dixA6A            1      <NA>       <NA>       True
1        mpf3x-BjTdTEA3yCZrAYPw            1  00:00:00   00:00:00      False
2        tUFrWirKiKi_TAnsVWINQQ            1  08:00:00   22:00:00      False
3        MTSW4McQd7CbVtyjqoe9mw            1  07:00:00   20:00:00      False
4        mWMc6_wTdE0EUBKIGXDVfA            1      <NA>       <NA>       True
...                         ...          ...       ...        ...        ...
1052417  IUQopTMmYQG-qRtBk-8QnA            0  11:00:00   17:00:00      False
1052418  c8GjPIOTGVmIemT7j5_SyQ            0  00:00:00   16:00:00      False
1052419  _QAMST-NrQobXduilWEqSw            0      <NA>       <NA>       True
1052420  mtGm22y5c2UHNXDFAjaPNw            0  10:00:00   17:00:00      False
1052421  jV_XOycEzSlTx-65W906pg            0      <NA>       <NA>       True

[1052422 rows x 5 columns]

#### Exporting Hours DataFrame

In [33]:
lib.export_data(EXPORT_DIRECTORY / 'yelp_business_hours.csv', df_business_hours)

PortfolioLogger.lib.tools: INFO: Exporting 5262110 elements (194.23 MB) to /Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/clean/yelp_business_hours_CLEAN.csv
PortfolioLogger.lib.performance: INFO: <function export_data at 0x10f9a1940> took 1.069 secs to complete.

PosixPath('/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/clean/yelp_business_hours_CLEAN.csv')

#### Dropping hours columns

In [34]:
df_business_cp3 = df_business_cp3.drop(to_drop, axis=1)

In [35]:
df_business_cp3.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,attributes.DogsAllowed,attributes.Alcohol,attributes.GoodForKids,attributes.RestaurantsAttire,attributes.Ambience,attributes.RestaurantsTableService,attributes.RestaurantsGoodForGroups,attributes.NoiseLevel,attributes.GoodForMeal,attributes.BusinessAcceptsBitcoin
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,...,NaN,u'none',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,...,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Creating backup

In [36]:
df_business_cp4 = df_business_cp3.copy()

### Cleaning Attributes columns

In [37]:
not_risky = []
for day, series in df_business_cp4.items():
    if day.startswith('attributes.'):
        log.info(day)
        if not lib.isrisky(series, err_rate=.5):
            not_risky.append(day)
not_risky

PortfolioLogger.yelp_dataset: INFO: attributes.ByAppointmentOnly
PortfolioLogger.yelp_dataset: INFO: attributes.BusinessAcceptsCreditCards
PortfolioLogger.yelp_dataset: INFO: attributes.BikeParking
PortfolioLogger.yelp_dataset: INFO: attributes.RestaurantsPriceRange2
PortfolioLogger.yelp_dataset: INFO: attributes.RestaurantsTakeOut
PortfolioLogger.yelp_dataset: INFO: attributes.RestaurantsDelivery
PortfolioLogger.yelp_dataset: INFO: attributes.Caters
PortfolioLogger.yelp_dataset: INFO: attributes.WiFi
PortfolioLogger.yelp_dataset: INFO: attributes.BusinessParking
PortfolioLogger.yelp_dataset: INFO: attributes.WheelchairAccessible
PortfolioLogger.yelp_dataset: INFO: attributes.HappyHour
PortfolioLogger.yelp_dataset: INFO: attributes.OutdoorSeating
PortfolioLogger.yelp_dataset: INFO: attributes.HasTV
PortfolioLogger.yelp_dataset: INFO: attributes.RestaurantsReservations
PortfolioLogger.yelp_dataset: INFO: attributes.DogsAllowed
PortfolioLogger.yelp_dataset: INFO: attributes.Alcohol
PortfolioLogger.yelp_dataset: INFO: attributes.GoodForKids
PortfolioLogger.yelp_dataset: INFO: attributes.RestaurantsAttire
PortfolioLogger.yelp_dataset: INFO: attributes.Ambience
PortfolioLogger.yelp_dataset: INFO: attributes.RestaurantsTableService
PortfolioLogger.yelp_dataset: INFO: attributes.RestaurantsGoodForGroups
PortfolioLogger.yelp_dataset: INFO: attributes.NoiseLevel
PortfolioLogger.yelp_dataset: INFO: attributes.GoodForMeal
PortfolioLogger.yelp_dataset: INFO: attributes.BusinessAcceptsBitcoin

['attributes.BusinessAcceptsCreditCards',
 'attributes.RestaurantsPriceRange2',
 'attributes.BusinessParking']

#### The attributes columns are all a little risky but I'll include them for extra data that shouldn't be relied on but can be helpful to see in a business

In [38]:
attributes_cols = []
for col, series in df_business_cp4.items():
    if col.startswith('attributes.'):
        attributes_cols.append(col)

lib.error_rates(df_business_cp4[attributes_cols])

                                      error_percent error_count
attributes.ByAppointmentOnly                 71.84%      108007
attributes.BusinessAcceptsCreditCards        20.34%       30581
attributes.BikeParking                       51.69%       77708
attributes.RestaurantsPriceRange2            43.25%       65032
attributes.RestaurantsTakeOut                60.19%       90489
attributes.RestaurantsDelivery               62.57%       94064
attributes.Caters                            73.31%      110219
attributes.WiFi                              62.14%       93432
attributes.BusinessParking                   39.42%       59261
attributes.WheelchairAccessible              80.74%      121393
attributes.HappyHour                         89.91%      135175
attributes.OutdoorSeating                    67.54%      101544
attributes.HasTV                             70.01%      105262
attributes.RestaurantsReservations           69.90%      105099
attributes.DogsAllowed                       87.84%      132062
attributes.Alcohol                           71.27%      107157
attributes.GoodForKids                       64.50%       96971
attributes.RestaurantsAttire                 73.89%      111091
attributes.Ambience                          70.55%      106067
attributes.RestaurantsTableService           86.71%      130364
attributes.RestaurantsGoodForGroups          70.62%      106176
attributes.NoiseLevel                        74.73%      112353
attributes.GoodForMeal                       80.65%      121259
attributes.BusinessAcceptsBitcoin            88.41%      132916

In [39]:
df_business_cp4[attributes_cols].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150346 entries, 0 to 150345
Data columns (total 24 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   attributes.ByAppointmentOnly           42339 non-null   object
 1   attributes.BusinessAcceptsCreditCards  119765 non-null  object
 2   attributes.BikeParking                 72638 non-null   object
 3   attributes.RestaurantsPriceRange2      85314 non-null   object
 4   attributes.RestaurantsTakeOut          59857 non-null   object
 5   attributes.RestaurantsDelivery         56282 non-null   object
 6   attributes.Caters                      40127 non-null   object
 7   attributes.WiFi                        56914 non-null   object
 8   attributes.BusinessParking             91085 non-null   object
 9   attributes.WheelchairAccessible        28953 non-null   object
 10  attributes.HappyHour                   15171 non-null   object
 11  attributes.OutdoorSeating              48802 non-null   object
 12  attributes.HasTV                       45084 non-null   object
 13  attributes.RestaurantsReservations     45247 non-null   object
 14  attributes.DogsAllowed                 18284 non-null   object
 15  attributes.Alcohol                     43189 non-null   object
 16  attributes.GoodForKids                 53375 non-null   object
 17  attributes.RestaurantsAttire           39255 non-null   object
 18  attributes.Ambience                    44279 non-null   object
 19  attributes.RestaurantsTableService     19982 non-null   object
 20  attributes.RestaurantsGoodForGroups    44170 non-null   object
 21  attributes.NoiseLevel                  37993 non-null   object
 22  attributes.GoodForMeal                 29087 non-null   object
 23  attributes.BusinessAcceptsBitcoin      17430 non-null   object
dtypes: object(24)
memory usage: 27.5+ MB

In [40]:
df_business_cp4[attributes_cols]

,attributes.ByAppointmentOnly,attributes.BusinessAcceptsCreditCards,attributes.BikeParking,attributes.RestaurantsPriceRange2,attributes.RestaurantsTakeOut,attributes.RestaurantsDelivery,attributes.Caters,attributes.WiFi,attributes.BusinessParking,attributes.WheelchairAccessible,...,attributes.DogsAllowed,attributes.Alcohol,attributes.GoodForKids,attributes.RestaurantsAttire,attributes.Ambience,attributes.RestaurantsTableService,attributes.RestaurantsGoodForGroups,attributes.NoiseLevel,attributes.GoodForMeal,attributes.BusinessAcceptsBitcoin
0,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,False,True,True,2,False,False,False,u'no',"{'garage': False, 'street': False, 'validated'...",True,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,False,False,True,1,True,False,True,u'free',"{'garage': False, 'street': True, 'validated':...",NaN,...,NaN,u'none',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,True,True,NaN,True,NaN,False,NaN,"{'garage': None, 'street': None, 'validated': ...",True,...,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150341,False,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150342,NaN,True,True,2,NaN,NaN,NaN,u'no',"{'garage': False, 'street': False, 'validated'...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150343,NaN,True,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150344,NaN,True,True,4,None,None,NaN,NaN,"{'garage': False, 'street': False, 'validated'...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150345,False,True,False,1,NaN,NaN,NaN,u'free',"{'garage': False, 'street': False, 'validated'...",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [41]:
for col, series in df_business_cp4.items():
    if col.startswith('attributes.'):
        log.info(col)
        log.info(df_business_cp4[col].unique())

PortfolioLogger.yelp_dataset: INFO: attributes.ByAppointmentOnly
PortfolioLogger.yelp_dataset: INFO: ['True' nan 'False' 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.BusinessAcceptsCreditCards
PortfolioLogger.yelp_dataset: INFO: [nan 'True' 'False' 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.BikeParking
PortfolioLogger.yelp_dataset: INFO: [nan 'True' 'False' 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.RestaurantsPriceRange2
PortfolioLogger.yelp_dataset: INFO: [nan '2' '1' '3' '4' 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.RestaurantsTakeOut
PortfolioLogger.yelp_dataset: INFO: [nan 'False' 'True' 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.RestaurantsDelivery
PortfolioLogger.yelp_dataset: INFO: [nan 'False' 'True' 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.Caters
PortfolioLogger.yelp_dataset: INFO: [nan 'False' 'True' 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.WiFi
PortfolioLogger.yelp_dataset: INFO: [nan "u'no'" "u'free'" "'free'" "'no'" 'None' "u'paid'" "'paid'"]
PortfolioLogger.yelp_dataset: INFO: attributes.BusinessParking
PortfolioLogger.yelp_dataset: INFO: [nan
 "{'garage': False, 'street': False, 'validated': False, 'lot': True, 'valet': False}"
 "{'garage': False, 'street': True, 'validated': False, 'lot': False, 'valet': False}"
 "{'garage': None, 'street': None, 'validated': None, 'lot': True, 'valet': False}"
 'None'
 "{'garage': False, 'street': False, 'validated': False, 'lot': False, 'valet': False}"
 "{'garage': None, 'street': False, 'validated': None, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': None, u'street': True, u'lot': False, u'validated': None}"
 "{'garage': False, 'street': True, 'validated': False, 'lot': True, 'valet': False}"
 "{'garage': True, 'street': False, 'validated': False, 'lot': False, 'valet': False}"
 "{'garage': True, 'street': False, 'validated': True, 'lot': False, 'valet': True}"
 "{'garage': None, 'street': True, 'validated': None, 'lot': False, 'valet': False}"
 "{'garage': False, 'street': True, 'validated': True, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': False, u'lot': True, u'validated': False}"
 "{u'valet': False, u'garage': False, u'street': None, u'lot': True, u'validated': False}"
 "{'garage': True, 'street': True, 'validated': False, 'lot': False, 'valet': False}"
 "{'garage': None, 'street': False, 'validated': None, 'lot': False, 'valet': False}"
 "{'garage': False, 'street': False, 'validated': False, 'lot': None, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': None, u'lot': None, u'validated': None}"
 "{'garage': False, 'street': False, 'validated': True, 'lot': False, 'valet': False}"
 "{u'valet': False, u'garage': None, u'street': None, u'lot': True, u'validated': None}"
 "{u'valet': False, u'garage': True, u'street': False, u'lot': True, u'validated': False}"
 "{u'valet': False, u'garage': False, u'street': False, u'lot': False, u'validated': False}"
 "{u'valet': False, u'garage': None, u'street': False, u'lot': None, u'validated': False}"
 "{'garage': True, 'street': False, 'validated': False, 'lot': True, 'valet': False}"
 "{'garage': False, 'street': True, 'validated': False, 'lot': None, 'valet': False}"
 "{'garage': False, 'street': True, 'validated': False, 'lot': False, 'valet': True}"
 "{'garage': False, 'street': False, 'validated': False, 'lot': True, 'valet': True}"
 "{'garage': False, 'street': None, 'validated': False, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': True, u'street': True, u'lot': False, u'validated': False}"
 "{'garage': False, 'street': False, 'validated': None, 'lot': True, 'valet': False}"
 "{'garage': None, 'street': True, 'validated': None, 'lot': None, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': True, u'lot': False, u'validated': False}"
 "{'garage': False, 'street': None, 'validated': False, 'lot': None, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': None, u'lot': None, u'validated': False}"
 "{'garage': True, 'street': True, 'validated': True, 'lot': True, 'valet': True}"
 "{u'valet': False, u'garage': False, u'street': True, u'lot': True, u'validated': False}"
 "{'garage': True, 'street': True, 'validated': False, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': None, u'street': None, u'lot': None, u'validated': False}"
 "{'garage': None, 'street': True, 'validated': False, 'lot': None, 'valet': False}"
 "{'garage': False}"
 "{'garage': True, 'street': True, 'validated': True, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': False, u'lot': True, u'validated': None}"
 "{u'valet': True, u'garage': True, u'street': False, u'lot': False, u'validated': False}"
 "{u'valet': False, u'garage': False, u'street': None, u'lot': True, u'validated': None}"
 "{'garage': None, 'street': True, 'validated': False, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': True, u'lot': None, u'validated': False}"
 "{'garage': None, 'street': None, 'validated': None, 'lot': False, 'valet': False}"
 "{'garage': False, 'street': False, 'validated': False, 'lot': False, 'valet': True}"
 "{'garage': False, 'street': None, 'validated': None, 'lot': None, 'valet': False}"
 "{'garage': False, 'street': True, 'validated': False, 'lot': True, 'valet': True}"
 "{'garage': True, 'street': None, 'validated': None, 'lot': None, 'valet': False}"
 "{'garage': False, 'street': False, 'validated': None, 'lot': False, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': False, u'lot': None, u'validated': False}"
 "{'garage': None, 'street': True, 'validated': False, 'lot': False, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': True, u'lot': False, u'validated': None}"
 "{'garage': True, 'street': False, 'validated': False, 'lot': False, 'valet': True}"
 "{'garage': True, 'street': None, 'validated': False, 'lot': None, 'valet': False}"
 "{u'valet': False, u'garage': None, u'street': True, u'lot': None, u'validated': False}"
 "{'garage': None, 'street': False, 'validated': False, 'lot': False, 'valet': False}"
 "{u'valet': False, u'garage': None, u'street': True, u'lot': None, u'validated': None}"
 "{'garage': None, 'street': False, 'validated': False, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': None, u'street': None, u'lot': False, u'validated': None}"
 "{u'valet': False, u'garage': False, u'street': True, u'lot': True, u'validated': True}"
 "{'garage': True, 'street': None, 'validated': False, 'lot': False, 'valet': False}"
 "{'garage': True, 'street': True, 'validated': False, 'lot': False, 'valet': True}"
 "{'garage': True, 'street': False, 'validated': True, 'lot': False, 'valet': False}"
 "{u'valet': False, u'garage': True, u'street': True, u'lot': None, u'validated': False}"
 "{u'valet': False, u'garage': True, u'street': None, u'lot': None, u'validated': None}"
 "{'garage': False, 'street': False, 'validated': None, 'lot': None, 'valet': False}"
 "{'garage': False, 'street': None, 'validated': None, 'lot': True, 'valet': False}"
 "{'garage': False, 'street': None, 'validated': False, 'lot': False, 'valet': False}"
 "{'garage': None, 'street': None, 'validated': False, 'lot': None, 'valet': False}"
 "{u'valet': False, u'garage': None, u'street': None, u'lot': True, u'validated': False}"
 "{u'valet': False, u'garage': None, u'street': False, u'lot': True, u'validated': None}"
 "{'garage': False, 'street': True, 'validated': True, 'lot': False, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': True, u'lot': None, u'validated': None}"
 "{u'valet': False, u'garage': None, u'street': True, u'lot': False, u'validated': False}"
 "{'garage': True, 'street': True, 'validated': True, 'lot': False, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': False, u'lot': None, u'validated': None}"
 "{'garage': False, 'street': True, 'validated': True, 'lot': False, 'valet': True}"
 "{'garage': None, 'street': True, 'validated': None, 'lot': True, 'valet': False}"
 "{'garage': None, 'street': None, 'validated': False, 'lot': False, 'valet': False}"
 "{'garage': None, 'street': False, 'validated': False, 'lot': None, 'valet': False}"
 "{'garage': True, 'street': True, 'validated': None, 'lot': False, 'valet': False}"
 "{'garage': None, 'street': None, 'validated': False, 'lot': True, 'valet': False}"
 "{'garage': False, 'street': False, 'validated': True, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': True, u'street': False, u'lot': None, u'validated': None}"
 "{'garage': True, 'street': False, 'validated': False, 'lot': True, 'valet': True}"
 "{u'garage': False, u'street': False, u'validated': False, u'lot': True, u'valet': False}"
 "{'garage': None, 'street': False, 'validated': None, 'lot': None, 'valet': False}"
 "{u'valet': False, u'garage': None, u'street': False, u'lot': True, u'validated': False}"
 "{'garage': True, 'street': True, 'validated': False, 'lot': True, 'valet': True}"
 "{u'valet': False, u'garage': True, u'street': False, u'lot': True, u'validated': None}"
 "{u'valet': True, u'garage': False, u'street': False, u'lot': False, u'validated': False}"
 "{'garage': True, 'street': False, 'validated': True, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': True, u'street': False, u'lot': False, u'validated': False}"
 "{'valet': False, 'garage': False, 'street': False, 'lot': False, 'validated': False}"
 "{u'valet': False, u'garage': False, u'street': None, u'lot': False, u'validated': False}"
 "{u'valet': True, u'garage': False, u'street': True, u'lot': True, u'validated': False}"
 "{u'valet': False, u'garage': None, u'street': None, u'lot': False, u'validated': False}"
 "{u'valet': False, u'garage': True, u'street': None, u'lot': False, u'validated': None}"
 "{u'valet': False, u'garage': True, u'street': True, u'lot': False, u'validated': None}"
 "{'garage': False, 'street': None, 'validated': None, 'lot': False, 'valet': False}"
 "{'garage': True, 'street': None, 'validated': None, 'lot': False, 'valet': False}"
 "{u'valet': False, u'garage': True, u'street': True, u'lot': None, u'validated': None}"
 "{'garage': False, 'street': True, 'validated': True, 'lot': True, 'valet': True}"
 "{'garage': True, 'street': True, 'validated': True, 'lot': False, 'valet': True}"
 "{u'valet': True, u'garage': True, u'street': True, u'lot': True, u'validated': True}"
 "{u'valet': False, u'garage': True, u'street': True, u'lot': True, u'validated': False}"
 "{'valet': False, 'garage': False, 'street': False, 'lot': True, 'validated': False}"
 "{u'valet': False, u'garage': True, u'street': False, u'lot': None, u'validated': False}"
 "{u'valet': False, u'garage': True, u'street': None, u'lot': None, u'validated': False}"
 "{u'valet': False, u'garage': None, u'street': False, u'lot': False, u'validated': False}"
 "{u'valet': False, u'garage': False, u'street': None, u'lot': False, u'validated': None}"
 "{'garage': False, 'street': False, 'validated': True, 'lot': False, 'valet': True}"
 "{'garage': False, 'street': False, 'validated': True, 'lot': True, 'valet': True}"
 "{u'valet': False, u'garage': True, u'street': None, u'lot': False, u'validated': False}"
 "{u'valet': False, u'garage': False, u'street': False, u'lot': False, u'validated': True}"
 "{'garage': False, 'street': True, 'validated': None, 'lot': True, 'valet': False}"
 "{'garage': False, 'street': True, 'validated': None, 'lot': False, 'valet': False}"
 "{'garage': True, 'street': False, 'validated': False, 'lot': None, 'valet': False}"
 "{u'valet': False, u'garage': None, u'street': False, u'lot': None, u'validated': None}"
 "{u'valet': False, u'garage': None, u'street': True, u'lot': True, u'validated': False}"
 "{'garage': True, 'street': None, 'validated': False, 'lot': True, 'valet': False}"
 "{'garage': True, 'street': False, 'validated': True, 'lot': True, 'valet': True}"
 "{u'valet': False, u'garage': None, u'street': False, u'lot': False, u'validated': None}"
 "{u'valet': True, u'garage': False, u'street': False, u'lot': False, u'validated': True}"
 "{'garage': False, 'street': True, 'validated': None, 'lot': None, 'valet': False}"
 "{u'valet': False, u'garage': True, u'street': None, u'lot': True, u'validated': None}"
 "{u'valet': True, u'garage': True, u'street': True, u'lot': False, u'validated': False}"
 "{u'valet': True, u'garage': False, u'street': False, u'lot': True, u'validated': False}"
 "{u'valet': True, u'garage': False, u'street': True, u'lot': False, u'validated': False}"
 "{'garage': False, 'street': None, 'validated': False, 'lot': None, 'valet': True}"
 "{u'valet': False, u'garage': None, u'street': True, u'lot': True, u'validated': None}"
 "{'valet': False}"
 "{'valet': False, 'garage': False, 'street': True, 'lot': False, 'validated': False}"
 "{u'valet': False, u'garage': True, u'street': False, u'lot': False, u'validated': True}"
 "{u'valet': False, u'garage': True, u'street': True, u'lot': True, u'validated': None}"
 "{'garage': False, 'validated': False, 'street': False, 'lot': False, 'valet': False}"
 "{u'garage': False, u'street': True, u'validated': False, u'lot': True, u'valet': False}"
 "{'garage': True, 'street': True, 'validated': False, 'lot': None, 'valet': False}"
 "{u'valet': False, u'garage': True, u'street': None, u'lot': True, u'validated': False}"
 "{u'garage': False, u'street': True, u'validated': False, u'lot': False, u'valet': False}"
 "{'garage': True, 'street': True, 'validated': None, 'lot': None, 'valet': False}"
 "{'garage': True, 'street': False, 'validated': None, 'lot': None, 'valet': False}"
 "{u'valet': True, u'garage': False, u'street': True, u'lot': False, u'validated': True}"
 "{'garage': True, 'street': None, 'validated': None, 'lot': True, 'valet': False}"
 '{}'
 "{u'valet': False, u'garage': False, u'street': True, u'lot': True, u'validated': None}"
 "{'garage': True, 'street': True, 'validated': None, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': False, u'lot': False, u'validated': None}"
 "{'garage': True, 'street': False, 'validated': None, 'lot': True, 'valet': False}"
 "{u'valet': True, u'garage': True, u'street': True, u'lot': True, u'validated': False}"
 "{u'valet': False, u'garage': True, u'street': True, u'lot': False, u'validated': True}"
 "{u'valet': False, u'garage': False, u'street': True, u'lot': False, u'validated': True}"
 "{u'valet': False, u'garage': True, u'street': False, u'lot': False, u'validated': None}"
 "{u'valet': True, u'garage': True, u'street': False, u'lot': True, u'validated': False}"
 "{u'valet': False, u'garage': False, u'street': False, u'lot': True, u'validated': True}"
 "{u'valet': False, u'garage': None, u'street': True, u'lot': None, u'validated': True}"
 "{u'garage': True, u'street': True, u'validated': False, u'lot': False, u'valet': False}"
 "{'garage': True, 'street': None, 'validated': True, 'lot': True, 'valet': False}"
 "{u'valet': True, u'garage': False, u'street': True, u'lot': True, u'validated': True}"
 "{u'garage': False, u'street': False, u'validated': False, u'lot': False, u'valet': False}"
 "{u'valet': False, u'garage': True, u'street': True, u'lot': True, u'validated': True}"
 "{u'garage': True, u'street': False, u'validated': False, u'lot': False, u'valet': True}"]
PortfolioLogger.yelp_dataset: INFO: attributes.WheelchairAccessible
PortfolioLogger.yelp_dataset: INFO: [nan 'True' 'False' 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.HappyHour
PortfolioLogger.yelp_dataset: INFO: [nan 'False' 'True' 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.OutdoorSeating
PortfolioLogger.yelp_dataset: INFO: [nan 'False' 'True' 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.HasTV
PortfolioLogger.yelp_dataset: INFO: [nan 'False' 'True' 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.RestaurantsReservations
PortfolioLogger.yelp_dataset: INFO: [nan 'False' 'True' 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.DogsAllowed
PortfolioLogger.yelp_dataset: INFO: [nan 'False' 'True' 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.Alcohol
PortfolioLogger.yelp_dataset: INFO: [nan "u'none'" "u'full_bar'" "'none'" "'full_bar'" "u'beer_and_wine'"
 "'beer_and_wine'" 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.GoodForKids
PortfolioLogger.yelp_dataset: INFO: [nan 'True' 'False' 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.RestaurantsAttire
PortfolioLogger.yelp_dataset: INFO: [nan "u'casual'" "'casual'" "u'formal'" "'dressy'" "u'dressy'" "'formal'"
 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.Ambience
PortfolioLogger.yelp_dataset: INFO: [nan 'None'
 "{'romantic': False, 'intimate': False, 'touristy': False, 'hipster': False, 'divey': False, 'classy': False, 'trendy': False, 'upscale': False, 'casual': False}"
 ...
 "{'touristy': False, 'hipster': None, 'romantic': False, 'divey': None, 'intimate': None, 'trendy': False, 'upscale': None, 'classy': True, 'casual': None}"
 "{'touristy': False, 'hipster': None, 'romantic': False, 'intimate': None, 'trendy': True, 'upscale': False, 'classy': False, 'casual': True}"
 "{'touristy': None, 'hipster': False, 'romantic': False, 'divey': None, 'intimate': False, 'trendy': False, 'upscale': None, 'classy': None, 'casual': True}"]
PortfolioLogger.yelp_dataset: INFO: attributes.RestaurantsTableService
PortfolioLogger.yelp_dataset: INFO: [nan 'False' 'True' 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.RestaurantsGoodForGroups
PortfolioLogger.yelp_dataset: INFO: [nan 'True' 'False' 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.NoiseLevel
PortfolioLogger.yelp_dataset: INFO: [nan "u'average'" "u'quiet'" "'average'" "u'loud'" "u'very_loud'"
 "'quiet'" "'very_loud'" "'loud'" 'None']
PortfolioLogger.yelp_dataset: INFO: attributes.GoodForMeal
PortfolioLogger.yelp_dataset: INFO: [nan
 "{'dessert': False, 'latenight': False, 'lunch': False, 'dinner': False, 'brunch': False, 'breakfast': False}"
 "{'dessert': False, 'latenight': False, 'lunch': True, 'dinner': False, 'brunch': False, 'breakfast': False}"
 "{'dessert': True, 'latenight': None, 'lunch': None, 'dinner': True, 'brunch': None, 'breakfast': None}"
 "{'dessert': False, 'latenight': False, 'lunch': True, 'dinner': True, 'brunch': False, 'breakfast': False}"
 "{'dessert': None, 'latenight': False, 'lunch': True, 'dinner': True, 'brunch': None, 'breakfast': False}"
 "{'dessert': None, 'latenight': None, 'lunch': None, 'dinner': True, 'brunch': None, 'breakfast': None}"
 "{'dessert': False, 'latenight': False, 'lunch': False, 'dinner': False, 'brunch': True, 'breakfast': False}"
 "{'dessert': False, 'latenight': True, 'lunch': False, 'dinner': False, 'brunch': False, 'breakfast': False}"
 "{'dessert': False, 'latenight': True, 'lunch': False, 'dinner': True, 'brunch': False, 'breakfast': False}"
 "{'dessert': False, 'latenight': False, 'lunch': False, 'dinner': True, 'brunch': False, 'breakfast': False}"
 "{'dessert': True, 'latenight': False, 'lunch': True, 'dinner': False, 'brunch': True, 'breakfast': True}"
 "{'dessert': None, 'latenight': None, 'lunch': True, 'dinner': True, 'brunch': False, 'breakfast': False}"
 "{'dessert': False, 'latenight': False, 'lunch': True, 'dinner': False, 'brunch': True, 'breakfast': True}"
 "{'dessert': None, 'latenight': None, 'lunch': True, 'dinner': True, 'brunch': True, 'breakfast': None}"
 "{u'breakfast': False, u'brunch': False, u'lunch': True, u'dinner': None, u'latenight': None, u'dessert': False}"
 "{u'breakfast': False, u'brunch': False, u'lunch': False, u'dinner': True, u'latenight': False, u'dessert': None}"
 "{'dessert': None, 'latenight': False, 'lunch': None, 'dinner': True, 'brunch': False, 'breakfast': False}"
 "{'dessert': False, 'latenight': False, 'lunch': True, 'dinner': None, 'brunch': False, 'breakfast': False}"

In [42]:
special_attribute = 'attributes.RestaurantsPriceRange2'
bool_attributes = [
    'attributes.ByAppointmentOnly',
    'attributes.BusinessAcceptsCreditCards',
    'attributes.BikeParking',
    'attributes.RestaurantsTakeOut',
    'attributes.RestaurantsDelivery',
    'attributes.Caters',
    'attributes.WheelchairAccessible',
    'attributes.HappyHour',
    'attributes.OutdoorSeating',
    'attributes.HasTV',
    'attributes.RestaurantsReservations',
    'attributes.DogsAllowed',
    'attributes.GoodForKids',
    'attributes.RestaurantsTableService',
    'attributes.RestaurantsGoodForGroups',
    'attributes.BusinessAcceptsBitcoin'
]
list_attributes = [
    'attributes.WiFi',
    'attributes.Alcohol',
    'attributes.RestaurantsAttire',
    'attributes.NoiseLevel'
]
dict_attributes = [
    'attributes.BusinessParking',
    'attributes.Ambience',
    'attributes.GoodForMeal'
]

In [43]:
pricing_remap = {'1': '$', '2': '$$', '3': '$$$', '4': '$$$$', pd.NA: 'None'}
df_business_cp4[special_attribute] = df_business_cp4[special_attribute].replace(pricing_remap)
df_business_cp4[special_attribute]

0         None
1         None
2           $$
3            $
4         None
          ...
150341     $$$
150342      $$
150343       $
150344    $$$$
150345       $
Name: attributes.RestaurantsPriceRange2, Length: 150346, dtype: object

In [44]:
df_business_cp4[special_attribute].value_counts()

attributes.RestaurantsPriceRange2
None    65066
$$      48581
$       28840
$$$      6667
$$$$     1192
Name: count, dtype: int64

In [45]:
bool_remap = {'True': True, 'False': False, np.nan: pd.NA, 'None': pd.NA}
for item in bool_attributes:
    df_business_cp4[item] = df_business_cp4[item].replace(bool_remap)
df_business_cp4[bool_attributes] = df_business_cp4[bool_attributes].astype('boolean')

In [46]:

list_remap = {
    np.nan: pd.NA,
    "u'none'": 'None',
    'none': 'None',
    "u'no'": 'No',
    "'no'": 'No',
    "u'free'": 'Free',
    "'free'": 'Free',
    "u'paid'": 'Paid',
    "'paid'": 'Paid',
    "'none'": 'none',
    "u'full_bar'": 'Full Bar',
    "'full_bar'": 'Full Bar',
    "u'beer_and_wine'": 'Beer and Wine',
     "'beer_and_wine'": 'Beer and Wine',
    "u'casual'": 'Casual',
    "'casual'": 'Casual',
    "u'dressy'": 'Dressy',
    "'dressy'": 'Dressy',
    "u'formal'": 'Formal',
    "'formal'": 'Formal',
    "u'quiet'": 'Quiet',
    "'quiet'": 'Quiet',
    "u'average'": 'Average',
    "'average'": 'Average',
    "u'loud'": 'Loud',
    "'loud'": 'Loud',
    "u'very_loud'": 'Very Loud',
    "'very_loud'": 'Very Loud'
}
df_business_cp4[list_attributes] = df_business_cp4[list_attributes].replace(list_remap)
df_business_cp4[list_attributes]

,attributes.WiFi,attributes.Alcohol,attributes.RestaurantsAttire,attributes.NoiseLevel
0,<NA>,<NA>,<NA>,<NA>
1,<NA>,<NA>,<NA>,<NA>
2,No,<NA>,<NA>,<NA>
3,Free,None,<NA>,<NA>
4,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...
150341,<NA>,<NA>,<NA>,<NA>
150342,No,<NA>,<NA>,<NA>
150343,<NA>,<NA>,<NA>,<NA>
150344,<NA>,<NA>,<NA>,<NA>
150345,Free,<NA>,<NA>,<NA>

In [47]:
for item in list_attributes:
    print(df_business_cp4[item].unique())

[<NA> 'No' 'Free' 'None' 'Paid']
[<NA> 'None' 'Full Bar' 'none' 'Beer and Wine']
[<NA> 'Casual' 'Formal' 'Dressy' 'None']
[<NA> 'Average' 'Quiet' 'Loud' 'Very Loud' 'None']

In [48]:
for col in dict_attributes:
    print(df_business_cp4[col].unique())

[nan
 "{'garage': False, 'street': False, 'validated': False, 'lot': True, 'valet': False}"
 "{'garage': False, 'street': True, 'validated': False, 'lot': False, 'valet': False}"
 "{'garage': None, 'street': None, 'validated': None, 'lot': True, 'valet': False}"
 'None'
 "{'garage': False, 'street': False, 'validated': False, 'lot': False, 'valet': False}"
 "{'garage': None, 'street': False, 'validated': None, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': None, u'street': True, u'lot': False, u'validated': None}"
 "{'garage': False, 'street': True, 'validated': False, 'lot': True, 'valet': False}"
 "{'garage': True, 'street': False, 'validated': False, 'lot': False, 'valet': False}"
 "{'garage': True, 'street': False, 'validated': True, 'lot': False, 'valet': True}"
 "{'garage': None, 'street': True, 'validated': None, 'lot': False, 'valet': False}"
 "{'garage': False, 'street': True, 'validated': True, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': False, u'lot': True, u'validated': False}"
 "{u'valet': False, u'garage': False, u'street': None, u'lot': True, u'validated': False}"
 "{'garage': True, 'street': True, 'validated': False, 'lot': False, 'valet': False}"
 "{'garage': None, 'street': False, 'validated': None, 'lot': False, 'valet': False}"
 "{'garage': False, 'street': False, 'validated': False, 'lot': None, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': None, u'lot': None, u'validated': None}"
 "{'garage': False, 'street': False, 'validated': True, 'lot': False, 'valet': False}"
 "{u'valet': False, u'garage': None, u'street': None, u'lot': True, u'validated': None}"
 "{u'valet': False, u'garage': True, u'street': False, u'lot': True, u'validated': False}"
 "{u'valet': False, u'garage': False, u'street': False, u'lot': False, u'validated': False}"
 "{u'valet': False, u'garage': None, u'street': False, u'lot': None, u'validated': False}"
 "{'garage': True, 'street': False, 'validated': False, 'lot': True, 'valet': False}"
 "{'garage': False, 'street': True, 'validated': False, 'lot': None, 'valet': False}"
 "{'garage': False, 'street': True, 'validated': False, 'lot': False, 'valet': True}"
 "{'garage': False, 'street': False, 'validated': False, 'lot': True, 'valet': True}"
 "{'garage': False, 'street': None, 'validated': False, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': True, u'street': True, u'lot': False, u'validated': False}"
 "{'garage': False, 'street': False, 'validated': None, 'lot': True, 'valet': False}"
 "{'garage': None, 'street': True, 'validated': None, 'lot': None, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': True, u'lot': False, u'validated': False}"
 "{'garage': False, 'street': None, 'validated': False, 'lot': None, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': None, u'lot': None, u'validated': False}"
 "{'garage': True, 'street': True, 'validated': True, 'lot': True, 'valet': True}"
 "{u'valet': False, u'garage': False, u'street': True, u'lot': True, u'validated': False}"
 "{'garage': True, 'street': True, 'validated': False, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': None, u'street': None, u'lot': None, u'validated': False}"
 "{'garage': None, 'street': True, 'validated': False, 'lot': None, 'valet': False}"
 "{'garage': False}"
 "{'garage': True, 'street': True, 'validated': True, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': False, u'lot': True, u'validated': None}"
 "{u'valet': True, u'garage': True, u'street': False, u'lot': False, u'validated': False}"
 "{u'valet': False, u'garage': False, u'street': None, u'lot': True, u'validated': None}"
 "{'garage': None, 'street': True, 'validated': False, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': True, u'lot': None, u'validated': False}"
 "{'garage': None, 'street': None, 'validated': None, 'lot': False, 'valet': False}"
 "{'garage': False, 'street': False, 'validated': False, 'lot': False, 'valet': True}"
 "{'garage': False, 'street': None, 'validated': None, 'lot': None, 'valet': False}"
 "{'garage': False, 'street': True, 'validated': False, 'lot': True, 'valet': True}"
 "{'garage': True, 'street': None, 'validated': None, 'lot': None, 'valet': False}"
 "{'garage': False, 'street': False, 'validated': None, 'lot': False, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': False, u'lot': None, u'validated': False}"
 "{'garage': None, 'street': True, 'validated': False, 'lot': False, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': True, u'lot': False, u'validated': None}"
 "{'garage': True, 'street': False, 'validated': False, 'lot': False, 'valet': True}"
 "{'garage': True, 'street': None, 'validated': False, 'lot': None, 'valet': False}"
 "{u'valet': False, u'garage': None, u'street': True, u'lot': None, u'validated': False}"
 "{'garage': None, 'street': False, 'validated': False, 'lot': False, 'valet': False}"
 "{u'valet': False, u'garage': None, u'street': True, u'lot': None, u'validated': None}"
 "{'garage': None, 'street': False, 'validated': False, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': None, u'street': None, u'lot': False, u'validated': None}"
 "{u'valet': False, u'garage': False, u'street': True, u'lot': True, u'validated': True}"
 "{'garage': True, 'street': None, 'validated': False, 'lot': False, 'valet': False}"
 "{'garage': True, 'street': True, 'validated': False, 'lot': False, 'valet': True}"
 "{'garage': True, 'street': False, 'validated': True, 'lot': False, 'valet': False}"
 "{u'valet': False, u'garage': True, u'street': True, u'lot': None, u'validated': False}"
 "{u'valet': False, u'garage': True, u'street': None, u'lot': None, u'validated': None}"
 "{'garage': False, 'street': False, 'validated': None, 'lot': None, 'valet': False}"
 "{'garage': False, 'street': None, 'validated': None, 'lot': True, 'valet': False}"
 "{'garage': False, 'street': None, 'validated': False, 'lot': False, 'valet': False}"
 "{'garage': None, 'street': None, 'validated': False, 'lot': None, 'valet': False}"
 "{u'valet': False, u'garage': None, u'street': None, u'lot': True, u'validated': False}"
 "{u'valet': False, u'garage': None, u'street': False, u'lot': True, u'validated': None}"
 "{'garage': False, 'street': True, 'validated': True, 'lot': False, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': True, u'lot': None, u'validated': None}"
 "{u'valet': False, u'garage': None, u'street': True, u'lot': False, u'validated': False}"
 "{'garage': True, 'street': True, 'validated': True, 'lot': False, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': False, u'lot': None, u'validated': None}"
 "{'garage': False, 'street': True, 'validated': True, 'lot': False, 'valet': True}"
 "{'garage': None, 'street': True, 'validated': None, 'lot': True, 'valet': False}"
 "{'garage': None, 'street': None, 'validated': False, 'lot': False, 'valet': False}"
 "{'garage': None, 'street': False, 'validated': False, 'lot': None, 'valet': False}"
 "{'garage': True, 'street': True, 'validated': None, 'lot': False, 'valet': False}"
 "{'garage': None, 'street': None, 'validated': False, 'lot': True, 'valet': False}"
 "{'garage': False, 'street': False, 'validated': True, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': True, u'street': False, u'lot': None, u'validated': None}"
 "{'garage': True, 'street': False, 'validated': False, 'lot': True, 'valet': True}"
 "{u'garage': False, u'street': False, u'validated': False, u'lot': True, u'valet': False}"
 "{'garage': None, 'street': False, 'validated': None, 'lot': None, 'valet': False}"
 "{u'valet': False, u'garage': None, u'street': False, u'lot': True, u'validated': False}"
 "{'garage': True, 'street': True, 'validated': False, 'lot': True, 'valet': True}"
 "{u'valet': False, u'garage': True, u'street': False, u'lot': True, u'validated': None}"
 "{u'valet': True, u'garage': False, u'street': False, u'lot': False, u'validated': False}"
 "{'garage': True, 'street': False, 'validated': True, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': True, u'street': False, u'lot': False, u'validated': False}"
 "{'valet': False, 'garage': False, 'street': False, 'lot': False, 'validated': False}"
 "{u'valet': False, u'garage': False, u'street': None, u'lot': False, u'validated': False}"
 "{u'valet': True, u'garage': False, u'street': True, u'lot': True, u'validated': False}"
 "{u'valet': False, u'garage': None, u'street': None, u'lot': False, u'validated': False}"
 "{u'valet': False, u'garage': True, u'street': None, u'lot': False, u'validated': None}"
 "{u'valet': False, u'garage': True, u'street': True, u'lot': False, u'validated': None}"
 "{'garage': False, 'street': None, 'validated': None, 'lot': False, 'valet': False}"
 "{'garage': True, 'street': None, 'validated': None, 'lot': False, 'valet': False}"
 "{u'valet': False, u'garage': True, u'street': True, u'lot': None, u'validated': None}"
 "{'garage': False, 'street': True, 'validated': True, 'lot': True, 'valet': True}"
 "{'garage': True, 'street': True, 'validated': True, 'lot': False, 'valet': True}"
 "{u'valet': True, u'garage': True, u'street': True, u'lot': True, u'validated': True}"
 "{u'valet': False, u'garage': True, u'street': True, u'lot': True, u'validated': False}"
 "{'valet': False, 'garage': False, 'street': False, 'lot': True, 'validated': False}"
 "{u'valet': False, u'garage': True, u'street': False, u'lot': None, u'validated': False}"
 "{u'valet': False, u'garage': True, u'street': None, u'lot': None, u'validated': False}"
 "{u'valet': False, u'garage': None, u'street': False, u'lot': False, u'validated': False}"
 "{u'valet': False, u'garage': False, u'street': None, u'lot': False, u'validated': None}"
 "{'garage': False, 'street': False, 'validated': True, 'lot': False, 'valet': True}"
 "{'garage': False, 'street': False, 'validated': True, 'lot': True, 'valet': True}"
 "{u'valet': False, u'garage': True, u'street': None, u'lot': False, u'validated': False}"
 "{u'valet': False, u'garage': False, u'street': False, u'lot': False, u'validated': True}"
 "{'garage': False, 'street': True, 'validated': None, 'lot': True, 'valet': False}"
 "{'garage': False, 'street': True, 'validated': None, 'lot': False, 'valet': False}"
 "{'garage': True, 'street': False, 'validated': False, 'lot': None, 'valet': False}"
 "{u'valet': False, u'garage': None, u'street': False, u'lot': None, u'validated': None}"
 "{u'valet': False, u'garage': None, u'street': True, u'lot': True, u'validated': False}"
 "{'garage': True, 'street': None, 'validated': False, 'lot': True, 'valet': False}"
 "{'garage': True, 'street': False, 'validated': True, 'lot': True, 'valet': True}"
 "{u'valet': False, u'garage': None, u'street': False, u'lot': False, u'validated': None}"
 "{u'valet': True, u'garage': False, u'street': False, u'lot': False, u'validated': True}"
 "{'garage': False, 'street': True, 'validated': None, 'lot': None, 'valet': False}"
 "{u'valet': False, u'garage': True, u'street': None, u'lot': True, u'validated': None}"
 "{u'valet': True, u'garage': True, u'street': True, u'lot': False, u'validated': False}"
 "{u'valet': True, u'garage': False, u'street': False, u'lot': True, u'validated': False}"
 "{u'valet': True, u'garage': False, u'street': True, u'lot': False, u'validated': False}"
 "{'garage': False, 'street': None, 'validated': False, 'lot': None, 'valet': True}"
 "{u'valet': False, u'garage': None, u'street': True, u'lot': True, u'validated': None}"
 "{'valet': False}"
 "{'valet': False, 'garage': False, 'street': True, 'lot': False, 'validated': False}"
 "{u'valet': False, u'garage': True, u'street': False, u'lot': False, u'validated': True}"
 "{u'valet': False, u'garage': True, u'street': True, u'lot': True, u'validated': None}"
 "{'garage': False, 'validated': False, 'street': False, 'lot': False, 'valet': False}"
 "{u'garage': False, u'street': True, u'validated': False, u'lot': True, u'valet': False}"
 "{'garage': True, 'street': True, 'validated': False, 'lot': None, 'valet': False}"
 "{u'valet': False, u'garage': True, u'street': None, u'lot': True, u'validated': False}"
 "{u'garage': False, u'street': True, u'validated': False, u'lot': False, u'valet': False}"
 "{'garage': True, 'street': True, 'validated': None, 'lot': None, 'valet': False}"
 "{'garage': True, 'street': False, 'validated': None, 'lot': None, 'valet': False}"
 "{u'valet': True, u'garage': False, u'street': True, u'lot': False, u'validated': True}"
 "{'garage': True, 'street': None, 'validated': None, 'lot': True, 'valet': False}"
 '{}'
 "{u'valet': False, u'garage': False, u'street': True, u'lot': True, u'validated': None}"
 "{'garage': True, 'street': True, 'validated': None, 'lot': True, 'valet': False}"
 "{u'valet': False, u'garage': False, u'street': False, u'lot': False, u'validated': None}"
 "{'garage': True, 'street': False, 'validated': None, 'lot': True, 'valet': False}"
 "{u'valet': True, u'garage': True, u'street': True, u'lot': True, u'validated': False}"
 "{u'valet': False, u'garage': True, u'street': True, u'lot': False, u'validated': True}"
 "{u'valet': False, u'garage': False, u'street': True, u'lot': False, u'validated': True}"
 "{u'valet': False, u'garage': True, u'street': False, u'lot': False, u'validated': None}"
 "{u'valet': True, u'garage': True, u'street': False, u'lot': True, u'validated': False}"
 "{u'valet': False, u'garage': False, u'street': False, u'lot': True, u'validated': True}"
 "{u'valet': False, u'garage': None, u'street': True, u'lot': None, u'validated': True}"
 "{u'garage': True, u'street': True, u'validated': False, u'lot': False, u'valet': False}"
 "{'garage': True, 'street': None, 'validated': True, 'lot': True, 'valet': False}"
 "{u'valet': True, u'garage': False, u'street': True, u'lot': True, u'validated': True}"
 "{u'garage': False, u'street': False, u'validated': False, u'lot': False, u'valet': False}"
 "{u'valet': False, u'garage': True, u'street': True, u'lot': True, u'validated': True}"
 "{u'garage': True, u'street': False, u'validated': False, u'lot': False, u'valet': True}"]
[nan 'None'
 "{'romantic': False, 'intimate': False, 'touristy': False, 'hipster': False, 'divey': False, 'classy': False, 'trendy': False, 'upscale': False, 'casual': False}"
 ...
 "{'touristy': False, 'hipster': None, 'romantic': False, 'divey': None, 'intimate': None, 'trendy': False, 'upscale': None, 'classy': True, 'casual': None}"
 "{'touristy': False, 'hipster': None, 'romantic': False, 'intimate': None, 'trendy': True, 'upscale': False, 'classy': False, 'casual': True}"
 "{'touristy': None, 'hipster': False, 'romantic': False, 'divey': None, 'intimate': False, 'trendy': False, 'upscale': None, 'classy': None, 'casual': True}"]
[nan
 "{'dessert': False, 'latenight': False, 'lunch': False, 'dinner': False, 'brunch': False, 'breakfast': False}"
 "{'dessert': False, 'latenight': False, 'lunch': True, 'dinner': False, 'brunch': False, 'breakfast': False}"
 "{'dessert': True, 'latenight': None, 'lunch': None, 'dinner': True, 'brunch': None, 'breakfast': None}"
 "{'dessert': False, 'latenight': False, 'lunch': True, 'dinner': True, 'brunch': False, 'breakfast': False}"
 "{'dessert': None, 'latenight': False, 'lunch': True, 'dinner': True, 'brunch': None, 'breakfast': False}"
 "{'dessert': None, 'latenight': None, 'lunch': None, 'dinner': True, 'brunch': None, 'breakfast': None}"
 "{'dessert': False, 'latenight': False, 'lunch': False, 'dinner': False, 'brunch': True, 'breakfast': False}"
 "{'dessert': False, 'latenight': True, 'lunch': False, 'dinner': False, 'brunch': False, 'breakfast': False}"
 "{'dessert': False, 'latenight': True, 'lunch': False, 'dinner': True, 'brunch': False, 'breakfast': False}"
 "{'dessert': False, 'latenight': False, 'lunch': False, 'dinner': True, 'brunch': False, 'breakfast': False}"
 "{'dessert': True, 'latenight': False, 'lunch': True, 'dinner': False, 'brunch': True, 'breakfast': True}"
 "{'dessert': None, 'latenight': None, 'lunch': True, 'dinner': True, 'brunch': False, 'breakfast': False}"
 "{'dessert': False, 'latenight': False, 'lunch': True, 'dinner': False, 'brunch': True, 'breakfast': True}"
 "{'dessert': None, 'latenight': None, 'lunch': True, 'dinner': True, 'brunch': True, 'breakfast': None}"
 "{u'breakfast': False, u'brunch': False, u'lunch': True, u'dinner': None, u'latenight': None, u'dessert': False}"
 "{u'breakfast': False, u'brunch': False, u'lunch': False, u'dinner': True, u'latenight': False, u'dessert': None}"
 "{'dessert': None, 'latenight': False, 'lunch': None, 'dinner': True, 'brunch': False, 'breakfast': False}"
 "{'dessert': False, 'latenight': False, 'lunch': True, 'dinner': None, 'brunch': False, 'breakfast': False}"
 "{u'breakfast': False, u'brunch': None, u'lunch': True, u'dinner': True, u'latenight': False, u'dessert': False}"
 "{'dessert': None, 'latenight': True, 'lunch': True, 'dinner': True, 'brunch': None, 'breakfast': False}"
 "{u'breakfast': False, u'brunch': False, u'lunch': True, u'dinner': True, u'latenight': False, u'dessert': None}"
 "{'dessert': False, 'latenight': True, 'lunch': True, 'dinner': True, 'brunch': False, 'breakfast': False}"
 "{'dessert': False, 'latenight': False, 'lunch': False, 'dinner': False, 'brunch': False, 'breakfast': True}"
 "{'dessert': False, 'latenight': False, 'lunch': False, 'dinner': False, 'brunch': True, 'breakfast': True}"
 "{'dessert': None, 'latenight': False, 'lunch': True, 'dinner': True, 'brunch': None, 'breakfast': None}"
 "{'dessert': None, 'latenight': False, 'lunch': True, 'dinner': True, 'brunch': False, 'breakfast': None}"
 "{'dessert': True, 'latenight': None, 'lunch': True, 'dinner': True, 'brunch': True, 'breakfast': None}"
 "{'dessert': False, 'latenight': False, 'lunch': True, 'dinner': True, 'brunch': True, 'breakfast': False}"
 "{'dessert': False, 'latenight': None, 'lunch': None, 'dinner': True, 'brunch': None, 'breakfast': None}"
 "{'dessert': False, 'latenight': False, 'lunch': True, 'dinner': False, 'brunch': False, 'breakfast': True}"
 "{'dessert': None, 'latenight': True, 'lunch': None, 'dinner': True, 'brunch': None, 'breakfast': False}"
 "{u'breakfast': True, u'brunch': None, u'lunch': None, u'dinner': None, u'latenight': False, u'dessert': False}"
 "{u'breakfast': None, u'brunch': False, u'lunch': True, u'dinner': True, u'latenight': False, u'dessert': False}"
 "{u'breakfast': None, u'brunch': None, u'lunch': None, u'dinner': True, u'latenight': None, u'dessert': None}"
 "{'dessert': None, 'latenight': None, 'lunch': None, 'dinner': None, 'brunch': False, 'breakfast': None}"
 "{'dessert': True, 'latenight': False, 'lunch': True, 'dinner': True, 'brunch': False, 'breakfast': True}"
 "{'dessert': None, 'latenight': None, 'lunch': True, 'dinner': True, 'brunch': None, 'breakfast': False}"
 "{'dessert': True, 'latenight': False, 'lunch': True, 'dinner': True, 'brunch': None, 'breakfast': None}"
 "{'dessert': None, 'latenight': False, 'lunch': True, 'dinner': True, 'brunch': False, 'breakfast': False}"
 "{'dessert': None, 'latenight': None, 'lunch': True, 'dinner': True, 'brunch': None, 'breakfast': None}"
 "{u'breakfast': False, u'brunch': False, u'lunch': None, u'dinner': True, u'latenight': None, u'dessert': False}"
 "{'dessert': False, 'latenight': None, 'lunch': True, 'dinner': True, 'brunch': False, 'breakfast': False}"
 'None'
 "{'dessert': False, 'latenight': False, 'lunch': True, 'dinner': True, 'brunch': False, 'breakfast': True}"
 "{'dessert': None, 'latenight': None, 'lunch': True, 'dinner': None, 'brunch': True, 'breakfast': True}"
 "{'dessert': False, 'latenight': False, 'lunch': True, 'dinner': None, 'brunch': None, 'breakfast': True}"
 "{'dessert': False, 'latenight': False, 'lunch': None, 'dinner': True, 'brunch': False, 'breakfast': False}"

### Creating backup

In [49]:
df_business_cp5 = df_business_cp4.copy()

### Cleaning up "Open" column to True/False instead of 1/0

In [50]:
df_business_cp5['is_open'] = df_business_cp5['is_open'].astype('bool')

### Creating Open and Closed dates from the review dataset
Dependency on yelp_review dataset to be cleaned

In [51]:
path_review = '/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/clean/yelp_review_CLEAN.csv'

In [52]:
df_review = lib.read_data(path_review)

PortfolioLogger.lib.tools: INFO: Encoding: ascii
PortfolioLogger.lib.tools: INFO: Stripping whitespaces from yelp_review_CLEAN.csv
PortfolioLogger.lib.performance: INFO: <function read_data at 0x10f9a1800> took 2.075 mins to complete.

In [53]:
df_review

,Unnamed: 0,review_id,user_id,business_id,stars,useful,funny,cool,date
0,0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,2018-07-07 22:09:11
1,1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5.0,1,0,1,2012-01-03 15:28:18
2,2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,0,0,0,2014-02-05 20:30:30
3,3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,2015-01-04 00:01:03
4,4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,1,0,1,2017-01-14 20:54:15
...,...,...,...,...,...,...,...,...,...
6990275,6990275,H0RIamZu0B0Ei0P4aeh3sQ,qskILQ3k0I_qcCMI-k6_QQ,jals67o91gcrD4DC81Vk6w,5.0,1,2,1,2014-12-17 21:45:20
6990276,6990276,shTPgbgdwTHSuU67mGCmZQ,Zo0th2m8Ez4gLSbHftiQvg,2vLksaMmSEcGbjI5gywpZA,5.0,2,1,2,2021-03-31 16:55:10
6990277,6990277,YNfNhgZlaaCO5Q_YJR4rEw,mm6E4FbCMwJmb7kPDZ5v2Q,R1khUUxidqfaJmcpmGd4aw,4.0,1,0,0,2019-12-30 03:56:30
6990278,6990278,i-I4ZOhoX70Nw5H0FwrQUA,YwAMC-jvZ1fvEUum6QkEkw,Rr9kKArrMhSLVE9a53q-aA,5.0,1,0,0,2022-01-19 18:59:27
6990279,6990279,RwcKOdEuLRHNJe4M9-qpqg,6JehEvdoCvZPJ_XIxnzIIw,VAeEXLbEcI9Emt9KGYq9aA,3.0,10,3,7,2018-01-02 22:50:47

In [54]:
df_review

,Unnamed: 0,review_id,user_id,business_id,stars,useful,funny,cool,date
0,0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,2018-07-07 22:09:11
1,1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5.0,1,0,1,2012-01-03 15:28:18
2,2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,0,0,0,2014-02-05 20:30:30
3,3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,2015-01-04 00:01:03
4,4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,1,0,1,2017-01-14 20:54:15
...,...,...,...,...,...,...,...,...,...
6990275,6990275,H0RIamZu0B0Ei0P4aeh3sQ,qskILQ3k0I_qcCMI-k6_QQ,jals67o91gcrD4DC81Vk6w,5.0,1,2,1,2014-12-17 21:45:20
6990276,6990276,shTPgbgdwTHSuU67mGCmZQ,Zo0th2m8Ez4gLSbHftiQvg,2vLksaMmSEcGbjI5gywpZA,5.0,2,1,2,2021-03-31 16:55:10
6990277,6990277,YNfNhgZlaaCO5Q_YJR4rEw,mm6E4FbCMwJmb7kPDZ5v2Q,R1khUUxidqfaJmcpmGd4aw,4.0,1,0,0,2019-12-30 03:56:30
6990278,6990278,i-I4ZOhoX70Nw5H0FwrQUA,YwAMC-jvZ1fvEUum6QkEkw,Rr9kKArrMhSLVE9a53q-aA,5.0,1,0,0,2022-01-19 18:59:27
6990279,6990279,RwcKOdEuLRHNJe4M9-qpqg,6JehEvdoCvZPJ_XIxnzIIw,VAeEXLbEcI9Emt9KGYq9aA,3.0,10,3,7,2018-01-02 22:50:47

In [55]:
df_business_cp5.columns

Index(['business_id', 'name', 'address', 'city', 'state', 'postal_code',
       'latitude', 'longitude', 'stars', 'review_count', 'is_open',
       'categories', 'attributes.ByAppointmentOnly',
       'attributes.BusinessAcceptsCreditCards', 'attributes.BikeParking',
       'attributes.RestaurantsPriceRange2', 'attributes.RestaurantsTakeOut',
       'attributes.RestaurantsDelivery', 'attributes.Caters',
       'attributes.WiFi', 'attributes.BusinessParking',
       'attributes.WheelchairAccessible', 'attributes.HappyHour',
       'attributes.OutdoorSeating', 'attributes.HasTV',
       'attributes.RestaurantsReservations', 'attributes.DogsAllowed',
       'attributes.Alcohol', 'attributes.GoodForKids',
       'attributes.RestaurantsAttire', 'attributes.Ambience',
       'attributes.RestaurantsTableService',
       'attributes.RestaurantsGoodForGroups', 'attributes.NoiseLevel',
       'attributes.GoodForMeal', 'attributes.BusinessAcceptsBitcoin'],
      dtype='object')

In [56]:
df_review = df_review[['business_id', 'date']]

In [57]:
df_review

                    business_id                 date
0        XQfwVwDr-v0ZS3_CbbE5Xw  2018-07-07 22:09:11
1        7ATYjTIgM3jUlt4UM3IypQ  2012-01-03 15:28:18
2        YjUWPpI6HXG530lwP-fb2A  2014-02-05 20:30:30
3        kxX2SOes4o-D3ZQBkiMRfA  2015-01-04 00:01:03
4        e4Vwtrqf-wpJfwesgvdgxQ  2017-01-14 20:54:15
...                         ...                  ...
6990275  jals67o91gcrD4DC81Vk6w  2014-12-17 21:45:20
6990276  2vLksaMmSEcGbjI5gywpZA  2021-03-31 16:55:10
6990277  R1khUUxidqfaJmcpmGd4aw  2019-12-30 03:56:30
6990278  Rr9kKArrMhSLVE9a53q-aA  2022-01-19 18:59:27
6990279  VAeEXLbEcI9Emt9KGYq9aA  2018-01-02 22:50:47

[6990280 rows x 2 columns]

In [58]:
review_ranges = df_review.groupby("business_id")['date'].agg(
    open_date='min',
    close_date='max'
).reset_index()

merged = df_business_cp5[['business_id', 'is_open']].merge(
    review_ranges,
    on='business_id',
    how='left'
)

# Assign NaT to businesses that are still open
merged['close_date'] = merged.apply(
    lambda r: pd.NaT if r['is_open'] == 1 else r['close_date'],
    axis=1
)

In [59]:
df_business_cp5 = df_business_cp5.merge(merged[['business_id', 'open_date', 'close_date']], on='business_id', how='left')

In [60]:
df_business_cp5['open_date'] = pd.to_datetime(df_business_cp5['open_date'])
df_business_cp5['close_date'] = pd.to_datetime(df_business_cp5['close_date'])

In [61]:
columns = list(df_business_cp5.columns)
columns

['business_id',
 'name',
 'address',
 'city',
 'state',
 'postal_code',
 'latitude',
 'longitude',
 'stars',
 'review_count',
 'is_open',
 'categories',
 'attributes.ByAppointmentOnly',
 'attributes.BusinessAcceptsCreditCards',
 'attributes.BikeParking',
 'attributes.RestaurantsPriceRange2',
 'attributes.RestaurantsTakeOut',
 'attributes.RestaurantsDelivery',
 'attributes.Caters',
 'attributes.WiFi',
 'attributes.BusinessParking',
 'attributes.WheelchairAccessible',
 'attributes.HappyHour',
 'attributes.OutdoorSeating',
 'attributes.HasTV',
 'attributes.RestaurantsReservations',
 'attributes.DogsAllowed',
 'attributes.Alcohol',
 'attributes.GoodForKids',
 'attributes.RestaurantsAttire',
 'attributes.Ambience',
 'attributes.RestaurantsTableService',
 'attributes.RestaurantsGoodForGroups',
 'attributes.NoiseLevel',
 'attributes.GoodForMeal',
 'attributes.BusinessAcceptsBitcoin',
 'open_date',
 'close_date']

In [62]:
reordered_columns = ['business_id',
 'name',
 'address',
 'city',
 'state',
 'postal_code',
 'latitude',
 'longitude',
 'stars',
 'review_count',
 'is_open',
 'open_date',
 'close_date',
 'categories',
 'attributes.ByAppointmentOnly',
 'attributes.BusinessAcceptsCreditCards',
 'attributes.BikeParking',
 'attributes.RestaurantsPriceRange2',
 'attributes.RestaurantsTakeOut',
 'attributes.RestaurantsDelivery',
 'attributes.Caters',
 'attributes.WiFi',
 'attributes.BusinessParking',
 'attributes.WheelchairAccessible',
 'attributes.HappyHour',
 'attributes.OutdoorSeating',
 'attributes.HasTV',
 'attributes.RestaurantsReservations',
 'attributes.DogsAllowed',
 'attributes.Alcohol',
 'attributes.GoodForKids',
 'attributes.RestaurantsAttire',
 'attributes.Ambience',
 'attributes.RestaurantsTableService',
 'attributes.RestaurantsGoodForGroups',
 'attributes.NoiseLevel',
 'attributes.GoodForMeal',
 'attributes.BusinessAcceptsBitcoin',]

In [63]:
df_business_cp5 = df_business_cp5[reordered_columns]

In [64]:
df_business_cp5

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,attributes.DogsAllowed,attributes.Alcohol,attributes.GoodForKids,attributes.RestaurantsAttire,attributes.Ambience,attributes.RestaurantsTableService,attributes.RestaurantsGoodForGroups,attributes.NoiseLevel,attributes.GoodForMeal,attributes.BusinessAcceptsBitcoin
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,...,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,NaN,<NA>
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,...,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,NaN,<NA>
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,...,False,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,NaN,<NA>
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,...,<NA>,None,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,NaN,<NA>
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,...,<NA>,<NA>,True,<NA>,NaN,<NA>,<NA>,<NA>,NaN,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150341,IUQopTMmYQG-qRtBk-8QnA,Binh's Nails,3388 Gateway Blvd,Edmonton,AB,T6J 5H2,53.468419,-113.492054,3.0,13,...,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,NaN,<NA>
150342,c8GjPIOTGVmIemT7j5_SyQ,Wild Birds Unlimited,2813 Bransford Ave,Nashville,TN,37204,36.115118,-86.766925,4.0,5,...,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,NaN,<NA>
150343,_QAMST-NrQobXduilWEqSw,Claire's Boutique,"6020 E 82nd St, Ste 46",Indianapolis,IN,46250,39.908707,-86.065088,3.5,8,...,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,NaN,<NA>
150344,mtGm22y5c2UHNXDFAjaPNw,Cyclery & Fitness Center,2472 Troy Rd,Edwardsville,IL,62025,38.782351,-89.950558,4.0,24,...,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,NaN,<NA>
150345,jV_XOycEzSlTx-65W906pg,Sic Ink,238 Apollo Beach Blvd,Apollo beach,FL,33572,27.771002,-82.394910,4.5,9,...,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,NaN,False

In [65]:
df_business_cp5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150346 entries, 0 to 150345
Data columns (total 38 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   business_id                            150346 non-null  object
 1   name                                   150346 non-null  object
 2   address                                150346 non-null  object
 3   city                                   150346 non-null  object
 4   state                                  150346 non-null  object
 5   postal_code                            150346 non-null  object
 6   latitude                               150346 non-null  float64
 7   longitude                              150346 non-null  float64
 8   stars                                  150346 non-null  float64
 9   review_count                           150346 non-null  int64
 10  is_open                                150346 non-null  bool
 11  open_date                              150346 non-null  datetime64[ns]
 12  close_date                             30648 non-null   datetime64[ns]
 13  categories                             150243 non-null  object
 14  attributes.ByAppointmentOnly           42299 non-null   boolean
 15  attributes.BusinessAcceptsCreditCards  119692 non-null  boolean
 16  attributes.BikeParking                 72558 non-null   boolean
 17  attributes.RestaurantsPriceRange2      150346 non-null  object
 18  attributes.RestaurantsTakeOut          57752 non-null   boolean
 19  attributes.RestaurantsDelivery         52334 non-null   boolean
 20  attributes.Caters                      40067 non-null   boolean
 21  attributes.WiFi                        56914 non-null   object
 22  attributes.BusinessParking             91085 non-null   object
 23  attributes.WheelchairAccessible        28926 non-null   boolean
 24  attributes.HappyHour                   15169 non-null   boolean
 25  attributes.OutdoorSeating              46920 non-null   boolean
 26  attributes.HasTV                       45065 non-null   boolean
 27  attributes.RestaurantsReservations     44959 non-null   boolean
 28  attributes.DogsAllowed                 18258 non-null   boolean
 29  attributes.Alcohol                     43189 non-null   object
 30  attributes.GoodForKids                 53347 non-null   boolean
 31  attributes.RestaurantsAttire           39255 non-null   object
 32  attributes.Ambience                    44279 non-null   object
 33  attributes.RestaurantsTableService     19967 non-null   boolean
 34  attributes.RestaurantsGoodForGroups    44149 non-null   boolean
 35  attributes.NoiseLevel                  37993 non-null   object
 36  attributes.GoodForMeal                 29087 non-null   object
 37  attributes.BusinessAcceptsBitcoin      17427 non-null   boolean
dtypes: bool(1), boolean(16), datetime64[ns](2), float64(3), int64(1), object(15)
memory usage: 28.8+ MB

## Cleaning States column
### Creating a backup

In [35]:
df_business_cp6 = df_business_cp5.copy()

## So I don't have to reprocess the whole dataset

In [3]:
# df_business_cp6 = lib.read_data(export_clean_directory / 'yelp_business_CLEAN.csv')

PortfolioLogger.lib.tools: INFO: Encoding: utf-8
PortfolioLogger.lib.tools: INFO: Stripping whitespaces from yelp_business_CLEAN.csv
PortfolioLogger.lib.tools: ERROR: Could not strip whitespaces for attributes.ByAppointmentOnly:
Can only use .str accessor with string values!
PortfolioLogger.lib.tools: ERROR: Could not strip whitespaces for attributes.BusinessAcceptsCreditCards:
Can only use .str accessor with string values!
PortfolioLogger.lib.tools: ERROR: Could not strip whitespaces for attributes.BikeParking:
Can only use .str accessor with string values!
PortfolioLogger.lib.tools: ERROR: Could not strip whitespaces for attributes.RestaurantsTakeOut:
Can only use .str accessor with string values!
PortfolioLogger.lib.tools: ERROR: Could not strip whitespaces for attributes.RestaurantsDelivery:
Can only use .str accessor with string values!
PortfolioLogger.lib.tools: ERROR: Could not strip whitespaces for attributes.Caters:
Can only use .str accessor with string values!
PortfolioLogger.lib.tools: ERROR: Could not strip whitespaces for attributes.WheelchairAccessible:
Can only use .str accessor with string values!
PortfolioLogger.lib.tools: ERROR: Could not strip whitespaces for attributes.HappyHour:
Can only use .str accessor with string values!
PortfolioLogger.lib.tools: ERROR: Could not strip whitespaces for attributes.OutdoorSeating:
Can only use .str accessor with string values!
PortfolioLogger.lib.tools: ERROR: Could not strip whitespaces for attributes.HasTV:
Can only use .str accessor with string values!
PortfolioLogger.lib.tools: ERROR: Could not strip whitespaces for attributes.RestaurantsReservations:
Can only use .str accessor with string values!
PortfolioLogger.lib.tools: ERROR: Could not strip whitespaces for attributes.DogsAllowed:
Can only use .str accessor with string values!
PortfolioLogger.lib.tools: ERROR: Could not strip whitespaces for attributes.GoodForKids:
Can only use .str accessor with string values!
PortfolioLogger.lib.tools: ERROR: Could not strip whitespaces for attributes.RestaurantsTableService:
Can only use .str accessor with string values!
PortfolioLogger.lib.tools: ERROR: Could not strip whitespaces for attributes.RestaurantsGoodForGroups:
Can only use .str accessor with string values!
PortfolioLogger.lib.tools: ERROR: Could not strip whitespaces for attributes.BusinessAcceptsBitcoin:
Can only use .str accessor with string values!
PortfolioLogger.lib.performance: INFO: <function read_data at 0x10dba1800> took 18.591 secs to complete.

In [36]:
df_business_cp6

,Unnamed: 0,business_id,name,address,city,state,postal_code,latitude,longitude,stars,...,attributes.DogsAllowed,attributes.Alcohol,attributes.GoodForKids,attributes.RestaurantsAttire,attributes.Ambience,attributes.RestaurantsTableService,attributes.RestaurantsGoodForGroups,attributes.NoiseLevel,attributes.GoodForMeal,attributes.BusinessAcceptsBitcoin
0,0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,...,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150341,150341,IUQopTMmYQG-qRtBk-8QnA,Binh's Nails,3388 Gateway Blvd,Edmonton,AB,T6J 5H2,53.468419,-113.492054,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150342,150342,c8GjPIOTGVmIemT7j5_SyQ,Wild Birds Unlimited,2813 Bransford Ave,Nashville,TN,37204,36.115118,-86.766925,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150343,150343,_QAMST-NrQobXduilWEqSw,Claire's Boutique,"6020 E 82nd St, Ste 46",Indianapolis,IN,46250,39.908707,-86.065088,3.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150344,150344,mtGm22y5c2UHNXDFAjaPNw,Cyclery & Fitness Center,2472 Troy Rd,Edwardsville,IL,62025,38.782351,-89.950558,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150345,150345,jV_XOycEzSlTx-65W906pg,Sic Ink,238 Apollo Beach Blvd,Apollo beach,FL,33572,27.771002,-82.394910,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [37]:
df_business_cp6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150346 entries, 0 to 150345
Data columns (total 39 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   Unnamed: 0                             150346 non-null  int64
 1   business_id                            150346 non-null  object
 2   name                                   150346 non-null  object
 3   address                                145219 non-null  object
 4   city                                   150346 non-null  object
 5   state                                  150346 non-null  object
 6   postal_code                            150273 non-null  object
 7   latitude                               150346 non-null  float64
 8   longitude                              150346 non-null  float64
 9   stars                                  150346 non-null  float64
 10  review_count                           150346 non-null  int64
 11  is_open                                150346 non-null  bool
 12  open_date                              150346 non-null  object
 13  close_date                             30648 non-null   object
 14  categories                             150243 non-null  object
 15  attributes.ByAppointmentOnly           42299 non-null   object
 16  attributes.BusinessAcceptsCreditCards  119692 non-null  object
 17  attributes.BikeParking                 72558 non-null   object
 18  attributes.RestaurantsPriceRange2      85280 non-null   object
 19  attributes.RestaurantsTakeOut          57752 non-null   object
 20  attributes.RestaurantsDelivery         52334 non-null   object
 21  attributes.Caters                      40067 non-null   object
 22  attributes.WiFi                        56864 non-null   object
 23  attributes.BusinessParking             88814 non-null   object
 24  attributes.WheelchairAccessible        28926 non-null   object
 25  attributes.HappyHour                   15169 non-null   object
 26  attributes.OutdoorSeating              46920 non-null   object
 27  attributes.HasTV                       45065 non-null   object
 28  attributes.RestaurantsReservations     44959 non-null   object
 29  attributes.DogsAllowed                 18258 non-null   object
 30  attributes.Alcohol                     27174 non-null   object
 31  attributes.GoodForKids                 53347 non-null   object
 32  attributes.RestaurantsAttire           39217 non-null   object
 33  attributes.Ambience                    43728 non-null   object
 34  attributes.RestaurantsTableService     19967 non-null   object
 35  attributes.RestaurantsGoodForGroups    44149 non-null   object
 36  attributes.NoiseLevel                  37954 non-null   object
 37  attributes.GoodForMeal                 28784 non-null   object
 38  attributes.BusinessAcceptsBitcoin      17427 non-null   object
dtypes: bool(1), float64(3), int64(2), object(33)
memory usage: 43.7+ MB

In [38]:
state_group = df_business_cp6.groupby('state')

In [39]:
states_to_drop = []
for state, data in state_group:
    if len(data['business_id'].unique()) <= 1000:
        states_to_drop.append(state)
    else:
        log.info(f'Valid State: {state}')
states_to_drop

PortfolioLogger.yelp_dataset: INFO: Valid State: AB
PortfolioLogger.yelp_dataset: INFO: Valid State: AZ
PortfolioLogger.yelp_dataset: INFO: Valid State: CA
PortfolioLogger.yelp_dataset: INFO: Valid State: DE
PortfolioLogger.yelp_dataset: INFO: Valid State: FL
PortfolioLogger.yelp_dataset: INFO: Valid State: ID
PortfolioLogger.yelp_dataset: INFO: Valid State: IL
PortfolioLogger.yelp_dataset: INFO: Valid State: IN
PortfolioLogger.yelp_dataset: INFO: Valid State: LA
PortfolioLogger.yelp_dataset: INFO: Valid State: MO
PortfolioLogger.yelp_dataset: INFO: Valid State: NJ
PortfolioLogger.yelp_dataset: INFO: Valid State: NV
PortfolioLogger.yelp_dataset: INFO: Valid State: PA
PortfolioLogger.yelp_dataset: INFO: Valid State: TN

['CO', 'HI', 'MA', 'MI', 'MT', 'NC', 'SD', 'TX', 'UT', 'VI', 'VT', 'WA', 'XMS']

In [41]:
indicies_to_drop = df_business_cp6[df_business_cp6['state'].isin(states_to_drop)].index
indicies_to_drop

Index([  9101,   9126,  10948,  12258,  14416,  29606,  32345,  32536,  34661,
        44088,  48919,  57832,  76352,  88413,  95091,  97813,  98685, 125353,
       126989, 135715, 144012],
      dtype='int64')

In [45]:
df_business_cp6 = df_business_cp6.drop(indicies_to_drop)

In [49]:
df_business_cp6.drop('Unnamed: 0', axis=1, inplace=True)
df_business_cp6

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,attributes.DogsAllowed,attributes.Alcohol,attributes.GoodForKids,attributes.RestaurantsAttire,attributes.Ambience,attributes.RestaurantsTableService,attributes.RestaurantsGoodForGroups,attributes.NoiseLevel,attributes.GoodForMeal,attributes.BusinessAcceptsBitcoin
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,...,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150341,IUQopTMmYQG-qRtBk-8QnA,Binh's Nails,3388 Gateway Blvd,Edmonton,AB,T6J 5H2,53.468419,-113.492054,3.0,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150342,c8GjPIOTGVmIemT7j5_SyQ,Wild Birds Unlimited,2813 Bransford Ave,Nashville,TN,37204,36.115118,-86.766925,4.0,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150343,_QAMST-NrQobXduilWEqSw,Claire's Boutique,"6020 E 82nd St, Ste 46",Indianapolis,IN,46250,39.908707,-86.065088,3.5,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150344,mtGm22y5c2UHNXDFAjaPNw,Cyclery & Fitness Center,2472 Troy Rd,Edwardsville,IL,62025,38.782351,-89.950558,4.0,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150345,jV_XOycEzSlTx-65W906pg,Sic Ink,238 Apollo Beach Blvd,Apollo beach,FL,33572,27.771002,-82.394910,4.5,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

### Get state with the most businesses/reviews to analyze

In [79]:
state_group = df_business_cp6.groupby('state', sort=True)
state_group

In [121]:
print(state_group['business_id'].size().max())
print(state_group['business_id'].size())
print(state_group['review_count'].sum().max())
print(state_group['review_count'].sum())

# state_group.filter(state_group['business_id'].size() == state_group['business_id'].size().max())
# state_group['business_id'].transform('size')
state_group['business_id'].size() == state_group['business_id'].size().max()
state_group['review_count'].sum() == state_group['review_count'].sum().max()

34039
state
AB     5573
AZ     9912
CA     5203
DE     2265
FL    26330
ID     4467
IL     2145
IN    11247
LA     9924
MO    10913
NJ     8536
NV     7715
PA    34039
TN    12056
Name: business_id, dtype: int64
1540790
state
AB     105477
AZ     412639
CA     339637
DE      67370
FL    1119926
ID     152086
IL      49676
IN     472565
LA     743176
MO     483897
NJ     249837
NV     409950
PA    1540790
TN     598195
Name: review_count, dtype: int64

state
AB    False
AZ    False
CA    False
DE    False
FL    False
ID    False
IL    False
IN    False
LA    False
MO    False
NJ    False
NV    False
PA     True
TN    False
Name: review_count, dtype: bool

In [123]:
df_business_cp_PA = df_business_cp6[df_business_cp6['state'] == 'PA']

In [124]:
lib.export_data(EXPORT_DIRECTORY / 'yelp_business_PA.csv', df_business_cp_PA)

PortfolioLogger.lib.tools: INFO: Exporting 1293482 elements (51.50 MB) to /Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/clean/yelp_business_PA_CLEAN.csv
PortfolioLogger.lib.performance: INFO: <function export_data at 0x10dba1940> took 0.268 secs to complete.

PosixPath('/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/clean/yelp_business_PA_CLEAN.csv')

# Exporting Cleaned Data
## Creating Clean backup

In [50]:
df_business_CLEANED = df_business_cp6.copy()

In [47]:
lib.export_data(EXPORT_DIRECTORY / 'yelp_business.csv', df_business_CLEANED)

PortfolioLogger.lib.tools: INFO: Exporting 5862675 elements (227.86 MB) to /Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/clean/yelp_business_CLEAN.csv
PortfolioLogger.lib.performance: INFO: <function export_data at 0x10dba1940> took 1.102 secs to complete.

PosixPath('/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/clean/yelp_business_CLEAN.csv')