In [1]:
import importlib
import datetime
import json
from pathlib import Path

import pandas as pd
import numpy as np

import lib
importlib.reload(lib)

log = lib.getLogger('yelp_dataset')
working_directory = Path().cwd()
export_directory = working_directory / 'yelp_dataset'
export_clean_directory = export_directory / 'clean'

In [2]:
path_dataset_review = '/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/yelp_academic_dataset_review.json'  # 5.34 GB

In [3]:
df_review = lib.read_json(path_dataset_review)

## Cleaning Review Dataset

In [4]:
df_review

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5.0,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15
...,...,...,...,...,...,...,...,...,...
6990275,H0RIamZu0B0Ei0P4aeh3sQ,qskILQ3k0I_qcCMI-k6_QQ,jals67o91gcrD4DC81Vk6w,5.0,1,2,1,Latest addition to services from ICCU is Apple...,2014-12-17 21:45:20
6990276,shTPgbgdwTHSuU67mGCmZQ,Zo0th2m8Ez4gLSbHftiQvg,2vLksaMmSEcGbjI5gywpZA,5.0,2,1,2,"This spot offers a great, affordable east week...",2021-03-31 16:55:10
6990277,YNfNhgZlaaCO5Q_YJR4rEw,mm6E4FbCMwJmb7kPDZ5v2Q,R1khUUxidqfaJmcpmGd4aw,4.0,1,0,0,This Home Depot won me over when I needed to g...,2019-12-30 03:56:30
6990278,i-I4ZOhoX70Nw5H0FwrQUA,YwAMC-jvZ1fvEUum6QkEkw,Rr9kKArrMhSLVE9a53q-aA,5.0,1,0,0,For when I'm feeling like ignoring my calorie-...,2022-01-19 18:59:27
6990279,RwcKOdEuLRHNJe4M9-qpqg,6JehEvdoCvZPJ_XIxnzIIw,VAeEXLbEcI9Emt9KGYq9aA,3.0,10,3,7,Located in the 'Walking District' in Nashville...,2018-01-02 22:50:47

In [5]:
df_review.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6990280 entries, 0 to 6990279
Data columns (total 9 columns):
 #   Column       Dtype
---  ------       -----
 0   review_id    object
 1   user_id      object
 2   business_id  object
 3   stars        float64
 4   useful       int64
 5   funny        int64
 6   cool         int64
 7   text         object
 8   date         object
dtypes: float64(1), int64(3), object(5)
memory usage: 480.0+ MB

In [6]:
lib.info(df_review)

PortfolioLogger.lib.tools: INFO: Null INFO ********************************************
PortfolioLogger.lib.tools: INFO: 0/9 columns contain null values
PortfolioLogger.lib.tools: INFO: 0 total null values
PortfolioLogger.lib.tools: INFO: 0 row(s) contain ALL null values
PortfolioLogger.lib.tools: INFO: 0 column(s) contain ALL null values
PortfolioLogger.lib.tools: INFO: Risk Rate INFO ***************************************
PortfolioLogger.lib.tools: INFO:
            error_percent error_count
review_id           0.00%           0
user_id             0.00%           0
business_id         0.00%           0
stars               0.00%           0
useful              0.00%           0
funny               0.00%           0
cool                0.00%           0
text                0.00%           0
date                0.00%           0
PortfolioLogger.lib.tools: INFO: Data Types INFO **************************************
PortfolioLogger.lib.tools: INFO:
            has_different_types has_<NA>
review_id                 False        0
user_id                   False        0
business_id               False        0
stars                     False        0
useful                    False        0
funny                     False        0
cool                      False        0
text                      False        0
date                      False        0
PortfolioLogger.lib.tools: INFO:  *****************************************************
/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/lib/tools.py:702: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  result = result.fillna(0)
PortfolioLogger.lib.tools: INFO:
                 review_id  user_id  business_id    stars   useful    funny  \
<class 'int'>            0        0            0        0  6990280  6990280
<class 'str'>      6990280  6990280      6990280        0        0        0
<class 'float'>          0        0            0  6990280        0        0

                    cool     text     date
<class 'int'>    6990280        0        0
<class 'str'>          0  6990280  6990280
<class 'float'>        0        0        0
PortfolioLogger.lib.tools: INFO: Values Counter INFO **********************************
PortfolioLogger.lib.tools: INFO: stars: <float64> BEGIN
PortfolioLogger.lib.tools: INFO: 	3.0: 691934
PortfolioLogger.lib.tools: INFO: 	5.0: 3231627
PortfolioLogger.lib.tools: INFO: 	4.0: 1452918
PortfolioLogger.lib.tools: INFO: 	1.0: 1069561
PortfolioLogger.lib.tools: INFO: 	2.0: 544240
PortfolioLogger.lib.tools: INFO: stars: <float64> END

PortfolioLogger.lib.tools: INFO: Columns ['review_id', 'user_id', 'business_id', 'useful', 'funny', 'cool', 'text', 'date'] exceeded maximum values of 20
PortfolioLogger.lib.performance: INFO: <function info at 0x10b5b0ae0> took 6.152 mins to complete.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6990280 entries, 0 to 6990279
Data columns (total 9 columns):
 #   Column       Dtype
---  ------       -----
 0   review_id    object
 1   user_id      object
 2   business_id  object
 3   stars        float64
 4   useful       int64
 5   funny        int64
 6   cool         int64
 7   text         object
 8   date         object
dtypes: float64(1), int64(3), object(5)
memory usage: 480.0+ MB

Wow, for this there are no null or error values?
### Creating backup

In [7]:
df_review_cp1 = df_review.copy()

### Converting 'date' column to Timestamp

In [8]:
df_review_cp1['date'] = pd.to_datetime(df_review_cp1['date'])

In [9]:
df_review_cp1

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5.0,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15
...,...,...,...,...,...,...,...,...,...
6990275,H0RIamZu0B0Ei0P4aeh3sQ,qskILQ3k0I_qcCMI-k6_QQ,jals67o91gcrD4DC81Vk6w,5.0,1,2,1,Latest addition to services from ICCU is Apple...,2014-12-17 21:45:20
6990276,shTPgbgdwTHSuU67mGCmZQ,Zo0th2m8Ez4gLSbHftiQvg,2vLksaMmSEcGbjI5gywpZA,5.0,2,1,2,"This spot offers a great, affordable east week...",2021-03-31 16:55:10
6990277,YNfNhgZlaaCO5Q_YJR4rEw,mm6E4FbCMwJmb7kPDZ5v2Q,R1khUUxidqfaJmcpmGd4aw,4.0,1,0,0,This Home Depot won me over when I needed to g...,2019-12-30 03:56:30
6990278,i-I4ZOhoX70Nw5H0FwrQUA,YwAMC-jvZ1fvEUum6QkEkw,Rr9kKArrMhSLVE9a53q-aA,5.0,1,0,0,For when I'm feeling like ignoring my calorie-...,2022-01-19 18:59:27
6990279,RwcKOdEuLRHNJe4M9-qpqg,6JehEvdoCvZPJ_XIxnzIIw,VAeEXLbEcI9Emt9KGYq9aA,3.0,10,3,7,Located in the 'Walking District' in Nashville...,2018-01-02 22:50:47

### Creating a DataFrame just for the review text column (because that take's a lot of memory)

In [11]:
df_review_cp1

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5.0,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15
...,...,...,...,...,...,...,...,...,...
6990275,H0RIamZu0B0Ei0P4aeh3sQ,qskILQ3k0I_qcCMI-k6_QQ,jals67o91gcrD4DC81Vk6w,5.0,1,2,1,Latest addition to services from ICCU is Apple...,2014-12-17 21:45:20
6990276,shTPgbgdwTHSuU67mGCmZQ,Zo0th2m8Ez4gLSbHftiQvg,2vLksaMmSEcGbjI5gywpZA,5.0,2,1,2,"This spot offers a great, affordable east week...",2021-03-31 16:55:10
6990277,YNfNhgZlaaCO5Q_YJR4rEw,mm6E4FbCMwJmb7kPDZ5v2Q,R1khUUxidqfaJmcpmGd4aw,4.0,1,0,0,This Home Depot won me over when I needed to g...,2019-12-30 03:56:30
6990278,i-I4ZOhoX70Nw5H0FwrQUA,YwAMC-jvZ1fvEUum6QkEkw,Rr9kKArrMhSLVE9a53q-aA,5.0,1,0,0,For when I'm feeling like ignoring my calorie-...,2022-01-19 18:59:27
6990279,RwcKOdEuLRHNJe4M9-qpqg,6JehEvdoCvZPJ_XIxnzIIw,VAeEXLbEcI9Emt9KGYq9aA,3.0,10,3,7,Located in the 'Walking District' in Nashville...,2018-01-02 22:50:47

### Exporting cleaned Review dataset

In [12]:
lib.export_data(export_clean_directory / 'yelp_review.csv', df_review_cp1)

PortfolioLogger.lib.tools: INFO: Exporting 62912520 elements (5809.09 MB) to /Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/clean/yelp_review_CLEAN.csv
PortfolioLogger.lib.performance: INFO: <function export_data at 0x10b5b1940> took 57.753 secs to complete.

PosixPath('/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/clean/yelp_review_CLEAN.csv')

# Exploring Review Dataset

In [ ]:
path_df_review = '/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/clean/yelp_review_CLEAN.csv'  # 5.34 GB

In [18]:
df = lib.read_data(path_df_review)

PortfolioLogger.lib.tools: INFO: Encoding: ascii
PortfolioLogger.lib.tools: INFO: Stripping whitespaces from yelp_review_CLEAN.csv
PortfolioLogger.lib.performance: INFO: <function read_data at 0x14561a0c0> took 2.308 mins to complete.