<a href="https://colab.research.google.com/github/christophermagno/christophermagno/blob/main/Projects/My%20Bookshelf/goodreads_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📚 Goodreads Bookshelf Project

## ⚒️ Tools Used
[![Python](https://img.shields.io/badge/Python-3776AB?logo=python&logoColor=fff)](#)
[![Pandas](https://img.shields.io/badge/Pandas-150458?logo=pandas&logoColor=fff)](#)
[![Jupyter](https://img.shields.io/badge/Jupyter-ffffff?logo=Jupyter)](#)
[![ETL](https://custom-icon-badges.demolab.com/badge/ETL-9370DB?logo=etl-logo&logoColor=fff)](#)
[![EDA](https://custom-icon-badges.demolab.com/badge/EDA-9370DB?logo=etl-logo&logoColor=fff)](#)
[![Tableau](https://custom-icon-badges.demolab.com/badge/Tableau-0176D3?logo=tableau&logoColor=fff)](#)
* Google API
* Open Library

## 📖 Project Summary
This project transforms raw **Goodreads export data** into a structured analytics dataset to examine long-term reading behavior, preferences, and trends. The goal was to demonstrate the ability to **extract third-party exported data**, resolve data quality issues, enrich incomplete datasets using **external APIs**, and deliver **insight-driven visualizations** in Tableau.

The analysis focuses on **reading volume, pace, author and genre preferences, and rating patterns over time**, converting personal data into a scalable analytical workflow similar to those used in consumer analytics and product usage analysis.

- **Tools:** Python, pandas, Google Books API, Open Library API, Tableau
- **Dataset Size:** 238 rows × 24 columns (post-cleaning)
- **Output:** Interactive Tableau dashboard + analytical summary

To view the Tableau visualization, please click [here](https://public.tableau.com/app/profile/christopher.magno/viz/MyLibrary_17654594548470/MyBookshelf).

In [ ]:
# TODO: Use KMeans clustering to consolidate into clear, logical categories
# TODO: Have radial chart be ordered by date.

In [ ]:
import re
import logging
import importlib
import requests
from pathlib import Path

from tqdm import tqdm
import pandas as pd

from google.colab import drive

# Project directory
PROJECT_DIR = Path('/content/drive/MyDrive/Colab Notebooks/christophermagno/Projects/My Bookshelf')

# Logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s', force=True)
log = logging.getLogger('Goodreads Project')

# Google Drive
drive.mount('/content/drive')
path_raw = PROJECT_DIR / 'goodreads_library_export.csv'

log.info(f'{path_raw.name} exists: {path_raw.exists()}')

2026-01-18 05:03:15,121 - INFO - goodreads_library_export.csv exists: True

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Read in the goodreads data

In [ ]:
df = pd.read_csv(path_raw)

## Checking out the data

In [ ]:
df.head()

,Book Id,Title,Author,Author l-f,Additional Authors,ISBN,ISBN13,My Rating,Average Rating,Publisher,...,Date Read,Date Added,Bookshelves,Bookshelves with positions,Exclusive Shelf,My Review,Spoiler,Private Notes,Read Count,Owned Copies
0,18400112,"The Devil Wears Scrubs (Dr. Jane McGill, #1)",Freida McFadden,"McFadden, Freida",NaN,"=""""","=""""",3,3.44,Hollywood Upstairs Publishing,...,NaN,2025/12/01,NaN,NaN,read,NaN,NaN,NaN,1,0
1,62047984,Yellowface,R.F. Kuang,"Kuang, R.F.",NaN,"=""""","=""""",4,3.73,William Morrow,...,NaN,2023/12/10,NaN,NaN,read,NaN,NaN,NaN,1,0
2,58416952,"The Will of the Many (Hierarchy, #1)",James Islington,"Islington, James",NaN,"=""1982141190""","=""9781982141196""",0,4.60,Gallery / Saga Press,...,NaN,2025/12/01,to-read,to-read (#52),to-read,NaN,NaN,NaN,0,0
3,20886354,"Skin Deep (Legion, #2)",Brandon Sanderson,"Sanderson, Brandon",Jon Foster,"=""""","=""""",4,4.12,Subterranean Press,...,2025/11/07,2025/11/07,NaN,NaN,read,NaN,NaN,NaN,1,0
4,58778536,Do Not Disturb,Freida McFadden,"McFadden, Freida",NaN,"=""""","=""""",3,3.90,Hollywood Upstairs Publishing,...,2025/11/13,2025/11/18,NaN,NaN,read,NaN,NaN,NaN,1,0

## Creating helper functions to clean ISBN code
They're currently stored as ="" or ="isbn#"

In [ ]:
def clean_isbn(isbn):
    return re.sub(r'["=]', '', isbn)

## There were no genres stored within the Goodreads dataset, so I'll be using GoogleAPI and Open Library to gather genre data for the books using the ISBN13 book code.

In [ ]:
def request_openlibrary_book_data(isbn):
    isbn = clean_isbn(isbn)
    url = f"https://openlibrary.org/isbn/{isbn}.json"
    response = requests.get(url)
    if not response:
        return {}

    response = response.json()

    # Get book "works" metadata (contains subjects)
    works_key = response.get("works", [{}])[0].get("key")
    if not works_key:
        return {}

    works_data = requests.get(f"https://openlibrary.org{works_key}.json").json()
    return works_data
request_openlibrary_book_data(df.loc[2, 'ISBN13'])

{'type': {'key': '/type/work'},
 'title': 'The Will of the Many',
 'authors': [{'author': {'key': '/authors/OL7468631A'},
   'type': {'key': '/type/author_role'}}],
 'key': '/works/OL31088394W',
 'subjects': ['series:Hierarchy', 'genre:high fantasy'],
 'description': "The Catenan Republic—the Hierarchy—may rule the world, but they do not know everything.\r\n\r\nI tell them my name is Vis Telimus. I tell them I was orphaned three years ago, and that only good fortune has got me into their most prestigious school. I tell them that, when I graduate, I will allow my strength and drive—what they call Will—to be leeched away and added to the power of those above me, as everyone must do.\r\n\r\nI tell them that I belong, and they believe me.\r\n\r\nBut the truth is that I have been sent to the Academy to solve a murder. To search for an ancient weapon. To uncover secrets that may tear the Republic apart.\r\n\r\nAnd that I will never cede my Will to the empire that executed my family.\r\n\r\nTo survive, though, I will have to rise through the Academy's ranks, and win. Because if I cannot, those who know my real name will no longer have any use for me.\r\n\r\nAnd if the Hierarchy finds out who I truly am, they will kill me.",
 'identifiers': {'wikidata': ['Q124153740'],
  'isfdb': ['3162383'],
  'musicbrainz': ['29f9e43d-4366-4c4d-aed9-9cbd119c5523'],
  'bookbrainz': ['d8641a1c-7d3c-4a95-b709-dc5bfe4b52b4'],
  'librarything': ['29563767'],
  'goodreads': ['91649761']},
 'latest_revision': 7,
 'revision': 7,
 'created': {'type': '/type/datetime', 'value': '2022-12-03T08:05:19.527459'},
 'last_modified': {'type': '/type/datetime',
  'value': '2025-12-14T14:09:34.276767'}}

In [ ]:
def request_googleapi_book_data(isbn):
    isbn = clean_isbn(isbn)
    url = f"https://www.googleapis.com/books/v1/volumes?q=isbn:{isbn}"
    response = requests.get(url).json()
    if not 'items' in response:
        return {}
    return response['items'][0]
request_googleapi_book_data(df.loc[2, 'ISBN13'])

{'kind': 'books#volume',
 'id': 'jlGUEAAAQBAJ',
 'etag': 'QszM2Y0drG4',
 'selfLink': 'https://www.googleapis.com/books/v1/volumes/jlGUEAAAQBAJ',
 'volumeInfo': {'title': 'The Will of the Many',
  'authors': ['James Islington'],
  'publisher': 'Simon and Schuster',
  'publishedDate': '2023-05-23',
  'description': 'At the elite Catenan Academy, a young fugitive uncovers layered mysteries and world-changing secrets in this “brilliant and gut-churning masterpiece” (Library Journal, starred review) by the internationally bestselling author of The Licanius Trilogy, James Islington. The Catenan Republic—the Hierarchy—may rule the world now, but they do not know everything. I tell them my name is Vis Telimus. I tell them I was orphaned after a tragic accident three years ago, and that good fortune alone has led to my acceptance into their most prestigious school. I tell them that once I graduate, I will gladly join the rest of civilized society in allowing my strength, my drive, and my focus—what they call Will—to be leeched away and added to the power of those above me, as millions already do. As all must eventually do. I tell them that I belong, and they believe me. But the truth is that I have been sent to the Academy to find answers. To solve a murder. To search for an ancient weapon. To uncover secrets that may tear the Republic apart. And that I will never, ever cede my Will to the empire that executed my family. To survive though, I will still have to rise through the Academy’s ranks. I will have to smile, and make friends, and pretend to be one of them, and win. Because if I cannot, then those who want to control me, who know my real name, will no longer have any use for me. And if the Hierarchy finds out who I truly am, they will kill me.',
  'industryIdentifiers': [{'type': 'ISBN_13', 'identifier': '9781982141196'},
   {'type': 'ISBN_10', 'identifier': '1982141190'}],
  'readingModes': {'text': True, 'image': False},
  'pageCount': 720,
  'printType': 'BOOK',
  'categories': ['Fiction'],
  'maturityRating': 'NOT_MATURE',
  'allowAnonLogging': True,
  'contentVersion': '2.11.10.0.preview.2',
  'panelizationSummary': {'containsEpubBubbles': False,
   'containsImageBubbles': False},
  'imageLinks': {'smallThumbnail': 'http://books.google.com/books/content?id=jlGUEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api',
   'thumbnail': 'http://books.google.com/books/content?id=jlGUEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'},
  'language': 'en',
  'previewLink': 'http://books.google.com/books?id=jlGUEAAAQBAJ&printsec=frontcover&dq=isbn:9781982141196&hl=&cd=1&source=gbs_api',
  'infoLink': 'https://play.google.com/store/books/details?id=jlGUEAAAQBAJ&source=gbs_api',
  'canonicalVolumeLink': 'https://play.google.com/store/books/details?id=jlGUEAAAQBAJ'},
 'saleInfo': {'country': 'US',
  'saleability': 'FOR_SALE',
  'isEbook': True,
  'listPrice': {'amount': 16.99, 'currencyCode': 'USD'},
  'retailPrice': {'amount': 16.99, 'currencyCode': 'USD'},
  'buyLink': 'https://play.google.com/store/books/details?id=jlGUEAAAQBAJ&rdid=book-jlGUEAAAQBAJ&rdot=1&source=gbs_api',
  'offers': [{'finskyOfferType': 1,
    'listPrice': {'amountInMicros': 16990000, 'currencyCode': 'USD'},
    'retailPrice': {'amountInMicros': 16990000, 'currencyCode': 'USD'},
    'giftable': True}]},
 'accessInfo': {'country': 'US',
  'viewability': 'PARTIAL',
  'embeddable': True,
  'publicDomain': False,
  'textToSpeechPermission': 'ALLOWED_FOR_ACCESSIBILITY',
  'epub': {'isAvailable': True,
   'acsTokenLink': 'http://books.google.com/books/download/The_Will_of_the_Many-sample-epub.acsm?id=jlGUEAAAQBAJ&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api'},
  'pdf': {'isAvailable': False},
  'webReaderLink': 'http://play.google.com/books/reader?id=jlGUEAAAQBAJ&hl=&source=gbs_api',
  'accessViewStatus': 'SAMPLE',
  'quoteSharingAllowed': False},
 'searchInfo': {'textSnippet': 'At the elite Catenan Academy, a young fugitive uncovers layered mysteries and world-changing secrets in this “brilliant and gut-churning masterpiece” (Library Journal, starred review) by the internationally bestselling author of The ...'}}

### Data that's useful in the gathered data from GoodleAPI and Open Library.
- volumeInfo
    - authors
    - title
    - publisher
    - publishDate
    - description
    - pageCount
    - categories [list]
    - maturityRating
    - imagelinks (do i want images?): [dict]
    - saleInfo
        - country
        - retailPrice
- subjects

In [ ]:
def clean_categories_list(categories, ignore=('collectionID', 'nyt')):

    new_categories = set()
    if not categories:
        return list(new_categories)

    for i in range(len(categories)):
        # Split and find categories to add to new_categories set
        for category in categories[i].split(', '):
            found = False
            for item in ignore:
                if item in category:
                    found = True
                    break
            if found:
                continue
            new_categories.add(category.title().replace('_', ' '))

    return list(new_categories)

### Final function to organize data for categories (genres)

In [ ]:
def get_book_data(isbn):
    """
    Function to gather additional data from google API and Open Library

    :param isbn: Book ISBN code
    :type isbn: str
    :return: dict
    """

    # Get and clean the ISBN
    isbn = clean_isbn(isbn)

    result = {'Categories': []}

    # Google API query
    googleapi_data = request_googleapi_book_data(isbn)
    if googleapi_data:
        result.update(
            {'Published Date': googleapi_data['volumeInfo'].get('publishedDate'),
            'Categories': clean_categories_list(googleapi_data['volumeInfo'].get('categories')),
            'Maturity Rating': googleapi_data['volumeInfo'].get('maturityRating'),
            'Description': googleapi_data['volumeInfo'].get('description'),
            'Country': googleapi_data['saleInfo'].get('country'),
            'Retail Price': googleapi_data['saleInfo'].get('retailPrice', {}).get('amount'),
            'Currency': googleapi_data['saleInfo'].get('retailPrice', {}).get('currencyCode')}
        )

    # Open AI query
    openai_categories_data = request_openlibrary_book_data(isbn).get('subjects', [])
    if openai_categories_data:
        result['Categories'].extend(clean_categories_list(openai_categories_data))

    # Sort the categories
    result['Categories'] = sorted(set((result['Categories'])))

    return result

### Sample request to see what data I get

In [ ]:
data = get_book_data(df.loc[2, 'ISBN13'])
data

{'Categories': ['Fiction', 'Genre:High Fantasy', 'Series:Hierarchy'],
 'Published Date': '2023-05-23',
 'Maturity Rating': 'NOT_MATURE',
 'Description': 'At the elite Catenan Academy, a young fugitive uncovers layered mysteries and world-changing secrets in this “brilliant and gut-churning masterpiece” (Library Journal, starred review) by the internationally bestselling author of The Licanius Trilogy, James Islington. The Catenan Republic—the Hierarchy—may rule the world now, but they do not know everything. I tell them my name is Vis Telimus. I tell them I was orphaned after a tragic accident three years ago, and that good fortune alone has led to my acceptance into their most prestigious school. I tell them that once I graduate, I will gladly join the rest of civilized society in allowing my strength, my drive, and my focus—what they call Will—to be leeched away and added to the power of those above me, as millions already do. As all must eventually do. I tell them that I belong, and they believe me. But the truth is that I have been sent to the Academy to find answers. To solve a murder. To search for an ancient weapon. To uncover secrets that may tear the Republic apart. And that I will never, ever cede my Will to the empire that executed my family. To survive though, I will still have to rise through the Academy’s ranks. I will have to smile, and make friends, and pretend to be one of them, and win. Because if I cannot, then those who want to control me, who know my real name, will no longer have any use for me. And if the Hierarchy finds out who I truly am, they will kill me.',
 'Country': 'US',
 'Retail Price': 16.99,
 'Currency': 'USD'}

## Add the extra data into the DataFrame

In [ ]:
df.columns

Index(['Book Id', 'Title', 'Author', 'Author l-f', 'Additional Authors',
       'ISBN', 'ISBN13', 'My Rating', 'Average Rating', 'Publisher', 'Binding',
       'Number of Pages', 'Year Published', 'Original Publication Year',
       'Date Read', 'Date Added', 'Bookshelves', 'Bookshelves with positions',
       'Exclusive Shelf', 'My Review', 'Spoiler', 'Private Notes',
       'Read Count', 'Owned Copies'],
      dtype='object')

In [ ]:
categories = []

# New df to concatenate
concat_df = pd.DataFrame(df['Book Id'])

# Categories dataframe
for idx, row in tqdm(df.iterrows(), total=len(df)):
    isbn = clean_isbn(row['ISBN13'])
    book_data = get_book_data(isbn)
    if book_data:
        for key, value in book_data.items():
            if key == 'Categories':
                for category in book_data['Categories']:
                    categories.append(
                        {'Book Id': row['Book Id'], 'Category': category}
                    )
                continue
            concat_df.at[idx, key] = value

concat_df

100%|██████████| 237/237 [03:39<00:00,  1.08it/s]

,Book Id,Published Date,Maturity Rating,Description,Country,Retail Price,Currency
0,18400112,2025-10-30,NOT_MATURE,Have you ever wondered why that 13-digit numbe...,US,None,None
1,62047984,2025-10-30,NOT_MATURE,Have you ever wondered why that 13-digit numbe...,US,None,None
2,58416952,2023-05-23,NOT_MATURE,"At the elite Catenan Academy, a young fugitive...",US,16.99,USD
3,20886354,2025-10-30,NOT_MATURE,Have you ever wondered why that 13-digit numbe...,US,None,None
4,58778536,2025-10-30,NOT_MATURE,Have you ever wondered why that 13-digit numbe...,US,None,None
...,...,...,...,...,...,...,...
232,40389527,2025-10-30,NOT_MATURE,Have you ever wondered why that 13-digit numbe...,US,None,None
233,38389488,2025-10-30,NOT_MATURE,Have you ever wondered why that 13-digit numbe...,US,None,None
234,39863488,2019-02-05,NOT_MATURE,"INSTANT NEW YORK TIMES BESTSELLER ""I love Jane...",US,None,None
235,43848929,2019-09-10,NOT_MATURE,"Malcolm Gladwell, host of the podcast Revision...",US,None,None
236,30141085,2025-10-30,NOT_MATURE,Have you ever wondered why that 13-digit numbe...,US,None,None

## Merge and create copy of new DataFrame

In [ ]:
df_cp1 = df.merge(concat_df, how='left', on='Book Id')

In [ ]:
df_cp1.columns

Index(['Book Id', 'Title', 'Author', 'Author l-f', 'Additional Authors',
       'ISBN', 'ISBN13', 'My Rating', 'Average Rating', 'Publisher', 'Binding',
       'Number of Pages', 'Year Published', 'Original Publication Year',
       'Date Read', 'Date Added', 'Bookshelves', 'Bookshelves with positions',
       'Exclusive Shelf', 'My Review', 'Spoiler', 'Private Notes',
       'Read Count', 'Owned Copies', 'Published Date', 'Maturity Rating',
       'Description', 'Country', 'Retail Price', 'Currency'],
      dtype='object')

In [ ]:
df_cp1.head()

,Book Id,Title,Author,Author l-f,Additional Authors,ISBN,ISBN13,My Rating,Average Rating,Publisher,...,Spoiler,Private Notes,Read Count,Owned Copies,Published Date,Maturity Rating,Description,Country,Retail Price,Currency
0,18400112,"The Devil Wears Scrubs (Dr. Jane McGill, #1)",Freida McFadden,"McFadden, Freida",NaN,"=""""","=""""",3,3.44,Hollywood Upstairs Publishing,...,NaN,NaN,1,0,2025-10-30,NOT_MATURE,Have you ever wondered why that 13-digit numbe...,US,None,None
1,62047984,Yellowface,R.F. Kuang,"Kuang, R.F.",NaN,"=""""","=""""",4,3.73,William Morrow,...,NaN,NaN,1,0,2025-10-30,NOT_MATURE,Have you ever wondered why that 13-digit numbe...,US,None,None
2,58416952,"The Will of the Many (Hierarchy, #1)",James Islington,"Islington, James",NaN,"=""1982141190""","=""9781982141196""",0,4.60,Gallery / Saga Press,...,NaN,NaN,0,0,2023-05-23,NOT_MATURE,"At the elite Catenan Academy, a young fugitive...",US,16.99,USD
3,20886354,"Skin Deep (Legion, #2)",Brandon Sanderson,"Sanderson, Brandon",Jon Foster,"=""""","=""""",4,4.12,Subterranean Press,...,NaN,NaN,1,0,2025-10-30,NOT_MATURE,Have you ever wondered why that 13-digit numbe...,US,None,None
4,58778536,Do Not Disturb,Freida McFadden,"McFadden, Freida",NaN,"=""""","=""""",3,3.90,Hollywood Upstairs Publishing,...,NaN,NaN,1,0,2025-10-30,NOT_MATURE,Have you ever wondered why that 13-digit numbe...,US,None,None

## Create a new Dataframe for the categories

In [ ]:
df_categories = pd.DataFrame(categories)
df_categories

       Book Id                     Category
0     18400112  Language Arts & Disciplines
1     62047984  Language Arts & Disciplines
2     58416952                      Fiction
3     58416952           Genre:High Fantasy
4     58416952             Series:Hierarchy
...        ...                          ...
3808  43848929               Social Science
3809  43848929                    Strangers
3810  43848929          Threat (Psychology)
3811  43848929                        Trust
3812  30141085  Language Arts & Disciplines

[3813 rows x 2 columns]

### Check genre counts

In [ ]:
category_counts = df_categories['Category'].value_counts()
category_counts

Category
Fiction                                                                                                 129
General                                                                                                  79
New York Times Bestseller                                                                                77
Language Arts & Disciplines                                                                              74
Fantasy                                                                                                  48
                                                                                                       ...
Fathers And Sons                                                                                          1
Fathers And Sons Fiction; Fiction Dystopian; Fiction Science Fiction General; American Fiction (Fict      1
Fathers And Sons--Fiction                                                                                 1
Hunger                                                                                                    1
Post-Apocalyptic Fiction                                                                                  1
Name: count, Length: 2052, dtype: int64

In [ ]:
len(category_counts)

2052

### 2052 categories is too much... let's prune the list
Remove some specific generic genres and any genre that only has 1

In [ ]:
categories_to_drop = [
    'Fiction',
    'General',
    'New York Times Bestseller',
    'Language Arts & Disciplines',
    'Romans',
    'Large Type Books',
    'New York Times Reviewed',
    'Reading Level-Grade 11',
    'Reading Level-Grade 12',
    'Open Library Staff Picks',
    'Long Now Manual For Civilization',
    'Ficción',
    'Novela',
    'Reading Level-Grade 10',
    'Reading Level-Grade 9'
] + category_counts[category_counts <= 3].index.tolist()
sorted(categories_to_drop)

['& Magic',
 '1000Blackgirlbooks',
 '153.4/4',
 '18.05 English Literature',
 '18.06 Anglo-American Literature',
 '1847-1912',
 '1866-1946',
 '1905-1997',
 '1911-1993',
 '1919-2010',
 '1939-1945',
 '1954-',
 '1961-1975',
 '1991',
 '2000S',
 '2001-02',
 '2005',
 '20Th Century',
 '21St Century Film And Literature',
 '306.81',
 '362.82/092 B',
 '813.5 S 3-8',
 '813/.3',
 '813/.54',
 '813/.6',
 '823.912',
 '823/.912',
 '883.01',
 '883/.001',
 '883/.01',
 'A Wrinkle In Time',
 'Ability',
 'Abridged Audio - Misc. Nonfiction',
 'Abuelos (Hombres)',
 'Abuse',
 'Academic Literacy',
 'Accessible Book',
 'Accounting',
 'Acculturation',
 'Achab (Personnage Fictif)',
 'Achille (Mythologie Grecque)',
 'Achilles',
 'Achilles (Greek Mythology)',
 'Achilles (Greek Mythology) In Literature',
 'Achilles (Greek Mythology)--Fiction',
 'Achilles (Greek Mythology)--Poetry',
 'Achilles--Poetry',
 'Action & Adventure - General',
 'Action And Adventure',
 'Actors',
 'Actors And Actresses',
 'Addiction',
 'Adolescence',
 'Adolescence In Literature',
 'Adolescentes',
 'Adolescents Fugueurs Dans La Littérature',
 'Adoption',
 'Adult',
 'Adult Children',
 'Adulto',
 'Adventure Fiction',
 'Adventure Stories',
 'Afghanistan',
 'Afghanistan-Konflikt',
 'Afghans',
 'African American',
 'African American & Black',
 'African American Children',
 'African American Families',
 'African American Teenage Girls',
 'African American Women',
 'African Americans',
 'African Americans--Fiction',
 'Age:Max:14',
 'Age:Min:10',
 'Ahab',
 'Air Pilots',
 'Airplane Crash Survival',
 "Al'Thor Rand (Fictitious Character)",
 'Aladdin (Legendary Character)',
 'Alibi',
 'Alien Contact',
 'Alienation In Teenagers',
 'Aliens',
 'Allegories',
 'Ambição',
 'America',
 'America In Fiction',
 'American',
 'American Adventure Stories',
 'American Authors',
 'American Detective And Mystery Stories',
 'American Fantasy',
 'American Poetry',
 'American Poets',
 'American Sea Stories',
 'American Short Stories',
 'American War Stories',
 'American Young Adult Fiction',
 'Americans',
 'Amistad Entre Hombres',
 'Amitie',
 'Amitié',
 'Amitié Masculine',
 'Amor A Sí Mismo (Psicología)',
 "Américaines D'Origine Asiatique",
 "Américains D'Origine Asiatique",
 "Américains D'Origine Coréenne",
 'Anachronism',
 'Anciens Combattants',
 'Ancient',
 'Ancient Greek Poetry',
 'Angela',
 'Anglais (Langue)',
 'Angleška Književnost',
 'Animal Experimentation',
 'Apartheid',
 'Apocalypse',
 'Apocalyptic & Post-Apocalyptic',
 'Apocalyptic Fiction',
 'Applied Psychology',
 'Aprobación De Sí Mismo',
 'Aptitudes Motoras',
 'Aquiles (Mitología Griega)',
 'Arabic Fiction',
 'Arctic Regions',
 'Arctic Regions -- Fiction',
 'Arctic Regions -- Juvenile Fiction',
 'Aristocracy',
 'Aristocracy (Social Class)',
 'Armand (Fictitious Character)',
 'Armand (Fictitious Character) -- Fiction',
 'Armand (Personnage Fictif) -- Romans',
 'Armand Gamache (Fictitious Character)',
 'Art',
 'Arthur (Fictitious Character)',
 'Arthur (Fictitious Character) Fiction',
 'Arthur Dent (Fictitious Character)',
 'Artic Regions',
 'Artificial Intelligence',
 'Artistas',
 'Artistes',
 'Artists',
 'Asesinato',
 'Asian & Asian American',
 'Asian American',
 'Asian American Women',
 'Asian Americans',
 'Aspect Psychologique',
 'Aspectos Morales Y Éticos',
 'Aspectos Psicológicos',
 'Aspects Psychologiques',
 'Assasins',
 'Assassins',
 'Assertiveness',
 'Assertiveness (Psychology)',
 'Assyro-Babylonian',
 'Asteroids',
 'Astronautes',
 'Astronauts',
 'Atomic Bomb',
 'Atonement',
 'Attachment Behavior',
 'Attitude Change',
 'Aufklärung',
 'Aufklärung <Kriminologie>',
 'Australia',
 'Austria',
 'Authoritarianism',
 'Authors',
 'Authors And Publishers',
 'Authorship',
 'Auto-Realización',
 'Autobiographies',
 'Autobiography',
 'Autographed Books',
 'Automation',
 'Automobile Racing Drivers',
 'Außerirdische Intelligenz',
 'Award:Hugo Award=1966',
 'Award:Hugo Award=1986',
 'Award:Hugo Award=Novel',
 'Award:Nebula Award=Novel',
 'Award:Newbery Award',
 'Bacha Bazi',
 'Backstories',
 'Baggins',
 'Baleines',
 'Ballenas',
 'Battle School (Imaginary Place)',
 'Battles',
 'Bean (Fictitious Character : Card)',
 'Bedrohung',
 'Belacqua',
 'Belletristische Darstellung',
 'Bereavement',
 'Berliner Mauer',
 'Besluitvorming',
 'Betrayal',
 'Betrayal--Fiction',
 'Bf 448 G543 2007',
 'Bf448 .G53 2007',
 'Bibliography',
 'Bibliotecarios',
 'Bibliothèques',
 'Bibliothécaires',
 'Bicycle Touring',
 'Bien Y Mal',
 'Bilbo (Fictitious Character)',
 'Bilbo Baggins (Fictitious Character)',
 'Biografi A.',
 'Biografía',
 'Biografías',
 'Biographers',
 'Biographie',
 'Biographies As Topic',
 'Biography & Autobiography / Cultural',
 'Biography & Autobiography / Personal Memoirs',
 'Biography & Memoir',
 'Biography As Topic',
 'Bird Language',
 'Black Humor (Literature)',
 'Black Teenage Girls',
 'Blessing And Cursing',
 'Blind',
 'Body',
 'Book Of Leviticus',
 'Book: Sga Sal',
 'Boys',
 'Boys--Fiction',
 'Brain',
 'Brainwashing',
 'Bram',
 'Bram)',
 'Brandon Sanderson',
 'Brass Knuckles',
 'Brigands And Robbers',
 'British',
 'British And Irish Drama (Dramatic Works By One Author)',
 'Brothers',
 'Buddhism',
 'Buried Treasure',
 'Business',
 'Bénédiction Et Malédiction',
 'Ca',
 'Cabin Fever',
 'Calif.)',
 'California',
 'Camps De Concentration',
 'Canadian Fiction',
 'Capitaines De Navire',
 'Capitalism',
 'Capitalist Civilization',
 'Capitanes De Barcos',
 'Captain (Fictitious Character)',
 'Captain (Fictitious Character)--Fiction',
 'Captain Ahab (Fictitious Character)',
 'Caretakers',
 'Caring',
 'Carnegie Medal',
 'Cartoons And Comics',
 'Cas',
 'Case Studies',
 'Casos De Estudio',
 'Castaway',
 'Castaways',
 'Catcher In The Rye (Salinger',
 'Caulfield',
 'Cautionary Tales And Verse',
 'Censorship',
 'Chagrin',
 'Chanteurs',
 'Chasse',
 'Chess',
 'Child Of Impaired Parents',
 'Child Sexual Abuse',
 'Child Soldiers',
 'Childhood',
 'Childhood And Youth',
 'Children',
 'Children And Adults',
 'Children Of Alcoholics',
 'Children Of Alcoholics--United States--Biography',
 'Children Of Alcoholics--West Virginia--Welch--Biography',
 "Children'S 12-Up - Fiction - Fantasy",
 "Children'S Books - Young Adult",
 "Children'S Books - Young Adult Fiction",
 "Children'S Stories",
 'Children: Grades 4-6',
 'Children: Young Adult (Gr. 10-12)',
 'Children: Young Adult (Gr. 7-9)',
 'Chinese',
 'Chinese Science Fiction',
 'Chinos',
 'Choice (Psychology)',
 'Choix (Psychologie)',
 'Chr 2004',
 'Christian',
 'Christopher Columbus In Fiction',
 'Church Decoration And Ornament',
 'Church History',
 'Ciegos',
 'Ciencia',
 'Ciencia Y Estado',
 'Circe',
 'Circe (Greek Mythology)',
 'Circe (Greek Mythology)--Fiction',
 'City And Town Life',
 'City Council Members',
 'Ciudades Y Pueblos',
 'Civics & Citizenship',
 'Civil War',
 'Civilization',
 'Clairvoyance',
 'Clase Alta',
 'Clases Sociales',
 'Class Systems',
 'Classes Sociales',
 'Classical & Medieval',
 'Classical Literature',
 'Classical Philology',
 'Cleveland (Ohio)',
 'Climate',
 'Clinical Medicine',
 'Clonage',
 'Cloning',
 'Cloning--Fiction',
 'Clumsiness',
 'Coffee',
 'Cognitive Dissonance',
 'Cognitive Psychology & Cognition',
 'Collected Works',
 'Collection:Canada Reads',
 'Collection:Canada Reads 2023',
 'Collections',
 'Collections & Anthologies',
 'Collectivism',
 'Collectivisme',
 'College Teachers',
 'Colonies Spatiales',
 'Colorado',
 'Combat',
 'Combinaties',
 'Comedians',
 'Comedy',
 'Comic And Graphic Books',
 'Comics & Graphic Novels / General',
 'Comics & Graphic Novels / Historical Fiction',
 'Comics & Graphic Novels / Literary',
 'Comics & Graphic Novels / Science Fiction',
 'Coming-Of-Age',
 'Comiques',
 'Communication',
 'Communication In Marriage',
 'Communists',
 'Comparative Literature',
 'Compassion',
 'Competitions',
 'Computadoras',
 'Computer Hackers',
 'Computer Hackers Sweden Stockholm Fiction',
 'Computer Viruses',
 'Computers',
 'Comunicación En El Matrimonio',
 'Concentration Camp Inmates',
 'Concentration Camps',
 'Conditions Sociales',
 'Consumption (Economics)',
 'Contemporary',
 'Contemporary Fiction',
 'Contemporary Women',
 'Continental European Fiction (Fictional Works By One Author)',
 'Control (Philosophy)',
 'Control (Psicología)',
 'Control (Psychology)',
 'Contrãole (Psychologie',
 'Contrôle (Psychologie)',
 'Contrôle (Psychologie.)',
 'Cooking',
 'Cooking Methods',
 'Correspondants De Guerre',
 'Correspondence',
 'Correspondence..',
 'Corruption',
 'Counseling',
 'Count (Fictitious Character)',
 'Count Dracula (Fictional Character)',
 'Country Life',
 'County Dracula (Fictitious Character)',
 'Couples Mariés',
 'Courage',
 'Cours Et Courtisans',
 'Cours Et Courtisans -- Romans',
 'Courts And Courtiers -- Fiction',
 'Covert Operations',
 'Crime Fiction',
 'Crimes Against',
 'Criminal Evidence',
 'Criminals',
 'Criticism And Interpretation',
 'Cruise Ships',
 'Cuentos De Amor',
 'Cuentos De Mar',
 'Cuentos Humorosos',
 'Cult Of Personality',
 'Cultural',
 'Cultural Heritage',
 'Culture',
 'Curses',
 'Custody Of Children',
 'Cycling',
 'Dactylic Hexameter',
 'Dallas',
 'Dark Academia',
 'Dark Fantasy',
 'Das Bo\x98Se',
 'Das Böse',
 'Das Gute',
 'Data Processing',
 'De Tissus',
 'Decisiones',
 'Democracy',
 'Demonology',
 'Dent',
 'Desamparados',
 'Desaparecidos',
 'Description And Travel',
 'Desertification',
 'Despotism',
 'Detective',
 'Detective And Mystery Fiction',
 'Detective And Mystery Stories',
 'Detectives',
 'Diaries',
 'Dictionaries',
 'Disappeared Persons',
 'Disasters',
 'Discoveries In Geography',
 'Discoveries In Geography In Fiction',
 'Discovery And Exploration',
 'Diseases',
 'Distopías',
 'Doctrines',
 'Document',
 'Dog Owners',
 'Dogs',
 'Domestic Fiction',
 'Dometic Fiction',
 'Donation Of Organs',
 "Donneurs D'Organes",
 "Dons D'Organes",
 'Drache',
 'Dracula',
 'Dracula (Personaje Literario)',
 'Dracula (Stoker',
 'Dracula (Stoker)',
 'Dracula I Litteraturen',
 'Dragones',
 'Dragons & Mythical Creatures',
 'Dragons -- Fiction',
 'Drama (Dramatic Works By One Author)',
 'Drowning',
 'Drug Abuse',
 'Drug Traffic',
 'Duan Pian Xiao Shuo',
 'Dune (Lieu Imaginaire)',
 'Dune (Lugar Imaginario)',
 'Dwarves',
 'Dysfunctional Families',
 'Dysfunctional Families--United States--Case Studies',
 'Dysfunctional Families--West Virginia--Welch--Case Studies',
 'Dystopia',
 'Dystopian Plays',
 'Dystopias In Literature',
 'Dystopies',
 'Dämon',
 'Décadence',
 'Développement Personnel',
 'Early Retirement',
 'Early Works To 1800',
 'Earth',
 'Ecology',
 'Editores',
 'Education',
 'Effect Of Human Beings On',
 'Elecciones Locales',
 'Elections',
 'Electronic Books',
 'Elementary Education Of Adults',
 'Elves',
 'Emotionally Disturbed Teenage Boys',
 'Empathy',
 'Employees',
 'End Games',
 'End Of The World',
 'Ender (Fictitious Character)',
 'Ender Wiggin (Fictitious Character)',
 'Enfance Et Jeunesse',
 "Enfant D'Alcoolique",
 'Enfant De Parents Alcooliques',
 'Enfants Aveugles',
 "Enfants D'Alcooliques",
 'Enfants Et Guerre',
 'Enfermos Mentales',
 'Engelse Fiksie',
 'Engelsk Skönlitteratur',
 'Englisch',
 'English',
 'English Authors',
 'English Fantasy Fiction',
 'English Horror Tales',
 'English Manuscripts',
 'English Political Fiction',
 'English Translations',
 'Enlevement',
 'Enquêtes',
 'Ensamhet',
 'Ensamstående Män',
 'Entführung',
 'Environmental Aspects',
 'Environmental Disasters',
 'Epic Fiction',
 'Epic Literature',
 'Epic Poem',
 'Epic Poetry',
 'Epileptics',
 'Epistolary Novels',
 'Erlebnisbericht',
 'Erwachsenwerden',
 'Esclavitud',
 'Escritos De Adolescentes',
 'Espacio Y Tiempo',
 'Espionage',
 'Esposas Maltratadas',
 'Esposos',
 'Essays',
 'Essays & Narratives',
 'Etc',
 'Etc--Fiction',
 'Etc.',
 'Ethnic & Regional',
 'Ethnic & Regional / Asian & Asian American',
 'Ethnic Conflict',
 'Ethnic Relations',
 'Europe',
 'Eve (Fictitious Character)',
 'Eve Dallas (Fictitious Character)',
 'Evidence-Based Medicine',
 'Examinations',
 'Existential Psychology',
 'Existential Psychotherapy',
 'Existentialism',
 'Existentialisme',
 'Existentiell Psykoterapi',
 'Experimentos',
 'Experiments',
 'Explorers',
 'Explorers In Fiction',
 'Extinction Event',
 'Extrasensory Perception',
 'Extraversion',
 'Extraversion (Psychology)',
 'Facsimiles',
 'Fairies',
 'Fairy Tales',
 'Fairy Tales & Folklore - General',
 'Fairy Tales & Folklore - Single Title',
 'Faith',
 'Familiars (Spirits)',
 'Familias',
 'Familias Problema Ticas',
 'Familias Problemáticas',
 'Familie',
 'Famille',
 'Famille Dysfonctionnelle',
 'Familles Inadaptées',
 'Family',
 'Family & Relationships',
 'Family Memoirs - Biography',
 'Family Relations',
 'Family Relationships',
 'Family Secrets',
 'Family Violence',
 'Fantasmes',
 'Fantastic Fiction',
 'Fantastique',
 'Fantasy & Magic',
 'Fantasy - General',
 'Fantasy .',
 'Faschismus',
 'Fate And Fatalism',
 'Father Time (Symbolic Character)',
 'Father-Son Relationship',
 'Fathers And Daughters',
 'Fathers And Sons',
 'Fathers And Sons Fiction; Fiction Dystopian; Fiction Science Fiction General; American Fiction (Fict',
 'Fathers And Sons--Fiction',
 'Feelgood',
 'Female Friendship',
 'Female Protagonist',
 'Femmes',
 'Fen Xi Xin Li Xue',
 'Feudalism',
 'Fic',
 'Ficcion',
 'Ficción',
 'Ficción Fantástica Inglesa',
 'Fiction',
 'Fiction (Fictional Works By One Author)',
 'Fiction - Fantasy',
 'Fiction - General',
 'Fiction - Horror',
 'Fiction - Science Fiction',
 'Fiction / Classics',
 'Fiction / Coming Of Age',
 'Fiction / Cultural Heritage',
 'Fiction / Fantasy / Action & Adventure',
 'Fiction / Fantasy / Dragons & Mythical Creatures',
 'Fiction / Fantasy / General',
 'Fiction / General',
 'Fiction / Historical',
 'Fiction / Historical / Ancient',
 'Fiction / Historical / General',
 'Fiction / Horror',
 'Fiction / Humorous / General',
 'Fiction / Mystery & Detective / General',
 'Fiction / Mystery & Detective / International Crime & Mystery',
 'Fiction / Mystery & Detective / Traditional',
 'Fiction / Psychological',
 'Fiction / Satire',
 'Fiction / Science Fiction / Action & Adventure',
 'Fiction / Science Fiction / Adventure',
 'Fiction / Science Fiction / Alien Contact',
 'Fiction / Science Fiction / General',
 'Fiction / Science Fiction / Hard Science Fiction',
 'Fiction / Science Fiction / Time Travel',
 'Fiction / Small Town & Rural',
 'Fiction / Suspense',
 'Fiction / Thrillers',
 'Fiction / Thrillers / Crime',
 'Fiction / Thrillers / General',
 'Fiction / Thrillers / Psychological',
 'Fiction / Thrillers / Suspense',
 'Fiction / Visionary & Metaphysical',
 'Fiction / Women',
 'Fiction Classics',
 'Fiction Subjects',
 'Fiction: Literature',
 'Fictional Works Publication Type',
 'Fictional Works [Publication Type]',
 'Fighter Kites',
 'Fighting',
 'Figure Skaters',
 'Figure Skating',
 'Filipino Americans',
 'Film And Video Adaptations',
 'Fin Du Monde',
 'Finance',
 'Financial Literacy',
 'Finnish Epic Poetry',
 'Flucht',
 'Folk Healers',
 'Folk Tales',
 'Food Memoir & Travel',
 'Forced Marriage',
 'Ford (Fictitious Character)',
 'Ford (Fictitious Character) Fiction',
 'Ford Prefect (Fictitious Character)',
 'Forecasting',
 'Forgiveness',
 'Form:Novel',
 'France',
 'Franchise:Red Rising',
 'Frankenstein Complex',
 'Frankl',
 'Français (Langue)',
 'Fraud',
 'Freedom',
 'Freedom Of Choice',
 'French',
 'French Language',
 'Freundschaft',
 'Friendship In Adolesce',
 'Frodo',
 'Frodo (Fictitious Character)',
 'Frodo Baggins (Fictitious Character)',
 'Frères',
 'Future',
 'Future Life',
 'Futuristic Fiction',
 'Futurology',
 'Fées',
 'Förintelsen',
 'Gamache',
 'Games',
 'Games & Activities',
 'Gandalf (Fictitious Character)',
 'Garçons',
 'Garçons Adolescents Dans La Littérature',
 'Gay Men',
 'Gays',
 'Gender And Violence',
 'General',
 'General & Miscellaneous Biography',
 'Genetic Engineering',
 'Genius',
 'Genre:High Fantasy',
 'Genre:Science Fiction',
 'Geographical Myths',
 'George)',
 'German Language Materials',
 'German Occupation Of France (1940-1945) Fast (Ocolc)Fst01353176',
 'German Poetry',
 'German Prisoners And Prisons',
 'Germany',
 'Gesellschaft',
 'Ghost',
 'Ghost Fiction',
 'Ghosts',
 'Gift Books',
 'Gifted Children',
 'Gifted Persons',
 'Girls',
 'Gods',
 'Gods--Fiction',
 'Goldfinch',
 'Golding',
 'Good And Evil -- Fiction',
 'Gothic',
 'Gothic & Horror',
 'Gothic Literature',
 'Governors',
 'Grade:Max:Undefined',
 'Grade:Min:Kindergarten And Up',
 'Grail',
 'Grammar',
 'Granddaughters',
 'Grandes Puissances',
 'Grandfathers',
 'Grandmothers',
 'Grandparents',
 'Grands-Pères',
 'Grannar',
 'Graphic Novels',
 'Great Books Of The Western World',
 'Great Britain',
 'Great Powers',
 'Greco-Roman Folklore & Mythology',
 'Gree Epic Poetry',
 'Greek',
 'Greek (Classical)',
 'Greek Epic Poetry',
 'Greek Gods',
 'Greek Language',
 'Greek Language Materials',
 'Greek Literature',
 'Greek Mythology',
 'Greek Poetry',
 'Greek--Fiction',
 'Greek--Translations Into English',
 'Greeks',
 'Greeks--Turkey--Fiction',
 'Grekisk Hjältediktning',
 'Grief',
 'Gritty',
 'Group Identity',
 'Guerra',
 'Guerra Civil',
 'Guerra De Troya',
 'Guerra Espacial',
 'Guerra Mundial Ii',
 'Guerras Imaginarias',
 'Guerre De Troie',
 'Guerre Du Viêt-Nam',
 'Guerre Mondiale',
 'Guerres Et Batailles Imaginaires',
 'H. G. (Herbert George)',
 'Habiletés De Survie',
 'Hackers',
 'Hallucinations And Illusions',
 'Happiness',
 'Hard Sci-Fi',
 'Hard Science Fiction',
 'Hard Science-Fiction',
 'Hari Seldon (Fictitious Character)',
 'Haunted Houses',
 'Hazaras',
 'Healing',
 'Healing Power Of Nature',
 'Health & Fitness',
 'Heart Of Gold',
 "Heather'S Pick",
 'Heaven',
 'Hector (Legendary Character)',
 'Hegemony',
 'Heiresses',
 'Heisenbugs',
 'Helen Of Troy (Greek Mythology)',
 'Heranwachsender',
 'Herman)',
 'Hermanos',
 'Hexameter',
 'Hi',
 'High Fantasy',
 'High Tech And Hard Science Fiction',
 'Hijos De Alcohólicos',
 'Hijos De Padres Alcoho Licos',
 'Hijos De Padres Alcohólicos',
 'Hiking',
 'Hinduism',
 'Hispanic Americans',
 'Histoire',
 'Historia',
 'Historians',
 'Historical Negationism',
 'History & Theory - General',
 'Hobbits (Fictitious Characters)',
 'Hobbits (Personnages Fictifs)',
 'Holden (Fictitious Character)',
 'Holden (Fictitious Character)--Fiction',
 'Holden (Personnage Fictif)',
 'Holden Acaulfield (Fictitious Character)',
 'Holden Caulfield (Fictitious Character)',
 'Hollywood (Los Angeles',
 'Holocaust',
 'Holocaust - Personal Narratives',
 'Holocaust - Study & Teaching',
 'Holocaust Biographies',
 'Holocauste',
 'Holocausto',
 'Homeless Persons',
 'Homeless Persons--Family Relationships',
 'Homeless Persons--Family Relationships--New York (State)--New York',
 'Homeless Persons--New York (State)--New York--Family Relationships',
 'Homer',
 'Homer.',
 'Homer.\x1e 4',
 'Homosexuality',
 'Hope',
 'Horror & Ghost Stories',
 'Horror - General',
 'Horror Stories',
 'Hotelkeepers',
 'Hotels',
 'Hour-Glasses',
 'Hq 734 G686 1999',
 'Hq734 .G7136 1999',
 'Hq734 .G7136 1999Bx',
 'Hugo Award Winner',
 'Human Behavior',
 'Human Cloning',
 'Human Relations',
 'Human Trafficking',
 'Human-Alien Encounters',
 'Human-Robot Relations',
 'Humans',
 'Humor / Essays',
 'Humor / Form / Essays',
 'Humor / Topic / Cultural',
 'Humoristiska Skildringar',
 'Humorous',
 'Humorous Stories',
 'Hunger',
 'Hurricane Katrina',
 'Hurricane Katrina (2005) Fast (Ocolc)Fst01755264',
 'Husbands',
 'Hv5132 .W35 2005',
 'Hymns',
 'Hyperspace',
 'Idaho',
 'Identité Collective',
 'Idiot (Television Program)',
 'Ignotus Award Winner',
 'Iliad (Homer)',
 'Ilias (Homerus)',
 'Illustrations',
 'Imaginary Places -- Fiction',
 'Imaginary Wars And Battles -- Fiction',
 'Imaginary Wars And Battles In Literature',
 'Imaginary Wars And Battles--Fiction',
 'Imaginärer Schauplatz',
 'Impostors And Imposture',
 'In Library',
 'In Literature',
 'Incest',
 'Indic Fiction (English)',
 'Individual Psychologists',
 'Industrialists',
 'Infinite Improbability Drive',
 'Influência',
 'Ingsoc',
 'Inheritance - The Inheritance Cycle',
 'Insurance Agents',
 'Intelligence Artificielle',
 'Internal Medicine',

In [ ]:
drop_mask = df_categories[df_categories['Category'].isin(categories_to_drop)]
df_categories = df_categories.drop(drop_mask.index, axis=0)
df_categories

       Book Id                    Category
8     22878967                        Epic
9     22878967                     Fantasy
10    22878967             Fantasy Fiction
13    22878967  Imaginary Wars And Battles
15    37640636          Action & Adventure
...        ...                         ...
3796  39863488               Psychological
3798  39863488                   Thrillers
3800  43848929             Conduct Of Life
3802  43848929     Interpersonal Relations
3807  43848929           Social Psychology

[984 rows x 2 columns]

## Cleaning main book Dataframe

In [ ]:
df_cp1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 30 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Book Id                     237 non-null    int64
 1   Title                       237 non-null    object
 2   Author                      237 non-null    object
 3   Author l-f                  237 non-null    object
 4   Additional Authors          55 non-null     object
 5   ISBN                        237 non-null    object
 6   ISBN13                      237 non-null    object
 7   My Rating                   237 non-null    int64
 8   Average Rating              237 non-null    float64
 9   Publisher                   233 non-null    object
 10  Binding                     237 non-null    object
 11  Number of Pages             236 non-null    float64
 12  Year Published              236 non-null    float64
 13  Original Publication Year   235 non-null    float64
 14  Date Read                   180 non-null    object
 15  Date Added                  237 non-null    object
 16  Bookshelves                 53 non-null     object
 17  Bookshelves with positions  53 non-null     object
 18  Exclusive Shelf             237 non-null    object
 19  My Review                   0 non-null      float64
 20  Spoiler                     0 non-null      float64
 21  Private Notes               1 non-null      object
 22  Read Count                  237 non-null    int64
 23  Owned Copies                237 non-null    int64
 24  Published Date              227 non-null    object
 25  Maturity Rating             227 non-null    object
 26  Description                 224 non-null    object
 27  Country                     227 non-null    object
 28  Retail Price                5 non-null      object
 29  Currency                    5 non-null      object
dtypes: float64(6), int64(4), object(20)
memory usage: 55.7+ KB

### Clean the `ISBN` columns

In [ ]:
for col, series in df_cp1[['ISBN', 'ISBN13']].items():
    df_cp1[col] = df_cp1[col].apply(clean_isbn)

### Fixing some author's names in `Author` column

In [ ]:
to_replace = {
    'Abraham   Verghese': 'Abraham Verghese',
    'Stephen        King': 'Stephen King'
}

for author, fixed in to_replace.items():
    df['Author'] = df['Author'].str.replace(author, fixed)

### Filling null values for `Additional Authors`

In [ ]:
df_cp1['Additional Authors'] = df_cp1['Additional Authors'].fillna('None')
df_cp1['Additional Authors'].isnull().sum()

np.int64(0)

### Filling null values for `Number of Pages`

In [ ]:
df_cp1['Number of Pages'] = df_cp1['Number of Pages'].fillna(0)
df_cp1['Additional Authors'].isnull().sum()
df_cp1['Number of Pages'] = df_cp1['Number of Pages'].astype(int)
df_cp1['Number of Pages'].isnull().sum()

np.int64(0)

### Was replaced with Published Date from GoogleAPI (had yyyy/mm/dd instead of just the year)

In [ ]:
df_cp1 = df_cp1.drop('Year Published', axis=1)

In [ ]:
df_cp1['Original Publication Year'] = df_cp1['Original Publication Year'].fillna(0)
df_cp1['Original Publication Year'] = df_cp1['Original Publication Year'].astype(int)

In [ ]:
df_cp1['Date Read'] = pd.to_datetime(df_cp1['Date Read'])
df_cp1['Date Added'] = pd.to_datetime(df_cp1['Date Added'])
df_cp1['Published Date'] = pd.to_datetime(df_cp1['Published Date'], format='mixed')

In [ ]:
df_cp1['Retail Price'] = df_cp1['Retail Price'].astype(float)

In [ ]:
df_cp1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Book Id                     237 non-null    int64
 1   Title                       237 non-null    object
 2   Author                      237 non-null    object
 3   Author l-f                  237 non-null    object
 4   Additional Authors          237 non-null    object
 5   ISBN                        237 non-null    object
 6   ISBN13                      237 non-null    object
 7   My Rating                   237 non-null    int64
 8   Average Rating              237 non-null    float64
 9   Publisher                   233 non-null    object
 10  Binding                     237 non-null    object
 11  Number of Pages             237 non-null    int64
 12  Original Publication Year   237 non-null    int64
 13  Date Read                   180 non-null    datetime64[ns]
 14  Date Added                  237 non-null    datetime64[ns]
 15  Bookshelves                 53 non-null     object
 16  Bookshelves with positions  53 non-null     object
 17  Exclusive Shelf             237 non-null    object
 18  My Review                   0 non-null      float64
 19  Spoiler                     0 non-null      float64
 20  Private Notes               1 non-null      object
 21  Read Count                  237 non-null    int64
 22  Owned Copies                237 non-null    int64
 23  Published Date              227 non-null    datetime64[ns]
 24  Maturity Rating             227 non-null    object
 25  Description                 224 non-null    object
 26  Country                     227 non-null    object
 27  Retail Price                5 non-null      float64
 28  Currency                    5 non-null      object
dtypes: datetime64[ns](3), float64(4), int64(6), object(16)
memory usage: 53.8+ KB

## Export Data

In [ ]:
df_cp1.to_csv(PROJECT_DIR / 'my_books_data.csv')
df_categories.to_csv(PROJECT_DIR / 'my_books_categories.csv')